import { InsertResult, MigrationInterface, ObjectLiteral, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';

// tslint:disable: max-line-length quotemark
export class AddingZnrMigration implements MigrationInterface {
    name = 'AddingZnrMigration1600810686673';

    async up(queryRunner: QueryRunner): Promise<any> {
        /* Insert cardSet */
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Zendikar Rising', shortName: 'ZNR' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        /* Insert Cards */
        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: 'Allied Assault',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Angel of Destiny',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Angelheart Protector',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: 'Archon of Emeria',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'Archpriest of Iona',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Attended Healer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Canyon Jerboa',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Cliffhaven Sell-Sword',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Dauntless Unity',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: 'Disenchant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: 'Emeria Captain',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: "Emeria's Call // Emeria, Shattered Skyclave",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: 'Expedition Healer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Farsight Adept',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Fearless Fledgling',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Felidar Retreat',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Journey to Oblivion',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: 'Kabira Outrider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Kabira Takedown // Kabira Plateau',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Kitesail Cleric',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: 'Kor Blademaster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: 'Kor Celebrant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: 'Legion Angel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Luminarch Aspirant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Makindi Ox',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Makindi Stampede // Makindi Mesas',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: 'Maul of the Skyclaves',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Mesa Lynx',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: "Nahiri's Binding",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: 'Ondu Inversion // Ondu Skyruins',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: 'Paired Tactician',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Practiced Tactics',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: 'Pressure Point',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Prowling Felidar',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: 'Resolute Strike',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: 'Sea Gate Banneret',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: 'Sejiri Shelter // Sejiri Glacier',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Shepherd of Heroes',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Skyclave Apparition',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Skyclave Cleric // Skyclave Basilica',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: 'Squad Commander',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'Smite the Monstrous',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: 'Tazeem Raptor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Tazri, Beacon of Unity',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Anticognition',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: 'Beyeen Veil // Beyeen Coast',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: 'Bubble Snare',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'Cascade Seer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Charix, the Raging Isle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Chilling Trap',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Cleric of Chill Depths',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Concerted Defense',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Confounding Conundrum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Coralhelm Chronicler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Cunning Geysermage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Deliberate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Expedition Diviner',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Field Research',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 59,
                    cardSet: cardSetId,
                    name: 'Glacial Grasp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Glasspool Mimic // Glasspool Shore',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Inscription of Insight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Into the Roil',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Jace, Mirror Mage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Jwari Disruption // Jwari Ruins',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: 'Living Tempest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: "Lullmage's Domination",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Maddening Cacophony',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Master of Winds',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Merfolk Falconer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Merfolk Windrobber',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Negate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Nimble Trapfinder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Risen Riptide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Roost of Drakes',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Ruin Crab',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Sea Gate Restoration // Sea Gate, Reborn',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: 'Sea Gate Stormcaller',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: 'Seafloor Stalker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: 'Shell Shield',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'Silundi Vision // Silundi Isle',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Skyclave Plunder',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: 'Skyclave Squid',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'Sure-Footed Infiltrator',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: 'Tazeem Roilmage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'Thieving Skydiver',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Umara Wizard // Umara Skyfalls',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Windrider Wizard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: 'Zulaport Duelist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Acquisitions Expert',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: "Agadeem's Awakening // Agadeem, the Undercrypt",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'Blackbloom Rogue // Blackbloom Bog',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Blood Beckoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Blood Price',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: "Bloodchief's Thirst",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Coveted Prize',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: 'Deadly Alliance',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: "Demon's Disciple",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Drana, the Last Bloodchief',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: "Drana's Silencer",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Dreadwurm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Expedition Skulker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: 'Feed the Swarm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Ghastly Gloomhunter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Guul Draz Mucklord',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Hagra Constrictor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Hagra Mauling // Hagra Broodpit',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Highborn Vampire',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Inscription of Ruin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Lithoform Blight',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: 'Malakir Blood-Priest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Malakir Rebirth // Malakir Mire',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: 'Marauding Blight-Priest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: 'Mind Carver',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Mind Drain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Nighthawk Scavenger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'Nimana Skitter-Sneak',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: 'Nimana Skydancer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: 'Nullpriest of Oblivion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: "Oblivion's Hunger",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: 'Pelakka Predation // Pelakka Caverns',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Scion of the Swarm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: 'Scourge of the Skyclaves',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Shadow Stinger',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: "Shadows' Verdict",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Skyclave Shade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Skyclave Shadowcat',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Soul Shatter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Subtle Strike',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: "Taborax, Hope's Demise",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Thwart the Grave',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Vanquish the Weak',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Zof Consumption // Zof Bloodbog',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Akoum Hellhound',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Akoum Warrior // Akoum Teeth',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Ardent Electromancer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: 'Cinderclasm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Cleansing Wildfire',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Expedition Champion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: 'Fireblade Charger',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: 'Fissure Wizard',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Goma Fada Vanguard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: 'Grotag Bug-Catcher',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Grotag Night-Runner',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Inordinate Rage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Kargan Intimidator',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: "Kazuul's Fury // Kazuul's Cliffs",
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Leyline Tyrant',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: 'Magmatic Channeler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Molten Blast',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Moraug, Fury of Akoum',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: "Nahiri's Lithoforming",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Pyroclastic Hellion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: 'Relic Robber',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: 'Rockslide Sorcerer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: 'Roil Eruption',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Roiling Vortex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Scavenged Blade',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Scorch Rider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Shatterskull Charger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Shatterskull Minotaur',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Shatterskull Smashing // Shatterskull, the Hammer Pass',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Sizzling Barrage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Skyclave Geopede',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Sneaking Guide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Song-Mad Treachery // Song-Mad Ruins',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Spikefield Hazard // Spikefield Cave',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Spitfire Lagac',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'Synchronized Spellcraft',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: 'Teeterpeak Ambusher',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'Thundering Rebuke',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Thundering Sparkmage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: 'Tormenting Voice',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Tuktuk Rubblefort',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: 'Valakut Awakening // Valakut Stoneforge',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Valakut Exploration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Wayward Guide-Beast',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'Adventure Awaits',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Ancient Greenwarden',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Ashaya, Soul of the Wild',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: 'Bala Ged Recovery // Bala Ged Sanctuary',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Broken Wings',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Canopy Baloth',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: 'Cragplate Baloth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Dauntless Survivor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Gnarlid Colony',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Inscription of Abundance',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Iridescent Hornbeetle',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: 'Joraga Visionary',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Kazandu Mammoth // Kazandu Valley',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: 'Kazandu Nectarpot',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Kazandu Stomper',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: 'Khalni Ambush // Khalni Territory',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Lotus Cobra',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Might of Murasa',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Murasa Brute',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Murasa Sproutling',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: "Nissa's Zendikon",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Oran-Rief Ooze',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Rabid Bite',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Reclaim the Wastes',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Roiling Regrowth',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Scale the Heights',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: 'Scute Swarm',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: 'Skyclave Pick-Axe',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'Springmantle Cleric',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Strength of Solidarity',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'Swarm Shambler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Tajuru Blightblade',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Tajuru Paragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: 'Tajuru Snarecaster',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: 'Tangled Florahedron // Tangled Vale',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Taunting Arbormage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: 'Territorial Scythecat',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'Turntimber Ascetic',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'Turntimber Symbiosis // Turntimber, Serpentine Wood',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Vastwood Fortification // Vastwood Thicket',
                    rarity: 'U',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: 'Vastwood Surge',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Veteran Adventurer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: 'Vine Gecko',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: 'Akiri, Fearless Voyager',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: 'Brushfire Elemental',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: "Cleric of Life's Bond",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Grakmaw, Skyclave Ravager',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Kargan Warleader',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: 'Kaza, Roil Chaser',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: 'Linvala, Shield of Sea Gate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: "Lullmage's Familiar",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Moss-Pit Skeleton',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Murasa Rootgrazer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Nahiri, Heir of the Ancients',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: 'Nissa of Shadowed Boughs',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: 'Omnath, Locus of Creation',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: 'Orah, Skyclave Hierophant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Phylath, World Sculptor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: "Ravager's Mace",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: 'Soaring Thought-Thief',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Spoils of Adventure',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Umara Mystic',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Verazol, the Split Current',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Yasharn, Implacable Earth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'Zagras, Thief of Heartbeats',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: 'Zareth San, the Trickster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Cliffhaven Kitesail',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Forsaken Monument',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Lithoform Engine',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Myriad Construct',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Relic Amulet',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Relic Axe',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Relic Golem',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Relic Vial',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Sea Gate Colossus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'Skyclave Relic',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Skyclave Sentinel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: 'Spare Supplies',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Stonework Packbeast',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Utility Knife',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Base Camp',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: 'Branchloft Pathway // Boulderloft Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Brightclimb Pathway // Grimclimb Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Clearwater Pathway // Murkwater Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Cragcrown Pathway // Timbercrown Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Crawling Barrens',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Needleverge Pathway // Pillarverge Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'Riverglide Pathway // Lavaglide Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Throne of Makindi',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Jace, Mirror Mage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Nahiri, Heir of the Ancients',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Nissa of Shadowed Boughs',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Branchloft Pathway // Boulderloft Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Brightclimb Pathway // Grimclimb Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Clearwater Pathway // Murkwater Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Cragcrown Pathway // Timbercrown Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'Needleverge Pathway // Pillarverge Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Riverglide Pathway // Lavaglide Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Canyon Jerboa',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: 'Fearless Fledgling',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: 'Felidar Retreat',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Makindi Ox',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Prowling Felidar',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: 'Ruin Crab',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Skyclave Squid',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Dreadwurm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Skyclave Shade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Akoum Hellhound',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: 'Moraug, Fury of Akoum',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Skyclave Geopede',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Spitfire Lagac',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Valakut Exploration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: 'Canopy Baloth',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: 'Kazandu Mammoth // Kazandu Valley',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: 'Kazandu Nectarpot',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: 'Lotus Cobra',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Scute Swarm',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Skyclave Pick-Axe',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Territorial Scythecat',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: 'Brushfire Elemental',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Omnath, Locus of Creation',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: 'Phylath, World Sculptor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Angel of Destiny',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: 'Archon of Emeria',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Archpriest of Iona',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: "Emeria's Call // Emeria, Shattered Skyclave",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Legion Angel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Luminarch Aspirant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: 'Maul of the Skyclaves',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Ondu Inversion // Ondu Skyruins',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: 'Skyclave Apparition',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Squad Commander',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Tazri, Beacon of Unity',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Charix, the Raging Isle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Confounding Conundrum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Coralhelm Chronicler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Glasspool Mimic // Glasspool Shore',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Inscription of Insight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: 'Maddening Cacophony',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Master of Winds',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: 'Nimble Trapfinder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'Sea Gate Restoration // Sea Gate, Reborn',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Sea Gate Stormcaller',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Thieving Skydiver',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: "Agadeem's Awakening // Agadeem, the Undercrypt",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Coveted Prize',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: 'Drana, the Last Bloodchief',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: 'Hagra Mauling // Hagra Broodpit',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Inscription of Ruin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: 'Nighthawk Scavenger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Nullpriest of Oblivion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: 'Scourge of the Skyclaves',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: "Shadows' Verdict",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: 'Soul Shatter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: "Taborax, Hope's Demise",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Kargan Intimidator',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: 'Leyline Tyrant',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Magmatic Channeler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: "Nahiri's Lithoforming",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Relic Robber',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Roiling Vortex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: 'Shatterskull Charger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Shatterskull Smashing // Shatterskull, the Hammer Pass',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Valakut Awakening // Valakut Stoneforge',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Wayward Guide-Beast',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Ancient Greenwarden',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Ashaya, Soul of the Wild',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'Cragplate Baloth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: 'Inscription of Abundance',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Oran-Rief Ooze',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Swarm Shambler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Tajuru Paragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'Turntimber Symbiosis // Turntimber, Serpentine Wood',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'Akiri, Fearless Voyager',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Grakmaw, Skyclave Ravager',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Kaza, Roil Chaser',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: 'Linvala, Shield of Sea Gate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'Orah, Skyclave Hierophant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: 'Verazol, the Split Current',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Yasharn, Implacable Earth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: 'Zagras, Thief of Heartbeats',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'Zareth San, the Trickster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: 'Forsaken Monument',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Lithoform Engine',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Myriad Construct',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'Skyclave Relic',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Crawling Barrens',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Throne of Makindi',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 383,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 384,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 385,
                    cardSet: cardSetId,
                    name: 'Orah, Skyclave Hierophant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 386,
                    cardSet: cardSetId,
                    name: 'Charix, the Raging Isle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 387,
                    cardSet: cardSetId,
                    name: 'Into the Roil',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 388,
                    cardSet: cardSetId,
                    name: "Bloodchief's Thirst",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 389,
                    cardSet: cardSetId,
                    name: 'Roil Eruption',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 390,
                    cardSet: cardSetId,
                    name: 'Roiling Regrowth',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 391,
                    cardSet: cardSetId,
                    name: 'Kargan Warleader',
                    rarity: 'U',
                    layout: 'normal',
                },
            ])
            .execute();
    }

    async down(queryRunner: QueryRunner): Promise<any> {
        // Get the card set id
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname: 'ZNR' })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname: 'ZNR' })
            .execute();
    }
}
