import { CardSet } from 'src/card/entity/card-set.entity';
import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';

export class migrationNameSe1611402162304 implements MigrationInterface {
    name = 'AddingKhmMigration1611402162304';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Kaldheim', short_name: 'KHM' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: 'Axgard Braggart',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Battershield Warrior',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Battlefield Raptor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: 'Beskir Shieldmate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'Bound in Gold',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Clarion Spirit',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Codespell Cleric',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Divine Gambit',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Doomskar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: 'Doomskar Oracle',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: 'Giant Ox',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: 'Glorious Protector',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: "Gods' Hall Guardian",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Goldmaw Champion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Halvar, God of Battle // Sword of the Realms',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Invoke the Divine',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Iron Verdict',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: "Kaya's Onslaught",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Master Skald',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Rally the Ranks',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: "Reidane, God of the Worthy // Valkmira, Protector's Shield",
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: 'Resplendent Marshal',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: 'Revitalize',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Righteous Valkyrie',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Rune of Sustenance',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Runeforge Champion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: 'Search for Glory',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Shepherd of the Cosmos',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: 'Sigrid, God-Favored',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: 'Spectral Steel',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: 'Stalwart Valkyrie',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Starnheim Courser',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: 'Starnheim Unleashed',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Story Seeker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: 'Usher of the Fallen',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: "Valkyrie's Sword",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: 'Valor of the Worthy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Warhorn Blast',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Wings of the Cosmos',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Alrund, God of the Cosmos // Hakka, Whispering Raven',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: "Alrund's Epiphany",
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'Annul',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: 'Ascendant Spirit',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Augury Raven',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Avalanche Caller',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: 'Behold the Multiverse',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: 'Berg Strider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'Bind the Monster',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Brinebarrow Intruder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Cosima, God of the Voyage // The Omenkeel',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Cosmos Charger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Cyclone Summoner',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Depart the Realm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Disdainful Stroke',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Draugr Thought-Thief',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Frost Augur',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Frostpeak Yeti',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Frostpyre Arcanist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 59,
                    cardSet: cardSetId,
                    name: "Giant's Amulet",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Glimpse the Cosmos',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Graven Lore',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Icebind Pillar',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Icebreaker Kraken',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Inga Rune-Eyes',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: 'Karfell Harbinger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: 'Littjara Kinseekers',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Mists of Littjara',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Mistwalker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Mystic Reflection',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Orvar, the All-Form',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Pilfering Hawk',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Ravenform',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Reflections of Littjara',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Run Ashore',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Rune of Flight',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Saw It Coming',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: 'Strategic Planning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: 'Undersea Invader',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: 'Blood on the Snow',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'Bloodsky Berserker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Burning-Rune Demon',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: 'Crippling Fear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'Deathknell Berserker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: 'Demonic Gifts',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'Dogged Pursuit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Draugr Necromancer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Draugr Recruiter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: "Draugr's Helm",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Dread Rider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: 'Dream Devourer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'Duskwielder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Egon, God of Death // Throne of Death',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Elderfang Disciple',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: 'Eradicator Valkyrie',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Feed the Serpent',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: 'Grim Draugr',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: 'Hailstorm Valkyrie',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Haunting Voyage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: 'Infernal Pet',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Jarl of the Forsaken',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Karfell Kennel-Master',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: "Koma's Faithful",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Poison the Cup',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Priest of the Haunted Edge',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Raise the Draugr',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Return Upon the Tide',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Rise of the Dread Marn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Rune of Mortality',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Skemfar Avenger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: 'Skemfar Shadowsage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Skull Raid',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: "Tergrid, God of Fright // Tergrid's Lantern",
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: "Tergrid's Shadow",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Valki, God of Lies // Tibalt, Cosmic Impostor',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Varragoth, Bloodsky Sire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'Vengeful Reaper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: 'Village Rites',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: 'Weigh Down',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: 'Withercrown',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: 'Arni Brokenbrow',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Axgard Cavalry',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: 'Basalt Ravager',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Birgi, God of Storytelling // Harnfel, Horn of Bounty',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: 'Breakneck Berserker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Calamity Bearer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Cinderheart Giant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Craven Hulk',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Crush the Weak',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: 'Demon Bolt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Doomskar Titan',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Dragonkin Berserker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Dual Strike',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Dwarven Hammer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Dwarven Reinforcements',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Fearless Liberator',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: 'Fearless Pup',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Frenzied Raider',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Frost Bite',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: 'Goldspan Dragon',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: 'Hagi Mob',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Immersturm Raider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: 'Magda, Brazen Outlaw',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Open the Omenpaths',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Provoke the Trolls',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Quakebringer',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: 'Reckless Crew',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Run Amok',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: 'Rune of Speed',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Seize the Spoils',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Shackles of Treachery',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: 'Smashing Success',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Squash',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: "Tibalt's Trickery",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: "Toralf, God of Fury // Toralf's Hammer",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: "Tormentor's Helm",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Tundra Fumarole',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Tuskeri Firewalker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Vault Robber',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Arachnoform',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Battle Mammoth',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Blessing of Frost',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Blizzard Brawl',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Boreal Outrider',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Broken Wings',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Elderleaf Mentor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Elven Bow',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Elvish Warmaster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'Esika, God of the Tree // The Prismatic Bridge',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: "Esika's Chariot",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'Fynn, the Fangbearer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Glittering Frost',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: 'Gnottvold Recluse',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Grizzled Outrider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: 'Guardian Gladewalker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Horizon Seeker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Icehide Troll',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'In Search of Greatness',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Jaspera Sentinel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Jorn, God of Winter // Kaldring, the Rimestaff',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: "King Harald's Revenge",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Kolvori, God of Kinship // The Ringhart Crest',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Littjara Glade-Warden',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: 'Mammoth Growth',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Masked Vandal',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Old-Growth Troll',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Path to the World Tree',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Ravenous Lindwurm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: 'Realmwalker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Rootless Yew',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: 'Roots of Wisdom',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Rune of Might',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: "Sarulf's Packmate",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Sculptor of Winter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Snakeskin Veil',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Spirit of the Aldergard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Struggle for Skemfar',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: 'Toski, Bearer of Secrets',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Tyvar Kell',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Vorinclex, Monstrous Raider',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Aegar, the Freezing Flame',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Arni Slays the Troll',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Ascent of the Worthy',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: 'Battle for Bretagard',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: 'Battle of Frost and Fire',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'The Bears of Littjara',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Binding the Old Gods',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'The Bloodsky Massacre',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Fall of the Impostor',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Firja, Judge of Valor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: "Firja's Retribution",
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: 'Forging the Tyrite Sword',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Harald, King of Skemfar',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: 'Harald Unites the Elves',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'Immersturm Predator',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'Invasion of the Giants',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Kardur, Doomscourge',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: "Kardur's Vicious Return",
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Kaya the Inexorable',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: "King Narfi's Betrayal",
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: 'Koll, the Forgemaster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: 'Koma, Cosmos Serpent',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: 'Maja, Bretagard Protector',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Moritte of the Frost',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Narfi, Betrayer King',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: 'Niko Aris',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: 'Niko Defies Destiny',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: "The Raven's Warning",
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Sarulf, Realm Eater',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Showdown of the Skalds',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Svella, Ice Shaper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: 'The Three Seasons',
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: "The Trickster-God's Heist",
                    rarity: 'U',
                    layout: 'saga',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: 'Vega, the Watcher',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Waking the Trolls',
                    rarity: 'R',
                    layout: 'saga',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: 'Bloodline Pretender',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: 'Colossal Plow',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Cosmos Elixir',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Funeral Longboat',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Goldvein Pick',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Maskwood Nexus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'Pyre of Heroes',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: "Raiders' Karve",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Raven Wings',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Replicating Ring',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Runed Crown',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Scorn Effigy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Weathered Runestone',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Alpine Meadow',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Arctic Treeline',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Axgard Armory',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Barkchannel Pathway // Tidechannel Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'Blightstep Pathway // Searstep Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Bretagard Stronghold',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: 'Darkbore Pathway // Slitherbore Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Faceless Haven',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Gates of Istfell',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Glacial Floodplain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: 'Gnottvold Slumbermound',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Great Hall of Starnheim',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Hengegate Pathway // Mistgate Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Highland Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Ice Tunnel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Immersturm Skullcairn',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'Littjara Mirrorlake',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Port of Karfell',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Rimewood Falls',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Shimmerdrift Vale',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Skemfar Elderhall',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Snowfield Sinkhole',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Sulfurous Mire',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Surtland Frostpyre',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Tyrite Sanctum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Volatile Fjord',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Woodland Chasm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'The World Tree',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Snow-Covered Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Valki, God of Lies // Tibalt, Cosmic Impostor',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Tyvar Kell',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'Kaya the Inexorable',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Niko Aris',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Barkchannel Pathway // Tidechannel Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: 'Blightstep Pathway // Searstep Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: 'Darkbore Pathway // Slitherbore Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Hengegate Pathway // Mistgate Pathway',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Starnheim Unleashed',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: "Alrund's Epiphany",
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Haunting Voyage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Quakebringer',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Battle Mammoth',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Halvar, God of Battle // Sword of the Realms',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: "Reidane, God of the Worthy // Valkmira, Protector's Shield",
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Sigrid, God-Favored',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Alrund, God of the Cosmos // Hakka, Whispering Raven',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Cosima, God of the Voyage // The Omenkeel',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: 'Inga Rune-Eyes',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: 'Orvar, the All-Form',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: 'Egon, God of Death // Throne of Death',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: "Tergrid, God of Fright // Tergrid's Lantern",
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Valki, God of Lies // Tibalt, Cosmic Impostor',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Varragoth, Bloodsky Sire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Arni Brokenbrow',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: 'Birgi, God of Storytelling // Harnfel, Horn of Bounty',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Magda, Brazen Outlaw',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: "Toralf, God of Fury // Toralf's Hammer",
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Esika, God of the Tree // The Prismatic Bridge',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: "Esika's Chariot",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Fynn, the Fangbearer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: 'Jorn, God of Winter // Kaldring, the Rimestaff',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Kolvori, God of Kinship // The Ringhart Crest',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Toski, Bearer of Secrets',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: 'Vorinclex, Monstrous Raider',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Aegar, the Freezing Flame',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: 'Firja, Judge of Valor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Harald, King of Skemfar',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Kardur, Doomscourge',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Koll, the Forgemaster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Koma, Cosmos Serpent',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Maja, Bretagard Protector',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Moritte of the Frost',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Narfi, Betrayer King',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: 'Sarulf, Realm Eater',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Svella, Ice Shaper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: 'Vega, the Watcher',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'Vorinclex, Monstrous Raider',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Doomskar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Glorious Protector',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: 'Rally the Ranks',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Resplendent Marshal',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: 'Righteous Valkyrie',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: 'Runeforge Champion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Search for Glory',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: 'Ascendant Spirit',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Cosmos Charger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: 'Cyclone Summoner',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: 'Graven Lore',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: 'Icebreaker Kraken',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: 'Mystic Reflection',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Reflections of Littjara',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: 'Blood on the Snow',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Burning-Rune Demon',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: 'Crippling Fear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Draugr Necromancer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Dream Devourer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: 'Eradicator Valkyrie',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Rise of the Dread Marn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Skemfar Avenger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Calamity Bearer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Dragonkin Berserker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Goldspan Dragon',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'Reckless Crew',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: "Tibalt's Trickery",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Tundra Fumarole',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Blessing of Frost',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Elvish Warmaster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'In Search of Greatness',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'Old-Growth Troll',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Realmwalker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Immersturm Predator',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: 'Cosmos Elixir',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'Maskwood Nexus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: 'Pyre of Heroes',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Faceless Haven',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: 'Tyrite Sanctum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'The World Tree',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: 'Valkyrie Harbinger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Surtland Elementalist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Cleaving Reaper',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'Surtland Flinger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Canopy Tactician',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Armed and Armored',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Starnheim Aspirant',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Warchanter Skald',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Youthful Valkyrie',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 383,
                    cardSet: cardSetId,
                    name: 'Absorb Identity',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 384,
                    cardSet: cardSetId,
                    name: "Giant's Grasp",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 385,
                    cardSet: cardSetId,
                    name: 'Elderfang Ritualist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 386,
                    cardSet: cardSetId,
                    name: 'Renegade Reaper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 387,
                    cardSet: cardSetId,
                    name: 'Thornmantle Striker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 388,
                    cardSet: cardSetId,
                    name: 'Bearded Axe',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 389,
                    cardSet: cardSetId,
                    name: "Fire Giant's Fury",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 390,
                    cardSet: cardSetId,
                    name: 'Gilded Assault Cart',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 391,
                    cardSet: cardSetId,
                    name: 'Elven Ambush',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 392,
                    cardSet: cardSetId,
                    name: 'Gladewalker Ritualist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 393,
                    cardSet: cardSetId,
                    name: 'Rampage of the Valkyries',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 394,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 395,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 396,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 397,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 398,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 399,
                    cardSet: cardSetId,
                    name: 'Realmwalker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 400,
                    cardSet: cardSetId,
                    name: 'Reflections of Littjara',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 401,
                    cardSet: cardSetId,
                    name: 'Usher of the Fallen',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 402,
                    cardSet: cardSetId,
                    name: 'Strategic Planning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 403,
                    cardSet: cardSetId,
                    name: 'Poison the Cup',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 404,
                    cardSet: cardSetId,
                    name: 'Frost Bite',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 405,
                    cardSet: cardSetId,
                    name: 'Masked Vandal',
                    rarity: 'C',
                    layout: 'normal',
                },
            ])
            .execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'KHM';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }
}
