import { CardSet } from '../card/entity/card-set.entity';
import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';

export class AddingStxMigration implements MigrationInterface {
    name = 'AddingStxMigration1617922479524';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Strixhaven: School of Mages', shortName: 'STX' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: 'Environmental Sciences',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Expanded Anatomy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Introduction to Annihilation',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: 'Introduction to Prophecy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'Mascot Exhibition',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Wandering Archaic // Explore the Vastlands',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Academic Probation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Ageless Guardian',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Beaming Defiance',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: 'Clever Lumimancer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: 'Combat Professor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: 'Defend the Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: 'Detention Vortex',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Devastating Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Dueling Coach',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Eager First-Year',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Elite Spellbinder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: 'Expel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Guiding Voice',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Leonin Lightscribe',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: "Mavinda, Students' Advocate",
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: 'Pilgrim of the Ages',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: 'Pillardrop Rescuer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Professor of Symbology',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Reduce to Memory',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Secret Rendezvous',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: "Semester's End",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Show of Confidence',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: 'Sparring Regimen',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: 'Star Pupil',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: "Stonebinder's Familiar",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Stonerise Spirit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: 'Strict Proctor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Study Break',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: 'Thunderous Orator',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: 'Arcane Subtraction',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: 'Archmage Emeritus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Burrog Befuddler',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Bury in Books',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Curate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: 'Divide by Zero',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'Dream Strix',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: 'Frost Trickster',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Ingenious Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Kelpie Guide',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: "Mentor's Guidance",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: 'Mercurial Transformation',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'Multiple Choice',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Pop Quiz',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Reject',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Resculpt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Serpentine Curve',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Snow Day',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Solve the Equation',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Soothsayer Adept',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Symmetry Sage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Teachings of the Archaics',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Tempted by the Oriq',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 59,
                    cardSet: cardSetId,
                    name: 'Test of Talents',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Vortex Runner',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Waterfall Aerialist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Wormhole Serpent',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Arrogant Poet',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Baleful Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: 'Brackish Trudge',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: 'Callous Bloodmage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Confront the Past',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Crushing Disappointment',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Essence Infusion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Eyetwitch',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Flunk',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Go Blank',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Hunt for Specimens',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Lash of Malice',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Leech Fanatic',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Mage Hunter',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: "Mage Hunters' Onslaught",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: 'Necrotic Fumes',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: 'Novice Dissector',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'Oriq Loremage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Plumb the Forbidden',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: "Poet's Quill",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'Professor Onyx',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: "Professor's Warning",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'Promising Duskmage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Sedgemoor Witch',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Specter of the Fens',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: 'Tenured Inkcaster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Umbral Juke',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: 'Unwilling Ingredient',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'Academic Dispute',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Ardent Dustspeaker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Blood Age General',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: 'Conspiracy Theorist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Crackle with Power',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: 'Draconic Intervention',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: "Dragon's Approach",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Efreet Flamepainter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: 'Enthusiastic Study',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Explosive Welcome',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Fervent Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: 'First Day of Class',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Fuming Effigy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Grinning Ignus',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Hall Monitor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Heated Debate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Igneous Inspiration',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Illuminate History',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Illustrious Historian',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: 'Mascot Interception',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Pigment Storm',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: 'Pillardrop Warden',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: 'Retriever Phoenix',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Start from Scratch',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Storm-Kiln Artist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'Sudden Breakthrough',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: 'Tome Shredder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: 'Twinscroll Shaman',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: 'Accomplished Alchemist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: 'Basic Conjuration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Bayou Groff',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: 'Big Play',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Bookwurm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: 'Charge Through',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Containment Breach',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Devouring Tendrils',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Dragonsguard Elite',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Ecological Appreciation',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: 'Emergent Sequence',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Exponential Growth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Field Trip',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Fortifying Draught',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Gnarled Professor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Honor Troll',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Karok Wrangler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: 'Leyline Invocation',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Mage Duel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Master Symmetrist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: 'Overgrown Arch',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: 'Professor of Zoomancy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Reckless Amplimancer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: 'Scurrid Colony',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Spined Karok',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Springmane Cervin',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Tangletrap',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: 'Verdant Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Augmenter Pugilist // Echoing Equation',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: 'Blex, Vexing Pest // Search for Blex',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Extus, Oriq Overlord // Awaken the Blood Avatar',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Flamescroll Celebrant // Revel in Silence',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: 'Jadzi, Oracle of Arcavios // Journey to the Oracle',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Kianne, Dean of Substance // Imbraham, Dean of Theory',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: 'Mila, Crafty Companion // Lukka, Wayward Bonder',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: 'Pestilent Cauldron // Restorative Burst',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: 'Plargg, Dean of Chaos // Augusta, Dean of Order',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Rowan, Scholar of Sparks // Will, Scholar of Frost',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Selfless Glyphweaver // Deadly Vanity',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Shaile, Dean of Radiance // Embrose, Dean of Shadow',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Torrent Sculptor // Flamethrower Sonata',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Uvilda, Dean of Perfection // Nassari, Dean of Expression',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Valentin, Dean of the Vein // Lisette, Dean of the Root',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Aether Helix',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Beledros Witherbloom',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Biomathematician',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Blade Historian',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Blood Researcher',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Blot Out the Sky',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'Body of Research',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: 'Closing Statement',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'Cram Session',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Creative Outburst',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: 'Culling Ritual',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Culmination of Studies',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: 'Daemogoth Titan',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Daemogoth Woe-Eater',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Deadly Brew',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'Decisive Denial',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Dina, Soul Steeper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Double Major',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: 'Dramatic Finale',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Elemental Expressionist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Elemental Masterpiece',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: 'Elemental Summoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Eureka Moment',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Exhilarating Elocution',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Expressive Iteration',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Fractal Summoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: 'Fracture',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Galazeth Prismari',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: 'Golden Ratio',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Harness Infinity',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: 'Hofri Ghostforge',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Humiliate',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Infuse with Vitality',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Inkling Summoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Kasmina, Enigma Sage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: 'Killian, Ink Duelist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Lorehold Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Lorehold Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Lorehold Excavation',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Lorehold Pledgemage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Maelstrom Muse',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: 'Magma Opus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: 'Make Your Mark',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'Manifestation Sage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Moldering Karok',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'Mortality Spear',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Needlethorn Drake',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Oggyar Battle-Seer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: 'Owlin Shieldmage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: 'Pest Summoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Practical Research',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: 'Prismari Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'Prismari Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'Prismari Pledgemage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Quandrix Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: 'Quandrix Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Quandrix Cultivator',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: 'Quandrix Pledgemage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: 'Quintorius, Field Historian',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: 'Radiant Scrollwielder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: 'Reconstruct History',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Relic Sloth',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Returned Pastcaller',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: 'Rip Apart',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: 'Rise of Extus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: 'Rootha, Mercurial Artist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Rushed Rebirth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Shadewing Laureate',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Shadrix Silverquill',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: 'Silverquill Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: 'Silverquill Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: 'Silverquill Pledgemage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Silverquill Silencer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: 'Spectacle Mage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: 'Spirit Summoning',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Spiteful Squad',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Square Up',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Stonebound Mentor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Tanazir Quandrix',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'Teach by Example',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: 'Tend the Pests',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Thrilling Discovery',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Vanishing Verse',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Velomachus Lorehold',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Venerable Warsinger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Witherbloom Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Witherbloom Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Witherbloom Pledgemage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Zimone, Quandrix Prodigy',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Biblioplex Assistant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'Campus Guide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Codie, Vociferous Codex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: 'Cogwork Archivist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Excavated Wall',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Letter of Acceptance',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Reflective Golem',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: 'Spell Satchel',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Strixhaven Stadium',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Team Pennant',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Zephyr Boots',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Access Tunnel',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Archway Commons',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'The Biblioplex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Frostboil Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Furycalm Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Hall of Oracles',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Lorehold Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Necroblossom Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Prismari Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Quandrix Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Shineshadow Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Silverquill Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Vineglimmer Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'Witherbloom Campus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Professor Onyx',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Mila, Crafty Companion // Lukka, Wayward Bonder',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Rowan, Scholar of Sparks // Will, Scholar of Frost',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: 'Kasmina, Enigma Sage',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Shadrix Silverquill',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Galazeth Prismari',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Beledros Witherbloom',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Velomachus Lorehold',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Tanazir Quandrix',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Mascot Exhibition',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Wandering Archaic // Explore the Vastlands',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Academic Probation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'Devastating Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Elite Spellbinder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Leonin Lightscribe',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: "Mavinda, Students' Advocate",
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: "Semester's End",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Sparring Regimen',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Strict Proctor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: 'Archmage Emeritus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Dream Strix',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Ingenious Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Multiple Choice',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Teachings of the Archaics',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: 'Tempted by the Oriq',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Baleful Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Callous Bloodmage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Confront the Past',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: 'Oriq Loremage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: "Poet's Quill",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: 'Sedgemoor Witch',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: 'Conspiracy Theorist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Crackle with Power',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Draconic Intervention',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Efreet Flamepainter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: 'Fervent Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Illuminate History',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: 'Retriever Phoenix',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Accomplished Alchemist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: 'Basic Conjuration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Dragonsguard Elite',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: 'Ecological Appreciation',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Exponential Growth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Gnarled Professor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: 'Verdant Mastery',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Augmenter Pugilist // Echoing Equation',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: 'Blex, Vexing Pest // Search for Blex',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Extus, Oriq Overlord // Awaken the Blood Avatar',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Flamescroll Celebrant // Revel in Silence',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Jadzi, Oracle of Arcavios // Journey to the Oracle',
                    rarity: 'M',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Kianne, Dean of Substance // Imbraham, Dean of Theory',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Pestilent Cauldron // Restorative Burst',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Plargg, Dean of Chaos // Augusta, Dean of Order',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Selfless Glyphweaver // Deadly Vanity',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: 'Shaile, Dean of Radiance // Embrose, Dean of Shadow',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Torrent Sculptor // Flamethrower Sonata',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: 'Uvilda, Dean of Perfection // Nassari, Dean of Expression',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'Valentin, Dean of the Vein // Lisette, Dean of the Root',
                    rarity: 'R',
                    layout: 'modal_dfc',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Blade Historian',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Blot Out the Sky',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: 'Body of Research',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Culling Ritual',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: 'Culmination of Studies',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: 'Daemogoth Titan',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Double Major',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: 'Dramatic Finale',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Elemental Expressionist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: 'Harness Infinity',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: 'Hofri Ghostforge',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: 'Lorehold Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: 'Magma Opus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Manifestation Sage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: 'Prismari Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Quandrix Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: 'Radiant Scrollwielder',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Rushed Rebirth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Silverquill Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: 'Silverquill Silencer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Vanishing Verse',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Venerable Warsinger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Witherbloom Command',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Codie, Vociferous Codex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Strixhaven Stadium',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'The Biblioplex',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: 'Frostboil Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Furycalm Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Hall of Oracles',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Necroblossom Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'Shineshadow Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'Vineglimmer Snarl',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Dragonsguard Elite',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'Archmage Emeritus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Fracture',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Expressive Iteration',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Mortality Spear',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Rip Apart',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Decisive Denial',
                    rarity: 'U',
                    layout: 'normal',
                },
            ])
            .execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'STX';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }
}
