import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingM201620400069138 implements MigrationInterface {
    name = 'addingM201620400069138';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Core Set 2020', shortName: 'M20' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Aerial Assault', rarity: 'C', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Ajani, Strength of the Pride', rarity: 'M', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Ancestral Blade', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Angel of Vitality', rarity: 'U', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Angelic Gift', rarity: 'C', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Apostle of Purifying Light', rarity: 'U', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Battalion Foot Soldier', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Bishop of Wings', rarity: 'R', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Brought Back', rarity: 'R', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Cavalier of Dawn', rarity: 'M', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Dawning Angel', rarity: 'C', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Daybreak Chaplain', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Devout Decree', rarity: 'U', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Disenchant', rarity: 'C', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Eternal Isolation', rarity: 'U', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Fencing Ace', rarity: 'U', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Gauntlets of Light', rarity: 'U', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Glaring Aegis', rarity: 'C', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Gods Willing', rarity: 'U', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Griffin Protector', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Griffin Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Hanged Executioner', rarity: 'R', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Herald of the Sun', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Inspired Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Inspiring Captain', rarity: 'C', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Leyline of Sanctity', rarity: 'R', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Loxodon Lifechanter', rarity: 'R', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Loyal Pegasus', rarity: 'U', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Master Splicer', rarity: 'U', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Moment of Heroism', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Moorland Inquisitor', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Pacifism', rarity: 'C', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Planar Cleansing', rarity: 'R', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Raise the Alarm', rarity: 'C', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Rule of Law', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Sephara, Sky\'s Blade', rarity: 'R', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Soulmender', rarity: 'C', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Squad Captain', rarity: 'C', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Starfield Mystic', rarity: 'R', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Steadfast Sentry', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Yoked Ox', rarity: 'C', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Aether Gust', rarity: 'U', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Agent of Treachery', rarity: 'R', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Air Elemental', rarity: 'U', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Anticipate', rarity: 'C', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Atemsis, All-Seeing', rarity: 'R', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Befuddle', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Bone to Ash', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Boreal Elemental', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Brineborn Cutthroat', rarity: 'U', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Captivating Gyre', rarity: 'U', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Cavalier of Gales', rarity: 'M', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Cerulean Drake', rarity: 'U', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Cloudkin Seer', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Convolute', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Drawn from Dreams', rarity: 'R', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Dungeon Geists', rarity: 'R', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Faerie Miscreant', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Flood of Tears', rarity: 'R', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Fortress Crab', rarity: 'C', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Frilled Sea Serpent', rarity: 'C', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Frost Lynx', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Hard Cover', rarity: 'U', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Leyline of Anticipation', rarity: 'R', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Masterful Replication', rarity: 'R', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Metropolis Sprite', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Moat Piranhas', rarity: 'C', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Mu Yanling, Sky Dancer', rarity: 'M', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Negate', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Octoprophet', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Portal of Sanctuary', rarity: 'U', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Renowned Weaponsmith', rarity: 'U', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Sage\'s Row Denizen', rarity: 'C', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Scholar of the Ages', rarity: 'U', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Sleep Paralysis', rarity: 'C', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Spectral Sailor', rarity: 'U', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Tale\'s End', rarity: 'R', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Unsummon', rarity: 'C', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Warden of Evos Isle', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Winged Words', rarity: 'C', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Yarok\'s Wavecrasher', rarity: 'U', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Zephyr Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Agonizing Syphon', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Audacious Thief', rarity: 'C', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Barony Vampire', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Bladebrand', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Blightbeetle', rarity: 'U', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Blood Burglar', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Blood for Bones', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Bloodsoaked Altar', rarity: 'U', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Bloodthirsty Aerialist', rarity: 'U', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Bone Splinters', rarity: 'C', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Boneclad Necromancer', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Cavalier of Night', rarity: 'M', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Disfigure', rarity: 'U', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Dread Presence', rarity: 'R', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Duress', rarity: 'C', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Embodiment of Agonies', rarity: 'R', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Epicure of Blood', rarity: 'C', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Fathom Fleet Cutthroat', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Feral Abomination', rarity: 'C', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Gorging Vulture', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Gravedigger', rarity: 'U', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Gruesome Scourger', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Knight of the Ebon Legion', rarity: 'R', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Legion\'s End', rarity: 'R', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Leyline of the Void', rarity: 'R', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Mind Rot', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Murder', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Noxious Grasp', rarity: 'U', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Rotting Regisaur', rarity: 'R', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Sanitarium Skeleton', rarity: 'C', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Scheming Symmetry', rarity: 'R', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Sorcerer of the Fang', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Sorin, Imperious Bloodlord', rarity: 'M', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Soul Salvage', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Thought Distortion', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Undead Servant', rarity: 'C', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Unholy Indenture', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Vampire of the Dire Moon', rarity: 'U', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Vengeful Warchief', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Vilis, Broker of Blood', rarity: 'R', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Yarok\'s Fenlurker', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Act of Treason', rarity: 'C', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Cavalier of Flame', rarity: 'M', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Chandra, Acolyte of Flame', rarity: 'R', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Chandra, Awakened Inferno', rarity: 'M', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Chandra, Novice Pyromancer', rarity: 'U', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Chandra\'s Embercat', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Chandra\'s Outrage', rarity: 'C', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Chandra\'s Regulator', rarity: 'R', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Chandra\'s Spitfire', rarity: 'U', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Daggersail Aeronaut', rarity: 'C', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Destructive Digger', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Dragon Mage', rarity: 'U', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Drakuseth, Maw of Flames', rarity: 'R', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Ember Hauler', rarity: 'U', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Fire Elemental', rarity: 'C', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Flame Sweep', rarity: 'U', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Fry', rarity: 'U', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Glint-Horn Buccaneer', rarity: 'R', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Goblin Bird-Grabber', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Goblin Ringleader', rarity: 'U', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Goblin Smuggler', rarity: 'C', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Infuriate', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Keldon Raider', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Lavakin Brawler', rarity: 'C', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Leyline of Combustion', rarity: 'R', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Maniacal Rage', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Marauding Raptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Mask of Immolation', rarity: 'U', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Pack Mastiff', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Rapacious Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Reckless Air Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Reduce to Ashes', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Repeated Reverberation', rarity: 'R', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Ripscale Predator', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Scampering Scorcher', rarity: 'U', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Scorch Spitter', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Shock', rarity: 'C', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Tectonic Rift', rarity: 'C', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Thunderkin Awakener', rarity: 'R', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Uncaged Fury', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Unchained Berserker', rarity: 'U', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Barkhide Troll', rarity: 'U', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Brightwood Tracker', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Cavalier of Thorns', rarity: 'M', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Centaur Courser', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Elvish Reclaimer', rarity: 'R', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Feral Invocation', rarity: 'C', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Ferocious Pup', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Gargos, Vicious Watcher', rarity: 'R', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Gift of Paradise', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Greenwood Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Growth Cycle', rarity: 'C', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Healer of the Glade', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Howling Giant', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Leafkin Druid', rarity: 'C', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Leyline of Abundance', rarity: 'R', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Loaming Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Mammoth Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Might of the Masses', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Natural End', rarity: 'C', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Netcaster Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Nightpack Ambusher', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Overcome', rarity: 'U', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Overgrowth Elemental', rarity: 'U', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Plummet', rarity: 'C', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Pulse of Murasa', rarity: 'U', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Rabid Bite', rarity: 'C', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Season of Growth', rarity: 'U', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Sedge Scorpion', rarity: 'C', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Shared Summons', rarity: 'R', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Shifting Ceratops', rarity: 'R', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Silverback Shaman', rarity: 'C', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Thicket Crasher', rarity: 'C', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Thrashing Brontodon', rarity: 'U', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Veil of Summer', rarity: 'U', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Vivien, Arkbow Ranger', rarity: 'M', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Voracious Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Vorstclaw', rarity: 'C', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Wakeroot Elemental', rarity: 'R', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Wolfkin Bond', rarity: 'C', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Wolfrider\'s Saddle', rarity: 'U', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Woodland Champion', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Corpse Knight', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Creeping Trailblazer', rarity: 'U', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Empyrean Eagle', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Ironroot Warlord', rarity: 'U', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Kaalia, Zenith Seeker', rarity: 'M', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Kethis, the Hidden Hand', rarity: 'M', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Kykar, Wind\'s Fury', rarity: 'M', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Lightning Stormkin', rarity: 'U', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Moldervine Reclamation', rarity: 'U', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Ogre Siegebreaker', rarity: 'U', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Omnath, Locus of the Roil', rarity: 'M', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Risen Reef', rarity: 'U', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Skyknight Vanguard', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Tomebound Lich', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Yarok, the Desecrated', rarity: 'M', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Anvilwrought Raptor', rarity: 'C', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Bag of Holding', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Colossus Hammer', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Diamond Knight', rarity: 'U', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Diviner\'s Lockbox', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Golos, Tireless Pilgrim', rarity: 'R', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Grafdigger\'s Cage', rarity: 'R', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Heart-Piercer Bow', rarity: 'C', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Icon of Ancestry', rarity: 'R', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Manifold Key', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Marauder\'s Axe', rarity: 'C', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Meteor Golem', rarity: 'U', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Mystic Forge', rarity: 'R', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Pattern Matcher', rarity: 'U', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Prismite', rarity: 'C', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Retributive Wand', rarity: 'U', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Salvager of Ruin', rarity: 'U', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Scuttlemutt', rarity: 'U', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Steel Overseer', rarity: 'R', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Stone Golem', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Vial of Dragonfire', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Bloodfell Caves', rarity: 'C', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Blossoming Sands', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Cryptic Caves', rarity: 'U', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Dismal Backwater', rarity: 'C', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Evolving Wilds', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Field of the Dead', rarity: 'R', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Jungle Hollow', rarity: 'C', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Lotus Field', rarity: 'R', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Rugged Highlands', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Scoured Barrens', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Swiftwater Cliffs', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Temple of Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Temple of Malady', rarity: 'R', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Temple of Mystery', rarity: 'R', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Temple of Silence', rarity: 'R', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Temple of Triumph', rarity: 'R', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Thornwood Falls', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Tranquil Cove', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Wind-Scarred Crag', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Rienne, Angel of Rebirth', rarity: 'M', layout: 'normal' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Ajani, Inspiring Leader', rarity: 'M', layout: 'normal' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Goldmane Griffin', rarity: 'R', layout: 'normal' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Savannah Sage', rarity: 'C', layout: 'normal' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Twinblade Paladin', rarity: 'U', layout: 'normal' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Mu Yanling, Celestial Wind', rarity: 'M', layout: 'normal' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Celestial Messenger', rarity: 'C', layout: 'normal' },
            { cardNumber: 288, cardSet: cardSetId, name: 'Waterkin Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 289, cardSet: cardSetId, name: 'Yanling\'s Harbinger', rarity: 'R', layout: 'normal' },
            { cardNumber: 290, cardSet: cardSetId, name: 'Sorin, Vampire Lord', rarity: 'M', layout: 'normal' },
            { cardNumber: 291, cardSet: cardSetId, name: 'Savage Gorger', rarity: 'C', layout: 'normal' },
            { cardNumber: 292, cardSet: cardSetId, name: 'Sorin\'s Guide', rarity: 'R', layout: 'normal' },
            { cardNumber: 293, cardSet: cardSetId, name: 'Thirsting Bloodlord', rarity: 'U', layout: 'normal' },
            { cardNumber: 294, cardSet: cardSetId, name: 'Chandra, Flame\'s Fury', rarity: 'M', layout: 'normal' },
            { cardNumber: 295, cardSet: cardSetId, name: 'Chandra\'s Flame Wave', rarity: 'R', layout: 'normal' },
            { cardNumber: 296, cardSet: cardSetId, name: 'Pyroclastic Elemental', rarity: 'U', layout: 'normal' },
            { cardNumber: 297, cardSet: cardSetId, name: 'Wildfire Elemental', rarity: 'C', layout: 'normal' },
            { cardNumber: 298, cardSet: cardSetId, name: 'Vivien, Nature\'s Avenger', rarity: 'M', layout: 'normal' },
            { cardNumber: 299, cardSet: cardSetId, name: 'Ethereal Elk', rarity: 'R', layout: 'normal' },
            { cardNumber: 300, cardSet: cardSetId, name: 'Gnarlback Rhino', rarity: 'U', layout: 'normal' },
            { cardNumber: 301, cardSet: cardSetId, name: 'Vivien\'s Crocodile', rarity: 'C', layout: 'normal' },
            { cardNumber: 302, cardSet: cardSetId, name: 'Angelic Guardian', rarity: 'R', layout: 'normal' },
            { cardNumber: 303, cardSet: cardSetId, name: 'Bastion Enforcer', rarity: 'C', layout: 'normal' },
            { cardNumber: 304, cardSet: cardSetId, name: 'Concordia Pegasus', rarity: 'C', layout: 'normal' },
            { cardNumber: 305, cardSet: cardSetId, name: 'Haazda Officer', rarity: 'C', layout: 'normal' },
            { cardNumber: 306, cardSet: cardSetId, name: 'Impassioned Orator', rarity: 'C', layout: 'normal' },
            { cardNumber: 307, cardSet: cardSetId, name: 'Imperial Outrider', rarity: 'C', layout: 'normal' },
            { cardNumber: 308, cardSet: cardSetId, name: 'Ironclad Krovod', rarity: 'C', layout: 'normal' },
            { cardNumber: 309, cardSet: cardSetId, name: 'Prowling Caracal', rarity: 'C', layout: 'normal' },
            { cardNumber: 310, cardSet: cardSetId, name: 'Serra\'s Guardian', rarity: 'R', layout: 'normal' },
            { cardNumber: 311, cardSet: cardSetId, name: 'Show of Valor', rarity: 'C', layout: 'normal' },
            { cardNumber: 312, cardSet: cardSetId, name: 'Siege Mastodon', rarity: 'C', layout: 'normal' },
            { cardNumber: 313, cardSet: cardSetId, name: 'Take Vengeance', rarity: 'C', layout: 'normal' },
            { cardNumber: 314, cardSet: cardSetId, name: 'Trusted Pegasus', rarity: 'C', layout: 'normal' },
            { cardNumber: 315, cardSet: cardSetId, name: 'Coral Merfolk', rarity: 'C', layout: 'normal' },
            { cardNumber: 316, cardSet: cardSetId, name: 'Phantom Warrior', rarity: 'C', layout: 'normal' },
            { cardNumber: 317, cardSet: cardSetId, name: 'Riddlemaster Sphinx', rarity: 'R', layout: 'normal' },
            { cardNumber: 318, cardSet: cardSetId, name: 'Snapping Drake', rarity: 'C', layout: 'normal' },
            { cardNumber: 319, cardSet: cardSetId, name: 'Bartizan Bats', rarity: 'C', layout: 'normal' },
            { cardNumber: 320, cardSet: cardSetId, name: 'Bogstomper', rarity: 'C', layout: 'normal' },
            { cardNumber: 321, cardSet: cardSetId, name: 'Dark Remedy', rarity: 'C', layout: 'normal' },
            { cardNumber: 322, cardSet: cardSetId, name: 'Disentomb', rarity: 'C', layout: 'normal' },
            { cardNumber: 323, cardSet: cardSetId, name: 'Gravewaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 324, cardSet: cardSetId, name: 'Skeleton Archer', rarity: 'C', layout: 'normal' },
            { cardNumber: 325, cardSet: cardSetId, name: 'Sorin\'s Thirst', rarity: 'C', layout: 'normal' },
            { cardNumber: 326, cardSet: cardSetId, name: 'Vampire Opportunist', rarity: 'C', layout: 'normal' },
            { cardNumber: 327, cardSet: cardSetId, name: 'Walking Corpse', rarity: 'C', layout: 'normal' },
            { cardNumber: 328, cardSet: cardSetId, name: 'Engulfing Eruption', rarity: 'C', layout: 'normal' },
            { cardNumber: 329, cardSet: cardSetId, name: 'Fearless Halberdier', rarity: 'C', layout: 'normal' },
            { cardNumber: 330, cardSet: cardSetId, name: 'Goblin Assailant', rarity: 'C', layout: 'normal' },
            { cardNumber: 331, cardSet: cardSetId, name: 'Hostile Minotaur', rarity: 'C', layout: 'normal' },
            { cardNumber: 332, cardSet: cardSetId, name: 'Immortal Phoenix', rarity: 'R', layout: 'normal' },
            { cardNumber: 333, cardSet: cardSetId, name: 'Nimble Birdsticker', rarity: 'C', layout: 'normal' },
            { cardNumber: 334, cardSet: cardSetId, name: 'Rubblebelt Recluse', rarity: 'C', layout: 'normal' },
            { cardNumber: 335, cardSet: cardSetId, name: 'Shivan Dragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 336, cardSet: cardSetId, name: 'Volcanic Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 337, cardSet: cardSetId, name: 'Aggressive Mammoth', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, cardSet: cardSetId, name: 'Bristling Boar', rarity: 'C', layout: 'normal' },
            { cardNumber: 339, cardSet: cardSetId, name: 'Canopy Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 340, cardSet: cardSetId, name: 'Frilled Sandwalla', rarity: 'C', layout: 'normal' },
            { cardNumber: 341, cardSet: cardSetId, name: 'Oakenform', rarity: 'C', layout: 'normal' },
            { cardNumber: 342, cardSet: cardSetId, name: 'Prized Unicorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 343, cardSet: cardSetId, name: 'Titanic Growth', rarity: 'C', layout: 'normal' },
            { cardNumber: 344, cardSet: cardSetId, name: 'Woodland Mystic', rarity: 'C', layout: 'normal' },
        ]).execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'M20';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
