import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingAkh1620389785749 implements MigrationInterface {
    name = 'addingAkh1620389785749';

    public async up(queryRunner: QueryRunner): Promise<void> {


        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Amonkhet', shortName: 'AKH' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Angel of Sanctions', rarity: 'M', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Anointed Procession', rarity: 'R', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Anointer Priest', rarity: 'C', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Approach of the Second Sun', rarity: 'R', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Aven Mindcensor', rarity: 'R', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Binding Mummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Cartouche of Solidarity', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Cast Out', rarity: 'U', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Compulsory Rest', rarity: 'C', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Devoted Crop-Mate', rarity: 'U', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Djeru\'s Resolve', rarity: 'C', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Fan Bearer', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Forsake the Worldly', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Gideon of the Trials', rarity: 'M', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Gideon\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Glory-Bound Initiate', rarity: 'R', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Gust Walker', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Impeccable Timing', rarity: 'C', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'In Oketra\'s Name', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Mighty Leap', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Oketra the True', rarity: 'M', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Oketra\'s Attendant', rarity: 'U', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Protection of the Hekma', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Regal Caracal', rarity: 'R', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Renewed Faith', rarity: 'U', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Rhet-Crop Spearmaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Sacred Cat', rarity: 'C', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Seraph of the Suns', rarity: 'U', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Sparring Mummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Supply Caravan', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Tah-Crop Elite', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Those Who Serve', rarity: 'C', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Time to Reflect', rarity: 'U', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Trial of Solidarity', rarity: 'U', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Trueheart Duelist', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Unwavering Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Vizier of Deferment', rarity: 'U', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Vizier of Remedies', rarity: 'U', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Winged Shepherd', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Ancient Crab', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Angler Drake', rarity: 'U', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'As Foretold', rarity: 'M', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Aven Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Cancel', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Cartouche of Knowledge', rarity: 'C', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Censor', rarity: 'U', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Compelling Argument', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Cryptic Serpent', rarity: 'U', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Curator of Mysteries', rarity: 'R', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Decision Paralysis', rarity: 'C', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Drake Haven', rarity: 'R', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Essence Scatter', rarity: 'C', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Floodwaters', rarity: 'C', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Galestrike', rarity: 'U', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Glyph Keeper', rarity: 'R', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Hekma Sentinels', rarity: 'C', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Hieroglyphic Illumination', rarity: 'C', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Illusory Wrappings', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Kefnet the Mindful', rarity: 'M', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Labyrinth Guardian', rarity: 'U', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Lay Claim', rarity: 'U', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Naga Oracle', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'New Perspectives', rarity: 'R', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Open into Wonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Pull from Tomorrow', rarity: 'R', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'River Serpent', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Sacred Excavation', rarity: 'U', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Scribe of the Mindful', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Seeker of Insight', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Shimmerscale Drake', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Slither Blade', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Tah-Crop Skirmisher', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Trial of Knowledge', rarity: 'U', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Vizier of Many Faces', rarity: 'R', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Vizier of Tumbling Sands', rarity: 'U', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Winds of Rebuke', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Zenith Seeker', rarity: 'U', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Archfiend of Ifnir', rarity: 'R', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Baleful Ammit', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Blighted Bat', rarity: 'C', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Bone Picker', rarity: 'U', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Bontu the Glorified', rarity: 'M', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Cartouche of Ambition', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Cruel Reality', rarity: 'M', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Cursed Minotaur', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Dispossess', rarity: 'R', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Doomed Dissenter', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Dread Wanderer', rarity: 'R', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Dune Beetle', rarity: 'C', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Faith of the Devoted', rarity: 'U', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Festering Mummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Final Reward', rarity: 'C', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Gravedigger', rarity: 'U', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Grim Strider', rarity: 'U', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Horror of the Broken Lands', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Lay Bare the Heart', rarity: 'U', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Liliana, Death\'s Majesty', rarity: 'M', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Liliana\'s Mastery', rarity: 'R', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Lord of the Accursed', rarity: 'U', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Miasmic Mummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Nest of Scarabs', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Painful Lesson', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Pitiless Vizier', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Plague Belcher', rarity: 'R', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Ruthless Sniper', rarity: 'U', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Scarab Feast', rarity: 'C', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Shadow of the Grave', rarity: 'R', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Soulstinger', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Splendid Agony', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Stir the Sands', rarity: 'U', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Supernatural Stamina', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Trespasser\'s Curse', rarity: 'C', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Trial of Ambition', rarity: 'U', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Unburden', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Wander in Death', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Wasteland Scorpion', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Ahn-Crop Crasher', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Battlefield Scavenger', rarity: 'U', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Blazing Volley', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Bloodlust Inciter', rarity: 'C', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Bloodrage Brawler', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Brute Strength', rarity: 'C', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'By Force', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Cartouche of Zeal', rarity: 'C', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Combat Celebrant', rarity: 'M', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Consuming Fervor', rarity: 'U', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Deem Worthy', rarity: 'U', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Desert Cerodon', rarity: 'C', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Electrify', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Emberhorn Minotaur', rarity: 'C', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Flameblade Adept', rarity: 'U', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Fling', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Glorious End', rarity: 'M', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Glorybringer', rarity: 'R', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Harsh Mentor', rarity: 'R', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Hazoret the Fervent', rarity: 'M', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Hazoret\'s Favor', rarity: 'R', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Heart-Piercer Manticore', rarity: 'R', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Hyena Pack', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Limits of Solidarity', rarity: 'U', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Magma Spray', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Manticore of the Gauntlet', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Minotaur Sureshot', rarity: 'C', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Nef-Crop Entangler', rarity: 'C', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Nimble-Blade Khenra', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Pathmaker Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Pursue Glory', rarity: 'C', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Soul-Scar Mage', rarity: 'R', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Sweltering Suns', rarity: 'R', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Thresher Lizard', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Tormenting Voice', rarity: 'C', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Trial of Zeal', rarity: 'U', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Trueheart Twins', rarity: 'U', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Violent Impact', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Warfire Javelineer', rarity: 'U', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Benefaction of Rhonas', rarity: 'C', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Bitterblade Warrior', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Cartouche of Strength', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Champion of Rhonas', rarity: 'R', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Channeler Initiate', rarity: 'R', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Colossapede', rarity: 'C', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Crocodile of the Crossing', rarity: 'U', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Defiant Greatmaw', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Dissenter\'s Deliverance', rarity: 'C', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Exemplar of Strength', rarity: 'U', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Giant Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Gift of Paradise', rarity: 'C', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Greater Sandwurm', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Hapatra\'s Mark', rarity: 'U', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Harvest Season', rarity: 'R', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Haze of Pollen', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Honored Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Hooded Brawler', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Initiate\'s Companion', rarity: 'C', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Manglehorn', rarity: 'U', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Naga Vitalist', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Oashra Cultivator', rarity: 'C', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Ornery Kudu', rarity: 'C', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Pouncing Cheetah', rarity: 'C', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Prowling Serpopard', rarity: 'R', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Quarry Hauler', rarity: 'C', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Rhonas the Indomitable', rarity: 'M', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Sandwurm Convergence', rarity: 'R', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Scaled Behemoth', rarity: 'U', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Shed Weakness', rarity: 'C', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Shefet Monitor', rarity: 'U', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Sixth Sense', rarity: 'U', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Spidery Grasp', rarity: 'C', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Stinging Shot', rarity: 'C', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Synchronized Strike', rarity: 'U', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Trial of Strength', rarity: 'U', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Vizier of the Menagerie', rarity: 'M', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Watchful Naga', rarity: 'U', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Ahn-Crop Champion', rarity: 'U', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Aven Wind Guide', rarity: 'U', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Bounty of the Luxa', rarity: 'R', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Decimator Beetle', rarity: 'U', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Enigma Drake', rarity: 'U', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Hapatra, Vizier of Poisons', rarity: 'R', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Honored Crop-Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Khenra Charioteer', rarity: 'U', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Merciless Javelineer', rarity: 'U', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Neheb, the Worthy', rarity: 'R', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Nissa, Steward of Elements', rarity: 'M', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Samut, Voice of Dissent', rarity: 'M', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Shadowstorm Vizier', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Temmet, Vizier of Naktamun', rarity: 'R', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Wayward Servant', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Weaver of Currents', rarity: 'U', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Dusk', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Commit', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Never', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Insult', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Mouth', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Start', rarity: 'U', layout: 'aftermath' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Reduce', rarity: 'U', layout: 'aftermath' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Destined', rarity: 'U', layout: 'aftermath' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Onward', rarity: 'U', layout: 'aftermath' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Spring', rarity: 'U', layout: 'aftermath' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Prepare', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Failure', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Rags', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Cut', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Heaven', rarity: 'R', layout: 'aftermath' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Bontu\'s Monument', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Edifice of Authority', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Embalmer\'s Tools', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Gate to the Afterlife', rarity: 'U', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Hazoret\'s Monument', rarity: 'U', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Honed Khopesh', rarity: 'C', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Kefnet\'s Monument', rarity: 'U', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Luxa River Shrine', rarity: 'C', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Oketra\'s Monument', rarity: 'U', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Oracle\'s Vault', rarity: 'R', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Pyramid of the Pantheon', rarity: 'R', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Rhonas\'s Monument', rarity: 'U', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Throne of the God-Pharaoh', rarity: 'R', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Watchers of the Dead', rarity: 'U', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Canyon Slough', rarity: 'R', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Cascading Cataracts', rarity: 'R', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Cradle of the Accursed', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Evolving Wilds', rarity: 'C', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Fetid Pools', rarity: 'R', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Grasping Dunes', rarity: 'U', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Irrigated Farmland', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Painted Bluffs', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Scattered Groves', rarity: 'R', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Sheltered Thicket', rarity: 'R', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Sunscorched Desert', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Gideon, Martial Paragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Companion of the Trials', rarity: 'U', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Gideon\'s Resolve', rarity: 'R', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Graceful Cat', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Stone Quarry', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Liliana, Death Wielder', rarity: 'M', layout: 'normal' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Desiccated Naga', rarity: 'U', layout: 'normal' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Liliana\'s Influence', rarity: 'R', layout: 'normal' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Tattered Mummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Foul Orchard', rarity: 'C', layout: 'normal' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Cinder Barrens', rarity: 'C', layout: 'normal' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Forsaken Sanctuary', rarity: 'C', layout: 'normal' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Highland Lake', rarity: 'C', layout: 'normal' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Meandering River', rarity: 'C', layout: 'normal' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Submerged Boneyard', rarity: 'C', layout: 'normal' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Timber Gorge', rarity: 'C', layout: 'normal' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Tranquil Expanse', rarity: 'C', layout: 'normal' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Woodland Stream', rarity: 'C', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'AKH';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
