import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingThb1620400825744 implements MigrationInterface {
    name = 'addingThb1620400825744';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Theros Beyond Death', shortName: 'THB' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Alseid of Life\'s Bounty', rarity: 'U', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Archon of Falling Stars', rarity: 'U', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Archon of Sun\'s Grace', rarity: 'R', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Banishing Light', rarity: 'U', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'The Birth of Meletis', rarity: 'U', layout: 'saga' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Captivating Unicorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Commanding Presence', rarity: 'U', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Dawn Evangel', rarity: 'U', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Daxos, Blessed by the Sun', rarity: 'U', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Daybreak Chimera', rarity: 'C', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Dreadful Apathy', rarity: 'C', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Eidolon of Obstruction', rarity: 'R', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Elspeth Conquers Death', rarity: 'R', layout: 'saga' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Elspeth, Sun\'s Nemesis', rarity: 'M', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Favored of Iroas', rarity: 'U', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Flicker of Fate', rarity: 'C', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Glory Bearers', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Heliod, Sun-Crowned', rarity: 'M', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Heliod\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Heliod\'s Pilgrim', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Heliod\'s Punishment', rarity: 'U', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Hero of the Pride', rarity: 'C', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Hero of the Winds', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Idyllic Tutor', rarity: 'R', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Indomitable Will', rarity: 'C', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Karametra\'s Blessing', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Lagonna-Band Storyteller', rarity: 'U', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Leonin of the Lost Pride', rarity: 'C', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Nyxborn Courser', rarity: 'C', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Omen of the Sun', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Phalanx Tactics', rarity: 'U', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Pious Wayfarer', rarity: 'C', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Reverent Hoplite', rarity: 'U', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Revoke Existence', rarity: 'C', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Rumbling Sentry', rarity: 'C', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Sentinel\'s Eyes', rarity: 'C', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Shatter the Sky', rarity: 'R', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Sunmane Pegasus', rarity: 'C', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Taranika, Akroan Veteran', rarity: 'R', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Transcendent Envoy', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Triumphant Surge', rarity: 'C', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Alirios, Enraptured', rarity: 'U', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Ashiok\'s Erasure', rarity: 'R', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Brine Giant', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Callaphe, Beloved of the Sea', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Chain to Memory', rarity: 'C', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Deny the Divine', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Eidolon of Philosophy', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Elite Instructor', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Glimpse of Freedom', rarity: 'U', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Ichthyomorphosis', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Kiora Bests the Sea God', rarity: 'M', layout: 'saga' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Medomai\'s Prophecy', rarity: 'U', layout: 'saga' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Memory Drain', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Nadir Kraken', rarity: 'R', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Naiad of Hidden Coves', rarity: 'C', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Nyxborn Seaguard', rarity: 'C', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Omen of the Sea', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'One with the Stars', rarity: 'U', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Protean Thaumaturge', rarity: 'R', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Riptide Turtle', rarity: 'C', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Sage of Mysteries', rarity: 'U', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Sea God\'s Scorn', rarity: 'U', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Shimmerwing Chimera', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Shoal Kraken', rarity: 'U', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Sleep of the Dead', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Starlit Mantle', rarity: 'C', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Stern Dismissal', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Stinging Lionfish', rarity: 'U', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Sweet Oblivion', rarity: 'U', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Thassa, Deep-Dwelling', rarity: 'M', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Thassa\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Thassa\'s Oracle', rarity: 'R', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Thirst for Meaning', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Threnody Singer', rarity: 'U', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Thryx, the Sudden Storm', rarity: 'R', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Towering-Wave Mystic', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Triton Waverider', rarity: 'C', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Vexing Gull', rarity: 'C', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Wavebreak Hippocamp', rarity: 'R', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Whirlwind Denial', rarity: 'U', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Witness of Tomorrows', rarity: 'C', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Agonizing Remorse', rarity: 'U', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Aphemia, the Cacophony', rarity: 'R', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Aspect of Lamprey', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Blight-Breath Catoblepas', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Cling to Dust', rarity: 'U', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Discordant Piper', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Drag to the Underworld', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Eat to Extinction', rarity: 'R', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Elspeth\'s Nightmare', rarity: 'U', layout: 'saga' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Enemy of Enlightenment', rarity: 'U', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Erebos, Bleak-Hearted', rarity: 'M', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Erebos\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Final Death', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Fruit of Tizerus', rarity: 'C', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Funeral Rites', rarity: 'C', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Gravebreaker Lamia', rarity: 'R', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Gray Merchant of Asphodel', rarity: 'U', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Grim Physician', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Hateful Eidolon', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Inevitable End', rarity: 'U', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Lampad of Death\'s Vigil', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Minion\'s Return', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Mire Triton', rarity: 'U', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Mire\'s Grasp', rarity: 'C', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Mogis\'s Favor', rarity: 'C', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Nightmare Shepherd', rarity: 'R', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Nyxborn Marauder', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Omen of the Dead', rarity: 'C', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Pharika\'s Libation', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Pharika\'s Spawn', rarity: 'U', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Rage-Scarred Berserker', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Scavenging Harpy', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Soulreaper of Mogis', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Temple Thief', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Treacherous Blessing', rarity: 'R', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Tymaret Calls the Dead', rarity: 'R', layout: 'saga' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Tymaret, Chosen from Death', rarity: 'U', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Underworld Charger', rarity: 'C', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Underworld Dreams', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Venomous Hierophant', rarity: 'C', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Woe Strider', rarity: 'R', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'The Akroan War', rarity: 'R', layout: 'saga' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Anax, Hardened in the Forge', rarity: 'U', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Arena Trickster', rarity: 'C', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Aspect of Manticore', rarity: 'C', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Blood Aspirant', rarity: 'U', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Careless Celebrant', rarity: 'U', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Dreamshaper Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Dreamstalker Manticore', rarity: 'U', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Escape Velocity', rarity: 'U', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Fateful End', rarity: 'U', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Final Flare', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Flummoxed Cyclops', rarity: 'C', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Furious Rise', rarity: 'U', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Hero of the Games', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Heroes of the Revel', rarity: 'U', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Impending Doom', rarity: 'U', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Incendiary Oracle', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Infuriate', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Iroas\'s Blessing', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Irreverent Revelers', rarity: 'C', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Nyxborn Brute', rarity: 'C', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Omen of the Forge', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Oread of Mountain\'s Blaze', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Ox of Agonas', rarity: 'M', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Phoenix of Ash', rarity: 'R', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Portent of Betrayal', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Purphoros, Bronze-Blooded', rarity: 'M', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Purphoros\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Satyr\'s Cunning', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Skophos Maze-Warden', rarity: 'U', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Skophos Warleader', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Stampede Rider', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Storm Herald', rarity: 'R', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Storm\'s Wrath', rarity: 'R', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Tectonic Giant', rarity: 'R', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Thrill of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'The Triumph of Anax', rarity: 'U', layout: 'saga' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Underworld Breach', rarity: 'R', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Underworld Fires', rarity: 'U', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Underworld Rage-Hound', rarity: 'C', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Wrap in Flames', rarity: 'C', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Arasta of the Endless Web', rarity: 'R', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'The Binding of the Titans', rarity: 'U', layout: 'saga' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Chainweb Aracnir', rarity: 'U', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Destiny Spinner', rarity: 'U', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Dryad of the Ilysian Grove', rarity: 'R', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'The First Iroan Games', rarity: 'R', layout: 'saga' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Gift of Strength', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Hydra\'s Growth', rarity: 'U', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Hyrax Tower Scout', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Ilysian Caryatid', rarity: 'C', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Inspire Awe', rarity: 'C', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Klothys\'s Design', rarity: 'U', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Loathsome Chimera', rarity: 'C', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Mantle of the Wolf', rarity: 'R', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Moss Viper', rarity: 'C', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Mystic Repeal', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Nessian Boar', rarity: 'R', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Nessian Hornbeetle', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Nessian Wanderer', rarity: 'U', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Nexus Wardens', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Nylea, Keen-Eyed', rarity: 'M', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Nylea\'s Forerunner', rarity: 'C', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Nylea\'s Huntmaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Nylea\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Nyx Herald', rarity: 'U', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Nyxbloom Ancient', rarity: 'M', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Nyxborn Colossus', rarity: 'C', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Omen of the Hunt', rarity: 'C', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Pheres-Band Brawler', rarity: 'U', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Plummet', rarity: 'C', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Relentless Pursuit', rarity: 'C', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Renata, Called to the Hunt', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Return to Nature', rarity: 'C', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Setessan Champion', rarity: 'R', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Setessan Petitioner', rarity: 'U', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Setessan Skirmisher', rarity: 'C', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Setessan Training', rarity: 'C', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Skola Grovedancer', rarity: 'C', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Voracious Typhon', rarity: 'C', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Warbriar Blessing', rarity: 'C', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Wolfwillow Haven', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Acolyte of Affliction', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Allure of the Unknown', rarity: 'R', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Ashiok, Nightmare Muse', rarity: 'M', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Atris, Oracle of Half-Truths', rarity: 'R', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Bronzehide Lion', rarity: 'R', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Calix, Destiny\'s Hand', rarity: 'M', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Dalakos, Crafter of Wonders', rarity: 'R', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Devourer of Memory', rarity: 'U', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Dream Trawler', rarity: 'R', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Enigmatic Incarnation', rarity: 'R', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Eutropia the Twice-Favored', rarity: 'U', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Gallia of the Endless Dance', rarity: 'R', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Haktos the Unscarred', rarity: 'R', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Hero of the Nyxborn', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Klothys, God of Destiny', rarity: 'M', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Kroxa, Titan of Death\'s Hunger', rarity: 'M', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Kunoros, Hound of Athreos', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Mischievous Chimera', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Polukranos, Unchained', rarity: 'M', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Rise to Glory', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Siona, Captain of the Pyleas', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Slaughter-Priest of Mogis', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Staggering Insight', rarity: 'U', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Uro, Titan of Nature\'s Wrath', rarity: 'M', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Warden of the Chained', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Altar of the Pantheon', rarity: 'C', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Bronze Sword', rarity: 'C', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Entrancing Lyre', rarity: 'U', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Mirror Shield', rarity: 'U', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Nyx Lotus', rarity: 'R', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Shadowspear', rarity: 'R', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Soul-Guide Lantern', rarity: 'U', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Thaumaturge\'s Familiar', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Thundering Chariot', rarity: 'U', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Traveler\'s Amulet', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Wings of Hubris', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Field of Ruin', rarity: 'U', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Labyrinth of Skophos', rarity: 'R', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Temple of Abandon', rarity: 'R', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Temple of Deceit', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Temple of Enlightenment', rarity: 'R', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Temple of Malice', rarity: 'R', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Temple of Plenty', rarity: 'R', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Unknown Shores', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Elspeth, Sun\'s Nemesis', rarity: 'M', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Ashiok, Nightmare Muse', rarity: 'M', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Calix, Destiny\'s Hand', rarity: 'M', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Daxos, Blessed by the Sun', rarity: 'U', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Heliod, Sun-Crowned', rarity: 'M', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Callaphe, Beloved of the Sea', rarity: 'U', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Thassa, Deep-Dwelling', rarity: 'M', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Erebos, Bleak-Hearted', rarity: 'M', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Tymaret, Chosen from Death', rarity: 'U', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Anax, Hardened in the Forge', rarity: 'U', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Purphoros, Bronze-Blooded', rarity: 'M', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Nylea, Keen-Eyed', rarity: 'M', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Renata, Called to the Hunt', rarity: 'U', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Klothys, God of Destiny', rarity: 'M', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Athreos, Shroud-Veiled', rarity: 'M', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Elspeth, Undaunted Hero', rarity: 'M', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Eidolon of Inspiration', rarity: 'U', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Elspeth\'s Devotee', rarity: 'R', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Sunlit Hoplite', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Ashiok, Sculptor of Fears', rarity: 'M', layout: 'normal' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Swimmer in Nightmares', rarity: 'U', layout: 'normal' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Mindwrack Harpy', rarity: 'C', layout: 'normal' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Ashiok\'s Forerunner', rarity: 'R', layout: 'normal' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 288, cardSet: cardSetId, name: 'Grasping Giant', rarity: 'R', layout: 'normal' },
            { cardNumber: 289, cardSet: cardSetId, name: 'Victory\'s Envoy', rarity: 'R', layout: 'normal' },
            { cardNumber: 290, cardSet: cardSetId, name: 'Sphinx Mindbreaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 291, cardSet: cardSetId, name: 'Serpent of Yawning Depths', rarity: 'R', layout: 'normal' },
            { cardNumber: 292, cardSet: cardSetId, name: 'Demon of Loathing', rarity: 'R', layout: 'normal' },
            { cardNumber: 293, cardSet: cardSetId, name: 'Underworld Sentinel', rarity: 'R', layout: 'normal' },
            { cardNumber: 294, cardSet: cardSetId, name: 'Deathbellow War Cry', rarity: 'R', layout: 'normal' },
            { cardNumber: 295, cardSet: cardSetId, name: 'Terror of Mount Velus', rarity: 'R', layout: 'normal' },
            { cardNumber: 296, cardSet: cardSetId, name: 'Ironscale Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 297, cardSet: cardSetId, name: 'Treeshaker Chimera', rarity: 'R', layout: 'normal' },
            { cardNumber: 298, cardSet: cardSetId, name: 'Archon of Sun\'s Grace', rarity: 'R', layout: 'normal' },
            { cardNumber: 299, cardSet: cardSetId, name: 'Eidolon of Obstruction', rarity: 'R', layout: 'normal' },
            { cardNumber: 300, cardSet: cardSetId, name: 'Heliod\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 301, cardSet: cardSetId, name: 'Idyllic Tutor', rarity: 'R', layout: 'normal' },
            { cardNumber: 302, cardSet: cardSetId, name: 'Shatter the Sky', rarity: 'R', layout: 'normal' },
            { cardNumber: 303, cardSet: cardSetId, name: 'Taranika, Akroan Veteran', rarity: 'R', layout: 'normal' },
            { cardNumber: 304, cardSet: cardSetId, name: 'Ashiok\'s Erasure', rarity: 'R', layout: 'normal' },
            { cardNumber: 305, cardSet: cardSetId, name: 'Nadir Kraken', rarity: 'R', layout: 'normal' },
            { cardNumber: 306, cardSet: cardSetId, name: 'Protean Thaumaturge', rarity: 'R', layout: 'normal' },
            { cardNumber: 307, cardSet: cardSetId, name: 'Thassa\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 308, cardSet: cardSetId, name: 'Thassa\'s Oracle', rarity: 'R', layout: 'normal' },
            { cardNumber: 309, cardSet: cardSetId, name: 'Thryx, the Sudden Storm', rarity: 'R', layout: 'normal' },
            { cardNumber: 310, cardSet: cardSetId, name: 'Wavebreak Hippocamp', rarity: 'R', layout: 'normal' },
            { cardNumber: 311, cardSet: cardSetId, name: 'Aphemia, the Cacophony', rarity: 'R', layout: 'normal' },
            { cardNumber: 312, cardSet: cardSetId, name: 'Eat to Extinction', rarity: 'R', layout: 'normal' },
            { cardNumber: 313, cardSet: cardSetId, name: 'Erebos\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 314, cardSet: cardSetId, name: 'Gravebreaker Lamia', rarity: 'R', layout: 'normal' },
            { cardNumber: 315, cardSet: cardSetId, name: 'Nightmare Shepherd', rarity: 'R', layout: 'normal' },
            { cardNumber: 316, cardSet: cardSetId, name: 'Treacherous Blessing', rarity: 'R', layout: 'normal' },
            { cardNumber: 317, cardSet: cardSetId, name: 'Woe Strider', rarity: 'R', layout: 'normal' },
            { cardNumber: 318, cardSet: cardSetId, name: 'Ox of Agonas', rarity: 'M', layout: 'normal' },
            { cardNumber: 319, cardSet: cardSetId, name: 'Phoenix of Ash', rarity: 'R', layout: 'normal' },
            { cardNumber: 320, cardSet: cardSetId, name: 'Purphoros\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 321, cardSet: cardSetId, name: 'Storm Herald', rarity: 'R', layout: 'normal' },
            { cardNumber: 322, cardSet: cardSetId, name: 'Storm\'s Wrath', rarity: 'R', layout: 'normal' },
            { cardNumber: 323, cardSet: cardSetId, name: 'Tectonic Giant', rarity: 'R', layout: 'normal' },
            { cardNumber: 324, cardSet: cardSetId, name: 'Underworld Breach', rarity: 'R', layout: 'normal' },
            { cardNumber: 325, cardSet: cardSetId, name: 'Arasta of the Endless Web', rarity: 'R', layout: 'normal' },
            { cardNumber: 326, cardSet: cardSetId, name: 'Dryad of the Ilysian Grove', rarity: 'R', layout: 'normal' },
            { cardNumber: 327, cardSet: cardSetId, name: 'Mantle of the Wolf', rarity: 'R', layout: 'normal' },
            { cardNumber: 328, cardSet: cardSetId, name: 'Nessian Boar', rarity: 'R', layout: 'normal' },
            { cardNumber: 329, cardSet: cardSetId, name: 'Nylea\'s Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 330, cardSet: cardSetId, name: 'Nyxbloom Ancient', rarity: 'M', layout: 'normal' },
            { cardNumber: 331, cardSet: cardSetId, name: 'Setessan Champion', rarity: 'R', layout: 'normal' },
            { cardNumber: 332, cardSet: cardSetId, name: 'Allure of the Unknown', rarity: 'R', layout: 'normal' },
            { cardNumber: 333, cardSet: cardSetId, name: 'Atris, Oracle of Half-Truths', rarity: 'R', layout: 'normal' },
            { cardNumber: 334, cardSet: cardSetId, name: 'Bronzehide Lion', rarity: 'R', layout: 'normal' },
            { cardNumber: 335, cardSet: cardSetId, name: 'Dalakos, Crafter of Wonders', rarity: 'R', layout: 'normal' },
            { cardNumber: 336, cardSet: cardSetId, name: 'Dream Trawler', rarity: 'R', layout: 'normal' },
            { cardNumber: 337, cardSet: cardSetId, name: 'Enigmatic Incarnation', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, cardSet: cardSetId, name: 'Gallia of the Endless Dance', rarity: 'R', layout: 'normal' },
            { cardNumber: 339, cardSet: cardSetId, name: 'Haktos the Unscarred', rarity: 'R', layout: 'normal' },
            { cardNumber: 340, cardSet: cardSetId, name: 'Kroxa, Titan of Death\'s Hunger', rarity: 'M', layout: 'normal' },
            { cardNumber: 341, cardSet: cardSetId, name: 'Kunoros, Hound of Athreos', rarity: 'R', layout: 'normal' },
            { cardNumber: 342, cardSet: cardSetId, name: 'Polukranos, Unchained', rarity: 'M', layout: 'normal' },
            { cardNumber: 343, cardSet: cardSetId, name: 'Uro, Titan of Nature\'s Wrath', rarity: 'M', layout: 'normal' },
            { cardNumber: 344, cardSet: cardSetId, name: 'Nyx Lotus', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, cardSet: cardSetId, name: 'Shadowspear', rarity: 'R', layout: 'normal' },
            { cardNumber: 346, cardSet: cardSetId, name: 'Labyrinth of Skophos', rarity: 'R', layout: 'normal' },
            { cardNumber: 347, cardSet: cardSetId, name: 'Temple of Abandon', rarity: 'R', layout: 'normal' },
            { cardNumber: 348, cardSet: cardSetId, name: 'Temple of Deceit', rarity: 'R', layout: 'normal' },
            { cardNumber: 349, cardSet: cardSetId, name: 'Temple of Enlightenment', rarity: 'R', layout: 'normal' },
            { cardNumber: 350, cardSet: cardSetId, name: 'Temple of Malice', rarity: 'R', layout: 'normal' },
            { cardNumber: 351, cardSet: cardSetId, name: 'Temple of Plenty', rarity: 'R', layout: 'normal' },
            { cardNumber: 352, cardSet: cardSetId, name: 'Arasta of the Endless Web', rarity: 'R', layout: 'normal' },
            { cardNumber: 353, cardSet: cardSetId, name: 'Alseid of Life\'s Bounty', rarity: 'U', layout: 'normal' },
            { cardNumber: 354, cardSet: cardSetId, name: 'Thirst for Meaning', rarity: 'C', layout: 'normal' },
            { cardNumber: 355, cardSet: cardSetId, name: 'Gray Merchant of Asphodel', rarity: 'U', layout: 'normal' },
            { cardNumber: 356, cardSet: cardSetId, name: 'Thrill of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 357, cardSet: cardSetId, name: 'Wolfwillow Haven', rarity: 'U', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'THB';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
