import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingEld1620400747690 implements MigrationInterface {
    name = 'addingEld1620400747690';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Throne of Eldraine', shortName: 'ELD' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Acclaimed Contender', rarity: 'R', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'All That Glitters', rarity: 'U', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Archon of Absolution', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Ardenvale Paladin', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Ardenvale Tactician', rarity: 'C', layout: 'adventure' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Bartered Cow', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Beloved Princess', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Charming Prince', rarity: 'R', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'The Circle of Loyalty', rarity: 'M', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Deafening Silence', rarity: 'U', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Faerie Guidemother', rarity: 'C', layout: 'adventure' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Flutterfox', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Fortifying Provisions', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Giant Killer', rarity: 'R', layout: 'adventure' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Glass Casket', rarity: 'U', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Happily Ever After', rarity: 'R', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Harmonious Archon', rarity: 'M', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Hushbringer', rarity: 'R', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Knight of the Keep', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Linden, the Steadfast Queen', rarity: 'R', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Lonesome Unicorn', rarity: 'C', layout: 'adventure' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Mysterious Pathlighter', rarity: 'U', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Outflank', rarity: 'C', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Prized Griffin', rarity: 'C', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Rally for the Throne', rarity: 'U', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Realm-Cloaked Giant', rarity: 'M', layout: 'adventure' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Righteousness', rarity: 'U', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Shepherd of the Flock', rarity: 'U', layout: 'adventure' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Shining Armor', rarity: 'C', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Silverflame Ritual', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Silverflame Squire', rarity: 'C', layout: 'adventure' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Syr Alin, the Lion\'s Claw', rarity: 'U', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Trapped in the Tower', rarity: 'C', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'True Love\'s Kiss', rarity: 'C', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Venerable Knight', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Worthy Knight', rarity: 'R', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Youthful Knight', rarity: 'C', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Animating Faerie', rarity: 'U', layout: 'adventure' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Brazen Borrower', rarity: 'M', layout: 'adventure' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Charmed Sleep', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Corridor Monitor', rarity: 'C', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Didn\'t Say Please', rarity: 'C', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Emry, Lurker of the Loch', rarity: 'R', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Fae of Wishes', rarity: 'R', layout: 'adventure' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Faerie Vandal', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Folio of Fancies', rarity: 'R', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Frogify', rarity: 'U', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Gadwick, the Wizened', rarity: 'R', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Hypnotic Sprite', rarity: 'U', layout: 'adventure' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Into the Story', rarity: 'U', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'The Magic Mirror', rarity: 'M', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Mantle of Tides', rarity: 'C', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Merfolk Secretkeeper', rarity: 'C', layout: 'adventure' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Midnight Clock', rarity: 'R', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Mirrormade', rarity: 'R', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Mistford River Turtle', rarity: 'C', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Moonlit Scavengers', rarity: 'C', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Mystical Dispute', rarity: 'U', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Opt', rarity: 'C', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Overwhelmed Apprentice', rarity: 'U', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Queen of Ice', rarity: 'C', layout: 'adventure' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Run Away Together', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Sage of the Falls', rarity: 'U', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'So Tiny', rarity: 'C', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Steelgaze Griffin', rarity: 'C', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Stolen by the Fae', rarity: 'R', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Syr Elenora, the Discerning', rarity: 'U', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Tome Raider', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Turn into a Pumpkin', rarity: 'U', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Unexplained Vision', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Vantress Gargoyle', rarity: 'R', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Vantress Paladin', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Wishful Merfolk', rarity: 'C', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Witching Well', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Ayara, First of Locthwain', rarity: 'R', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Bake into a Pie', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Barrow Witches', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Belle of the Brawl', rarity: 'U', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Blacklance Paragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Bog Naughty', rarity: 'U', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Cauldron Familiar', rarity: 'U', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'The Cauldron of Eternity', rarity: 'M', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Cauldron\'s Gift', rarity: 'U', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Clackbridge Troll', rarity: 'R', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Epic Downfall', rarity: 'U', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Eye Collector', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Festive Funeral', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Foreboding Fruit', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Forever Young', rarity: 'C', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Foulmire Knight', rarity: 'U', layout: 'adventure' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Giant\'s Skewer', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Lash of Thorns', rarity: 'C', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Locthwain Paladin', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Lost Legion', rarity: 'C', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Malevolent Noble', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Memory Theft', rarity: 'C', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Murderous Rider', rarity: 'R', layout: 'adventure' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Oathsworn Knight', rarity: 'R', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Order of Midnight', rarity: 'U', layout: 'adventure' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Piper of the Swarm', rarity: 'R', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Rankle, Master of Pranks', rarity: 'M', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Reaper of Night', rarity: 'C', layout: 'adventure' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Reave Soul', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Revenge of Ravens', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Smitten Swordmaster', rarity: 'C', layout: 'adventure' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Specter\'s Shriek', rarity: 'U', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Syr Konrad, the Grim', rarity: 'U', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Tempting Witch', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Wicked Guardian', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Wishclaw Talisman', rarity: 'R', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Witch\'s Vengeance', rarity: 'R', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Barge In', rarity: 'C', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Bloodhaze Wolverine', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Blow Your House Down', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Bonecrusher Giant', rarity: 'R', layout: 'adventure' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Brimstone Trebuchet', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Burning-Yard Trainer', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Claim the Firstborn', rarity: 'U', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Crystal Slipper', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Embercleave', rarity: 'M', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Embereth Paladin', rarity: 'C', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Embereth Shieldbreaker', rarity: 'U', layout: 'adventure' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Ferocity of the Wilds', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Fervent Champion', rarity: 'R', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Fires of Invention', rarity: 'R', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Fling', rarity: 'C', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Irencrag Feat', rarity: 'R', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Irencrag Pyromancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Joust', rarity: 'U', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Mad Ratter', rarity: 'U', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Merchant of the Vale', rarity: 'C', layout: 'adventure' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Ogre Errant', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Opportunistic Dragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Raging Redcap', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Redcap Melee', rarity: 'U', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Redcap Raiders', rarity: 'C', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Rimrock Knight', rarity: 'C', layout: 'adventure' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Robber of the Rich', rarity: 'M', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Scorching Dragonfire', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Searing Barrage', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Seven Dwarves', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Skullknocker Ogre', rarity: 'U', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Slaying Fire', rarity: 'U', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Sundering Stroke', rarity: 'R', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Syr Carah, the Bold', rarity: 'U', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Thrill of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Torbran, Thane of Red Fell', rarity: 'R', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Weaselback Redcap', rarity: 'C', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Beanstalk Giant', rarity: 'U', layout: 'adventure' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Curious Pair', rarity: 'C', layout: 'adventure' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Edgewall Innkeeper', rarity: 'U', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Feasting Troll King', rarity: 'R', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Fell the Pheasant', rarity: 'C', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Fierce Witchstalker', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Flaxen Intruder', rarity: 'U', layout: 'adventure' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Garenbrig Carver', rarity: 'C', layout: 'adventure' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Garenbrig Paladin', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Garenbrig Squire', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Giant Opportunity', rarity: 'U', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Gilded Goose', rarity: 'R', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'The Great Henge', rarity: 'M', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Insatiable Appetite', rarity: 'C', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Keeper of Fables', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Kenrith\'s Transformation', rarity: 'U', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Lovestruck Beast', rarity: 'R', layout: 'adventure' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Maraleaf Rider', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Oakhame Adversary', rarity: 'U', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Once and Future', rarity: 'U', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Once Upon a Time', rarity: 'R', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Outmuscle', rarity: 'C', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Questing Beast', rarity: 'M', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Return of the Wildspeaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Return to Nature', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Rosethorn Acolyte', rarity: 'C', layout: 'adventure' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Rosethorn Halberd', rarity: 'C', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Sporecap Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Syr Faren, the Hengehammer', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Tall as a Beanstalk', rarity: 'C', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Trail of Crumbs', rarity: 'U', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Tuinvale Treefolk', rarity: 'C', layout: 'adventure' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Wicked Wolf', rarity: 'R', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Wildborn Preserver', rarity: 'R', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Wildwood Tracker', rarity: 'C', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Wolf\'s Quarry', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Yorvo, Lord of Garenbrig', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Dance of the Manse', rarity: 'R', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Doom Foretold', rarity: 'R', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Drown in the Loch', rarity: 'U', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Escape to the Wilds', rarity: 'R', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Faeburrow Elder', rarity: 'R', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Garruk, Cursed Huntsman', rarity: 'M', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Grumgully, the Generous', rarity: 'U', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Improbable Alliance', rarity: 'U', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Inspiring Veteran', rarity: 'U', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Lochmere Serpent', rarity: 'R', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Maraleaf Pixie', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Oko, Thief of Crowns', rarity: 'M', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Outlaws\' Merriment', rarity: 'M', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'The Royal Scions', rarity: 'M', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Savvy Hunter', rarity: 'U', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Shinechaser', rarity: 'U', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Steelclaw Lance', rarity: 'U', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Stormfist Crusader', rarity: 'R', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Wandermare', rarity: 'U', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Wintermoor Commander', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Arcanist\'s Owl', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Covetous Urge', rarity: 'U', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Deathless Knight', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Elite Headhunter', rarity: 'U', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Fireborn Knight', rarity: 'U', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Loch Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Oakhame Ranger', rarity: 'U', layout: 'adventure' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Rampart Smasher', rarity: 'U', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Resolute Rider', rarity: 'U', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Thunderous Snapper', rarity: 'U', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Clockwork Servant', rarity: 'U', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Crashing Drawbridge', rarity: 'C', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Enchanted Carriage', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Gingerbrute', rarity: 'C', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Golden Egg', rarity: 'C', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Henge Walker', rarity: 'C', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Heraldic Banner', rarity: 'U', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Inquisitive Puppet', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Jousting Dummy', rarity: 'C', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Locthwain Gargoyle', rarity: 'C', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Lucky Clover', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Prophet of the Peak', rarity: 'C', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Roving Keep', rarity: 'C', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Scalding Cauldron', rarity: 'C', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Shambling Suit', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Signpost Scarecrow', rarity: 'C', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Sorcerer\'s Broom', rarity: 'U', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Sorcerous Spyglass', rarity: 'R', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Spinning Wheel', rarity: 'U', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Stonecoil Serpent', rarity: 'R', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Weapon Rack', rarity: 'C', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Witch\'s Oven', rarity: 'U', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Castle Ardenvale', rarity: 'R', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Castle Embereth', rarity: 'R', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Castle Garenbrig', rarity: 'R', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Castle Locthwain', rarity: 'R', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Castle Vantress', rarity: 'R', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Dwarven Mine', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Fabled Passage', rarity: 'R', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Gingerbread Cabin', rarity: 'C', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Idyllic Grange', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Mystic Sanctuary', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Tournament Grounds', rarity: 'U', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Witch\'s Cottage', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Garruk, Cursed Huntsman', rarity: 'M', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Oko, Thief of Crowns', rarity: 'M', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'The Royal Scions', rarity: 'M', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Ardenvale Tactician', rarity: 'C', layout: 'adventure' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Faerie Guidemother', rarity: 'C', layout: 'adventure' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Giant Killer', rarity: 'R', layout: 'adventure' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Lonesome Unicorn', rarity: 'C', layout: 'adventure' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Realm-Cloaked Giant', rarity: 'M', layout: 'adventure' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Shepherd of the Flock', rarity: 'U', layout: 'adventure' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Silverflame Squire', rarity: 'C', layout: 'adventure' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Animating Faerie', rarity: 'U', layout: 'adventure' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Brazen Borrower', rarity: 'M', layout: 'adventure' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Fae of Wishes', rarity: 'R', layout: 'adventure' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Hypnotic Sprite', rarity: 'U', layout: 'adventure' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Merfolk Secretkeeper', rarity: 'C', layout: 'adventure' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Queen of Ice', rarity: 'C', layout: 'adventure' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Foulmire Knight', rarity: 'U', layout: 'adventure' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Murderous Rider', rarity: 'R', layout: 'adventure' },
            { cardNumber: 288, cardSet: cardSetId, name: 'Order of Midnight', rarity: 'U', layout: 'adventure' },
            { cardNumber: 289, cardSet: cardSetId, name: 'Reaper of Night', rarity: 'C', layout: 'adventure' },
            { cardNumber: 290, cardSet: cardSetId, name: 'Smitten Swordmaster', rarity: 'C', layout: 'adventure' },
            { cardNumber: 291, cardSet: cardSetId, name: 'Bonecrusher Giant', rarity: 'R', layout: 'adventure' },
            { cardNumber: 292, cardSet: cardSetId, name: 'Embereth Shieldbreaker', rarity: 'U', layout: 'adventure' },
            { cardNumber: 293, cardSet: cardSetId, name: 'Merchant of the Vale', rarity: 'C', layout: 'adventure' },
            { cardNumber: 294, cardSet: cardSetId, name: 'Rimrock Knight', rarity: 'C', layout: 'adventure' },
            { cardNumber: 295, cardSet: cardSetId, name: 'Beanstalk Giant', rarity: 'U', layout: 'adventure' },
            { cardNumber: 296, cardSet: cardSetId, name: 'Curious Pair', rarity: 'C', layout: 'adventure' },
            { cardNumber: 297, cardSet: cardSetId, name: 'Flaxen Intruder', rarity: 'U', layout: 'adventure' },
            { cardNumber: 298, cardSet: cardSetId, name: 'Garenbrig Carver', rarity: 'C', layout: 'adventure' },
            { cardNumber: 299, cardSet: cardSetId, name: 'Lovestruck Beast', rarity: 'R', layout: 'adventure' },
            { cardNumber: 300, cardSet: cardSetId, name: 'Rosethorn Acolyte', rarity: 'C', layout: 'adventure' },
            { cardNumber: 301, cardSet: cardSetId, name: 'Tuinvale Treefolk', rarity: 'C', layout: 'adventure' },
            { cardNumber: 302, cardSet: cardSetId, name: 'Oakhame Ranger', rarity: 'U', layout: 'adventure' },
            { cardNumber: 303, cardSet: cardSetId, name: 'Kenrith, the Returned King', rarity: 'M', layout: 'normal' },
            { cardNumber: 304, cardSet: cardSetId, name: 'Rowan, Fearless Sparkmage', rarity: 'M', layout: 'normal' },
            { cardNumber: 305, cardSet: cardSetId, name: 'Garrison Griffin', rarity: 'C', layout: 'normal' },
            { cardNumber: 306, cardSet: cardSetId, name: 'Rowan\'s Battleguard', rarity: 'U', layout: 'normal' },
            { cardNumber: 307, cardSet: cardSetId, name: 'Rowan\'s Stalwarts', rarity: 'R', layout: 'normal' },
            { cardNumber: 308, cardSet: cardSetId, name: 'Wind-Scarred Crag', rarity: 'C', layout: 'normal' },
            { cardNumber: 309, cardSet: cardSetId, name: 'Oko, the Trickster', rarity: 'M', layout: 'normal' },
            { cardNumber: 310, cardSet: cardSetId, name: 'Oko\'s Accomplices', rarity: 'C', layout: 'normal' },
            { cardNumber: 311, cardSet: cardSetId, name: 'Bramblefort Fink', rarity: 'U', layout: 'normal' },
            { cardNumber: 312, cardSet: cardSetId, name: 'Oko\'s Hospitality', rarity: 'R', layout: 'normal' },
            { cardNumber: 313, cardSet: cardSetId, name: 'Thornwood Falls', rarity: 'C', layout: 'normal' },
            { cardNumber: 314, cardSet: cardSetId, name: 'Mace of the Valiant', rarity: 'R', layout: 'normal' },
            { cardNumber: 315, cardSet: cardSetId, name: 'Silverwing Squadron', rarity: 'R', layout: 'normal' },
            { cardNumber: 316, cardSet: cardSetId, name: 'Faerie Formation', rarity: 'R', layout: 'normal' },
            { cardNumber: 317, cardSet: cardSetId, name: 'Shimmer Dragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 318, cardSet: cardSetId, name: 'Workshop Elders', rarity: 'R', layout: 'normal' },
            { cardNumber: 319, cardSet: cardSetId, name: 'Chittering Witch', rarity: 'R', layout: 'normal' },
            { cardNumber: 320, cardSet: cardSetId, name: 'Taste of Death', rarity: 'R', layout: 'normal' },
            { cardNumber: 321, cardSet: cardSetId, name: 'Embereth Skyblazer', rarity: 'R', layout: 'normal' },
            { cardNumber: 322, cardSet: cardSetId, name: 'Steelbane Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 323, cardSet: cardSetId, name: 'Thorn Mammoth', rarity: 'R', layout: 'normal' },
            { cardNumber: 324, cardSet: cardSetId, name: 'Alela, Artful Provocateur', rarity: 'M', layout: 'normal' },
            { cardNumber: 325, cardSet: cardSetId, name: 'Banish into Fable', rarity: 'R', layout: 'normal' },
            { cardNumber: 326, cardSet: cardSetId, name: 'Chulane, Teller of Tales', rarity: 'M', layout: 'normal' },
            { cardNumber: 327, cardSet: cardSetId, name: 'Gluttonous Troll', rarity: 'R', layout: 'normal' },
            { cardNumber: 328, cardSet: cardSetId, name: 'Knights\' Charge', rarity: 'R', layout: 'normal' },
            { cardNumber: 329, cardSet: cardSetId, name: 'Korvold, Fae-Cursed King', rarity: 'M', layout: 'normal' },
            { cardNumber: 330, cardSet: cardSetId, name: 'Syr Gwyn, Hero of Ashvale', rarity: 'M', layout: 'normal' },
            { cardNumber: 331, cardSet: cardSetId, name: 'Arcane Signet', rarity: 'C', layout: 'normal' },
            { cardNumber: 332, cardSet: cardSetId, name: 'Tome of Legends', rarity: 'R', layout: 'normal' },
            { cardNumber: 333, cardSet: cardSetId, name: 'Command Tower', rarity: 'C', layout: 'normal' },
            { cardNumber: 334, cardSet: cardSetId, name: 'Acclaimed Contender', rarity: 'R', layout: 'normal' },
            { cardNumber: 335, cardSet: cardSetId, name: 'Charming Prince', rarity: 'R', layout: 'normal' },
            { cardNumber: 336, cardSet: cardSetId, name: 'The Circle of Loyalty', rarity: 'M', layout: 'normal' },
            { cardNumber: 337, cardSet: cardSetId, name: 'Happily Ever After', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, cardSet: cardSetId, name: 'Harmonious Archon', rarity: 'M', layout: 'normal' },
            { cardNumber: 339, cardSet: cardSetId, name: 'Hushbringer', rarity: 'R', layout: 'normal' },
            { cardNumber: 340, cardSet: cardSetId, name: 'Linden, the Steadfast Queen', rarity: 'R', layout: 'normal' },
            { cardNumber: 341, cardSet: cardSetId, name: 'Worthy Knight', rarity: 'R', layout: 'normal' },
            { cardNumber: 342, cardSet: cardSetId, name: 'Emry, Lurker of the Loch', rarity: 'R', layout: 'normal' },
            { cardNumber: 343, cardSet: cardSetId, name: 'Folio of Fancies', rarity: 'R', layout: 'normal' },
            { cardNumber: 344, cardSet: cardSetId, name: 'Gadwick, the Wizened', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, cardSet: cardSetId, name: 'The Magic Mirror', rarity: 'M', layout: 'normal' },
            { cardNumber: 346, cardSet: cardSetId, name: 'Midnight Clock', rarity: 'R', layout: 'normal' },
            { cardNumber: 347, cardSet: cardSetId, name: 'Mirrormade', rarity: 'R', layout: 'normal' },
            { cardNumber: 348, cardSet: cardSetId, name: 'Stolen by the Fae', rarity: 'R', layout: 'normal' },
            { cardNumber: 349, cardSet: cardSetId, name: 'Vantress Gargoyle', rarity: 'R', layout: 'normal' },
            { cardNumber: 350, cardSet: cardSetId, name: 'Ayara, First of Locthwain', rarity: 'R', layout: 'normal' },
            { cardNumber: 351, cardSet: cardSetId, name: 'Blacklance Paragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 352, cardSet: cardSetId, name: 'The Cauldron of Eternity', rarity: 'M', layout: 'normal' },
            { cardNumber: 353, cardSet: cardSetId, name: 'Clackbridge Troll', rarity: 'R', layout: 'normal' },
            { cardNumber: 354, cardSet: cardSetId, name: 'Oathsworn Knight', rarity: 'R', layout: 'normal' },
            { cardNumber: 355, cardSet: cardSetId, name: 'Piper of the Swarm', rarity: 'R', layout: 'normal' },
            { cardNumber: 356, cardSet: cardSetId, name: 'Rankle, Master of Pranks', rarity: 'M', layout: 'normal' },
            { cardNumber: 357, cardSet: cardSetId, name: 'Wishclaw Talisman', rarity: 'R', layout: 'normal' },
            { cardNumber: 358, cardSet: cardSetId, name: 'Witch\'s Vengeance', rarity: 'R', layout: 'normal' },
            { cardNumber: 359, cardSet: cardSetId, name: 'Embercleave', rarity: 'M', layout: 'normal' },
            { cardNumber: 360, cardSet: cardSetId, name: 'Fervent Champion', rarity: 'R', layout: 'normal' },
            { cardNumber: 361, cardSet: cardSetId, name: 'Fires of Invention', rarity: 'R', layout: 'normal' },
            { cardNumber: 362, cardSet: cardSetId, name: 'Irencrag Feat', rarity: 'R', layout: 'normal' },
            { cardNumber: 363, cardSet: cardSetId, name: 'Irencrag Pyromancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 364, cardSet: cardSetId, name: 'Opportunistic Dragon', rarity: 'R', layout: 'normal' },
            { cardNumber: 365, cardSet: cardSetId, name: 'Robber of the Rich', rarity: 'M', layout: 'normal' },
            { cardNumber: 366, cardSet: cardSetId, name: 'Sundering Stroke', rarity: 'R', layout: 'normal' },
            { cardNumber: 367, cardSet: cardSetId, name: 'Torbran, Thane of Red Fell', rarity: 'R', layout: 'normal' },
            { cardNumber: 368, cardSet: cardSetId, name: 'Feasting Troll King', rarity: 'R', layout: 'normal' },
            { cardNumber: 369, cardSet: cardSetId, name: 'Gilded Goose', rarity: 'R', layout: 'normal' },
            { cardNumber: 370, cardSet: cardSetId, name: 'The Great Henge', rarity: 'M', layout: 'normal' },
            { cardNumber: 371, cardSet: cardSetId, name: 'Once Upon a Time', rarity: 'R', layout: 'normal' },
            { cardNumber: 372, cardSet: cardSetId, name: 'Questing Beast', rarity: 'M', layout: 'normal' },
            { cardNumber: 373, cardSet: cardSetId, name: 'Return of the Wildspeaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 374, cardSet: cardSetId, name: 'Wicked Wolf', rarity: 'R', layout: 'normal' },
            { cardNumber: 375, cardSet: cardSetId, name: 'Wildborn Preserver', rarity: 'R', layout: 'normal' },
            { cardNumber: 376, cardSet: cardSetId, name: 'Yorvo, Lord of Garenbrig', rarity: 'R', layout: 'normal' },
            { cardNumber: 377, cardSet: cardSetId, name: 'Dance of the Manse', rarity: 'R', layout: 'normal' },
            { cardNumber: 378, cardSet: cardSetId, name: 'Doom Foretold', rarity: 'R', layout: 'normal' },
            { cardNumber: 379, cardSet: cardSetId, name: 'Escape to the Wilds', rarity: 'R', layout: 'normal' },
            { cardNumber: 380, cardSet: cardSetId, name: 'Faeburrow Elder', rarity: 'R', layout: 'normal' },
            { cardNumber: 381, cardSet: cardSetId, name: 'Lochmere Serpent', rarity: 'R', layout: 'normal' },
            { cardNumber: 382, cardSet: cardSetId, name: 'Outlaws\' Merriment', rarity: 'M', layout: 'normal' },
            { cardNumber: 383, cardSet: cardSetId, name: 'Stormfist Crusader', rarity: 'R', layout: 'normal' },
            { cardNumber: 384, cardSet: cardSetId, name: 'Sorcerous Spyglass', rarity: 'R', layout: 'normal' },
            { cardNumber: 385, cardSet: cardSetId, name: 'Stonecoil Serpent', rarity: 'R', layout: 'normal' },
            { cardNumber: 386, cardSet: cardSetId, name: 'Castle Ardenvale', rarity: 'R', layout: 'normal' },
            { cardNumber: 387, cardSet: cardSetId, name: 'Castle Embereth', rarity: 'R', layout: 'normal' },
            { cardNumber: 388, cardSet: cardSetId, name: 'Castle Garenbrig', rarity: 'R', layout: 'normal' },
            { cardNumber: 389, cardSet: cardSetId, name: 'Castle Locthwain', rarity: 'R', layout: 'normal' },
            { cardNumber: 390, cardSet: cardSetId, name: 'Castle Vantress', rarity: 'R', layout: 'normal' },
            { cardNumber: 391, cardSet: cardSetId, name: 'Fabled Passage', rarity: 'R', layout: 'normal' },
            { cardNumber: 392, cardSet: cardSetId, name: 'Piper of the Swarm', rarity: 'R', layout: 'normal' },
            { cardNumber: 393, cardSet: cardSetId, name: 'Glass Casket', rarity: 'U', layout: 'normal' },
            { cardNumber: 394, cardSet: cardSetId, name: 'Slaying Fire', rarity: 'U', layout: 'normal' },
            { cardNumber: 395, cardSet: cardSetId, name: 'Kenrith\'s Transformation', rarity: 'U', layout: 'normal' },
            { cardNumber: 396, cardSet: cardSetId, name: 'Improbable Alliance', rarity: 'U', layout: 'normal' },
            { cardNumber: 397, cardSet: cardSetId, name: 'Inspiring Veteran', rarity: 'U', layout: 'normal' },
        ]).execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'ELD';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
