import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingGrn1620391083464 implements MigrationInterface {
    name = 'addingGrn1620391083464';

    public async up(queryRunner: QueryRunner): Promise<void> {
    
const insertResult: InsertResult = await queryRunner.manager
.createQueryBuilder()
.insert()
.into('card_set')
.values({ name: 'Guilds of Ravnica', shortName: 'GRN' })
.execute();
const cardSetId: number = insertResult.identifiers[0].id;

await queryRunner.manager.createQueryBuilder().insert().into('card').values([
{ cardNumber: 1, cardSet: cardSetId, name: 'Blade Instructor', rarity: 'C', layout: 'normal'},
{ cardNumber: 2, cardSet: cardSetId, name: 'Bounty Agent', rarity: 'R', layout: 'normal'},
{ cardNumber: 3, cardSet: cardSetId, name: 'Candlelight Vigil', rarity: 'C', layout: 'normal'},
{ cardNumber: 4, cardSet: cardSetId, name: 'Citywide Bust', rarity: 'R', layout: 'normal'},
{ cardNumber: 5, cardSet: cardSetId, name: 'Collar the Culprit', rarity: 'C', layout: 'normal'},
{ cardNumber: 6, cardSet: cardSetId, name: 'Conclave Tribunal', rarity: 'U', layout: 'normal'},
{ cardNumber: 7, cardSet: cardSetId, name: 'Crush Contraband', rarity: 'U', layout: 'normal'},
{ cardNumber: 8, cardSet: cardSetId, name: 'Dawn of Hope', rarity: 'R', layout: 'normal'},
{ cardNumber: 9, cardSet: cardSetId, name: 'Demotion', rarity: 'U', layout: 'normal'},
{ cardNumber: 10, cardSet: cardSetId, name: 'Divine Visitation', rarity: 'M', layout: 'normal'},
{ cardNumber: 11, cardSet: cardSetId, name: 'Flight of Equenauts', rarity: 'U', layout: 'normal'},
{ cardNumber: 12, cardSet: cardSetId, name: 'Gird for Battle', rarity: 'U', layout: 'normal'},
{ cardNumber: 13, cardSet: cardSetId, name: 'Haazda Marshal', rarity: 'U', layout: 'normal'},
{ cardNumber: 14, cardSet: cardSetId, name: 'Healer\'s Hawk', rarity: 'C', layout: 'normal'},
{ cardNumber: 15, cardSet: cardSetId, name: 'Hunted Witness', rarity: 'C', layout: 'normal'},
{ cardNumber: 16, cardSet: cardSetId, name: 'Inspiring Unicorn', rarity: 'U', layout: 'normal'},
{ cardNumber: 17, cardSet: cardSetId, name: 'Intrusive Packbeast', rarity: 'C', layout: 'normal'},
{ cardNumber: 18, cardSet: cardSetId, name: 'Ledev Guardian', rarity: 'C', layout: 'normal'},
{ cardNumber: 19, cardSet: cardSetId, name: 'Light of the Legion', rarity: 'R', layout: 'normal'},
{ cardNumber: 20, cardSet: cardSetId, name: 'Loxodon Restorer', rarity: 'C', layout: 'normal'},
{ cardNumber: 21, cardSet: cardSetId, name: 'Luminous Bonds', rarity: 'C', layout: 'normal'},
{ cardNumber: 22, cardSet: cardSetId, name: 'Parhelion Patrol', rarity: 'C', layout: 'normal'},
{ cardNumber: 23, cardSet: cardSetId, name: 'Righteous Blow', rarity: 'C', layout: 'normal'},
{ cardNumber: 24, cardSet: cardSetId, name: 'Roc Charger', rarity: 'U', layout: 'normal'},
{ cardNumber: 25, cardSet: cardSetId, name: 'Skyline Scout', rarity: 'C', layout: 'normal'},
{ cardNumber: 26, cardSet: cardSetId, name: 'Sunhome Stalwart', rarity: 'U', layout: 'normal'},
{ cardNumber: 27, cardSet: cardSetId, name: 'Sworn Companions', rarity: 'C', layout: 'normal'},
{ cardNumber: 28, cardSet: cardSetId, name: 'Take Heart', rarity: 'C', layout: 'normal'},
{ cardNumber: 29, cardSet: cardSetId, name: 'Tenth District Guard', rarity: 'C', layout: 'normal'},
{ cardNumber: 30, cardSet: cardSetId, name: 'Venerated Loxodon', rarity: 'R', layout: 'normal'},
{ cardNumber: 31, cardSet: cardSetId, name: 'Capture Sphere', rarity: 'C', layout: 'normal'},
{ cardNumber: 32, cardSet: cardSetId, name: 'Chemister\'s Insight', rarity: 'U', layout: 'normal'},
{ cardNumber: 33, cardSet: cardSetId, name: 'Citywatch Sphinx', rarity: 'U', layout: 'normal'},
{ cardNumber: 34, cardSet: cardSetId, name: 'Dazzling Lights', rarity: 'C', layout: 'normal'},
{ cardNumber: 35, cardSet: cardSetId, name: 'Devious Cover-Up', rarity: 'C', layout: 'normal'},
{ cardNumber: 36, cardSet: cardSetId, name: 'Dimir Informant', rarity: 'C', layout: 'normal'},
{ cardNumber: 37, cardSet: cardSetId, name: 'Disdainful Stroke', rarity: 'C', layout: 'normal'},
{ cardNumber: 38, cardSet: cardSetId, name: 'Dream Eater', rarity: 'M', layout: 'normal'},
{ cardNumber: 39, cardSet: cardSetId, name: 'Drowned Secrets', rarity: 'R', layout: 'normal'},
{ cardNumber: 40, cardSet: cardSetId, name: 'Enhanced Surveillance', rarity: 'U', layout: 'normal'},
{ cardNumber: 41, cardSet: cardSetId, name: 'Guild Summit', rarity: 'U', layout: 'normal'},
{ cardNumber: 42, cardSet: cardSetId, name: 'Leapfrog', rarity: 'C', layout: 'normal'},
{ cardNumber: 43, cardSet: cardSetId, name: 'Maximize Altitude', rarity: 'C', layout: 'normal'},
{ cardNumber: 44, cardSet: cardSetId, name: 'Mission Briefing', rarity: 'R', layout: 'normal'},
{ cardNumber: 45, cardSet: cardSetId, name: 'Murmuring Mystic', rarity: 'U', layout: 'normal'},
{ cardNumber: 46, cardSet: cardSetId, name: 'Muse Drake', rarity: 'C', layout: 'normal'},
{ cardNumber: 47, cardSet: cardSetId, name: 'Narcomoeba', rarity: 'R', layout: 'normal'},
{ cardNumber: 48, cardSet: cardSetId, name: 'Nightveil Sprite', rarity: 'U', layout: 'normal'},
{ cardNumber: 49, cardSet: cardSetId, name: 'Omnispell Adept', rarity: 'R', layout: 'normal'},
{ cardNumber: 50, cardSet: cardSetId, name: 'Passwall Adept', rarity: 'C', layout: 'normal'},
{ cardNumber: 51, cardSet: cardSetId, name: 'Quasiduplicate', rarity: 'R', layout: 'normal'},
{ cardNumber: 52, cardSet: cardSetId, name: 'Radical Idea', rarity: 'C', layout: 'normal'},
{ cardNumber: 53, cardSet: cardSetId, name: 'Selective Snare', rarity: 'U', layout: 'normal'},
{ cardNumber: 54, cardSet: cardSetId, name: 'Sinister Sabotage', rarity: 'U', layout: 'normal'},
{ cardNumber: 55, cardSet: cardSetId, name: 'Thoughtbound Phantasm', rarity: 'U', layout: 'normal'},
{ cardNumber: 56, cardSet: cardSetId, name: 'Unexplained Disappearance', rarity: 'C', layout: 'normal'},
{ cardNumber: 57, cardSet: cardSetId, name: 'Vedalken Mesmerist', rarity: 'C', layout: 'normal'},
{ cardNumber: 58, cardSet: cardSetId, name: 'Wall of Mist', rarity: 'C', layout: 'normal'},
{ cardNumber: 59, cardSet: cardSetId, name: 'Watcher in the Mist', rarity: 'C', layout: 'normal'},
{ cardNumber: 60, cardSet: cardSetId, name: 'Wishcoin Crab', rarity: 'C', layout: 'normal'},
{ cardNumber: 61, cardSet: cardSetId, name: 'Barrier of Bones', rarity: 'C', layout: 'normal'},
{ cardNumber: 62, cardSet: cardSetId, name: 'Bartizan Bats', rarity: 'C', layout: 'normal'},
{ cardNumber: 63, cardSet: cardSetId, name: 'Blood Operative', rarity: 'R', layout: 'normal'},
{ cardNumber: 64, cardSet: cardSetId, name: 'Burglar Rat', rarity: 'C', layout: 'normal'},
{ cardNumber: 65, cardSet: cardSetId, name: 'Child of Night', rarity: 'C', layout: 'normal'},
{ cardNumber: 66, cardSet: cardSetId, name: 'Creeping Chill', rarity: 'U', layout: 'normal'},
{ cardNumber: 67, cardSet: cardSetId, name: 'Dead Weight', rarity: 'C', layout: 'normal'},
{ cardNumber: 68, cardSet: cardSetId, name: 'Deadly Visit', rarity: 'C', layout: 'normal'},
{ cardNumber: 69, cardSet: cardSetId, name: 'Doom Whisperer', rarity: 'M', layout: 'normal'},
{ cardNumber: 70, cardSet: cardSetId, name: 'Douser of Lights', rarity: 'C', layout: 'normal'},
{ cardNumber: 71, cardSet: cardSetId, name: 'Gruesome Menagerie', rarity: 'R', layout: 'normal'},
{ cardNumber: 72, cardSet: cardSetId, name: 'Hired Poisoner', rarity: 'C', layout: 'normal'},
{ cardNumber: 73, cardSet: cardSetId, name: 'Kraul Swarm', rarity: 'U', layout: 'normal'},
{ cardNumber: 74, cardSet: cardSetId, name: 'Lotleth Giant', rarity: 'U', layout: 'normal'},
{ cardNumber: 75, cardSet: cardSetId, name: 'Mausoleum Secrets', rarity: 'R', layout: 'normal'},
{ cardNumber: 76, cardSet: cardSetId, name: 'Mephitic Vapors', rarity: 'C', layout: 'normal'},
{ cardNumber: 77, cardSet: cardSetId, name: 'Midnight Reaper', rarity: 'R', layout: 'normal'},
{ cardNumber: 78, cardSet: cardSetId, name: 'Moodmark Painter', rarity: 'C', layout: 'normal'},
{ cardNumber: 79, cardSet: cardSetId, name: 'Necrotic Wound', rarity: 'U', layout: 'normal'},
{ cardNumber: 80, cardSet: cardSetId, name: 'Never Happened', rarity: 'C', layout: 'normal'},
{ cardNumber: 81, cardSet: cardSetId, name: 'Pilfering Imp', rarity: 'U', layout: 'normal'},
{ cardNumber: 82, cardSet: cardSetId, name: 'Plaguecrafter', rarity: 'U', layout: 'normal'},
{ cardNumber: 83, cardSet: cardSetId, name: 'Price of Fame', rarity: 'U', layout: 'normal'},
{ cardNumber: 84, cardSet: cardSetId, name: 'Ritual of Soot', rarity: 'R', layout: 'normal'},
{ cardNumber: 85, cardSet: cardSetId, name: 'Severed Strands', rarity: 'C', layout: 'normal'},
{ cardNumber: 86, cardSet: cardSetId, name: 'Spinal Centipede', rarity: 'C', layout: 'normal'},
{ cardNumber: 87, cardSet: cardSetId, name: 'Undercity Necrolisk', rarity: 'U', layout: 'normal'},
{ cardNumber: 88, cardSet: cardSetId, name: 'Veiled Shade', rarity: 'C', layout: 'normal'},
{ cardNumber: 89, cardSet: cardSetId, name: 'Vicious Rumors', rarity: 'C', layout: 'normal'},
{ cardNumber: 90, cardSet: cardSetId, name: 'Whispering Snitch', rarity: 'U', layout: 'normal'},
{ cardNumber: 91, cardSet: cardSetId, name: 'Arclight Phoenix', rarity: 'M', layout: 'normal'},
{ cardNumber: 92, cardSet: cardSetId, name: 'Barging Sergeant', rarity: 'C', layout: 'normal'},
{ cardNumber: 93, cardSet: cardSetId, name: 'Book Devourer', rarity: 'U', layout: 'normal'},
{ cardNumber: 94, cardSet: cardSetId, name: 'Command the Storm', rarity: 'C', layout: 'normal'},
{ cardNumber: 95, cardSet: cardSetId, name: 'Cosmotronic Wave', rarity: 'C', layout: 'normal'},
{ cardNumber: 96, cardSet: cardSetId, name: 'Direct Current', rarity: 'C', layout: 'normal'},
{ cardNumber: 97, cardSet: cardSetId, name: 'Electrostatic Field', rarity: 'U', layout: 'normal'},
{ cardNumber: 98, cardSet: cardSetId, name: 'Erratic Cyclops', rarity: 'R', layout: 'normal'},
{ cardNumber: 99, cardSet: cardSetId, name: 'Experimental Frenzy', rarity: 'R', layout: 'normal'},
{ cardNumber: 100, cardSet: cardSetId, name: 'Fearless Halberdier', rarity: 'C', layout: 'normal'},
{ cardNumber: 101, cardSet: cardSetId, name: 'Fire Urchin', rarity: 'C', layout: 'normal'},
{ cardNumber: 102, cardSet: cardSetId, name: 'Goblin Banneret', rarity: 'U', layout: 'normal'},
{ cardNumber: 103, cardSet: cardSetId, name: 'Goblin Cratermaker', rarity: 'U', layout: 'normal'},
{ cardNumber: 104, cardSet: cardSetId, name: 'Goblin Locksmith', rarity: 'C', layout: 'normal'},
{ cardNumber: 105, cardSet: cardSetId, name: 'Gravitic Punch', rarity: 'C', layout: 'normal'},
{ cardNumber: 106, cardSet: cardSetId, name: 'Hellkite Whelp', rarity: 'U', layout: 'normal'},
{ cardNumber: 107, cardSet: cardSetId, name: 'Inescapable Blaze', rarity: 'U', layout: 'normal'},
{ cardNumber: 108, cardSet: cardSetId, name: 'Lava Coil', rarity: 'U', layout: 'normal'},
{ cardNumber: 109, cardSet: cardSetId, name: 'Legion Warboss', rarity: 'R', layout: 'normal'},
{ cardNumber: 110, cardSet: cardSetId, name: 'Maniacal Rage', rarity: 'C', layout: 'normal'},
{ cardNumber: 111, cardSet: cardSetId, name: 'Maximize Velocity', rarity: 'C', layout: 'normal'},
{ cardNumber: 112, cardSet: cardSetId, name: 'Ornery Goblin', rarity: 'C', layout: 'normal'},
{ cardNumber: 113, cardSet: cardSetId, name: 'Risk Factor', rarity: 'R', layout: 'normal'},
{ cardNumber: 114, cardSet: cardSetId, name: 'Rubblebelt Boar', rarity: 'C', layout: 'normal'},
{ cardNumber: 115, cardSet: cardSetId, name: 'Runaway Steam-Kin', rarity: 'R', layout: 'normal'},
{ cardNumber: 116, cardSet: cardSetId, name: 'Smelt-Ward Minotaur', rarity: 'U', layout: 'normal'},
{ cardNumber: 117, cardSet: cardSetId, name: 'Street Riot', rarity: 'U', layout: 'normal'},
{ cardNumber: 118, cardSet: cardSetId, name: 'Sure Strike', rarity: 'C', layout: 'normal'},
{ cardNumber: 119, cardSet: cardSetId, name: 'Torch Courier', rarity: 'C', layout: 'normal'},
{ cardNumber: 120, cardSet: cardSetId, name: 'Wojek Bodyguard', rarity: 'C', layout: 'normal'},
{ cardNumber: 121, cardSet: cardSetId, name: 'Affectionate Indrik', rarity: 'U', layout: 'normal'},
{ cardNumber: 122, cardSet: cardSetId, name: 'Arboretum Elemental', rarity: 'U', layout: 'normal'},
{ cardNumber: 123, cardSet: cardSetId, name: 'Beast Whisperer', rarity: 'R', layout: 'normal'},
{ cardNumber: 124, cardSet: cardSetId, name: 'Bounty of Might', rarity: 'R', layout: 'normal'},
{ cardNumber: 125, cardSet: cardSetId, name: 'Circuitous Route', rarity: 'U', layout: 'normal'},
{ cardNumber: 126, cardSet: cardSetId, name: 'Crushing Canopy', rarity: 'C', layout: 'normal'},
{ cardNumber: 127, cardSet: cardSetId, name: 'Devkarin Dissident', rarity: 'C', layout: 'normal'},
{ cardNumber: 128, cardSet: cardSetId, name: 'District Guide', rarity: 'U', layout: 'normal'},
{ cardNumber: 129, cardSet: cardSetId, name: 'Generous Stray', rarity: 'C', layout: 'normal'},
{ cardNumber: 130, cardSet: cardSetId, name: 'Golgari Raiders', rarity: 'U', layout: 'normal'},
{ cardNumber: 131, cardSet: cardSetId, name: 'Grappling Sundew', rarity: 'U', layout: 'normal'},
{ cardNumber: 132, cardSet: cardSetId, name: 'Hatchery Spider', rarity: 'R', layout: 'normal'},
{ cardNumber: 133, cardSet: cardSetId, name: 'Hitchclaw Recluse', rarity: 'C', layout: 'normal'},
{ cardNumber: 134, cardSet: cardSetId, name: 'Ironshell Beetle', rarity: 'C', layout: 'normal'},
{ cardNumber: 135, cardSet: cardSetId, name: 'Kraul Foragers', rarity: 'C', layout: 'normal'},
{ cardNumber: 136, cardSet: cardSetId, name: 'Kraul Harpooner', rarity: 'U', layout: 'normal'},
{ cardNumber: 137, cardSet: cardSetId, name: 'Might of the Masses', rarity: 'U', layout: 'normal'},
{ cardNumber: 138, cardSet: cardSetId, name: 'Nullhide Ferox', rarity: 'M', layout: 'normal'},
{ cardNumber: 139, cardSet: cardSetId, name: 'Pack\'s Favor', rarity: 'C', layout: 'normal'},
{ cardNumber: 140, cardSet: cardSetId, name: 'Pause for Reflection', rarity: 'C', layout: 'normal'},
{ cardNumber: 141, cardSet: cardSetId, name: 'Pelt Collector', rarity: 'R', layout: 'normal'},
{ cardNumber: 142, cardSet: cardSetId, name: 'Portcullis Vine', rarity: 'C', layout: 'normal'},
{ cardNumber: 143, cardSet: cardSetId, name: 'Prey Upon', rarity: 'C', layout: 'normal'},
{ cardNumber: 144, cardSet: cardSetId, name: 'Siege Wurm', rarity: 'C', layout: 'normal'},
{ cardNumber: 145, cardSet: cardSetId, name: 'Sprouting Renewal', rarity: 'U', layout: 'normal'},
{ cardNumber: 146, cardSet: cardSetId, name: 'Urban Utopia', rarity: 'C', layout: 'normal'},
{ cardNumber: 147, cardSet: cardSetId, name: 'Vigorspore Wurm', rarity: 'C', layout: 'normal'},
{ cardNumber: 148, cardSet: cardSetId, name: 'Vivid Revival', rarity: 'R', layout: 'normal'},
{ cardNumber: 149, cardSet: cardSetId, name: 'Wary Okapi', rarity: 'C', layout: 'normal'},
{ cardNumber: 150, cardSet: cardSetId, name: 'Wild Ceratok', rarity: 'C', layout: 'normal'},
{ cardNumber: 151, cardSet: cardSetId, name: 'Artful Takedown', rarity: 'C', layout: 'normal'},
{ cardNumber: 152, cardSet: cardSetId, name: 'Assassin\'s Trophy', rarity: 'R', layout: 'normal'},
{ cardNumber: 153, cardSet: cardSetId, name: 'Aurelia, Exemplar of Justice', rarity: 'M', layout: 'normal'},
{ cardNumber: 154, cardSet: cardSetId, name: 'Beacon Bolt', rarity: 'U', layout: 'normal'},
{ cardNumber: 155, cardSet: cardSetId, name: 'Beamsplitter Mage', rarity: 'U', layout: 'normal'},
{ cardNumber: 156, cardSet: cardSetId, name: 'Boros Challenger', rarity: 'U', layout: 'normal'},
{ cardNumber: 157, cardSet: cardSetId, name: 'Camaraderie', rarity: 'R', layout: 'normal'},
{ cardNumber: 158, cardSet: cardSetId, name: 'Centaur Peacemaker', rarity: 'C', layout: 'normal'},
{ cardNumber: 159, cardSet: cardSetId, name: 'Chance for Glory', rarity: 'M', layout: 'normal'},
{ cardNumber: 160, cardSet: cardSetId, name: 'Charnel Troll', rarity: 'R', layout: 'normal'},
{ cardNumber: 161, cardSet: cardSetId, name: 'Conclave Cavalier', rarity: 'U', layout: 'normal'},
{ cardNumber: 162, cardSet: cardSetId, name: 'Conclave Guildmage', rarity: 'U', layout: 'normal'},
{ cardNumber: 163, cardSet: cardSetId, name: 'Crackling Drake', rarity: 'U', layout: 'normal'},
{ cardNumber: 164, cardSet: cardSetId, name: 'Darkblade Agent', rarity: 'C', layout: 'normal'},
{ cardNumber: 165, cardSet: cardSetId, name: 'Deafening Clarion', rarity: 'R', layout: 'normal'},
{ cardNumber: 166, cardSet: cardSetId, name: 'Dimir Spybug', rarity: 'U', layout: 'normal'},
{ cardNumber: 167, cardSet: cardSetId, name: 'Disinformation Campaign', rarity: 'U', layout: 'normal'},
{ cardNumber: 168, cardSet: cardSetId, name: 'Emmara, Soul of the Accord', rarity: 'R', layout: 'normal'},
{ cardNumber: 169, cardSet: cardSetId, name: 'Erstwhile Trooper', rarity: 'C', layout: 'normal'},
{ cardNumber: 170, cardSet: cardSetId, name: 'Etrata, the Silencer', rarity: 'R', layout: 'normal'},
{ cardNumber: 171, cardSet: cardSetId, name: 'Firemind\'s Research', rarity: 'R', layout: 'normal'},
{ cardNumber: 172, cardSet: cardSetId, name: 'Garrison Sergeant', rarity: 'C', layout: 'normal'},
{ cardNumber: 173, cardSet: cardSetId, name: 'Glowspore Shaman', rarity: 'U', layout: 'normal'},
{ cardNumber: 174, cardSet: cardSetId, name: 'Goblin Electromancer', rarity: 'C', layout: 'normal'},
{ cardNumber: 175, cardSet: cardSetId, name: 'Golgari Findbroker', rarity: 'U', layout: 'normal'},
{ cardNumber: 176, cardSet: cardSetId, name: 'Hammer Dropper', rarity: 'C', layout: 'normal'},
{ cardNumber: 177, cardSet: cardSetId, name: 'House Guildmage', rarity: 'U', layout: 'normal'},
{ cardNumber: 178, cardSet: cardSetId, name: 'Hypothesizzle', rarity: 'C', layout: 'normal'},
{ cardNumber: 179, cardSet: cardSetId, name: 'Ionize', rarity: 'R', layout: 'normal'},
{ cardNumber: 180, cardSet: cardSetId, name: 'Izoni, Thousand-Eyed', rarity: 'R', layout: 'normal'},
{ cardNumber: 181, cardSet: cardSetId, name: 'Join Shields', rarity: 'U', layout: 'normal'},
{ cardNumber: 182, cardSet: cardSetId, name: 'Justice Strike', rarity: 'U', layout: 'normal'},
{ cardNumber: 183, cardSet: cardSetId, name: 'Knight of Autumn', rarity: 'R', layout: 'normal'},
{ cardNumber: 184, cardSet: cardSetId, name: 'Lazav, the Multifarious', rarity: 'M', layout: 'normal'},
{ cardNumber: 185, cardSet: cardSetId, name: 'League Guildmage', rarity: 'U', layout: 'normal'},
{ cardNumber: 186, cardSet: cardSetId, name: 'Ledev Champion', rarity: 'U', layout: 'normal'},
{ cardNumber: 187, cardSet: cardSetId, name: 'Legion Guildmage', rarity: 'U', layout: 'normal'},
{ cardNumber: 188, cardSet: cardSetId, name: 'March of the Multitudes', rarity: 'M', layout: 'normal'},
{ cardNumber: 189, cardSet: cardSetId, name: 'Mnemonic Betrayal', rarity: 'M', layout: 'normal'},
{ cardNumber: 190, cardSet: cardSetId, name: 'Molderhulk', rarity: 'U', layout: 'normal'},
{ cardNumber: 191, cardSet: cardSetId, name: 'Nightveil Predator', rarity: 'U', layout: 'normal'},
{ cardNumber: 192, cardSet: cardSetId, name: 'Niv-Mizzet, Parun', rarity: 'R', layout: 'normal'},
{ cardNumber: 193, cardSet: cardSetId, name: 'Notion Rain', rarity: 'C', layout: 'normal'},
{ cardNumber: 194, cardSet: cardSetId, name: 'Ochran Assassin', rarity: 'U', layout: 'normal'},
{ cardNumber: 195, cardSet: cardSetId, name: 'Ral, Izzet Viceroy', rarity: 'M', layout: 'normal'},
{ cardNumber: 196, cardSet: cardSetId, name: 'Rhizome Lurcher', rarity: 'C', layout: 'normal'},
{ cardNumber: 197, cardSet: cardSetId, name: 'Rosemane Centaur', rarity: 'C', layout: 'normal'},
{ cardNumber: 198, cardSet: cardSetId, name: 'Skyknight Legionnaire', rarity: 'C', layout: 'normal'},
{ cardNumber: 199, cardSet: cardSetId, name: 'Sonic Assault', rarity: 'C', layout: 'normal'},
{ cardNumber: 200, cardSet: cardSetId, name: 'Sumala Woodshaper', rarity: 'C', layout: 'normal'},
{ cardNumber: 201, cardSet: cardSetId, name: 'Swarm Guildmage', rarity: 'U', layout: 'normal'},
{ cardNumber: 202, cardSet: cardSetId, name: 'Swathcutter Giant', rarity: 'U', layout: 'normal'},
{ cardNumber: 203, cardSet: cardSetId, name: 'Swiftblade Vindicator', rarity: 'R', layout: 'normal'},
{ cardNumber: 204, cardSet: cardSetId, name: 'Tajic, Legion\'s Edge', rarity: 'R', layout: 'normal'},
{ cardNumber: 205, cardSet: cardSetId, name: 'Thief of Sanity', rarity: 'R', layout: 'normal'},
{ cardNumber: 206, cardSet: cardSetId, name: 'Thought Erasure', rarity: 'U', layout: 'normal'},
{ cardNumber: 207, cardSet: cardSetId, name: 'Thousand-Year Storm', rarity: 'M', layout: 'normal'},
{ cardNumber: 208, cardSet: cardSetId, name: 'Trostani Discordant', rarity: 'M', layout: 'normal'},
{ cardNumber: 209, cardSet: cardSetId, name: 'Truefire Captain', rarity: 'U', layout: 'normal'},
{ cardNumber: 210, cardSet: cardSetId, name: 'Undercity Uprising', rarity: 'C', layout: 'normal'},
{ cardNumber: 211, cardSet: cardSetId, name: 'Underrealm Lich', rarity: 'M', layout: 'normal'},
{ cardNumber: 212, cardSet: cardSetId, name: 'Unmoored Ego', rarity: 'R', layout: 'normal'},
{ cardNumber: 213, cardSet: cardSetId, name: 'Vraska, Golgari Queen', rarity: 'M', layout: 'normal'},
{ cardNumber: 214, cardSet: cardSetId, name: 'Wee Dragonauts', rarity: 'U', layout: 'normal'},
{ cardNumber: 215, cardSet: cardSetId, name: 'Worldsoul Colossus', rarity: 'U', layout: 'normal'},
{ cardNumber: 216, cardSet: cardSetId, name: 'Fresh-Faced Recruit', rarity: 'C', layout: 'normal'},
{ cardNumber: 217, cardSet: cardSetId, name: 'Piston-Fist Cyclops', rarity: 'C', layout: 'normal'},
{ cardNumber: 218, cardSet: cardSetId, name: 'Pitiless Gorgon', rarity: 'C', layout: 'normal'},
{ cardNumber: 219, cardSet: cardSetId, name: 'Vernadi Shieldmate', rarity: 'C', layout: 'normal'},
{ cardNumber: 220, cardSet: cardSetId, name: 'Whisper Agent', rarity: 'C', layout: 'normal'},
{ cardNumber: 221, cardSet: cardSetId, name: 'Assure', rarity: 'R', layout: 'split'},
{ cardNumber: 222, cardSet: cardSetId, name: 'Connive', rarity: 'R', layout: 'split'},
{ cardNumber: 223, cardSet: cardSetId, name: 'Discovery', rarity: 'U', layout: 'split'},
{ cardNumber: 224, cardSet: cardSetId, name: 'Expansion', rarity: 'R', layout: 'split'},
{ cardNumber: 225, cardSet: cardSetId, name: 'Find', rarity: 'R', layout: 'split'},
{ cardNumber: 226, cardSet: cardSetId, name: 'Flower', rarity: 'U', layout: 'split'},
{ cardNumber: 227, cardSet: cardSetId, name: 'Integrity', rarity: 'U', layout: 'split'},
{ cardNumber: 228, cardSet: cardSetId, name: 'Invert', rarity: 'U', layout: 'split'},
{ cardNumber: 229, cardSet: cardSetId, name: 'Response', rarity: 'R', layout: 'split'},
{ cardNumber: 230, cardSet: cardSetId, name: 'Status', rarity: 'U', layout: 'split'},
{ cardNumber: 231, cardSet: cardSetId, name: 'Boros Locket', rarity: 'C', layout: 'normal'},
{ cardNumber: 232, cardSet: cardSetId, name: 'Chamber Sentry', rarity: 'R', layout: 'normal'},
{ cardNumber: 233, cardSet: cardSetId, name: 'Chromatic Lantern', rarity: 'R', layout: 'normal'},
{ cardNumber: 234, cardSet: cardSetId, name: 'Dimir Locket', rarity: 'C', layout: 'normal'},
{ cardNumber: 235, cardSet: cardSetId, name: 'Gatekeeper Gargoyle', rarity: 'U', layout: 'normal'},
{ cardNumber: 236, cardSet: cardSetId, name: 'Glaive of the Guildpact', rarity: 'U', layout: 'normal'},
{ cardNumber: 237, cardSet: cardSetId, name: 'Golgari Locket', rarity: 'C', layout: 'normal'},
{ cardNumber: 238, cardSet: cardSetId, name: 'Izzet Locket', rarity: 'C', layout: 'normal'},
{ cardNumber: 239, cardSet: cardSetId, name: 'Rampaging Monument', rarity: 'U', layout: 'normal'},
{ cardNumber: 240, cardSet: cardSetId, name: 'Selesnya Locket', rarity: 'C', layout: 'normal'},
{ cardNumber: 241, cardSet: cardSetId, name: 'Silent Dart', rarity: 'U', layout: 'normal'},
{ cardNumber: 242, cardSet: cardSetId, name: 'Wand of Vertebrae', rarity: 'U', layout: 'normal'},
{ cardNumber: 243, cardSet: cardSetId, name: 'Boros Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 244, cardSet: cardSetId, name: 'Boros Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 245, cardSet: cardSetId, name: 'Dimir Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 246, cardSet: cardSetId, name: 'Dimir Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 247, cardSet: cardSetId, name: 'Gateway Plaza', rarity: 'C', layout: 'normal'},
{ cardNumber: 248, cardSet: cardSetId, name: 'Golgari Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 249, cardSet: cardSetId, name: 'Golgari Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 250, cardSet: cardSetId, name: 'Guildmages\' Forum', rarity: 'R', layout: 'normal'},
{ cardNumber: 251, cardSet: cardSetId, name: 'Izzet Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 252, cardSet: cardSetId, name: 'Izzet Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 253, cardSet: cardSetId, name: 'Overgrown Tomb', rarity: 'R', layout: 'normal'},
{ cardNumber: 254, cardSet: cardSetId, name: 'Sacred Foundry', rarity: 'R', layout: 'normal'},
{ cardNumber: 255, cardSet: cardSetId, name: 'Selesnya Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 256, cardSet: cardSetId, name: 'Selesnya Guildgate', rarity: 'C', layout: 'normal'},
{ cardNumber: 257, cardSet: cardSetId, name: 'Steam Vents', rarity: 'R', layout: 'normal'},
{ cardNumber: 258, cardSet: cardSetId, name: 'Temple Garden', rarity: 'R', layout: 'normal'},
{ cardNumber: 259, cardSet: cardSetId, name: 'Watery Grave', rarity: 'R', layout: 'normal'},
{ cardNumber: 260, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal'},
{ cardNumber: 261, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal'},
{ cardNumber: 262, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal'},
{ cardNumber: 263, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal'},
{ cardNumber: 264, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal'},
{ cardNumber: 265, cardSet: cardSetId, name: 'Ral, Caller of Storms', rarity: 'M', layout: 'normal'},
{ cardNumber: 266, cardSet: cardSetId, name: 'Ral\'s Dispersal', rarity: 'R', layout: 'normal'},
{ cardNumber: 267, cardSet: cardSetId, name: 'Precision Bolt', rarity: 'C', layout: 'normal'},
{ cardNumber: 268, cardSet: cardSetId, name: 'Ral\'s Staticaster', rarity: 'U', layout: 'normal'},
{ cardNumber: 269, cardSet: cardSetId, name: 'Vraska, Regal Gorgon', rarity: 'M', layout: 'normal'},
{ cardNumber: 270, cardSet: cardSetId, name: 'Kraul Raider', rarity: 'C', layout: 'normal'},
{ cardNumber: 271, cardSet: cardSetId, name: 'Attendant of Vraska', rarity: 'U', layout: 'normal'},
{ cardNumber: 272, cardSet: cardSetId, name: 'Vraska\'s Stoneglare', rarity: 'R', layout: 'normal'},
{ cardNumber: 273, cardSet: cardSetId, name: 'Impervious Greatwurm', rarity: 'M', layout: 'normal'},
]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'GRN';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
