import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingRna1620394763075 implements MigrationInterface {
    name = 'addingRna1620394763075';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Ravnica Allegiance', shortName: 'RNA' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Angel of Grace', rarity: 'M', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Angelic Exaltation', rarity: 'U', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Archway Angel', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Arrester\'s Zeal', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Bring to Trial', rarity: 'C', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Civic Stalwart', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Concordia Pegasus', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Expose to Daylight', rarity: 'C', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Forbidding Spirit', rarity: 'U', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Haazda Officer', rarity: 'C', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Hero of Precinct One', rarity: 'R', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Impassioned Orator', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Justiciar\'s Portal', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Knight of Sorrows', rarity: 'C', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Lumbering Battlement', rarity: 'R', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Ministrant of Obligation', rarity: 'U', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Prowling Caracal', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Rally to Battle', rarity: 'U', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Resolute Watchdog', rarity: 'U', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Sentinel\'s Mark', rarity: 'U', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Sky Tether', rarity: 'U', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Smothering Tithe', rarity: 'R', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Spirit of the Spires', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Summary Judgment', rarity: 'C', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Syndicate Messenger', rarity: 'C', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Tenth District Veteran', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Tithe Taker', rarity: 'R', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Twilight Panther', rarity: 'C', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Unbreakable Formation', rarity: 'R', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Watchful Giant', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Arrester\'s Admonition', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Benthic Biomancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Chillbringer', rarity: 'C', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Clear the Mind', rarity: 'C', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Code of Constraint', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Coral Commando', rarity: 'C', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Essence Capture', rarity: 'U', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Eyes Everywhere', rarity: 'U', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Faerie Duelist', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Gateway Sneak', rarity: 'U', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Humongulus', rarity: 'C', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Mass Manipulation', rarity: 'R', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Mesmerizing Benthid', rarity: 'M', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Persistent Petitioners', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Precognitive Perception', rarity: 'R', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Prying Eyes', rarity: 'C', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Pteramander', rarity: 'U', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Quench', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Sage\'s Row Savant', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Senate Courier', rarity: 'C', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Shimmer of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Skatewing Spy', rarity: 'U', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Skitter Eel', rarity: 'C', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Slimebind', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Sphinx of Foresight', rarity: 'R', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Swirling Torrent', rarity: 'U', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Thought Collapse', rarity: 'C', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Verity Circle', rarity: 'R', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Wall of Lost Thoughts', rarity: 'U', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Windstorm Drake', rarity: 'U', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Awaken the Erstwhile', rarity: 'R', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Bankrupt in Blood', rarity: 'U', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Blade Juggler', rarity: 'C', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Bladebrand', rarity: 'C', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Bloodmist Infiltrator', rarity: 'U', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Carrion Imp', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Catacomb Crocodile', rarity: 'C', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Clear the Stage', rarity: 'U', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Consign to the Pit', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Cry of the Carnarium', rarity: 'U', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Dead Revels', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Debtors\' Transport', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Drill Bit', rarity: 'U', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Font of Agonies', rarity: 'R', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Grotesque Demise', rarity: 'C', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Gutterbones', rarity: 'R', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Ill-Gotten Inheritance', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Noxious Groodion', rarity: 'C', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Orzhov Enforcer', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Orzhov Racketeers', rarity: 'U', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Pestilent Spirit', rarity: 'R', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Plague Wight', rarity: 'C', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Priest of Forgotten Gods', rarity: 'R', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Rakdos Trumpeter', rarity: 'C', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Spawn of Mayhem', rarity: 'M', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Spire Mangler', rarity: 'U', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Thirsting Shade', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Undercity Scavenger', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Undercity\'s Embrace', rarity: 'C', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Vindictive Vampire', rarity: 'U', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Act of Treason', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Amplifire', rarity: 'R', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Burn Bright', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Burning-Tree Vandal', rarity: 'C', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Cavalcade of Calamity', rarity: 'U', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Clamor Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Dagger Caster', rarity: 'U', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Deface', rarity: 'C', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Electrodominance', rarity: 'R', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Feral Maaka', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Flames of the Raze-Boar', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Gates Ablaze', rarity: 'U', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Ghor-Clan Wrecker', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Goblin Gathering', rarity: 'C', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Gravel-Hide Goblin', rarity: 'C', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Immolation Shaman', rarity: 'R', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Light Up the Stage', rarity: 'U', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Mirror March', rarity: 'R', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Rix Maadi Reveler', rarity: 'R', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Rubble Reading', rarity: 'C', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Rubblebelt Recluse', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Rumbling Ruin', rarity: 'U', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Scorchmark', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Skarrgan Hellkite', rarity: 'M', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Skewer the Critics', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Smelt-Ward Ignus', rarity: 'U', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Spear Spewer', rarity: 'C', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Spikewheel Acrobat', rarity: 'C', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Storm Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Tin Street Dodger', rarity: 'U', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Axebane Beast', rarity: 'C', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Biogenic Ooze', rarity: 'M', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Biogenic Upgrade', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'End-Raze Forerunners', rarity: 'R', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Enraged Ceratok', rarity: 'U', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Gatebreaker Ram', rarity: 'U', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Gift of Strength', rarity: 'C', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Growth-Chamber Guardian', rarity: 'R', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Gruul Beastmaster', rarity: 'U', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Guardian Project', rarity: 'R', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Incubation Druid', rarity: 'R', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Mammoth Spider', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Open the Gates', rarity: 'C', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Rampage of the Clans', rarity: 'R', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Rampaging Rendhorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Regenesis', rarity: 'U', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Root Snare', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Sagittars\' Volley', rarity: 'C', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Saruli Caretaker', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Sauroform Hybrid', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Silhana Wayfinder', rarity: 'U', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Steeple Creeper', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Stony Strength', rarity: 'C', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Sylvan Brushstrider', rarity: 'C', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Territorial Boar', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Titanic Brawl', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Tower Defense', rarity: 'U', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Trollbred Guardian', rarity: 'U', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Wilderness Reclamation', rarity: 'U', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Wrecking Beast', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Absorb', rarity: 'R', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Aeromunculus', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Applied Biomancy', rarity: 'C', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Azorius Knight-Arbiter', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Azorius Skyguard', rarity: 'U', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Basilica Bell-Haunt', rarity: 'U', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Bedevil', rarity: 'R', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Biomancer\'s Familiar', rarity: 'R', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Bolrac-Clan Crusher', rarity: 'U', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Captive Audience', rarity: 'M', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Cindervines', rarity: 'R', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Clan Guildmage', rarity: 'U', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Combine Guildmage', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Cult Guildmage', rarity: 'U', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Deputy of Detention', rarity: 'R', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Domri, Chaos Bringer', rarity: 'M', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Dovin, Grand Arbiter', rarity: 'M', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Dovin\'s Acuity', rarity: 'U', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Emergency Powers', rarity: 'M', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Ethereal Absolution', rarity: 'R', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Final Payment', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Fireblade Artist', rarity: 'U', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Frenzied Arynx', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Frilled Mystic', rarity: 'U', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Galloping Lizrog', rarity: 'U', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Get the Point', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Grasping Thrull', rarity: 'C', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Growth Spiral', rarity: 'C', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Gruul Spellbreaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Gyre Engineer', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Hackrobat', rarity: 'U', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'High Alert', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Hydroid Krasis', rarity: 'M', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Imperious Oligarch', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Judith, the Scourge Diva', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Kaya, Orzhov Usurper', rarity: 'M', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Kaya\'s Wrath', rarity: 'R', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Knight of the Last Breath', rarity: 'U', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Lavinia, Azorius Renegade', rarity: 'R', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Lawmage\'s Binding', rarity: 'C', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Macabre Mockery', rarity: 'U', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Mortify', rarity: 'U', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Nikya of the Old Ways', rarity: 'R', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Pitiless Pontiff', rarity: 'U', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Prime Speaker Vannifar', rarity: 'M', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Rafter Demon', rarity: 'C', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Rakdos Firewheeler', rarity: 'U', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Rakdos Roustabout', rarity: 'C', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Rakdos, the Showstopper', rarity: 'M', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Ravager Wurm', rarity: 'M', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Rhythm of the Wild', rarity: 'U', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Rubblebelt Runner', rarity: 'C', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Savage Smash', rarity: 'C', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Senate Guildmage', rarity: 'U', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Seraph of the Scales', rarity: 'M', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Sharktocrab', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Simic Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Sphinx of New Prahv', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Sphinx\'s Insight', rarity: 'C', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Sunder Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Syndicate Guildmage', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Teysa Karlov', rarity: 'R', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Theater of Horrors', rarity: 'R', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Zegana, Utopian Speaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Zhur-Taa Goblin', rarity: 'U', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Footlight Fiend', rarity: 'C', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Rubble Slinger', rarity: 'C', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Scuttlegator', rarity: 'C', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Senate Griffin', rarity: 'C', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Vizkopa Vampire', rarity: 'C', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Bedeck', rarity: 'R', layout: 'split' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Carnival', rarity: 'U', layout: 'split' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Collision', rarity: 'U', layout: 'split' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Consecrate', rarity: 'U', layout: 'split' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Depose', rarity: 'U', layout: 'split' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Incubation', rarity: 'U', layout: 'split' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Repudiate', rarity: 'R', layout: 'split' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Revival', rarity: 'R', layout: 'split' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Thrash', rarity: 'R', layout: 'split' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Warrant', rarity: 'R', layout: 'split' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Azorius Locket', rarity: 'C', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Gate Colossus', rarity: 'U', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Glass of the Guildpact', rarity: 'R', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Gruul Locket', rarity: 'C', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Junktroller', rarity: 'U', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Orzhov Locket', rarity: 'C', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Rakdos Locket', rarity: 'C', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Scrabbling Claws', rarity: 'U', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Screaming Shield', rarity: 'U', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Simic Locket', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Sphinx of the Guildpact', rarity: 'U', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Tome of the Guildpact', rarity: 'R', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Azorius Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Azorius Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Blood Crypt', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Breeding Pool', rarity: 'R', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Gateway Plaza', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Godless Shrine', rarity: 'R', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Gruul Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Gruul Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Hallowed Fountain', rarity: 'R', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Orzhov Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Orzhov Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Plaza of Harmony', rarity: 'R', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Rakdos Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Rakdos Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Simic Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Simic Guildgate', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Stomping Ground', rarity: 'R', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Dovin, Architect of Law', rarity: 'M', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Elite Arrester', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Dovin\'s Dismissal', rarity: 'R', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Dovin\'s Automaton', rarity: 'U', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Domri, City Smasher', rarity: 'M', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Ragefire', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Charging War Boar', rarity: 'U', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Domri\'s Nodorog', rarity: 'R', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'The Haunt of Hightower', rarity: 'M', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'RNA';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
