import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingM211620401126927 implements MigrationInterface {
    name = 'addingM211620401126927';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Core Set 2021', shortName: 'M21' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Ugin, the Spirit Dragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Alpine Watchdog', rarity: 'C', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Angelic Ascension', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Anointed Chorister', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Aven Gagglemaster', rarity: 'U', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Baneslayer Angel', rarity: 'M', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Basri Ket', rarity: 'M', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Basri\'s Acolyte', rarity: 'C', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Basri\'s Lieutenant', rarity: 'R', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Basri\'s Solidarity', rarity: 'U', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Celestial Enforcer', rarity: 'C', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Concordia Pegasus', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Containment Priest', rarity: 'R', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Daybreak Charger', rarity: 'C', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Defiant Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Dub', rarity: 'C', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Faith\'s Fetters', rarity: 'U', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Falconer Adept', rarity: 'U', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Feat of Resistance', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Gale Swooper', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Glorious Anthem', rarity: 'R', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Griffin Aerie', rarity: 'U', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Idol of Endurance', rarity: 'R', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Legion\'s Judgment', rarity: 'C', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Light of Promise', rarity: 'U', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Makeshift Battalion', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Mangara, the Diplomat', rarity: 'M', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Nine Lives', rarity: 'R', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Pack Leader', rarity: 'R', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Rambunctious Mutt', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Revitalize', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Runed Halo', rarity: 'R', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Sanctum of Tranquil Light', rarity: 'U', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Seasoned Hallowblade', rarity: 'U', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Secure the Scene', rarity: 'C', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Selfless Savior', rarity: 'U', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Siege Striker', rarity: 'U', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Speaker of the Heavens', rarity: 'R', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Staunch Shieldmate', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Swift Response', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Tempered Veteran', rarity: 'U', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Valorous Steed', rarity: 'C', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Vryn Wingmare', rarity: 'U', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Warded Battlements', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Barrin, Tolarian Archmage', rarity: 'R', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Cancel', rarity: 'C', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Capture Sphere', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Discontinuity', rarity: 'M', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Enthralling Hold', rarity: 'U', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Frantic Inventory', rarity: 'C', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Frost Breath', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Ghostly Pilferer', rarity: 'R', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Jeskai Elder', rarity: 'U', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Keen Glidemaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Library Larcenist', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Lofty Denial', rarity: 'C', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Miscast', rarity: 'U', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Mistral Singer', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Opt', rarity: 'C', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Pursued Whale', rarity: 'R', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Rain of Revelation', rarity: 'U', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Read the Tides', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Rewind', rarity: 'U', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Riddleform', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Roaming Ghostlight', rarity: 'C', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Rookie Mistake', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Rousing Read', rarity: 'C', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Sanctum of Calm Waters', rarity: 'U', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'See the Truth', rarity: 'R', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Shacklegeist', rarity: 'R', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Shipwreck Dowser', rarity: 'U', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Spined Megalodon', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Stormwing Entity', rarity: 'R', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Sublime Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Teferi\'s Ageless Insight', rarity: 'R', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Teferi\'s Protege', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Teferi\'s Tutelage', rarity: 'U', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Tide Skimmer', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Tolarian Kraken', rarity: 'U', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Tome Anima', rarity: 'C', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Unsubstantiate', rarity: 'U', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Vodalian Arcanist', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Waker of Waves', rarity: 'U', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Wall of Runes', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Wishcoin Crab', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Alchemist\'s Gift', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Archfiend\'s Vessel', rarity: 'U', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Bad Deal', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Blood Glutton', rarity: 'C', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Caged Zombie', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Carrion Grub', rarity: 'U', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Crypt Lurker', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Deathbloom Thallid', rarity: 'C', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Demonic Embrace', rarity: 'R', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Duress', rarity: 'C', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Eliminate', rarity: 'U', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Fetid Imp', rarity: 'C', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Finishing Blow', rarity: 'C', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Gloom Sower', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Goremand', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Grasp of Darkness', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Grim Tutor', rarity: 'M', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Hooded Blightfang', rarity: 'R', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Infernal Scarring', rarity: 'C', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Kaervek, the Spiteful', rarity: 'R', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Kitesail Freebooter', rarity: 'U', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Liliana, Waker of the Dead', rarity: 'M', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Liliana\'s Devotee', rarity: 'U', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Liliana\'s Standard Bearer', rarity: 'R', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Liliana\'s Steward', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Malefic Scythe', rarity: 'U', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Masked Blackguard', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Massacre Wurm', rarity: 'M', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Mind Rot', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Necromentia', rarity: 'R', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Peer into the Abyss', rarity: 'R', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Pestilent Haze', rarity: 'U', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Rise Again', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Sanctum of Stone Fangs', rarity: 'U', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Sanguine Indulgence', rarity: 'C', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Silversmote Ghoul', rarity: 'U', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Skeleton Archer', rarity: 'C', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Tavern Swindler', rarity: 'U', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Thieves\' Guild Enforcer', rarity: 'R', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Village Rites', rarity: 'C', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Vito, Thorn of the Dusk Rose', rarity: 'R', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Walking Corpse', rarity: 'C', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Witch\'s Cauldron', rarity: 'U', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Battle-Rattle Shaman', rarity: 'U', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Bolt Hound', rarity: 'U', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Bone Pit Brute', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Brash Taunter', rarity: 'R', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Burn Bright', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Chandra, Heart of Fire', rarity: 'M', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Chandra\'s Incinerator', rarity: 'R', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Chandra\'s Magmutt', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Chandra\'s Pyreling', rarity: 'U', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Conspicuous Snoop', rarity: 'R', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Crash Through', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Destructive Tampering', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Double Vision', rarity: 'R', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Fiery Emancipation', rarity: 'M', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Furious Rise', rarity: 'U', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Furor of the Bitten', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Gadrak, the Crown-Scourge', rarity: 'R', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Goblin Arsonist', rarity: 'C', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Goblin Wizardry', rarity: 'C', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Havoc Jester', rarity: 'U', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Heartfire Immolator', rarity: 'U', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Hellkite Punisher', rarity: 'U', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Hobblefiend', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Igneous Cur', rarity: 'C', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Kinetic Augur', rarity: 'U', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Onakke Ogre', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Pitchburn Devils', rarity: 'C', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Sanctum of Shattered Heights', rarity: 'U', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Scorching Dragonfire', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Shock', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Soul Sear', rarity: 'U', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Spellgorger Weird', rarity: 'C', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Subira, Tulzidi Caravanner', rarity: 'R', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Sure Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Terror of the Peaks', rarity: 'M', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Thrill of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Traitorous Greed', rarity: 'U', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Transmogrify', rarity: 'R', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Turn to Slag', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Turret Ogre', rarity: 'C', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Unleash Fury', rarity: 'U', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Volcanic Geyser', rarity: 'U', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Volcanic Salvo', rarity: 'R', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Azusa, Lost but Seeking', rarity: 'R', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Burlfist Oak', rarity: 'U', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Canopy Stalker', rarity: 'U', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Colossal Dreadmaw', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Cultivate', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Drowsing Tyrannodon', rarity: 'C', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Elder Gargaroth', rarity: 'M', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Feline Sovereign', rarity: 'R', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Fierce Empath', rarity: 'U', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Fungal Rebirth', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Garruk, Unleashed', rarity: 'M', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Garruk\'s Gorehorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Garruk\'s Harbinger', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Garruk\'s Uprising', rarity: 'U', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Gnarled Sage', rarity: 'C', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Heroic Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Hunter\'s Edge', rarity: 'C', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Invigorating Surge', rarity: 'U', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Jolrael, Mwonvuli Recluse', rarity: 'R', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Life Goes On', rarity: 'C', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Llanowar Visionary', rarity: 'C', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Ornery Dilophosaur', rarity: 'C', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Portcullis Vine', rarity: 'C', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Pridemalkin', rarity: 'C', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Primal Might', rarity: 'R', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Quirion Dryad', rarity: 'U', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Ranger\'s Guile', rarity: 'C', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Return to Nature', rarity: 'C', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Run Afoul', rarity: 'C', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Sabertooth Mauler', rarity: 'C', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Sanctum of Fruitful Harvest', rarity: 'U', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Scavenging Ooze', rarity: 'R', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Setessan Training', rarity: 'C', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Skyway Sniper', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Snarespinner', rarity: 'C', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Sporeweb Weaver', rarity: 'R', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Thrashing Brontodon', rarity: 'U', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Titanic Growth', rarity: 'C', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Track Down', rarity: 'C', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Trufflesnout', rarity: 'C', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Warden of the Woods', rarity: 'U', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Wildwood Scourge', rarity: 'U', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Alpine Houndmaster', rarity: 'U', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Conclave Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Dire Fleet Warmonger', rarity: 'U', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Experimental Overload', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Indulging Patrician', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Leafkin Avenger', rarity: 'U', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Lorescale Coatl', rarity: 'U', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Niambi, Esteemed Speaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Obsessive Stitcher', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Radha, Heart of Keld', rarity: 'R', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Sanctum of All', rarity: 'R', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Twinblade Assassin', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Watcher of the Spheres', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Chromatic Orrery', rarity: 'M', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Chrome Replicator', rarity: 'U', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Epitaph Golem', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Forgotten Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Mazemind Tome', rarity: 'R', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Meteorite', rarity: 'U', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Palladium Myr', rarity: 'U', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Prismite', rarity: 'C', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Short Sword', rarity: 'C', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Silent Dart', rarity: 'C', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Skyscanner', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Solemn Simulacrum', rarity: 'R', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Sparkhunter Masticore', rarity: 'R', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Tormod\'s Crypt', rarity: 'U', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Animal Sanctuary', rarity: 'R', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Bloodfell Caves', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Blossoming Sands', rarity: 'C', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Dismal Backwater', rarity: 'C', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Fabled Passage', rarity: 'R', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Jungle Hollow', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Radiant Fountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Rugged Highlands', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Scoured Barrens', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Swiftwater Cliffs', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Temple of Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Temple of Malady', rarity: 'R', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Temple of Mystery', rarity: 'R', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Temple of Silence', rarity: 'R', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Temple of Triumph', rarity: 'R', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Thornwood Falls', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Tranquil Cove', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Wind-Scarred Crag', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Rin and Seri, Inseparable', rarity: 'M', layout: 'normal' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Ugin, the Spirit Dragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Basri Ket', rarity: 'M', layout: 'normal' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Liliana, Waker of the Dead', rarity: 'M', layout: 'normal' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Chandra, Heart of Fire', rarity: 'M', layout: 'normal' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Garruk, Unleashed', rarity: 'M', layout: 'normal' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Ugin, the Spirit Dragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Basri Ket', rarity: 'M', layout: 'normal' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Basri\'s Acolyte', rarity: 'C', layout: 'normal' },
            { cardNumber: 288, cardSet: cardSetId, name: 'Basri\'s Lieutenant', rarity: 'R', layout: 'normal' },
            { cardNumber: 289, cardSet: cardSetId, name: 'Basri\'s Solidarity', rarity: 'U', layout: 'normal' },
            { cardNumber: 290, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 291, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 292, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 293, cardSet: cardSetId, name: 'Teferi, Master of Time', rarity: 'M', layout: 'normal' },
            { cardNumber: 294, cardSet: cardSetId, name: 'Teferi\'s Ageless Insight', rarity: 'R', layout: 'normal' },
            { cardNumber: 295, cardSet: cardSetId, name: 'Teferi\'s Protege', rarity: 'C', layout: 'normal' },
            { cardNumber: 296, cardSet: cardSetId, name: 'Teferi\'s Tutelage', rarity: 'U', layout: 'normal' },
            { cardNumber: 297, cardSet: cardSetId, name: 'Liliana, Waker of the Dead', rarity: 'M', layout: 'normal' },
            { cardNumber: 298, cardSet: cardSetId, name: 'Liliana\'s Devotee', rarity: 'U', layout: 'normal' },
            { cardNumber: 299, cardSet: cardSetId, name: 'Liliana\'s Standard Bearer', rarity: 'R', layout: 'normal' },
            { cardNumber: 300, cardSet: cardSetId, name: 'Liliana\'s Steward', rarity: 'C', layout: 'normal' },
            { cardNumber: 301, cardSet: cardSetId, name: 'Chandra, Heart of Fire', rarity: 'M', layout: 'normal' },
            { cardNumber: 302, cardSet: cardSetId, name: 'Chandra\'s Incinerator', rarity: 'R', layout: 'normal' },
            { cardNumber: 303, cardSet: cardSetId, name: 'Chandra\'s Magmutt', rarity: 'C', layout: 'normal' },
            { cardNumber: 304, cardSet: cardSetId, name: 'Chandra\'s Pyreling', rarity: 'U', layout: 'normal' },
            { cardNumber: 305, cardSet: cardSetId, name: 'Garruk, Unleashed', rarity: 'M', layout: 'normal' },
            { cardNumber: 306, cardSet: cardSetId, name: 'Garruk\'s Gorehorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 307, cardSet: cardSetId, name: 'Garruk\'s Harbinger', rarity: 'R', layout: 'normal' },
            { cardNumber: 308, cardSet: cardSetId, name: 'Garruk\'s Uprising', rarity: 'U', layout: 'normal' },
            { cardNumber: 309, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 310, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 311, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 312, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 313, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 314, cardSet: cardSetId, name: 'Containment Priest', rarity: 'R', layout: 'normal' },
            { cardNumber: 315, cardSet: cardSetId, name: 'Grim Tutor', rarity: 'M', layout: 'normal' },
            { cardNumber: 316, cardSet: cardSetId, name: 'Massacre Wurm', rarity: 'M', layout: 'normal' },
            { cardNumber: 317, cardSet: cardSetId, name: 'Cultivate', rarity: 'R', layout: 'normal' },
            { cardNumber: 318, cardSet: cardSetId, name: 'Scavenging Ooze', rarity: 'R', layout: 'normal' },
            { cardNumber: 319, cardSet: cardSetId, name: 'Solemn Simulacrum', rarity: 'R', layout: 'normal' },
            { cardNumber: 320, cardSet: cardSetId, name: 'Basri, Devoted Paladin', rarity: 'M', layout: 'normal' },
            { cardNumber: 321, cardSet: cardSetId, name: 'Adherent of Hope', rarity: 'C', layout: 'normal' },
            { cardNumber: 322, cardSet: cardSetId, name: 'Basri\'s Aegis', rarity: 'R', layout: 'normal' },
            { cardNumber: 323, cardSet: cardSetId, name: 'Sigiled Contender', rarity: 'U', layout: 'normal' },
            { cardNumber: 324, cardSet: cardSetId, name: 'Teferi, Timeless Voyager', rarity: 'M', layout: 'normal' },
            { cardNumber: 325, cardSet: cardSetId, name: 'Historian of Zhalfir', rarity: 'U', layout: 'normal' },
            { cardNumber: 326, cardSet: cardSetId, name: 'Mystic Skyfish', rarity: 'C', layout: 'normal' },
            { cardNumber: 327, cardSet: cardSetId, name: 'Teferi\'s Wavecaster', rarity: 'R', layout: 'normal' },
            { cardNumber: 328, cardSet: cardSetId, name: 'Liliana, Death Mage', rarity: 'M', layout: 'normal' },
            { cardNumber: 329, cardSet: cardSetId, name: 'Liliana\'s Scorn', rarity: 'R', layout: 'normal' },
            { cardNumber: 330, cardSet: cardSetId, name: 'Liliana\'s Scrounger', rarity: 'U', layout: 'normal' },
            { cardNumber: 331, cardSet: cardSetId, name: 'Spirit of Malevolence', rarity: 'C', layout: 'normal' },
            { cardNumber: 332, cardSet: cardSetId, name: 'Chandra, Flame\'s Catalyst', rarity: 'M', layout: 'normal' },
            { cardNumber: 333, cardSet: cardSetId, name: 'Chandra\'s Firemaw', rarity: 'R', layout: 'normal' },
            { cardNumber: 334, cardSet: cardSetId, name: 'Keral Keep Disciples', rarity: 'U', layout: 'normal' },
            { cardNumber: 335, cardSet: cardSetId, name: 'Storm Caller', rarity: 'C', layout: 'normal' },
            { cardNumber: 336, cardSet: cardSetId, name: 'Garruk, Savage Herald', rarity: 'M', layout: 'normal' },
            { cardNumber: 337, cardSet: cardSetId, name: 'Garruk\'s Warsteed', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, cardSet: cardSetId, name: 'Predatory Wurm', rarity: 'U', layout: 'normal' },
            { cardNumber: 339, cardSet: cardSetId, name: 'Wildwood Patrol', rarity: 'C', layout: 'normal' },
            { cardNumber: 340, cardSet: cardSetId, name: 'Baneslayer Angel', rarity: 'M', layout: 'normal' },
            { cardNumber: 341, cardSet: cardSetId, name: 'Glorious Anthem', rarity: 'R', layout: 'normal' },
            { cardNumber: 342, cardSet: cardSetId, name: 'Idol of Endurance', rarity: 'R', layout: 'normal' },
            { cardNumber: 343, cardSet: cardSetId, name: 'Mangara, the Diplomat', rarity: 'M', layout: 'normal' },
            { cardNumber: 344, cardSet: cardSetId, name: 'Nine Lives', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, cardSet: cardSetId, name: 'Pack Leader', rarity: 'R', layout: 'normal' },
            { cardNumber: 346, cardSet: cardSetId, name: 'Runed Halo', rarity: 'R', layout: 'normal' },
            { cardNumber: 347, cardSet: cardSetId, name: 'Speaker of the Heavens', rarity: 'R', layout: 'normal' },
            { cardNumber: 348, cardSet: cardSetId, name: 'Barrin, Tolarian Archmage', rarity: 'R', layout: 'normal' },
            { cardNumber: 349, cardSet: cardSetId, name: 'Discontinuity', rarity: 'M', layout: 'normal' },
            { cardNumber: 350, cardSet: cardSetId, name: 'Ghostly Pilferer', rarity: 'R', layout: 'normal' },
            { cardNumber: 351, cardSet: cardSetId, name: 'Pursued Whale', rarity: 'R', layout: 'normal' },
            { cardNumber: 352, cardSet: cardSetId, name: 'See the Truth', rarity: 'R', layout: 'normal' },
            { cardNumber: 353, cardSet: cardSetId, name: 'Shacklegeist', rarity: 'R', layout: 'normal' },
            { cardNumber: 354, cardSet: cardSetId, name: 'Stormwing Entity', rarity: 'R', layout: 'normal' },
            { cardNumber: 355, cardSet: cardSetId, name: 'Sublime Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 356, cardSet: cardSetId, name: 'Demonic Embrace', rarity: 'R', layout: 'normal' },
            { cardNumber: 357, cardSet: cardSetId, name: 'Hooded Blightfang', rarity: 'R', layout: 'normal' },
            { cardNumber: 358, cardSet: cardSetId, name: 'Kaervek, the Spiteful', rarity: 'R', layout: 'normal' },
            { cardNumber: 359, cardSet: cardSetId, name: 'Necromentia', rarity: 'R', layout: 'normal' },
            { cardNumber: 360, cardSet: cardSetId, name: 'Peer into the Abyss', rarity: 'R', layout: 'normal' },
            { cardNumber: 361, cardSet: cardSetId, name: 'Thieves\' Guild Enforcer', rarity: 'R', layout: 'normal' },
            { cardNumber: 362, cardSet: cardSetId, name: 'Vito, Thorn of the Dusk Rose', rarity: 'R', layout: 'normal' },
            { cardNumber: 363, cardSet: cardSetId, name: 'Brash Taunter', rarity: 'R', layout: 'normal' },
            { cardNumber: 364, cardSet: cardSetId, name: 'Conspicuous Snoop', rarity: 'R', layout: 'normal' },
            { cardNumber: 365, cardSet: cardSetId, name: 'Double Vision', rarity: 'R', layout: 'normal' },
            { cardNumber: 366, cardSet: cardSetId, name: 'Fiery Emancipation', rarity: 'M', layout: 'normal' },
            { cardNumber: 367, cardSet: cardSetId, name: 'Gadrak, the Crown-Scourge', rarity: 'R', layout: 'normal' },
            { cardNumber: 368, cardSet: cardSetId, name: 'Subira, Tulzidi Caravanner', rarity: 'R', layout: 'normal' },
            { cardNumber: 369, cardSet: cardSetId, name: 'Terror of the Peaks', rarity: 'M', layout: 'normal' },
            { cardNumber: 370, cardSet: cardSetId, name: 'Transmogrify', rarity: 'R', layout: 'normal' },
            { cardNumber: 371, cardSet: cardSetId, name: 'Volcanic Salvo', rarity: 'R', layout: 'normal' },
            { cardNumber: 372, cardSet: cardSetId, name: 'Azusa, Lost but Seeking', rarity: 'R', layout: 'normal' },
            { cardNumber: 373, cardSet: cardSetId, name: 'Elder Gargaroth', rarity: 'M', layout: 'normal' },
            { cardNumber: 374, cardSet: cardSetId, name: 'Feline Sovereign', rarity: 'R', layout: 'normal' },
            { cardNumber: 375, cardSet: cardSetId, name: 'Heroic Intervention', rarity: 'R', layout: 'normal' },
            { cardNumber: 376, cardSet: cardSetId, name: 'Jolrael, Mwonvuli Recluse', rarity: 'R', layout: 'normal' },
            { cardNumber: 377, cardSet: cardSetId, name: 'Primal Might', rarity: 'R', layout: 'normal' },
            { cardNumber: 378, cardSet: cardSetId, name: 'Sporeweb Weaver', rarity: 'R', layout: 'normal' },
            { cardNumber: 379, cardSet: cardSetId, name: 'Niambi, Esteemed Speaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 380, cardSet: cardSetId, name: 'Radha, Heart of Keld', rarity: 'R', layout: 'normal' },
            { cardNumber: 381, cardSet: cardSetId, name: 'Sanctum of All', rarity: 'R', layout: 'normal' },
            { cardNumber: 382, cardSet: cardSetId, name: 'Chromatic Orrery', rarity: 'M', layout: 'normal' },
            { cardNumber: 383, cardSet: cardSetId, name: 'Mazemind Tome', rarity: 'R', layout: 'normal' },
            { cardNumber: 384, cardSet: cardSetId, name: 'Sparkhunter Masticore', rarity: 'R', layout: 'normal' },
            { cardNumber: 385, cardSet: cardSetId, name: 'Animal Sanctuary', rarity: 'R', layout: 'normal' },
            { cardNumber: 386, cardSet: cardSetId, name: 'Fabled Passage', rarity: 'R', layout: 'normal' },
            { cardNumber: 387, cardSet: cardSetId, name: 'Temple of Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 388, cardSet: cardSetId, name: 'Temple of Malady', rarity: 'R', layout: 'normal' },
            { cardNumber: 389, cardSet: cardSetId, name: 'Temple of Mystery', rarity: 'R', layout: 'normal' },
            { cardNumber: 390, cardSet: cardSetId, name: 'Temple of Silence', rarity: 'R', layout: 'normal' },
            { cardNumber: 391, cardSet: cardSetId, name: 'Temple of Triumph', rarity: 'R', layout: 'normal' },
            { cardNumber: 392, cardSet: cardSetId, name: 'Pack Leader', rarity: 'R', layout: 'normal' },
            { cardNumber: 393, cardSet: cardSetId, name: 'Selfless Savior', rarity: 'U', layout: 'normal' },
            { cardNumber: 394, cardSet: cardSetId, name: 'Frantic Inventory', rarity: 'C', layout: 'normal' },
            { cardNumber: 395, cardSet: cardSetId, name: 'Eliminate', rarity: 'U', layout: 'normal' },
            { cardNumber: 396, cardSet: cardSetId, name: 'Heartfire Immolator', rarity: 'U', layout: 'normal' },
            { cardNumber: 397, cardSet: cardSetId, name: 'Llanowar Visionary', rarity: 'C', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'M21';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
