import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingBfz1620386823589 implements MigrationInterface {
    name = 'AddingBfzMigration1620386823589';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Battle For Zendikar', shortName: 'BFZ' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Bane of Bala Ged', rarity: 'U', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Blight Herder', rarity: 'R', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Breaker of Armies', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Conduit of Ruin', rarity: 'R', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Deathless Behemoth', rarity: 'U', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Desolation Twin', rarity: 'R', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Eldrazi Devastator', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Endless One', rarity: 'R', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Gruesome Slaughter', rarity: 'R', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Kozilek\'s Channeler', rarity: 'C', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Oblivion Sower', rarity: 'M', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Ruin Processor', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Scour from Existence', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Titan\'s Presence', rarity: 'U', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Ulamog, the Ceaseless Hunger', rarity: 'M', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Ulamog\'s Despoiler', rarity: 'U', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Void Winnower', rarity: 'M', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Angel of Renewal', rarity: 'U', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Angelic Gift', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Cliffside Lookout', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Courier Griffin', rarity: 'C', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Emeria Shepherd', rarity: 'R', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Encircling Fissure', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Expedition Envoy', rarity: 'U', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Felidar Cub', rarity: 'C', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Felidar Sovereign', rarity: 'R', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Fortified Rampart', rarity: 'C', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Ghostly Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Gideon, Ally of Zendikar', rarity: 'M', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Gideon\'s Reproach', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Hero of Goma Fada', rarity: 'R', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Inspired Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Kitesail Scout', rarity: 'C', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Kor Bladewhirl', rarity: 'U', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Kor Castigator', rarity: 'C', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Kor Entanglers', rarity: 'U', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Lantern Scout', rarity: 'R', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Lithomancer\'s Focus', rarity: 'C', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Makindi Patrol', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Ondu Greathorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Ondu Rising', rarity: 'U', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Planar Outburst', rarity: 'R', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Quarantine Field', rarity: 'M', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Retreat to Emeria', rarity: 'U', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Roil\'s Retribution', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Serene Steward', rarity: 'U', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Shadow Glider', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Sheer Drop', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Smite the Monstrous', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Stasis Snare', rarity: 'U', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Stone Haven Medic', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Tandem Tactics', rarity: 'C', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Unified Front', rarity: 'U', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Adverse Conditions', rarity: 'U', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Benthic Infiltrator', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Cryptic Cruiser', rarity: 'U', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Drowner of Hope', rarity: 'R', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Eldrazi Skyspawner', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Horribly Awry', rarity: 'U', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Incubator Drone', rarity: 'C', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Mist Intruder', rarity: 'C', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Murk Strider', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Oracle of Dust', rarity: 'C', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Ruination Guide', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Salvage Drone', rarity: 'C', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Spell Shrivel', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Tide Drifter', rarity: 'U', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Ulamog\'s Reclaimer', rarity: 'U', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Anticipate', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Brilliant Spectrum', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Cloud Manta', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Clutch of Currents', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Coastal Discovery', rarity: 'U', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Coralhelm Guide', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Dampening Pulse', rarity: 'U', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Dispel', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Exert Influence', rarity: 'R', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Guardian of Tazeem', rarity: 'R', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Halimar Tidecaller', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Part the Waterveil', rarity: 'M', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Prism Array', rarity: 'R', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Retreat to Coralhelm', rarity: 'U', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Roilmage\'s Trick', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Rush of Ice', rarity: 'C', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Scatter to the Winds', rarity: 'R', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Tightening Coils', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Ugin\'s Insight', rarity: 'R', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Wave-Wing Elemental', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Windrider Patrol', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Complete Disregard', rarity: 'C', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Culling Drone', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Dominator Drone', rarity: 'C', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Grave Birthing', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Grip of Desolation', rarity: 'U', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Mind Raker', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Silent Skimmer', rarity: 'C', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Skitterskin', rarity: 'U', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Sludge Crawler', rarity: 'C', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Smothering Abomination', rarity: 'R', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Swarm Surge', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Transgress the Mind', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Wasteland Strangler', rarity: 'R', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Altar\'s Reap', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Bloodbond Vampire', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Bone Splinters', rarity: 'C', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Carrier Thrall', rarity: 'U', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Defiant Bloodlord', rarity: 'R', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Demon\'s Grasp', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Drana, Liberator of Malakir', rarity: 'M', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Dutiful Return', rarity: 'C', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Geyserfield Stalker', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Guul Draz Overseer', rarity: 'R', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Hagra Sharpshooter', rarity: 'U', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Kalastria Healer', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Kalastria Nightwatch', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Malakir Familiar', rarity: 'U', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Mire\'s Malice', rarity: 'C', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Nirkana Assassin', rarity: 'C', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Ob Nixilis Reignited', rarity: 'M', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Painful Truths', rarity: 'R', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Retreat to Hagra', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Rising Miasma', rarity: 'U', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Ruinous Path', rarity: 'R', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Vampiric Rites', rarity: 'U', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Voracious Null', rarity: 'C', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Zulaport Cutthroat', rarity: 'U', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Barrage Tyrant', rarity: 'R', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Crumble to Dust', rarity: 'U', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Kozilek\'s Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Molten Nursery', rarity: 'U', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Nettle Drone', rarity: 'C', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Processor Assault', rarity: 'U', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Serpentine Spike', rarity: 'R', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Touch of the Void', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Turn Against', rarity: 'U', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Vestige of Emrakul', rarity: 'C', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Vile Aggregate', rarity: 'U', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Akoum Firebird', rarity: 'M', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Akoum Hellkite', rarity: 'R', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Akoum Stonewaker', rarity: 'U', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Belligerent Whiptail', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Boiling Earth', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Chasm Guide', rarity: 'U', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Dragonmaster Outcast', rarity: 'M', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Firemantle Mage', rarity: 'U', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Goblin War Paint', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Lavastep Raider', rarity: 'C', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Makindi Sliderunner', rarity: 'C', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Ondu Champion', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Outnumber', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Radiant Flames', rarity: 'R', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Reckless Cohort', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Retreat to Valakut', rarity: 'U', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Rolling Thunder', rarity: 'U', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Shatterskull Recruit', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Stonefury', rarity: 'C', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Sure Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Tunneling Geopede', rarity: 'U', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Valakut Invoker', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Valakut Predator', rarity: 'C', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Volcanic Upheaval', rarity: 'C', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Zada, Hedron Grinder', rarity: 'R', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Blisterpod', rarity: 'C', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Brood Monitor', rarity: 'U', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Call the Scions', rarity: 'C', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Eyeless Watcher', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'From Beyond', rarity: 'R', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Unnatural Aggression', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Void Attendant', rarity: 'U', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Beastcaller Savant', rarity: 'R', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Broodhunter Wurm', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Earthen Arms', rarity: 'C', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Giant Mantis', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Greenwarden of Murasa', rarity: 'M', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Infuse with the Elements', rarity: 'U', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Jaddi Offshoot', rarity: 'U', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Lifespring Druid', rarity: 'C', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Murasa Ranger', rarity: 'U', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Natural Connection', rarity: 'C', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Nissa\'s Renewal', rarity: 'R', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Oran-Rief Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Oran-Rief Invoker', rarity: 'C', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Plated Crusher', rarity: 'U', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Plummet', rarity: 'C', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Reclaiming Vines', rarity: 'C', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Retreat to Kazandu', rarity: 'U', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Rot Shambler', rarity: 'U', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Scythe Leopard', rarity: 'U', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Seek the Wilds', rarity: 'C', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Snapping Gnarlid', rarity: 'C', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Swell of Growth', rarity: 'C', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Sylvan Scrying', rarity: 'U', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Tajuru Beastmaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Tajuru Stalwart', rarity: 'C', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Tajuru Warcaller', rarity: 'U', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Territorial Baloth', rarity: 'C', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Undergrowth Champion', rarity: 'M', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Woodland Wanderer', rarity: 'R', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Brood Butcher', rarity: 'R', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Brutal Expulsion', rarity: 'R', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Catacomb Sifter', rarity: 'U', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Dust Stalker', rarity: 'R', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Fathom Feeder', rarity: 'R', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Forerunner of Slaughter', rarity: 'U', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Herald of Kozilek', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Sire of Stagnation', rarity: 'M', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Ulamog\'s Nullifier', rarity: 'U', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Angelic Captain', rarity: 'R', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Bring to Light', rarity: 'R', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Drana\'s Emissary', rarity: 'U', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Grove Rumbler', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Grovetender Druids', rarity: 'U', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Kiora, Master of the Depths', rarity: 'M', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'March from the Tomb', rarity: 'R', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Munda, Ambush Leader', rarity: 'R', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Noyan Dar, Roil Shaper', rarity: 'R', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Omnath, Locus of Rage', rarity: 'M', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Resolute Blademaster', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Roil Spout', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Skyrider Elf', rarity: 'U', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Veteran Warleader', rarity: 'R', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Aligned Hedron Network', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Hedron Archive', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Hedron Blade', rarity: 'C', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Pathway Arrows', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Pilgrim\'s Eye', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Slab Hammer', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Ally Encampment', rarity: 'R', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Blighted Cataract', rarity: 'U', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Blighted Fen', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Blighted Gorge', rarity: 'U', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Blighted Steppe', rarity: 'U', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Blighted Woodland', rarity: 'U', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Canopy Vista', rarity: 'R', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Cinder Glade', rarity: 'R', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Evolving Wilds', rarity: 'C', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Fertile Thicket', rarity: 'C', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Looming Spires', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Lumbering Falls', rarity: 'R', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Mortuary Mire', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Prairie Stream', rarity: 'R', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Sanctum of Ugin', rarity: 'R', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Sandstone Bridge', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Shambling Vent', rarity: 'R', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Shrine of the Forsaken Gods', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Skyline Cascade', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Smoldering Marsh', rarity: 'R', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Spawning Bed', rarity: 'U', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Sunken Hollow', rarity: 'R', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'BFZ';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
