import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingKld1620387962198 implements MigrationInterface {
    name = 'addingKld1620387962198';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Kaladesh', shortName: 'KLD' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Acrobatic Maneuver', rarity: 'C', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Aerial Responder', rarity: 'U', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Aetherstorm Roc', rarity: 'R', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Angel of Invention', rarity: 'M', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Authority of the Consuls', rarity: 'R', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Aviary Mechanic', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Built to Last', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Captured by the Consulate', rarity: 'R', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Cataclysmic Gearhulk', rarity: 'M', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Consulate Surveillance', rarity: 'U', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Consul\'s Shieldguard', rarity: 'U', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Eddytrail Hawk', rarity: 'C', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Fairgrounds Warden', rarity: 'U', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Fragmentize', rarity: 'C', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Fumigate', rarity: 'R', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Gearshift Ace', rarity: 'U', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Glint-Sleeve Artisan', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Herald of the Fair', rarity: 'C', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Impeccable Timing', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Inspired Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Master Trinketeer', rarity: 'R', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Ninth Bridge Patrol', rarity: 'C', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Pressure Point', rarity: 'C', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Propeller Pioneer', rarity: 'C', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Refurbish', rarity: 'U', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Revoke Privileges', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Servo Exhibition', rarity: 'U', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Skyswirl Harrier', rarity: 'C', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Skywhaler\'s Shot', rarity: 'U', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Tasseled Dromedary', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Thriving Ibex', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Toolcraft Exemplar', rarity: 'R', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Trusty Companion', rarity: 'U', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Visionary Augmenter', rarity: 'U', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Wispweaver Angel', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Aether Meltdown', rarity: 'U', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Aether Theorist', rarity: 'C', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Aether Tradewinds', rarity: 'C', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Aethersquall Ancient', rarity: 'R', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Ceremonious Rejection', rarity: 'U', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Confiscation Coup', rarity: 'R', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Curio Vendor', rarity: 'C', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Disappearing Act', rarity: 'U', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Dramatic Reversal', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Era of Innovation', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Experimental Aviator', rarity: 'U', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Failed Inspection', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Gearseeker Serpent', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Glimmer of Genius', rarity: 'U', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Glint-Nest Crane', rarity: 'U', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Hightide Hermit', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Insidious Will', rarity: 'R', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Janjeet Sentry', rarity: 'U', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Long-Finned Skywhale', rarity: 'U', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Malfunction', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Metallurgic Summonings', rarity: 'M', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Minister of Inquiries', rarity: 'U', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Nimble Innovator', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Padeem, Consul of Innovation', rarity: 'R', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Paradoxical Outcome', rarity: 'R', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Revolutionary Rebuff', rarity: 'C', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Saheeli\'s Artistry', rarity: 'R', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Select for Inspection', rarity: 'C', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Shrewd Negotiation', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Tezzeret\'s Ambition', rarity: 'C', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Thriving Turtle', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Torrential Gearhulk', rarity: 'M', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Vedalken Blademaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Weldfast Wingsmith', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Wind Drake', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Aetherborn Marauder', rarity: 'U', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Ambitious Aetherborn', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Demon of Dark Schemes', rarity: 'M', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Dhund Operative', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Diabolic Tutor', rarity: 'U', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Die Young', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Dukhara Scavenger', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Eliminate the Competition', rarity: 'R', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Embraal Bruiser', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Essence Extraction', rarity: 'U', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Fortuitous Find', rarity: 'C', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Foundry Screecher', rarity: 'C', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Fretwork Colony', rarity: 'U', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Gonti, Lord of Luxury', rarity: 'R', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Harsh Scrutiny', rarity: 'U', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Lawless Broker', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Live Fast', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Lost Legacy', rarity: 'R', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Make Obsolete', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Marionette Master', rarity: 'R', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Maulfist Squad', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Midnight Oil', rarity: 'R', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Mind Rot', rarity: 'C', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Morbid Curiosity', rarity: 'U', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Night Market Lookout', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Noxious Gearhulk', rarity: 'M', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Ovalchase Daredevil', rarity: 'U', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Prakhata Club Security', rarity: 'C', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Rush of Vitality', rarity: 'C', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Subtle Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Syndicate Trafficker', rarity: 'R', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Thriving Rats', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Tidy Conclusion', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Underhanded Designs', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Weaponcraft Enthusiast', rarity: 'U', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Aethertorch Renegade', rarity: 'U', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Brazen Scourge', rarity: 'U', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Built to Smash', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Cathartic Reunion', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Chandra, Torch of Defiance', rarity: 'M', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Chandra\'s Pyrohelix', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Combustible Gearhulk', rarity: 'M', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Demolish', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Fateful Showdown', rarity: 'R', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Furious Reprisal', rarity: 'U', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Giant Spectacle', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Harnessed Lightning', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Hijack', rarity: 'C', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Incendiary Sabotage', rarity: 'U', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Inventor\'s Apprentice', rarity: 'U', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Lathnu Hellion', rarity: 'R', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Madcap Experiment', rarity: 'R', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Maulfist Doorbuster', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Pia Nalaar', rarity: 'R', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Quicksmith Genius', rarity: 'U', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Reckless Fireweaver', rarity: 'C', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Renegade Tactics', rarity: 'C', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Ruinous Gremlin', rarity: 'C', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Salivating Gremlins', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Skyship Stalker', rarity: 'R', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Spark of Creativity', rarity: 'U', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Speedway Fanatic', rarity: 'U', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Spireside Infiltrator', rarity: 'C', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Spontaneous Artist', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Start Your Engines', rarity: 'U', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Territorial Gorger', rarity: 'R', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Terror of the Fairgrounds', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Thriving Grubs', rarity: 'C', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Wayward Giant', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Welding Sparks', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Appetite for the Unnatural', rarity: 'C', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Arborback Stomper', rarity: 'U', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Architect of the Untamed', rarity: 'R', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Armorcraft Judge', rarity: 'U', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Attune with Aether', rarity: 'C', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Blossoming Defense', rarity: 'U', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Bristling Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Commencement of Festivities', rarity: 'C', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Cowl Prowler', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Creeping Mold', rarity: 'U', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Cultivator of Blades', rarity: 'R', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Dubious Challenge', rarity: 'R', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Durable Handicraft', rarity: 'U', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Elegant Edgecrafters', rarity: 'U', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Fairgrounds Trumpeter', rarity: 'U', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Ghirapur Guide', rarity: 'U', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Highspire Artisan', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Hunt the Weak', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Kujar Seedsculptor', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Larger Than Life', rarity: 'C', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Longtusk Cub', rarity: 'U', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Nature\'s Way', rarity: 'U', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Nissa, Vital Force', rarity: 'M', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Ornamental Courage', rarity: 'C', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Oviya Pashiri, Sage Lifecrafter', rarity: 'R', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Peema Outrider', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Riparian Tiger', rarity: 'C', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Sage of Shaila\'s Claim', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Servant of the Conduit', rarity: 'U', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Take Down', rarity: 'C', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Thriving Rhino', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Verdurous Gearhulk', rarity: 'M', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Wild Wanderer', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Wildest Dreams', rarity: 'R', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Wily Bandar', rarity: 'C', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Cloudblazer', rarity: 'U', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Contraband Kingpin', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Depala, Pilot Exemplar', rarity: 'R', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Dovin Baan', rarity: 'M', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Empyreal Voyager', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Engineered Might', rarity: 'U', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Hazardous Conditions', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Kambal, Consul of Allocation', rarity: 'R', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Rashmi, Eternities Crafter', rarity: 'M', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Restoration Gearsmith', rarity: 'U', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Saheeli Rai', rarity: 'M', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'Unlicensed Disintegration', rarity: 'U', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'Veteran Motorist', rarity: 'U', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Voltaic Brawler', rarity: 'U', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Whirler Virtuoso', rarity: 'U', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Accomplished Automaton', rarity: 'C', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Aetherflux Reservoir', rarity: 'R', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Aetherworks Marvel', rarity: 'M', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Animation Module', rarity: 'R', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Aradara Express', rarity: 'C', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Ballista Charger', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Bastion Mastodon', rarity: 'C', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Bomat Bazaar Barge', rarity: 'U', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Bomat Courier', rarity: 'R', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Chief of the Foundry', rarity: 'U', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Cogworker\'s Puzzleknot', rarity: 'C', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Consulate Skygate', rarity: 'C', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Cultivator\'s Caravan', rarity: 'R', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Deadlock Trap', rarity: 'R', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Decoction Module', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Demolition Stomper', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Dukhara Peafowl', rarity: 'C', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Dynavolt Tower', rarity: 'R', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Eager Construct', rarity: 'C', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Electrostatic Pummeler', rarity: 'R', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Fabrication Module', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Filigree Familiar', rarity: 'U', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Fireforger\'s Puzzleknot', rarity: 'C', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Fleetwheel Cruiser', rarity: 'R', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Foundry Inspector', rarity: 'U', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Ghirapur Orrery', rarity: 'R', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Glassblower\'s Puzzleknot', rarity: 'C', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Inventor\'s Goggles', rarity: 'C', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Iron League Steed', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Key to the City', rarity: 'R', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Metalspinner\'s Puzzleknot', rarity: 'C', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Metalwork Colossus', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Multiform Wonder', rarity: 'R', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Narnam Cobra', rarity: 'C', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Ovalchase Dragster', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Panharmonicon', rarity: 'R', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Perpetual Timepiece', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Prakhata Pillar-Bug', rarity: 'C', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Prophetic Prism', rarity: 'C', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Renegade Freighter', rarity: 'C', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Scrapheap Scrounger', rarity: 'R', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Self-Assembler', rarity: 'C', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Sky Skiff', rarity: 'C', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Skysovereign, Consul Flagship', rarity: 'M', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Smuggler\'s Copter', rarity: 'R', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Snare Thopter', rarity: 'U', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'Torch Gauntlet', rarity: 'C', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Weldfast Monitor', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Whirlermaker', rarity: 'U', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Woodweaver\'s Puzzleknot', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Workshop Assistant', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Aether Hub', rarity: 'U', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Blooming Marsh', rarity: 'R', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Botanical Sanctum', rarity: 'R', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Concealed Courtyard', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Inspiring Vantage', rarity: 'R', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Inventors\' Fair', rarity: 'R', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Sequestered Stash', rarity: 'U', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Spirebluff Canal', rarity: 'R', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Chandra, Pyrogenius', rarity: 'M', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Flame Lash', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Liberating Combustion', rarity: 'R', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Renegade Firebrand', rarity: 'U', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Stone Quarry', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Nissa, Nature\'s Artisan', rarity: 'M', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Guardian of the Great Conduit', rarity: 'U', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Terrain Elemental', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Verdant Crescendo', rarity: 'R', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Woodland Stream', rarity: 'C', layout: 'normal' },
        ]).execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'KLD';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
