import { CardSet } from "../card/entity/card-set.entity";
import { InsertResult, MigrationInterface, QueryRunner } from "typeorm";

export class addingIko1620400921320 implements MigrationInterface {
    name = 'addingIko1620400921320';

    public async up(queryRunner: QueryRunner): Promise<void> {

        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Ikoria: Lair of Behemoths', shortName: 'IKO' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager.createQueryBuilder().insert().into('card').values([
            { cardNumber: 1, cardSet: cardSetId, name: 'Adaptive Shimmerer', rarity: 'C', layout: 'normal' },
            { cardNumber: 2, cardSet: cardSetId, name: 'Farfinder', rarity: 'C', layout: 'normal' },
            { cardNumber: 3, cardSet: cardSetId, name: 'Mysterious Egg', rarity: 'C', layout: 'normal' },
            { cardNumber: 4, cardSet: cardSetId, name: 'Blade Banish', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, cardSet: cardSetId, name: 'Checkpoint Officer', rarity: 'C', layout: 'normal' },
            { cardNumber: 6, cardSet: cardSetId, name: 'Coordinated Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, cardSet: cardSetId, name: 'Cubwarden', rarity: 'R', layout: 'normal' },
            { cardNumber: 8, cardSet: cardSetId, name: 'Daysquad Marshal', rarity: 'C', layout: 'normal' },
            { cardNumber: 9, cardSet: cardSetId, name: 'Divine Arrow', rarity: 'C', layout: 'normal' },
            { cardNumber: 10, cardSet: cardSetId, name: 'Drannith Healer', rarity: 'C', layout: 'normal' },
            { cardNumber: 11, cardSet: cardSetId, name: 'Drannith Magistrate', rarity: 'R', layout: 'normal' },
            { cardNumber: 12, cardSet: cardSetId, name: 'Fight as One', rarity: 'U', layout: 'normal' },
            { cardNumber: 13, cardSet: cardSetId, name: 'Flourishing Fox', rarity: 'U', layout: 'normal' },
            { cardNumber: 14, cardSet: cardSetId, name: 'Garrison Cat', rarity: 'C', layout: 'normal' },
            { cardNumber: 15, cardSet: cardSetId, name: 'Helica Glider', rarity: 'C', layout: 'normal' },
            { cardNumber: 16, cardSet: cardSetId, name: 'Huntmaster Liger', rarity: 'U', layout: 'normal' },
            { cardNumber: 17, cardSet: cardSetId, name: 'Imposing Vantasaur', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, cardSet: cardSetId, name: 'Keensight Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 19, cardSet: cardSetId, name: 'Lavabrink Venturer', rarity: 'R', layout: 'normal' },
            { cardNumber: 20, cardSet: cardSetId, name: 'Light of Hope', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, cardSet: cardSetId, name: 'Luminous Broodmoth', rarity: 'M', layout: 'normal' },
            { cardNumber: 22, cardSet: cardSetId, name: 'Majestic Auricorn', rarity: 'U', layout: 'normal' },
            { cardNumber: 23, cardSet: cardSetId, name: 'Maned Serval', rarity: 'C', layout: 'normal' },
            { cardNumber: 24, cardSet: cardSetId, name: 'Mythos of Snapdax', rarity: 'R', layout: 'normal' },
            { cardNumber: 25, cardSet: cardSetId, name: 'Pacifism', rarity: 'C', layout: 'normal' },
            { cardNumber: 26, cardSet: cardSetId, name: 'Patagia Tiger', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, cardSet: cardSetId, name: 'Perimeter Sergeant', rarity: 'C', layout: 'normal' },
            { cardNumber: 28, cardSet: cardSetId, name: 'Sanctuary Lockdown', rarity: 'U', layout: 'normal' },
            { cardNumber: 29, cardSet: cardSetId, name: 'Savai Sabertooth', rarity: 'C', layout: 'normal' },
            { cardNumber: 30, cardSet: cardSetId, name: 'Snare Tactician', rarity: 'C', layout: 'normal' },
            { cardNumber: 31, cardSet: cardSetId, name: 'Solid Footing', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, cardSet: cardSetId, name: 'Splendor Mare', rarity: 'U', layout: 'normal' },
            { cardNumber: 33, cardSet: cardSetId, name: 'Spontaneous Flight', rarity: 'C', layout: 'normal' },
            { cardNumber: 34, cardSet: cardSetId, name: 'Stormwild Capridor', rarity: 'U', layout: 'normal' },
            { cardNumber: 35, cardSet: cardSetId, name: 'Swallow Whole', rarity: 'U', layout: 'normal' },
            { cardNumber: 36, cardSet: cardSetId, name: 'Valiant Rescuer', rarity: 'U', layout: 'normal' },
            { cardNumber: 37, cardSet: cardSetId, name: 'Vulpikeet', rarity: 'C', layout: 'normal' },
            { cardNumber: 38, cardSet: cardSetId, name: 'Will of the All-Hunter', rarity: 'U', layout: 'normal' },
            { cardNumber: 39, cardSet: cardSetId, name: 'Aegis Turtle', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, cardSet: cardSetId, name: 'Anticipate', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, cardSet: cardSetId, name: 'Archipelagore', rarity: 'U', layout: 'normal' },
            { cardNumber: 42, cardSet: cardSetId, name: 'Avian Oddity', rarity: 'U', layout: 'normal' },
            { cardNumber: 43, cardSet: cardSetId, name: 'Boon of the Wish-Giver', rarity: 'U', layout: 'normal' },
            { cardNumber: 44, cardSet: cardSetId, name: 'Capture Sphere', rarity: 'C', layout: 'normal' },
            { cardNumber: 45, cardSet: cardSetId, name: 'Convolute', rarity: 'C', layout: 'normal' },
            { cardNumber: 46, cardSet: cardSetId, name: 'Crystacean', rarity: 'C', layout: 'normal' },
            { cardNumber: 47, cardSet: cardSetId, name: 'Dreamtail Heron', rarity: 'C', layout: 'normal' },
            { cardNumber: 48, cardSet: cardSetId, name: 'Escape Protocol', rarity: 'U', layout: 'normal' },
            { cardNumber: 49, cardSet: cardSetId, name: 'Essence Scatter', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, cardSet: cardSetId, name: 'Facet Reader', rarity: 'C', layout: 'normal' },
            { cardNumber: 51, cardSet: cardSetId, name: 'Frost Lynx', rarity: 'C', layout: 'normal' },
            { cardNumber: 52, cardSet: cardSetId, name: 'Frostveil Ambush', rarity: 'C', layout: 'normal' },
            { cardNumber: 53, cardSet: cardSetId, name: 'Glimmerbell', rarity: 'C', layout: 'normal' },
            { cardNumber: 54, cardSet: cardSetId, name: 'Gust of Wind', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, cardSet: cardSetId, name: 'Hampering Snare', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, cardSet: cardSetId, name: 'Keep Safe', rarity: 'C', layout: 'normal' },
            { cardNumber: 57, cardSet: cardSetId, name: 'Mystic Subdual', rarity: 'U', layout: 'normal' },
            { cardNumber: 58, cardSet: cardSetId, name: 'Mythos of Illuna', rarity: 'R', layout: 'normal' },
            { cardNumber: 59, cardSet: cardSetId, name: 'Neutralize', rarity: 'U', layout: 'normal' },
            { cardNumber: 60, cardSet: cardSetId, name: 'Of One Mind', rarity: 'C', layout: 'normal' },
            { cardNumber: 61, cardSet: cardSetId, name: 'Ominous Seas', rarity: 'U', layout: 'normal' },
            { cardNumber: 62, cardSet: cardSetId, name: 'Phase Dolphin', rarity: 'C', layout: 'normal' },
            { cardNumber: 63, cardSet: cardSetId, name: 'Pollywog Symbiote', rarity: 'U', layout: 'normal' },
            { cardNumber: 64, cardSet: cardSetId, name: 'Pouncing Shoreshark', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, cardSet: cardSetId, name: 'Reconnaissance Mission', rarity: 'U', layout: 'normal' },
            { cardNumber: 66, cardSet: cardSetId, name: 'Sea-Dasher Octopus', rarity: 'R', layout: 'normal' },
            { cardNumber: 67, cardSet: cardSetId, name: 'Shark Typhoon', rarity: 'R', layout: 'normal' },
            { cardNumber: 68, cardSet: cardSetId, name: 'Startling Development', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, cardSet: cardSetId, name: 'Thieving Otter', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, cardSet: cardSetId, name: 'Voracious Greatshark', rarity: 'R', layout: 'normal' },
            { cardNumber: 71, cardSet: cardSetId, name: 'Wingfold Pteron', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, cardSet: cardSetId, name: 'Wingspan Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 73, cardSet: cardSetId, name: 'Bastion of Remembrance', rarity: 'U', layout: 'normal' },
            { cardNumber: 74, cardSet: cardSetId, name: 'Blitz Leech', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, cardSet: cardSetId, name: 'Blood Curdle', rarity: 'C', layout: 'normal' },
            { cardNumber: 76, cardSet: cardSetId, name: 'Boot Nipper', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, cardSet: cardSetId, name: 'Bushmeat Poacher', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, cardSet: cardSetId, name: 'Call of the Death-Dweller', rarity: 'U', layout: 'normal' },
            { cardNumber: 79, cardSet: cardSetId, name: 'Cavern Whisperer', rarity: 'C', layout: 'normal' },
            { cardNumber: 80, cardSet: cardSetId, name: 'Chittering Harvester', rarity: 'U', layout: 'normal' },
            { cardNumber: 81, cardSet: cardSetId, name: 'Corpse Churn', rarity: 'C', layout: 'normal' },
            { cardNumber: 82, cardSet: cardSetId, name: 'Dark Bargain', rarity: 'C', layout: 'normal' },
            { cardNumber: 83, cardSet: cardSetId, name: 'Dead Weight', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, cardSet: cardSetId, name: 'Dirge Bat', rarity: 'R', layout: 'normal' },
            { cardNumber: 85, cardSet: cardSetId, name: 'Durable Coilbug', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, cardSet: cardSetId, name: 'Duskfang Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 87, cardSet: cardSetId, name: 'Easy Prey', rarity: 'U', layout: 'normal' },
            { cardNumber: 88, cardSet: cardSetId, name: 'Extinction Event', rarity: 'R', layout: 'normal' },
            { cardNumber: 89, cardSet: cardSetId, name: 'Gloom Pangolin', rarity: 'C', layout: 'normal' },
            { cardNumber: 90, cardSet: cardSetId, name: 'Grimdancer', rarity: 'U', layout: 'normal' },
            { cardNumber: 91, cardSet: cardSetId, name: 'Heartless Act', rarity: 'U', layout: 'normal' },
            { cardNumber: 92, cardSet: cardSetId, name: 'Hunted Nightmare', rarity: 'R', layout: 'normal' },
            { cardNumber: 93, cardSet: cardSetId, name: 'Insatiable Hemophage', rarity: 'U', layout: 'normal' },
            { cardNumber: 94, cardSet: cardSetId, name: 'Lurking Deadeye', rarity: 'C', layout: 'normal' },
            { cardNumber: 95, cardSet: cardSetId, name: 'Memory Leak', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, cardSet: cardSetId, name: 'Mutual Destruction', rarity: 'C', layout: 'normal' },
            { cardNumber: 97, cardSet: cardSetId, name: 'Mythos of Nethroi', rarity: 'R', layout: 'normal' },
            { cardNumber: 98, cardSet: cardSetId, name: 'Nightsquad Commando', rarity: 'C', layout: 'normal' },
            { cardNumber: 99, cardSet: cardSetId, name: 'Serrated Scorpion', rarity: 'C', layout: 'normal' },
            { cardNumber: 100, cardSet: cardSetId, name: 'Suffocating Fumes', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, cardSet: cardSetId, name: 'Unbreakable Bond', rarity: 'U', layout: 'normal' },
            { cardNumber: 102, cardSet: cardSetId, name: 'Unexpected Fangs', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, cardSet: cardSetId, name: 'Unlikely Aid', rarity: 'C', layout: 'normal' },
            { cardNumber: 104, cardSet: cardSetId, name: 'Void Beckoner', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, cardSet: cardSetId, name: 'Whisper Squad', rarity: 'C', layout: 'normal' },
            { cardNumber: 106, cardSet: cardSetId, name: 'Zagoth Mamba', rarity: 'U', layout: 'normal' },
            { cardNumber: 107, cardSet: cardSetId, name: 'Blazing Volley', rarity: 'C', layout: 'normal' },
            { cardNumber: 108, cardSet: cardSetId, name: 'Blisterspit Gremlin', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, cardSet: cardSetId, name: 'Blitz of the Thunder-Raptor', rarity: 'U', layout: 'normal' },
            { cardNumber: 110, cardSet: cardSetId, name: 'Cathartic Reunion', rarity: 'C', layout: 'normal' },
            { cardNumber: 111, cardSet: cardSetId, name: 'Clash of Titans', rarity: 'U', layout: 'normal' },
            { cardNumber: 112, cardSet: cardSetId, name: 'Cloudpiercer', rarity: 'C', layout: 'normal' },
            { cardNumber: 113, cardSet: cardSetId, name: 'Drannith Stinger', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, cardSet: cardSetId, name: 'Everquill Phoenix', rarity: 'R', layout: 'normal' },
            { cardNumber: 115, cardSet: cardSetId, name: 'Ferocious Tigorilla', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, cardSet: cardSetId, name: 'Fire Prophecy', rarity: 'C', layout: 'normal' },
            { cardNumber: 117, cardSet: cardSetId, name: 'Flame Spill', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, cardSet: cardSetId, name: 'Footfall Crater', rarity: 'U', layout: 'normal' },
            { cardNumber: 119, cardSet: cardSetId, name: 'Forbidden Friendship', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, cardSet: cardSetId, name: 'Frenzied Raptor', rarity: 'C', layout: 'normal' },
            { cardNumber: 121, cardSet: cardSetId, name: 'Frillscare Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, cardSet: cardSetId, name: 'Go for Blood', rarity: 'C', layout: 'normal' },
            { cardNumber: 123, cardSet: cardSetId, name: 'Heightened Reflexes', rarity: 'C', layout: 'normal' },
            { cardNumber: 124, cardSet: cardSetId, name: 'Lava Serpent', rarity: 'C', layout: 'normal' },
            { cardNumber: 125, cardSet: cardSetId, name: 'Lukka, Coppercoat Outcast', rarity: 'M', layout: 'normal' },
            { cardNumber: 126, cardSet: cardSetId, name: 'Momentum Rumbler', rarity: 'U', layout: 'normal' },
            { cardNumber: 127, cardSet: cardSetId, name: 'Mythos of Vadrok', rarity: 'R', layout: 'normal' },
            { cardNumber: 128, cardSet: cardSetId, name: 'Porcuparrot', rarity: 'U', layout: 'normal' },
            { cardNumber: 129, cardSet: cardSetId, name: 'Prickly Marmoset', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, cardSet: cardSetId, name: 'Pyroceratops', rarity: 'C', layout: 'normal' },
            { cardNumber: 131, cardSet: cardSetId, name: 'Raking Claws', rarity: 'C', layout: 'normal' },
            { cardNumber: 132, cardSet: cardSetId, name: 'Reptillian Reflection', rarity: 'U', layout: 'normal' },
            { cardNumber: 133, cardSet: cardSetId, name: 'Rooting Moloch', rarity: 'U', layout: 'normal' },
            { cardNumber: 134, cardSet: cardSetId, name: 'Rumbling Rockslide', rarity: 'C', layout: 'normal' },
            { cardNumber: 135, cardSet: cardSetId, name: 'Sanctuary Smasher', rarity: 'U', layout: 'normal' },
            { cardNumber: 136, cardSet: cardSetId, name: 'Shredded Sails', rarity: 'C', layout: 'normal' },
            { cardNumber: 137, cardSet: cardSetId, name: 'Spelleater Wolverine', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, cardSet: cardSetId, name: 'Tentative Connection', rarity: 'C', layout: 'normal' },
            { cardNumber: 139, cardSet: cardSetId, name: 'Unpredictable Cyclone', rarity: 'R', layout: 'normal' },
            { cardNumber: 140, cardSet: cardSetId, name: 'Weaponize the Monsters', rarity: 'U', layout: 'normal' },
            { cardNumber: 141, cardSet: cardSetId, name: 'Yidaro, Wandering Monster', rarity: 'R', layout: 'normal' },
            { cardNumber: 142, cardSet: cardSetId, name: 'Adventurous Impulse', rarity: 'C', layout: 'normal' },
            { cardNumber: 143, cardSet: cardSetId, name: 'Almighty Brushwagg', rarity: 'C', layout: 'normal' },
            { cardNumber: 144, cardSet: cardSetId, name: 'Auspicious Starrix', rarity: 'U', layout: 'normal' },
            { cardNumber: 145, cardSet: cardSetId, name: 'Barrier Breach', rarity: 'U', layout: 'normal' },
            { cardNumber: 146, cardSet: cardSetId, name: 'Bristling Boar', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, cardSet: cardSetId, name: 'Charge of the Forever-Beast', rarity: 'U', layout: 'normal' },
            { cardNumber: 148, cardSet: cardSetId, name: 'Colossification', rarity: 'R', layout: 'normal' },
            { cardNumber: 149, cardSet: cardSetId, name: 'Essence Symbiote', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, cardSet: cardSetId, name: 'Excavation Mole', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, cardSet: cardSetId, name: 'Exuberant Wolfbear', rarity: 'U', layout: 'normal' },
            { cardNumber: 152, cardSet: cardSetId, name: 'Fertilid', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, cardSet: cardSetId, name: 'Flycatcher Giraffid', rarity: 'C', layout: 'normal' },
            { cardNumber: 154, cardSet: cardSetId, name: 'Fully Grown', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, cardSet: cardSetId, name: 'Gemrazer', rarity: 'R', layout: 'normal' },
            { cardNumber: 156, cardSet: cardSetId, name: 'Glowstone Recluse', rarity: 'U', layout: 'normal' },
            { cardNumber: 157, cardSet: cardSetId, name: 'Greater Sandwurm', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, cardSet: cardSetId, name: 'Honey Mammoth', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, cardSet: cardSetId, name: 'Hornbash Mentor', rarity: 'U', layout: 'normal' },
            { cardNumber: 160, cardSet: cardSetId, name: 'Humble Naturalist', rarity: 'C', layout: 'normal' },
            { cardNumber: 161, cardSet: cardSetId, name: 'Ivy Elemental', rarity: 'U', layout: 'normal' },
            { cardNumber: 162, cardSet: cardSetId, name: 'Kogla, the Titan Ape', rarity: 'R', layout: 'normal' },
            { cardNumber: 163, cardSet: cardSetId, name: 'Lead the Stampede', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, cardSet: cardSetId, name: 'Migration Path', rarity: 'U', layout: 'normal' },
            { cardNumber: 165, cardSet: cardSetId, name: 'Migratory Greathorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 166, cardSet: cardSetId, name: 'Monstrous Step', rarity: 'U', layout: 'normal' },
            { cardNumber: 167, cardSet: cardSetId, name: 'Mosscoat Goriak', rarity: 'C', layout: 'normal' },
            { cardNumber: 168, cardSet: cardSetId, name: 'Mythos of Brokkos', rarity: 'R', layout: 'normal' },
            { cardNumber: 169, cardSet: cardSetId, name: 'Plummet', rarity: 'C', layout: 'normal' },
            { cardNumber: 170, cardSet: cardSetId, name: 'Ram Through', rarity: 'C', layout: 'normal' },
            { cardNumber: 171, cardSet: cardSetId, name: 'Sudden Spinnerets', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, cardSet: cardSetId, name: 'Survivor\'s Bond', rarity: 'C', layout: 'normal' },
            { cardNumber: 173, cardSet: cardSetId, name: 'Thwart the Enemy', rarity: 'C', layout: 'normal' },
            { cardNumber: 174, cardSet: cardSetId, name: 'Titanoth Rex', rarity: 'U', layout: 'normal' },
            { cardNumber: 175, cardSet: cardSetId, name: 'Vivien, Monsters\' Advocate', rarity: 'M', layout: 'normal' },
            { cardNumber: 176, cardSet: cardSetId, name: 'Wilt', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, cardSet: cardSetId, name: 'Back for More', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, cardSet: cardSetId, name: 'Boneyard Lurker', rarity: 'U', layout: 'normal' },
            { cardNumber: 179, cardSet: cardSetId, name: 'Brokkos, Apex of Forever', rarity: 'M', layout: 'normal' },
            { cardNumber: 180, cardSet: cardSetId, name: 'Channeled Force', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, cardSet: cardSetId, name: 'Chevill, Bane of Monsters', rarity: 'M', layout: 'normal' },
            { cardNumber: 182, cardSet: cardSetId, name: 'Death\'s Oasis', rarity: 'R', layout: 'normal' },
            { cardNumber: 183, cardSet: cardSetId, name: 'Dire Tactics', rarity: 'U', layout: 'normal' },
            { cardNumber: 184, cardSet: cardSetId, name: 'Eerie Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 185, cardSet: cardSetId, name: 'Emergent Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, cardSet: cardSetId, name: 'Frondland Felidar', rarity: 'R', layout: 'normal' },
            { cardNumber: 187, cardSet: cardSetId, name: 'General Kudro of Drannith', rarity: 'M', layout: 'normal' },
            { cardNumber: 188, cardSet: cardSetId, name: 'General\'s Enforcer', rarity: 'U', layout: 'normal' },
            { cardNumber: 189, cardSet: cardSetId, name: 'Genesis Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 190, cardSet: cardSetId, name: 'Illuna, Apex of Wishes', rarity: 'M', layout: 'normal' },
            { cardNumber: 191, cardSet: cardSetId, name: 'Inspired Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 192, cardSet: cardSetId, name: 'Kinnan, Bonder Prodigy', rarity: 'M', layout: 'normal' },
            { cardNumber: 193, cardSet: cardSetId, name: 'Labyrinth Raptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 194, cardSet: cardSetId, name: 'Lore Drakkis', rarity: 'U', layout: 'normal' },
            { cardNumber: 195, cardSet: cardSetId, name: 'Narset of the Ancient Way', rarity: 'M', layout: 'normal' },
            { cardNumber: 196, cardSet: cardSetId, name: 'Necropanther', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, cardSet: cardSetId, name: 'Nethroi, Apex of Death', rarity: 'M', layout: 'normal' },
            { cardNumber: 198, cardSet: cardSetId, name: 'Offspring\'s Revenge', rarity: 'R', layout: 'normal' },
            { cardNumber: 199, cardSet: cardSetId, name: 'Parcelbeast', rarity: 'U', layout: 'normal' },
            { cardNumber: 200, cardSet: cardSetId, name: 'Primal Empathy', rarity: 'U', layout: 'normal' },
            { cardNumber: 201, cardSet: cardSetId, name: 'Quartzwood Crasher', rarity: 'R', layout: 'normal' },
            { cardNumber: 202, cardSet: cardSetId, name: 'Regal Leosaur', rarity: 'U', layout: 'normal' },
            { cardNumber: 203, cardSet: cardSetId, name: 'Rielle, the Everwise', rarity: 'M', layout: 'normal' },
            { cardNumber: 204, cardSet: cardSetId, name: 'Ruinous Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 205, cardSet: cardSetId, name: 'Savai Thundermane', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, cardSet: cardSetId, name: 'Skull Prophet', rarity: 'U', layout: 'normal' },
            { cardNumber: 207, cardSet: cardSetId, name: 'Skycat Sovereign', rarity: 'R', layout: 'normal' },
            { cardNumber: 208, cardSet: cardSetId, name: 'Slitherwisp', rarity: 'R', layout: 'normal' },
            { cardNumber: 209, cardSet: cardSetId, name: 'Snapdax, Apex of the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 210, cardSet: cardSetId, name: 'Song of Creation', rarity: 'R', layout: 'normal' },
            { cardNumber: 211, cardSet: cardSetId, name: 'Sprite Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, cardSet: cardSetId, name: 'Titans\' Nest', rarity: 'R', layout: 'normal' },
            { cardNumber: 213, cardSet: cardSetId, name: 'Trumpeting Gnarr', rarity: 'U', layout: 'normal' },
            { cardNumber: 214, cardSet: cardSetId, name: 'Vadrok, Apex of Thunder', rarity: 'M', layout: 'normal' },
            { cardNumber: 215, cardSet: cardSetId, name: 'Whirlwind of Thought', rarity: 'R', layout: 'normal' },
            { cardNumber: 216, cardSet: cardSetId, name: 'Winota, Joiner of Forces', rarity: 'M', layout: 'normal' },
            { cardNumber: 217, cardSet: cardSetId, name: 'Zenith Flare', rarity: 'U', layout: 'normal' },
            { cardNumber: 218, cardSet: cardSetId, name: 'Alert Heedbonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, cardSet: cardSetId, name: 'Cunning Nightbonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 220, cardSet: cardSetId, name: 'Fiend Artisan', rarity: 'M', layout: 'normal' },
            { cardNumber: 221, cardSet: cardSetId, name: 'Gyruda, Doom of Depths', rarity: 'R', layout: 'normal' },
            { cardNumber: 222, cardSet: cardSetId, name: 'Jegantha, the Wellspring', rarity: 'R', layout: 'normal' },
            { cardNumber: 223, cardSet: cardSetId, name: 'Jubilant Skybonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 224, cardSet: cardSetId, name: 'Kaheera, the Orphanguard', rarity: 'R', layout: 'normal' },
            { cardNumber: 225, cardSet: cardSetId, name: 'Keruga, the Macrosage', rarity: 'R', layout: 'normal' },
            { cardNumber: 226, cardSet: cardSetId, name: 'Lurrus of the Dream-Den', rarity: 'R', layout: 'normal' },
            { cardNumber: 227, cardSet: cardSetId, name: 'Lutri, the Spellchaser', rarity: 'R', layout: 'normal' },
            { cardNumber: 228, cardSet: cardSetId, name: 'Obosh, the Preypiercer', rarity: 'R', layout: 'normal' },
            { cardNumber: 229, cardSet: cardSetId, name: 'Proud Wildbonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 230, cardSet: cardSetId, name: 'Sonorous Howlbonder', rarity: 'U', layout: 'normal' },
            { cardNumber: 231, cardSet: cardSetId, name: 'Umori, the Collector', rarity: 'R', layout: 'normal' },
            { cardNumber: 232, cardSet: cardSetId, name: 'Yorion, Sky Nomad', rarity: 'R', layout: 'normal' },
            { cardNumber: 233, cardSet: cardSetId, name: 'Zirda, the Dawnwaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 234, cardSet: cardSetId, name: 'Crystalline Giant', rarity: 'R', layout: 'normal' },
            { cardNumber: 235, cardSet: cardSetId, name: 'Indatha Crystal', rarity: 'U', layout: 'normal' },
            { cardNumber: 236, cardSet: cardSetId, name: 'Ketria Crystal', rarity: 'U', layout: 'normal' },
            { cardNumber: 237, cardSet: cardSetId, name: 'The Ozolith', rarity: 'R', layout: 'normal' },
            { cardNumber: 238, cardSet: cardSetId, name: 'Raugrin Crystal', rarity: 'U', layout: 'normal' },
            { cardNumber: 239, cardSet: cardSetId, name: 'Savai Crystal', rarity: 'U', layout: 'normal' },
            { cardNumber: 240, cardSet: cardSetId, name: 'Sleeper Dart', rarity: 'C', layout: 'normal' },
            { cardNumber: 241, cardSet: cardSetId, name: 'Springjaw Trap', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, cardSet: cardSetId, name: 'Zagoth Crystal', rarity: 'U', layout: 'normal' },
            { cardNumber: 243, cardSet: cardSetId, name: 'Bloodfell Caves', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, cardSet: cardSetId, name: 'Blossoming Sands', rarity: 'C', layout: 'normal' },
            { cardNumber: 245, cardSet: cardSetId, name: 'Bonder\'s Enclave', rarity: 'R', layout: 'normal' },
            { cardNumber: 246, cardSet: cardSetId, name: 'Dismal Backwater', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, cardSet: cardSetId, name: 'Evolving Wilds', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, cardSet: cardSetId, name: 'Indatha Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 249, cardSet: cardSetId, name: 'Jungle Hollow', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, cardSet: cardSetId, name: 'Ketria Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 251, cardSet: cardSetId, name: 'Raugrin Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 252, cardSet: cardSetId, name: 'Rugged Highlands', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, cardSet: cardSetId, name: 'Savai Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 254, cardSet: cardSetId, name: 'Scoured Barrens', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, cardSet: cardSetId, name: 'Swiftwater Cliffs', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, cardSet: cardSetId, name: 'Thornwood Falls', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, cardSet: cardSetId, name: 'Tranquil Cove', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, cardSet: cardSetId, name: 'Wind-Scarred Crag', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, cardSet: cardSetId, name: 'Zagoth Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 260, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 262, cardSet: cardSetId, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, cardSet: cardSetId, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, cardSet: cardSetId, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, cardSet: cardSetId, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, cardSet: cardSetId, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, cardSet: cardSetId, name: 'Zilortha, Strength Incarnate', rarity: 'M', layout: 'normal' },
            { cardNumber: 276, cardSet: cardSetId, name: 'Lukka, Coppercoat Outcast', rarity: 'M', layout: 'normal' },
            { cardNumber: 277, cardSet: cardSetId, name: 'Vivien, Monsters\' Advocate', rarity: 'M', layout: 'normal' },
            { cardNumber: 278, cardSet: cardSetId, name: 'Narset of the Ancient Way', rarity: 'M', layout: 'normal' },
            { cardNumber: 279, cardSet: cardSetId, name: 'Cubwarden', rarity: 'R', layout: 'normal' },
            { cardNumber: 280, cardSet: cardSetId, name: 'Huntmaster Liger', rarity: 'U', layout: 'normal' },
            { cardNumber: 281, cardSet: cardSetId, name: 'Majestic Auricorn', rarity: 'U', layout: 'normal' },
            { cardNumber: 282, cardSet: cardSetId, name: 'Vulpikeet', rarity: 'C', layout: 'normal' },
            { cardNumber: 283, cardSet: cardSetId, name: 'Archipelagore', rarity: 'U', layout: 'normal' },
            { cardNumber: 284, cardSet: cardSetId, name: 'Dreamtail Heron', rarity: 'C', layout: 'normal' },
            { cardNumber: 285, cardSet: cardSetId, name: 'Pouncing Shoreshark', rarity: 'U', layout: 'normal' },
            { cardNumber: 286, cardSet: cardSetId, name: 'Sea-Dasher Octopus', rarity: 'R', layout: 'normal' },
            { cardNumber: 287, cardSet: cardSetId, name: 'Cavern Whisperer', rarity: 'C', layout: 'normal' },
            { cardNumber: 288, cardSet: cardSetId, name: 'Chittering Harvester', rarity: 'U', layout: 'normal' },
            { cardNumber: 289, cardSet: cardSetId, name: 'Dirge Bat', rarity: 'R', layout: 'normal' },
            { cardNumber: 290, cardSet: cardSetId, name: 'Insatiable Hemophage', rarity: 'U', layout: 'normal' },
            { cardNumber: 291, cardSet: cardSetId, name: 'Cloudpiercer', rarity: 'C', layout: 'normal' },
            { cardNumber: 292, cardSet: cardSetId, name: 'Everquill Phoenix', rarity: 'R', layout: 'normal' },
            { cardNumber: 293, cardSet: cardSetId, name: 'Porcuparrot', rarity: 'U', layout: 'normal' },
            { cardNumber: 294, cardSet: cardSetId, name: 'Auspicious Starrix', rarity: 'U', layout: 'normal' },
            { cardNumber: 295, cardSet: cardSetId, name: 'Gemrazer', rarity: 'R', layout: 'normal' },
            { cardNumber: 296, cardSet: cardSetId, name: 'Glowstone Recluse', rarity: 'U', layout: 'normal' },
            { cardNumber: 297, cardSet: cardSetId, name: 'Migratory Greathorn', rarity: 'C', layout: 'normal' },
            { cardNumber: 298, cardSet: cardSetId, name: 'Boneyard Lurker', rarity: 'U', layout: 'normal' },
            { cardNumber: 299, cardSet: cardSetId, name: 'Brokkos, Apex of Forever', rarity: 'M', layout: 'normal' },
            { cardNumber: 300, cardSet: cardSetId, name: 'Illuna, Apex of Wishes', rarity: 'M', layout: 'normal' },
            { cardNumber: 301, cardSet: cardSetId, name: 'Lore Drakkis', rarity: 'U', layout: 'normal' },
            { cardNumber: 302, cardSet: cardSetId, name: 'Necropanther', rarity: 'U', layout: 'normal' },
            { cardNumber: 303, cardSet: cardSetId, name: 'Nethroi, Apex of Death', rarity: 'M', layout: 'normal' },
            { cardNumber: 304, cardSet: cardSetId, name: 'Parcelbeast', rarity: 'U', layout: 'normal' },
            { cardNumber: 305, cardSet: cardSetId, name: 'Regal Leosaur', rarity: 'U', layout: 'normal' },
            { cardNumber: 306, cardSet: cardSetId, name: 'Snapdax, Apex of the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 307, cardSet: cardSetId, name: 'Trumpeting Gnarr', rarity: 'U', layout: 'normal' },
            { cardNumber: 308, cardSet: cardSetId, name: 'Vadrok, Apex of Thunder', rarity: 'M', layout: 'normal' },
            { cardNumber: 309, cardSet: cardSetId, name: 'Indatha Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 310, cardSet: cardSetId, name: 'Ketria Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 311, cardSet: cardSetId, name: 'Raugrin Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 312, cardSet: cardSetId, name: 'Savai Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 313, cardSet: cardSetId, name: 'Zagoth Triome', rarity: 'R', layout: 'normal' },
            { cardNumber: 314, cardSet: cardSetId, name: 'Drannith Magistrate', rarity: 'R', layout: 'normal' },
            { cardNumber: 315, cardSet: cardSetId, name: 'Lavabrink Venturer', rarity: 'R', layout: 'normal' },
            { cardNumber: 316, cardSet: cardSetId, name: 'Luminous Broodmoth', rarity: 'M', layout: 'normal' },
            { cardNumber: 317, cardSet: cardSetId, name: 'Mythos of Snapdax', rarity: 'R', layout: 'normal' },
            { cardNumber: 318, cardSet: cardSetId, name: 'Mythos of Illuna', rarity: 'R', layout: 'normal' },
            { cardNumber: 319, cardSet: cardSetId, name: 'Shark Typhoon', rarity: 'R', layout: 'normal' },
            { cardNumber: 320, cardSet: cardSetId, name: 'Voracious Greatshark', rarity: 'R', layout: 'normal' },
            { cardNumber: 321, cardSet: cardSetId, name: 'Extinction Event', rarity: 'R', layout: 'normal' },
            { cardNumber: 322, cardSet: cardSetId, name: 'Hunted Nightmare', rarity: 'R', layout: 'normal' },
            { cardNumber: 323, cardSet: cardSetId, name: 'Mythos of Nethroi', rarity: 'R', layout: 'normal' },
            { cardNumber: 324, cardSet: cardSetId, name: 'Mythos of Vadrok', rarity: 'R', layout: 'normal' },
            { cardNumber: 325, cardSet: cardSetId, name: 'Unpredictable Cyclone', rarity: 'R', layout: 'normal' },
            { cardNumber: 326, cardSet: cardSetId, name: 'Yidaro, Wandering Monster', rarity: 'R', layout: 'normal' },
            { cardNumber: 327, cardSet: cardSetId, name: 'Colossification', rarity: 'R', layout: 'normal' },
            { cardNumber: 328, cardSet: cardSetId, name: 'Kogla, the Titan Ape', rarity: 'R', layout: 'normal' },
            { cardNumber: 329, cardSet: cardSetId, name: 'Mythos of Brokkos', rarity: 'R', layout: 'normal' },
            { cardNumber: 330, cardSet: cardSetId, name: 'Chevill, Bane of Monsters', rarity: 'M', layout: 'normal' },
            { cardNumber: 331, cardSet: cardSetId, name: 'Death\'s Oasis', rarity: 'R', layout: 'normal' },
            { cardNumber: 332, cardSet: cardSetId, name: 'Eerie Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 333, cardSet: cardSetId, name: 'Emergent Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 334, cardSet: cardSetId, name: 'Frondland Felidar', rarity: 'R', layout: 'normal' },
            { cardNumber: 335, cardSet: cardSetId, name: 'General Kudro of Drannith', rarity: 'M', layout: 'normal' },
            { cardNumber: 336, cardSet: cardSetId, name: 'Genesis Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 337, cardSet: cardSetId, name: 'Inspired Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, cardSet: cardSetId, name: 'Kinnan, Bonder Prodigy', rarity: 'M', layout: 'normal' },
            { cardNumber: 339, cardSet: cardSetId, name: 'Labyrinth Raptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 340, cardSet: cardSetId, name: 'Offspring\'s Revenge', rarity: 'R', layout: 'normal' },
            { cardNumber: 341, cardSet: cardSetId, name: 'Quartzwood Crasher', rarity: 'R', layout: 'normal' },
            { cardNumber: 342, cardSet: cardSetId, name: 'Rielle, the Everwise', rarity: 'M', layout: 'normal' },
            { cardNumber: 343, cardSet: cardSetId, name: 'Ruinous Ultimatum', rarity: 'R', layout: 'normal' },
            { cardNumber: 344, cardSet: cardSetId, name: 'Skycat Sovereign', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, cardSet: cardSetId, name: 'Slitherwisp', rarity: 'R', layout: 'normal' },
            { cardNumber: 346, cardSet: cardSetId, name: 'Song of Creation', rarity: 'R', layout: 'normal' },
            { cardNumber: 347, cardSet: cardSetId, name: 'Titans\' Nest', rarity: 'R', layout: 'normal' },
            { cardNumber: 348, cardSet: cardSetId, name: 'Whirlwind of Thought', rarity: 'R', layout: 'normal' },
            { cardNumber: 349, cardSet: cardSetId, name: 'Winota, Joiner of Forces', rarity: 'M', layout: 'normal' },
            { cardNumber: 350, cardSet: cardSetId, name: 'Fiend Artisan', rarity: 'M', layout: 'normal' },
            { cardNumber: 351, cardSet: cardSetId, name: 'Gyruda, Doom of Depths', rarity: 'R', layout: 'normal' },
            { cardNumber: 352, cardSet: cardSetId, name: 'Jegantha, the Wellspring', rarity: 'R', layout: 'normal' },
            { cardNumber: 353, cardSet: cardSetId, name: 'Kaheera, the Orphanguard', rarity: 'R', layout: 'normal' },
            { cardNumber: 354, cardSet: cardSetId, name: 'Keruga, the Macrosage', rarity: 'R', layout: 'normal' },
            { cardNumber: 355, cardSet: cardSetId, name: 'Lurrus of the Dream-Den', rarity: 'R', layout: 'normal' },
            { cardNumber: 356, cardSet: cardSetId, name: 'Lutri, the Spellchaser', rarity: 'R', layout: 'normal' },
            { cardNumber: 357, cardSet: cardSetId, name: 'Obosh, the Preypiercer', rarity: 'R', layout: 'normal' },
            { cardNumber: 358, cardSet: cardSetId, name: 'Umori, the Collector', rarity: 'R', layout: 'normal' },
            { cardNumber: 359, cardSet: cardSetId, name: 'Yorion, Sky Nomad', rarity: 'R', layout: 'normal' },
            { cardNumber: 360, cardSet: cardSetId, name: 'Zirda, the Dawnwaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 361, cardSet: cardSetId, name: 'Crystalline Giant', rarity: 'R', layout: 'normal' },
            { cardNumber: 362, cardSet: cardSetId, name: 'The Ozolith', rarity: 'R', layout: 'normal' },
            { cardNumber: 363, cardSet: cardSetId, name: 'Bonder\'s Enclave', rarity: 'R', layout: 'normal' },
            { cardNumber: 364, cardSet: cardSetId, name: 'Colossification', rarity: 'R', layout: 'normal' },
            { cardNumber: 365, cardSet: cardSetId, name: 'Flourishing Fox', rarity: 'U', layout: 'normal' },
            { cardNumber: 366, cardSet: cardSetId, name: 'Heartless Act', rarity: 'U', layout: 'normal' },
            { cardNumber: 367, cardSet: cardSetId, name: 'Forbidden Friendship', rarity: 'C', layout: 'normal' },
            { cardNumber: 368, cardSet: cardSetId, name: 'Migration Path', rarity: 'U', layout: 'normal' },
            { cardNumber: 369, cardSet: cardSetId, name: 'Sprite Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 370, cardSet: cardSetId, name: 'Huntmaster Liger', rarity: 'U', layout: 'normal' },
            { cardNumber: 371, cardSet: cardSetId, name: 'Luminous Broodmoth', rarity: 'M', layout: 'normal' },
            { cardNumber: 372, cardSet: cardSetId, name: 'Pollywog Symbiote', rarity: 'U', layout: 'normal' },
            { cardNumber: 373, cardSet: cardSetId, name: 'Void Beckoner', rarity: 'U', layout: 'normal' },
            { cardNumber: 374, cardSet: cardSetId, name: 'Everquill Phoenix', rarity: 'R', layout: 'normal' },
            { cardNumber: 375, cardSet: cardSetId, name: 'Yidaro, Wandering Monster', rarity: 'R', layout: 'normal' },
            { cardNumber: 376, cardSet: cardSetId, name: 'Gemrazer', rarity: 'R', layout: 'normal' },
            { cardNumber: 377, cardSet: cardSetId, name: 'Titanoth Rex', rarity: 'U', layout: 'normal' },
            { cardNumber: 378, cardSet: cardSetId, name: 'Brokkos, Apex of Forever', rarity: 'M', layout: 'normal' },
            { cardNumber: 379, cardSet: cardSetId, name: 'Illuna, Apex of Wishes', rarity: 'M', layout: 'normal' },
            { cardNumber: 380, cardSet: cardSetId, name: 'Nethroi, Apex of Death', rarity: 'M', layout: 'normal' },
            { cardNumber: 381, cardSet: cardSetId, name: 'Snapdax, Apex of the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 382, cardSet: cardSetId, name: 'Sprite Dragon', rarity: 'U', layout: 'normal' },
            { cardNumber: 383, cardSet: cardSetId, name: 'Vadrok, Apex of Thunder', rarity: 'M', layout: 'normal' },
            { cardNumber: 384, cardSet: cardSetId, name: 'Gyruda, Doom of Depths', rarity: 'R', layout: 'normal' },
            { cardNumber: 385, cardSet: cardSetId, name: 'Mysterious Egg', rarity: 'C', layout: 'normal' },
            { cardNumber: 386, cardSet: cardSetId, name: 'Dirge Bat', rarity: 'R', layout: 'normal' },
            { cardNumber: 387, cardSet: cardSetId, name: 'Crystalline Giant', rarity: 'R', layout: 'normal' },
        ]).execute();

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'IKO';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }

}
