import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';

export class AddingAfr1627731090125 implements MigrationInterface {
    name = 'addingAfr1627731090125';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Adventures in the Forgotten Realms', shortName: 'AFR' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: '+2 Mace',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Arborea Pegasus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Blink Dog',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: 'The Book of Exalted Deeds',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'Celestial Unicorn',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Cleric Class',
                    rarity: 'U',
                    layout: 'class',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Cloister Gargoyle',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Dancing Sword',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Dawnbringer Cleric',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: "Delver's Torch",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: 'Devoted Paladin',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: 'Divine Smite',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: "Dragon's Disciple",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Dwarfhold Champion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Flumph',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Gloom Stalker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Grand Master of Flowers',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: 'Guardian of Faith',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Half-Elf Monk',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Icingdeath, Frost Tyrant',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: 'Ingenious Smith',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: 'Keen-Eared Sentry',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: 'Loyal Warhound',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Minimus Containment',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Monk of the Open Hand',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Moon-Blessed Cleric',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: 'Nadaar, Selfless Paladin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Oswald Fiddlebender',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: 'Paladin Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: "Paladin's Shield",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: 'Planar Ally',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Plate Armor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: 'Portable Hole',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Potion of Healing',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: 'Priest of Ancient Lore',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: 'Rally Maneuver',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: "Ranger's Hawk",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Steadfast Paladin',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Teleportation Circle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Veteran Dungeoneer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: 'White Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'You Hear Something on Watch',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: "You're Ambushed on the Road",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Aberrant Mind Sorcerer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Air-Cult Elemental',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: 'Arcane Investigator',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: 'Bar the Gate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'The Blackstaff of Waterdeep',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Blue Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Charmed Sleep',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Clever Conjurer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Contact Other Plane',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Demilich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Displacer Beast',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Djinni Windseer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Dragon Turtle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Eccentric Apprentice',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Feywild Trickster',
                    rarity: 'U',
                    layout: 'normal',
                },
                { cardNumber: 59, cardSet: cardSetId, name: 'Fly', rarity: 'U', layout: 'normal' },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Grazilaxx, Illithid Scholar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Guild Thief',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Iymrith, Desert Doom',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Mind Flayer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Mordenkainen',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: "Mordenkainen's Polymorph",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: 'Pixie Guide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Power of Persuasion',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Ray of Frost',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Rimeshield Frost Giant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Scion of Stygia',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Secret Door',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Shocking Grasp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Shortcut Seeker',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Silver Raven',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Soulknife Spy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Split the Party',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: 'Sudden Insight',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: "Tasha's Hideous Laughter",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: "Trickster's Talisman",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'True Polymorph',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Wizard Class',
                    rarity: 'U',
                    layout: 'class',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: "Wizard's Spellbook",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'You Come to a River',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: "You Find the Villains' Lair",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'You See a Guard Approach',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Yuan-Ti Malison',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Acererak the Archlich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: 'Asmodeus the Archfiend',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Baleful Beholder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: 'Black Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'The Book of Vile Darkness',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Check for Traps',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Clattering Skeletons',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: 'Deadly Dispute',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Death-Priest of Myrkul',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: "Demogorgon's Clutches",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: 'Devour Intellect',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Drider',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: 'Dungeon Crawler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Ebondeath, Dracolich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Eyes of the Beholder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: "Fates' Reversal",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Feign Death',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Forsworn Paladin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Gelatinous Cube',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Grim Bounty',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Grim Wanderer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Herald of Hadar',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Hired Hexblade',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: 'Hoard Robber',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Lightfoot Rogue',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: 'Lolth, Spider Queen',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: 'Manticore',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Power Word Kill',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Precipitous Drop',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'Ray of Enfeeblement',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: "Reaper's Talisman",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: 'Sepulcher Ghoul',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: 'Shambling Ghast',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: 'Skullport Merchant',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Sphere of Annihilation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: "Thieves' Tools",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Vampire Spawn',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: 'Vorpal Sword',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Warlock Class',
                    rarity: 'U',
                    layout: 'class',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Westgate Regent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Wight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Yuan-Ti Fang-Blade',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: 'Zombie Ogre',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Armory Veteran',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Barbarian Class',
                    rarity: 'U',
                    layout: 'class',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Battle Cry Goblin',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Boots of Speed',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Brazen Dwarf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Burning Hands',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: 'Chaos Channeler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Critical Hit',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Delina, Wild Mage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: "Dragon's Fire",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: 'Dueling Rapier',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Earth-Cult Elemental',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: "Farideh's Fireball",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Flameskull',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Goblin Javelineer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Goblin Morningstar',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: 'Hoarding Ogre',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Hobgoblin Bandit Lord',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: 'Hobgoblin Captain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Hulking Bugbear',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Improvised Weaponry',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: 'Inferno of the Star Mounts',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Jaded Sell-Sword',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: 'Kick in the Door',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: 'Magic Missile',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: 'Meteor Swarm',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Minion of the Mighty',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Orb of Dragonkind',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Plundering Barbarian',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Price of Loyalty',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Red Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Rust Monster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Swarming Goblins',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Tiger-Tribe Hunter',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Unexpected Windfall',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Valor Singer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Wish',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Xorn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'You Come to the Gnoll Camp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: 'You Find Some Prisoners',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'You See a Pair of Goblins',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Zalto, Fire Giant Duke',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: 'Zariel, Archduke of Avernus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Bulette',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: "Bull's Strength",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Choose Your Weapon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Circle of Dreams Druid',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'Circle of the Moon Druid',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Compelled Duel',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Dire Wolf Prowler',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: 'Druid Class',
                    rarity: 'U',
                    layout: 'class',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Ellywick Tumblestrum',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Elturgard Ranger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: 'Find the Path',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Froghemoth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Gnoll Hunter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Green Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Hill Giant Herdgorger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: "Hunter's Mark",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Inspiring Bard',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: 'Instrument of the Bards',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Intrepid Outlander',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: 'Loathsome Troll',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Long Rest',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Lurking Roper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Neverwinter Dryad',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Ochre Jelly',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: 'Old Gnawbone',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Owlbear',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Plummet',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Prosperous Innkeeper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Purple Worm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Ranger Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: "Ranger's Longbow",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: 'Scaled Herbalist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'Spoils of the Hunt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Sylvan Shepherd',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'The Tarrasque',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Underdark Basilisk',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Varis, Silverymoon Ranger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: 'Wandering Troubadour',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: 'Werewolf Pack Leader',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Wild Shape',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: 'You Find a Cursed Idol',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'You Happen On a Glade',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'You Meet in a Tavern',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Adult Gold Dragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: 'Bard Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Barrowin of Clan Undurr',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: 'Bruenor Battlehammer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: "Drizzt Do'Urden",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: "Farideh, Devil's Chosen",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: 'Fighter Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Gretchen Titchwillow',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Hama Pashar, Ruin Seeker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: 'Kalain, Reclusive Painter',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: "Krydle of Baldur's Gate",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: 'Minsc, Beloved Ranger',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Monk Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Orcus, Prince of Undeath',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Rogue Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: "Shessra, Death's Whisper",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: 'Skeletal Swarming',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: 'Sorcerer Class',
                    rarity: 'R',
                    layout: 'class',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Targ Nar, Demon-Fang Gnoll',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: 'Tiamat',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: 'Trelasarra, Moon Dancer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Triumphant Adventurer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Volo, Guide to Monsters',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Xanathar, Guild Kingpin',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Bag of Holding',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'The Deck of Many Things',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: 'Dungeon Map',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Eye of Vecna',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Fifty Feet of Rope',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Greataxe',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Hand of Vecna',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Iron Golem',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Leather Armor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Mimic',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Spare Dagger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Spiked Pit Trap',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'Treasure Chest',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Cave of the Frost Dragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: 'Den of the Bugbear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Dungeon Descent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Evolving Wilds',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Hall of Storm Giants',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: 'Hive of the Eye Tyrant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Lair of the Hydra',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Temple of the Dragon Queen',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Treasure Vault',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Grand Master of Flowers',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Mordenkainen',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Lolth, Spider Queen',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Zariel, Archduke of Avernus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Ellywick Tumblestrum',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Icingdeath, Frost Tyrant',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'White Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Blue Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Iymrith, Desert Doom',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: 'Black Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: 'Ebondeath, Dracolich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Inferno of the Star Mounts',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Red Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: 'Green Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Old Gnawbone',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Adult Gold Dragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Tiamat',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Arborea Pegasus',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: 'Blink Dog',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Celestial Unicorn',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Cloister Gargoyle',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Nadaar, Selfless Paladin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: 'Oswald Fiddlebender',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: 'Displacer Beast',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: 'Djinni Windseer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: 'Dragon Turtle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Mind Flayer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Pixie Guide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Rimeshield Frost Giant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: 'Baleful Beholder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Clattering Skeletons',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: 'Gelatinous Cube',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Manticore',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: 'Westgate Regent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Wight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: 'Delina, Wild Mage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Goblin Javelineer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Hulking Bugbear',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: 'Minion of the Mighty',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Rust Monster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: 'Xorn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Zalto, Fire Giant Duke',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Bulette',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Dire Wolf Prowler',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Gnoll Hunter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Loathsome Troll',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Lurking Roper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Neverwinter Dryad',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: 'Ochre Jelly',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Owlbear',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: 'Purple Worm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'The Tarrasque',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Underdark Basilisk',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Varis, Silverymoon Ranger',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: 'Barrowin of Clan Undurr',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Bruenor Battlehammer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: "Drizzt Do'Urden",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: "Farideh, Devil's Chosen",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Gretchen Titchwillow',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: 'Hama Pashar, Ruin Seeker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Kalain, Reclusive Painter',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: "Krydle of Baldur's Gate",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: 'Minsc, Beloved Ranger',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: "Shessra, Death's Whisper",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: 'Trelasarra, Moon Dancer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Volo, Guide to Monsters',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: 'Iron Golem',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Mimic',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: 'Cave of the Frost Dragon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Den of the Bugbear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Dungeon Descent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: 'Evolving Wilds',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Hall of Storm Giants',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Hive of the Eye Tyrant',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Lair of the Hydra',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Temple of the Dragon Queen',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Treasure Vault',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'The Book of Exalted Deeds',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: 'Dancing Sword',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Flumph',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Guardian of Faith',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Loyal Warhound',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'Teleportation Circle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'The Blackstaff of Waterdeep',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Demilich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Grazilaxx, Illithid Scholar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: "Tasha's Hideous Laughter",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'True Polymorph',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: "Wizard's Spellbook",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Yuan-Ti Malison',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: 'Acererak the Archlich',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'Asmodeus the Archfiend',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: 'The Book of Vile Darkness',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Forsworn Paladin',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Sphere of Annihilation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'Vorpal Sword',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Flameskull',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Hobgoblin Bandit Lord',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Meteor Swarm',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Orb of Dragonkind',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Wish',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 383,
                    cardSet: cardSetId,
                    name: 'Circle of Dreams Druid',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 384,
                    cardSet: cardSetId,
                    name: 'Froghemoth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 385,
                    cardSet: cardSetId,
                    name: 'Instrument of the Bards',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 386,
                    cardSet: cardSetId,
                    name: 'Long Rest',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 387,
                    cardSet: cardSetId,
                    name: 'Werewolf Pack Leader',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 388,
                    cardSet: cardSetId,
                    name: 'Orcus, Prince of Undeath',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 389,
                    cardSet: cardSetId,
                    name: 'Skeletal Swarming',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 390,
                    cardSet: cardSetId,
                    name: 'Triumphant Adventurer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 391,
                    cardSet: cardSetId,
                    name: 'Xanathar, Guild Kingpin',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 392,
                    cardSet: cardSetId,
                    name: 'The Deck of Many Things',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 393,
                    cardSet: cardSetId,
                    name: 'Eye of Vecna',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 394,
                    cardSet: cardSetId,
                    name: 'Hand of Vecna',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 395,
                    cardSet: cardSetId,
                    name: 'Treasure Chest',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 396,
                    cardSet: cardSetId,
                    name: 'Vorpal Sword',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 397,
                    cardSet: cardSetId,
                    name: 'Treasure Chest',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 398,
                    cardSet: cardSetId,
                    name: 'Portable Hole',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 399,
                    cardSet: cardSetId,
                    name: "You Find the Villains' Lair",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 400,
                    cardSet: cardSetId,
                    name: 'Power Word Kill',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 401,
                    cardSet: cardSetId,
                    name: 'Magic Missile',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 402,
                    cardSet: cardSetId,
                    name: 'Prosperous Innkeeper',
                    rarity: 'U',
                    layout: 'normal',
                },
            ])
            .execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'AFR';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }
}
