import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { Card } from '../card/entity/card.entity';
import { UniqueCard } from '../card/entity/unique-card.entity';

export class addingMid1631469344595 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Innistrad: Midnight Hunt', shortName: 'MID' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: 'Adeline, Resplendent Cathar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Ambitious Farmhand // Seasoned Cathar',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Beloved Beggar // Generous Soul',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: 'Bereaved Survivor // Dauntless Avenger',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'Blessed Defiance',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Borrowed Time',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Brutal Cathar // Moonrage Brute',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Candlegrove Witch',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Candletrap',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: 'Cathar Commando',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: "Cathar's Call",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: 'Celestus Sanctifier',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: 'Chaplain of Alms // Chapel Shieldgeist',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Clarion Cathars',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Curse of Silence',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Duelcraft Trainer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Enduring Angel // Angelic Enforcer',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: 'Fateful Absence',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Flare of Faith',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Gavony Dawnguard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: 'Gavony Silversmith',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: 'Gavony Trapper',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: "Hedgewitch's Mask",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Homestead Courage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Intrepid Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Loyal Gryff',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: 'Lunarch Veteran // Luminous Phantom',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Mourning Patrol // Morning Apparition',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: "Odric's Outrider",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: 'Ritual Guardian',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: 'Ritual of Hope',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Search Party Captain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: "Sigarda's Splendor",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Sigardian Savior',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: 'Soul-Guide Gryff',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: 'Sungold Barrage',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: 'Sungold Sentinel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Sunset Revelry',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Thraben Exorcism',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Unruly Mob',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: 'Vanquish the Horde',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'Baithook Angler // Hook-Haunt Drifter',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: 'Component Collector',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Consider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Covetous Castaway // Ghostly Castigator',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: 'Curse of Surveillance',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: 'Delver of Secrets // Insectile Aberration',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'Devious Cover-Up',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Dissipate',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Drownyard Amalgam',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Fading Hope',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Falcon Abomination',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Firmament Sage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Flip the Switch',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Galedrifter // Waildrifter',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Geistwave',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Grafted Identity',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Larder Zombie',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 59,
                    cardSet: cardSetId,
                    name: 'Lier, Disciple of the Drowned',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Locked in the Cemetery',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Malevolent Hermit // Benevolent Geist',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Memory Deluge',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Mysterious Tome // Chilling Chronicle',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Nebelgast Intruder',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: 'Ominous Roost',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: 'Organ Hoarder',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Otherworldly Gaze',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Overwhelmed Archivist // Archive Haunt',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Patrician Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Phantom Carriage',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Poppet Stitcher // Poppet Factory',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Revenge of the Drowned',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Secrets of the Key',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Shipwreck Sifters',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Skaab Wrangler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Sludge Monster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: 'Spectral Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: 'Startle',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: 'Stormrider Spirit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'Suspicious Stowaway // Seafaring Werewolf',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Triskaidekaphile',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: 'Unblinking Observer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'Vivisection',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: 'Arrogant Outlaw',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'Baneblade Scoundrel // Baneclaw Marauder',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Bat Whisperer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Bladebrand',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: 'Blood Pact',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Bloodline Culling',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: 'Bloodtithe Collector',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'Champion of the Perished',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Covert Cutpurse // Covetous Geist',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Crawl from the Cellar',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: 'Curse of Leeches // Leeching Lurker',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Defenestrate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: 'Diregraf Horde',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: 'Dreadhound',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Duress',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: 'Eaten Alive',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Ecstatic Awakener // Awoken Demon',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Foul Play',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: 'Ghoulish Procession',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Gisa, Glorious Resurrector',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Graveyard Trespasser // Graveyard Glutton',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Heirloom Mirror // Inherited Fiend',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Hobbling Zombie',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Infernal Grasp',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Jadar, Ghoulcaller of Nephalia',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Jerren, Corrupted Bishop // Ormendahl, the Corrupter',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: 'Lord of the Forsaken',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Mask of Griselbrand',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: 'The Meathook Massacre',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: 'Morbid Opportunist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Morkrut Behemoth',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Necrosynthesis',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'No Way Out',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: 'Novice Occultist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: "Olivia's Midnight Ambush",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: 'Rotten Reunion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: 'Shady Traveler // Stalking Predator',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Siege Zombie',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: 'Slaughter Specialist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Stromkirk Bloodthief',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: 'Tainted Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Vampire Interloper',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Vengeful Strangler // Strangling Grasp',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Abandon the Post',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Ardent Elementalist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: 'Bloodthirsty Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Brimstone Vandal',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Burn Down the House',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Burn the Accursed',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Cathartic Pyre',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Curse of Shaken Faith',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Electric Revelation',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: 'Falkenrath Perforator',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Falkenrath Pit Fighter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Famished Foragers',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: 'Fangblade Brigand // Fangblade Eviscerator',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: 'Festival Crasher',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Flame Channeler // Embodiment of Flame',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: 'Geistflame Reservoir',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Harvesttide Infiltrator // Harvesttide Assailant',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Immolation',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Lambholt Harrier',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: 'Light Up the Night',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Lunar Frenzy',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: "Moonrager's Slash",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Moonveil Regent',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Mounted Dreadknight',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: "Neonate's Rush",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Obsessive Astronomer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: "Pack's Betrayal",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: 'Play with Fire',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: 'Purifying Dragon',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Raze the Effigy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Reckless Stormseeker // Storm-Charged Slasher',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Seize the Storm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Smoldering Egg // Ashmouth Dragon',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Spellrune Painter // Spellrune Howler',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Stolen Vitality',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Sunstreak Phoenix',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Tavern Ruffian // Tavern Smasher',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Thermo-Alchemist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Village Watch // Village Reavers',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Voldaren Ambusher',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Voldaren Stinger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'Augur of Autumn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: 'Bird Admirer // Wing Shredder',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'Bounding Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Bramble Armor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: 'Briarbridge Tracker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Brood Weaver',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: 'Burly Breaker // Dire-Strain Demolisher',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Candlelit Cavalry',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Clear Shot',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'Consuming Blob',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Contortionist Troupe',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Dawnhart Mentor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: 'Dawnhart Rejuvenator',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Deathbonnet Sprout // Deathbonnet Hulk',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Defend the Celestus',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: "Dryad's Revival",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Duel for Dominance',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Eccentric Farmer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Harvesttide Sentry',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Hound Tamer // Untamed Pup',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: 'Howl of the Hunt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Might of the Old Ways',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: 'Outland Liberator // Frenzied Trapbreaker',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Path to the Festival',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: 'Pestilent Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Plummet',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Primal Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Return to Nature',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Rise of the Ants',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: "Saryth, the Viper's Fang",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Shadowbeast Sighting',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Snarling Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Storm the Festival',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Tapping at the Window',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Timberland Guide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: 'Tireless Hauler // Dire-Strain Brawler',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: "Tovolar's Huntmaster // Tovolar's Packleader",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'Turn the Earth',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Unnatural Growth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'Willow Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Wrenn and Seven',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Angelfire Ignition',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: 'Arcane Infusion',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Bladestitched Skaab',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: "Can't Stay Away",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'Corpse Cobble',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'Croaking Counterpart',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Dawnhart Wardens',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: 'Dennick, Pious Apprentice // Dennick, Pious Apparition',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Devoted Grafkeeper // Departed Soulkeeper',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: 'Dire-Strain Rampage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: 'Diregraf Rebirth',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: 'Faithful Mending',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: 'Fleshtaker',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Florian, Voldaren Scion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Galvanic Iteration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: "Ghoulcaller's Harvest",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: 'Grizzly Ghoul',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: 'Hallowed Respite',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Hungry for More',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Join the Dance',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Katilda, Dawnhart Prime',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: 'Kessig Naturalist // Lord of the Ulvenwald',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: 'Liesa, Forgotten Archangel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: "Ludevic, Necrogenius // Olag, Ludevic's Hubris",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Old Stickfingers',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: 'Rem Karolus, Stalwart Slayer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: 'Rite of Harmony',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Rite of Oblivion',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Rootcoil Creeper',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Sacred Fire',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Sigarda, Champion of Light',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'Siphon Insight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: 'Slogurk, the Overslime',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Storm Skreelix',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Sunrise Cavalier',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Teferi, Who Slows the Sunset',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Tovolar, Dire Overlord // Tovolar, the Midnight Scourge',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Unnatural Moonrise',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Vadrik, Astral Archmage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Vampire Socialite',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Wake to Slaughter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Winterthorn Blessing',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'The Celestus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Crossroads Candleguide',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: "Jack-o'-Lantern",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Moonsilver Key',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Mystic Skull // Mystic Monstrosity',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Pithing Needle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: 'Silver Bolt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Stuffed Bear',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Deserted Beach',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Evolving Wilds',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Field of Ruin',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Haunted Ridge',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'Hostile Hostel // Creeping Inn',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Overgrown Farmland',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Rockfall Vale',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Shipwreck Marsh',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Wrenn and Seven',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Teferi, Who Slows the Sunset',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Deserted Beach',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Haunted Ridge',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Overgrown Farmland',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Rockfall Vale',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Shipwreck Marsh',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Brutal Cathar // Moonrage Brute',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Candlegrove Witch',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'Suspicious Stowaway // Seafaring Werewolf',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Baneblade Scoundrel // Baneclaw Marauder',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Graveyard Trespasser // Graveyard Glutton',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: 'Shady Traveler // Stalking Predator',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: 'Fangblade Brigand // Fangblade Eviscerator',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Harvesttide Infiltrator // Harvesttide Assailant',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Reckless Stormseeker // Storm-Charged Slasher',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: 'Spellrune Painter // Spellrune Howler',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Tavern Ruffian // Tavern Smasher',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Village Watch // Village Reavers',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Bird Admirer // Wing Shredder',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Burly Breaker // Dire-Strain Demolisher',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: 'Dawnhart Mentor',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Dawnhart Rejuvenator',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Hound Tamer // Untamed Pup',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Outland Liberator // Frenzied Trapbreaker',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: "Saryth, the Viper's Fang",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: 'Tireless Hauler // Dire-Strain Brawler',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: "Tovolar's Huntmaster // Tovolar's Packleader",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Dawnhart Wardens',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Katilda, Dawnhart Prime',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Kessig Naturalist // Lord of the Ulvenwald',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: 'Tovolar, Dire Overlord // Tovolar, the Midnight Scourge',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Adeline, Resplendent Cathar',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: 'Lier, Disciple of the Drowned',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Gisa, Glorious Resurrector',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: 'Jadar, Ghoulcaller of Nephalia',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Jerren, Corrupted Bishop // Ormendahl, the Corrupter',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: 'Dennick, Pious Apprentice // Dennick, Pious Apparition',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Florian, Voldaren Scion',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Liesa, Forgotten Archangel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: "Ludevic, Necrogenius // Olag, Ludevic's Hubris",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Old Stickfingers',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: 'Rem Karolus, Stalwart Slayer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Sigarda, Champion of Light',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Slogurk, the Overslime',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Vadrik, Astral Archmage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Curse of Silence',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Enduring Angel // Angelic Enforcer',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Fateful Absence',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Intrepid Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: "Sigarda's Splendor",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Sigardian Savior',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: 'Sungold Sentinel',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'Vanquish the Horde',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Curse of Surveillance',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Grafted Identity',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: 'Malevolent Hermit // Benevolent Geist',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Memory Deluge',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: 'Patrician Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: 'Poppet Stitcher // Poppet Factory',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Sludge Monster',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: 'Spectral Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Triskaidekaphile',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: 'Bloodline Culling',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: 'Champion of the Perished',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: 'Curse of Leeches // Leeching Lurker',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: 'Lord of the Forsaken',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Mask of Griselbrand',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: 'The Meathook Massacre',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Slaughter Specialist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: 'Tainted Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Bloodthirsty Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Burn Down the House',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: 'Curse of Shaken Faith',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Falkenrath Pit Fighter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Geistflame Reservoir',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Light Up the Night',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Moonveil Regent',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Smoldering Egg // Ashmouth Dragon',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'Sunstreak Phoenix',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: 'Augur of Autumn',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Briarbridge Tracker',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Consuming Blob',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Primal Adversary',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'Storm the Festival',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'Unnatural Growth',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Willow Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Angelfire Ignition',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: "Can't Stay Away",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'Croaking Counterpart',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: 'Dire-Strain Rampage',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Galvanic Iteration',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: "Ghoulcaller's Harvest",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'Hallowed Respite',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: 'Rite of Harmony',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Siphon Insight',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Wake to Slaughter',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'The Celestus',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Pithing Needle',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Hostile Hostel // Creeping Inn',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 383,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 384,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 385,
                    cardSet: cardSetId,
                    name: 'Champion of the Perished',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 386,
                    cardSet: cardSetId,
                    name: 'Triskaidekaphile',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 387,
                    cardSet: cardSetId,
                    name: 'Gavony Dawnguard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 388,
                    cardSet: cardSetId,
                    name: 'Consider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 389,
                    cardSet: cardSetId,
                    name: 'Infernal Grasp',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 390,
                    cardSet: cardSetId,
                    name: 'Play with Fire',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 391,
                    cardSet: cardSetId,
                    name: 'Join the Dance',
                    rarity: 'U',
                    layout: 'normal',
                },
            ])
            .execute();

        const cardName = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'a')
            .select()
            .leftJoin(UniqueCard, 'b', 'a.name = b.card_name')
            .where('b.id is null')
            .groupBy('a.name')
            .getMany();

        const uniqueCardName = cardName.map(c => {
            return { cardName: c.name };
        });
        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into(UniqueCard)
            .values(uniqueCardName)
            .execute();

        await queryRunner.query(
            'Update card a inner join unique_card b on a.name= b.card_name set a.unique_card_1 = b.id where a.unique_card_1 is null',
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'AFR';
        const cardSet = await queryRunner.manager
            .getRepository(CardSet)
            .createQueryBuilder('cardset')
            .where('cardset.short_name = :shortname', { shortname })
            .getOne();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_amount')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }
}
