import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';
import { CardAmount } from '../card/entity/card-amount.entity';
import { CardSet } from '../card/entity/card-set.entity';
import { Card } from '../card/entity/card.entity';
import { UniqueCard } from '../card/entity/unique-card.entity';

export class addingVow1636386139861 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        const insertResult: InsertResult = await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card_set')
            .values({ name: 'Innistrad: Crimson Vow', shortName: 'VOW' })
            .execute();
        const cardSetId: number = insertResult.identifiers[0].id;

        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into('card')
            .values([
                {
                    cardNumber: 1,
                    cardSet: cardSetId,
                    name: 'Adamant Will',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 2,
                    cardSet: cardSetId,
                    name: 'Angelic Quartermaster',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 3,
                    cardSet: cardSetId,
                    name: 'Arm the Cathars',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 4,
                    cardSet: cardSetId,
                    name: "Bride's Gown",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 5,
                    cardSet: cardSetId,
                    name: 'By Invitation Only',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 6,
                    cardSet: cardSetId,
                    name: 'Cemetery Protector',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 7,
                    cardSet: cardSetId,
                    name: 'Circle of Confinement',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 8,
                    cardSet: cardSetId,
                    name: 'Dawnhart Geist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 9,
                    cardSet: cardSetId,
                    name: 'Distracting Geist // Clever Distraction',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 10,
                    cardSet: cardSetId,
                    name: 'Drogskol Infantry // Drogskol Armaments',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 11,
                    cardSet: cardSetId,
                    name: 'Estwald Shieldbasher',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 12,
                    cardSet: cardSetId,
                    name: "Faithbound Judge // Sinner's Judgment",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 13,
                    cardSet: cardSetId,
                    name: 'Fierce Retribution',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 14,
                    cardSet: cardSetId,
                    name: 'Fleeting Spirit',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 15,
                    cardSet: cardSetId,
                    name: 'Gryff Rider',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 16,
                    cardSet: cardSetId,
                    name: 'Gryffwing Cavalry',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 17,
                    cardSet: cardSetId,
                    name: 'Hallowed Haunting',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 18,
                    cardSet: cardSetId,
                    name: 'Heron of Hope',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 19,
                    cardSet: cardSetId,
                    name: 'Heron-Blessed Geist',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 20,
                    cardSet: cardSetId,
                    name: 'Hopeful Initiate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 21,
                    cardSet: cardSetId,
                    name: "Katilda, Dawnhart Martyr // Katilda's Rising Dawn",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 22,
                    cardSet: cardSetId,
                    name: "Kindly Ancestor // Ancestor's Embrace",
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 23,
                    cardSet: cardSetId,
                    name: 'Lantern Flare',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 24,
                    cardSet: cardSetId,
                    name: 'Militia Rallier',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 25,
                    cardSet: cardSetId,
                    name: 'Nebelgast Beguiler',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 26,
                    cardSet: cardSetId,
                    name: 'Nurturing Presence',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 27,
                    cardSet: cardSetId,
                    name: 'Ollenbock Escort',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 28,
                    cardSet: cardSetId,
                    name: 'Panicked Bystander // Cackling Culprit',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 29,
                    cardSet: cardSetId,
                    name: 'Parish-Blade Trainee',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 30,
                    cardSet: cardSetId,
                    name: 'Piercing Light',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 31,
                    cardSet: cardSetId,
                    name: 'Radiant Grace // Radiant Restraints',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 32,
                    cardSet: cardSetId,
                    name: 'Resistance Squad',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 33,
                    cardSet: cardSetId,
                    name: 'Sanctify',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 34,
                    cardSet: cardSetId,
                    name: 'Savior of Ollenbock',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 35,
                    cardSet: cardSetId,
                    name: "Sigarda's Imprisonment",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 36,
                    cardSet: cardSetId,
                    name: "Sigarda's Summons",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 37,
                    cardSet: cardSetId,
                    name: 'Supernatural Rescue',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 38,
                    cardSet: cardSetId,
                    name: 'Thalia, Guardian of Thraben',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 39,
                    cardSet: cardSetId,
                    name: 'Traveling Minister',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 40,
                    cardSet: cardSetId,
                    name: 'Twinblade Geist // Twinblade Invocation',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 41,
                    cardSet: cardSetId,
                    name: 'Unholy Officiant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 42,
                    cardSet: cardSetId,
                    name: 'Valorous Stance',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 43,
                    cardSet: cardSetId,
                    name: 'Vampire Slayer',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 44,
                    cardSet: cardSetId,
                    name: 'Voice of the Blessed',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 45,
                    cardSet: cardSetId,
                    name: 'Wedding Announcement // Wedding Festivity',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 46,
                    cardSet: cardSetId,
                    name: 'Welcoming Vampire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 47,
                    cardSet: cardSetId,
                    name: "Alchemist's Retrieval",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 48,
                    cardSet: cardSetId,
                    name: 'Binding Geist // Spectral Binding',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 49,
                    cardSet: cardSetId,
                    name: 'Biolume Egg // Biolume Serpent',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 50,
                    cardSet: cardSetId,
                    name: 'Cemetery Illuminator',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 51,
                    cardSet: cardSetId,
                    name: 'Chill of the Grave',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 52,
                    cardSet: cardSetId,
                    name: 'Cobbled Lancer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 53,
                    cardSet: cardSetId,
                    name: 'Consuming Tide',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 54,
                    cardSet: cardSetId,
                    name: 'Cradle of Safety',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 55,
                    cardSet: cardSetId,
                    name: 'Cruel Witness',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 56,
                    cardSet: cardSetId,
                    name: 'Diver Skaab',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 57,
                    cardSet: cardSetId,
                    name: 'Dreadlight Monstrosity',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 58,
                    cardSet: cardSetId,
                    name: 'Dreamshackle Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 59,
                    cardSet: cardSetId,
                    name: 'Fear of Death',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 60,
                    cardSet: cardSetId,
                    name: 'Geistlight Snare',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 61,
                    cardSet: cardSetId,
                    name: 'Geralf, Visionary Stitcher',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 62,
                    cardSet: cardSetId,
                    name: 'Gutter Skulker // Gutter Shortcut',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 63,
                    cardSet: cardSetId,
                    name: 'Hullbreaker Horror',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 64,
                    cardSet: cardSetId,
                    name: 'Inspired Idea',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 65,
                    cardSet: cardSetId,
                    name: "Jacob Hauken, Inspector // Hauken's Insight",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 66,
                    cardSet: cardSetId,
                    name: "Lantern Bearer // Lanterns' Lift",
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 67,
                    cardSet: cardSetId,
                    name: 'Lunar Rejection',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 68,
                    cardSet: cardSetId,
                    name: 'Mirrorhall Mimic // Ghastly Mimicry',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 69,
                    cardSet: cardSetId,
                    name: 'Mischievous Catgeist // Catlike Curiosity',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 70,
                    cardSet: cardSetId,
                    name: 'Necroduality',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 71,
                    cardSet: cardSetId,
                    name: 'Overcharged Amalgam',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 72,
                    cardSet: cardSetId,
                    name: 'Patchwork Crawler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 73,
                    cardSet: cardSetId,
                    name: 'Repository Skaab',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 74,
                    cardSet: cardSetId,
                    name: 'Scattered Thoughts',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 75,
                    cardSet: cardSetId,
                    name: 'Screaming Swarm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 76,
                    cardSet: cardSetId,
                    name: 'Selhoff Entomber',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 77,
                    cardSet: cardSetId,
                    name: 'Serpentine Ambush',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 78,
                    cardSet: cardSetId,
                    name: 'Skywarp Skaab',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 79,
                    cardSet: cardSetId,
                    name: 'Soulcipher Board // Cipherbound Spirit',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 80,
                    cardSet: cardSetId,
                    name: 'Steelclad Spirit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 81,
                    cardSet: cardSetId,
                    name: 'Stitched Assistant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 82,
                    cardSet: cardSetId,
                    name: 'Stormchaser Drake',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 83,
                    cardSet: cardSetId,
                    name: 'Syncopate',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 84,
                    cardSet: cardSetId,
                    name: 'Syphon Essence',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 85,
                    cardSet: cardSetId,
                    name: 'Thirst for Discovery',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 86,
                    cardSet: cardSetId,
                    name: 'Wanderlight Spirit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 87,
                    cardSet: cardSetId,
                    name: 'Wash Away',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 88,
                    cardSet: cardSetId,
                    name: 'Whispering Wizard',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 89,
                    cardSet: cardSetId,
                    name: 'Winged Portent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 90,
                    cardSet: cardSetId,
                    name: 'Witness the Future',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 91,
                    cardSet: cardSetId,
                    name: 'Wretched Throng',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 92,
                    cardSet: cardSetId,
                    name: 'Aim for the Head',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 93,
                    cardSet: cardSetId,
                    name: 'Archghoul of Thraben',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 94,
                    cardSet: cardSetId,
                    name: 'Bleed Dry',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 95,
                    cardSet: cardSetId,
                    name: 'Blood Fountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 96,
                    cardSet: cardSetId,
                    name: 'Bloodcrazed Socialite',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 97,
                    cardSet: cardSetId,
                    name: 'Bloodsworn Squire // Bloodsworn Knight',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 98,
                    cardSet: cardSetId,
                    name: 'Bloodvial Purveyor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 99,
                    cardSet: cardSetId,
                    name: 'Catapult Fodder // Catapult Captain',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 100,
                    cardSet: cardSetId,
                    name: 'Cemetery Desecrator',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 101,
                    cardSet: cardSetId,
                    name: 'Concealing Curtains // Revealing Eye',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 102,
                    cardSet: cardSetId,
                    name: 'Courier Bat',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 103,
                    cardSet: cardSetId,
                    name: 'Demonic Bargain',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 104,
                    cardSet: cardSetId,
                    name: 'Desperate Farmer // Depraved Harvester',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 105,
                    cardSet: cardSetId,
                    name: 'Diregraf Scavenger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 106,
                    cardSet: cardSetId,
                    name: 'Doomed Dissenter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 107,
                    cardSet: cardSetId,
                    name: 'Dread Fugue',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 108,
                    cardSet: cardSetId,
                    name: 'Dreadfeast Demon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 109,
                    cardSet: cardSetId,
                    name: 'Dying to Serve',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 110,
                    cardSet: cardSetId,
                    name: "Edgar's Awakening",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 111,
                    cardSet: cardSetId,
                    name: 'Falkenrath Forebear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 112,
                    cardSet: cardSetId,
                    name: 'Fell Stinger',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 113,
                    cardSet: cardSetId,
                    name: 'Gift of Fangs',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 114,
                    cardSet: cardSetId,
                    name: 'Gluttonous Guest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 115,
                    cardSet: cardSetId,
                    name: 'Graf Reaver',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 116,
                    cardSet: cardSetId,
                    name: 'Grisly Ritual',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 117,
                    cardSet: cardSetId,
                    name: "Groom's Finery",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 118,
                    cardSet: cardSetId,
                    name: 'Headless Rider',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 119,
                    cardSet: cardSetId,
                    name: 'Henrika Domnathi // Henrika, Infernal Seer',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 120,
                    cardSet: cardSetId,
                    name: "Hero's Downfall",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 121,
                    cardSet: cardSetId,
                    name: 'Innocent Traveler // Malicious Invader',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 122,
                    cardSet: cardSetId,
                    name: 'Mindleech Ghoul',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 123,
                    cardSet: cardSetId,
                    name: 'Parasitic Grasp',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 124,
                    cardSet: cardSetId,
                    name: 'Path of Peril',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 125,
                    cardSet: cardSetId,
                    name: 'Persistent Specimen',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 126,
                    cardSet: cardSetId,
                    name: 'Pointed Discussion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 127,
                    cardSet: cardSetId,
                    name: 'Ragged Recluse // Odious Witch',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 128,
                    cardSet: cardSetId,
                    name: 'Restless Bloodseeker // Bloodsoaked Reveler',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 129,
                    cardSet: cardSetId,
                    name: 'Rot-Tide Gargantua',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 130,
                    cardSet: cardSetId,
                    name: 'Skulking Killer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 131,
                    cardSet: cardSetId,
                    name: 'Sorin the Mirthless',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 132,
                    cardSet: cardSetId,
                    name: 'Toxrill, the Corrosive',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 133,
                    cardSet: cardSetId,
                    name: 'Undead Butler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 134,
                    cardSet: cardSetId,
                    name: 'Undying Malice',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 135,
                    cardSet: cardSetId,
                    name: 'Unhallowed Phalanx',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 136,
                    cardSet: cardSetId,
                    name: "Vampire's Kiss",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 137,
                    cardSet: cardSetId,
                    name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 138,
                    cardSet: cardSetId,
                    name: 'Wedding Security',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 139,
                    cardSet: cardSetId,
                    name: 'Abrade',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 140,
                    cardSet: cardSetId,
                    name: "Alchemist's Gambit",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 141,
                    cardSet: cardSetId,
                    name: 'Alluring Suitor // Deadly Dancer',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 142,
                    cardSet: cardSetId,
                    name: 'Ancestral Anger',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 143,
                    cardSet: cardSetId,
                    name: 'Ballista Watcher // Ballista Wielder',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 144,
                    cardSet: cardSetId,
                    name: 'Belligerent Guest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 145,
                    cardSet: cardSetId,
                    name: 'Blood Hypnotist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 146,
                    cardSet: cardSetId,
                    name: 'Blood Petal Celebrant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 147,
                    cardSet: cardSetId,
                    name: 'Bloody Betrayal',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 148,
                    cardSet: cardSetId,
                    name: 'Cemetery Gatekeeper',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 149,
                    cardSet: cardSetId,
                    name: 'Chandra, Dressed to Kill',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 150,
                    cardSet: cardSetId,
                    name: 'Change of Fortune',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 151,
                    cardSet: cardSetId,
                    name: 'Creepy Puppeteer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 152,
                    cardSet: cardSetId,
                    name: 'Curse of Hospitality',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 153,
                    cardSet: cardSetId,
                    name: 'Daybreak Combatants',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 154,
                    cardSet: cardSetId,
                    name: 'Dominating Vampire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 155,
                    cardSet: cardSetId,
                    name: 'End the Festivities',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 156,
                    cardSet: cardSetId,
                    name: 'Falkenrath Celebrants',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 157,
                    cardSet: cardSetId,
                    name: 'Fearful Villager // Fearsome Werewolf',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 158,
                    cardSet: cardSetId,
                    name: 'Flame-Blessed Bolt',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 159,
                    cardSet: cardSetId,
                    name: 'Frenzied Devils',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 160,
                    cardSet: cardSetId,
                    name: 'Honeymoon Hearse',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 161,
                    cardSet: cardSetId,
                    name: 'Hungry Ridgewolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 162,
                    cardSet: cardSetId,
                    name: 'Ill-Tempered Loner // Howlpack Avenger',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 163,
                    cardSet: cardSetId,
                    name: 'Into the Night',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 164,
                    cardSet: cardSetId,
                    name: 'Kessig Flamebreather',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 165,
                    cardSet: cardSetId,
                    name: 'Kessig Wolfrider',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 166,
                    cardSet: cardSetId,
                    name: 'Lacerate Flesh',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 167,
                    cardSet: cardSetId,
                    name: 'Lambholt Raconteur // Lambholt Ravager',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 168,
                    cardSet: cardSetId,
                    name: 'Lightning Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 169,
                    cardSet: cardSetId,
                    name: 'Magma Pummeler',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 170,
                    cardSet: cardSetId,
                    name: 'Manaform Hellkite',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 171,
                    cardSet: cardSetId,
                    name: 'Markov Retribution',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 172,
                    cardSet: cardSetId,
                    name: "Olivia's Attendants",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 173,
                    cardSet: cardSetId,
                    name: 'Pyre Spawn',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 174,
                    cardSet: cardSetId,
                    name: 'Reckless Impulse',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 175,
                    cardSet: cardSetId,
                    name: 'Rending Flame',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 176,
                    cardSet: cardSetId,
                    name: 'Runebound Wolf',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 177,
                    cardSet: cardSetId,
                    name: 'Sanguine Statuette',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 178,
                    cardSet: cardSetId,
                    name: 'Stensia Uprising',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 179,
                    cardSet: cardSetId,
                    name: 'Sure Strike',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 180,
                    cardSet: cardSetId,
                    name: "Vampires' Vengeance",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 181,
                    cardSet: cardSetId,
                    name: 'Volatile Arsonist // Dire-Strain Anarchist',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 182,
                    cardSet: cardSetId,
                    name: 'Voldaren Epicure',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 183,
                    cardSet: cardSetId,
                    name: 'Voltaic Visionary // Volt-Charged Berserker',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 184,
                    cardSet: cardSetId,
                    name: 'Weary Prisoner // Wrathful Jailbreaker',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 185,
                    cardSet: cardSetId,
                    name: 'Apprentice Sharpshooter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 186,
                    cardSet: cardSetId,
                    name: 'Ascendant Packleader',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 187,
                    cardSet: cardSetId,
                    name: 'Avabruck Caretaker // Hollowhenge Huntmaster',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 188,
                    cardSet: cardSetId,
                    name: 'Bramble Armor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 189,
                    cardSet: cardSetId,
                    name: 'Bramble Wurm',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 190,
                    cardSet: cardSetId,
                    name: "Cartographer's Survey",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 191,
                    cardSet: cardSetId,
                    name: 'Cemetery Prowler',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 192,
                    cardSet: cardSetId,
                    name: 'Cloaked Cadet',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 193,
                    cardSet: cardSetId,
                    name: 'Crawling Infestation',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 194,
                    cardSet: cardSetId,
                    name: 'Crushing Canopy',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 195,
                    cardSet: cardSetId,
                    name: 'Cultivator Colossus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 196,
                    cardSet: cardSetId,
                    name: 'Dawnhart Disciple',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 197,
                    cardSet: cardSetId,
                    name: 'Dig Up',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 198,
                    cardSet: cardSetId,
                    name: 'Dormant Grove // Gnarled Grovestrider',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 199,
                    cardSet: cardSetId,
                    name: 'Flourishing Hunter',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 200,
                    cardSet: cardSetId,
                    name: 'Glorious Sunrise',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 201,
                    cardSet: cardSetId,
                    name: 'Hamlet Vanguard',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 202,
                    cardSet: cardSetId,
                    name: 'Hiveheart Shaman',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 203,
                    cardSet: cardSetId,
                    name: 'Hookhand Mariner // Riphook Raider',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 204,
                    cardSet: cardSetId,
                    name: 'Howling Moon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 205,
                    cardSet: cardSetId,
                    name: 'Howlpack Piper // Wildsong Howler',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 206,
                    cardSet: cardSetId,
                    name: 'Infestation Expert // Infested Werewolf',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 207,
                    cardSet: cardSetId,
                    name: 'Laid to Rest',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 208,
                    cardSet: cardSetId,
                    name: 'Massive Might',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 209,
                    cardSet: cardSetId,
                    name: 'Moldgraf Millipede',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 210,
                    cardSet: cardSetId,
                    name: 'Mulch',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 211,
                    cardSet: cardSetId,
                    name: "Nature's Embrace",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 212,
                    cardSet: cardSetId,
                    name: 'Oakshade Stalker // Moonlit Ambusher',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 213,
                    cardSet: cardSetId,
                    name: 'Packsong Pup',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 214,
                    cardSet: cardSetId,
                    name: 'Reclusive Taxidermist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 215,
                    cardSet: cardSetId,
                    name: 'Retrieve',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 216,
                    cardSet: cardSetId,
                    name: 'Rural Recruit',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 217,
                    cardSet: cardSetId,
                    name: 'Sawblade Slinger',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 218,
                    cardSet: cardSetId,
                    name: 'Sheltering Boughs',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 219,
                    cardSet: cardSetId,
                    name: 'Snarling Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 220,
                    cardSet: cardSetId,
                    name: 'Spiked Ripsaw',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 221,
                    cardSet: cardSetId,
                    name: 'Splendid Reclamation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 222,
                    cardSet: cardSetId,
                    name: 'Spore Crawler',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 223,
                    cardSet: cardSetId,
                    name: 'Sporeback Wolf',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 224,
                    cardSet: cardSetId,
                    name: 'Toxic Scorpion',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 225,
                    cardSet: cardSetId,
                    name: 'Ulvenwald Oddity // Ulvenwald Behemoth',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 226,
                    cardSet: cardSetId,
                    name: 'Weaver of Blossoms // Blossom-Clad Werewolf',
                    rarity: 'C',
                    layout: 'transform',
                },
                {
                    cardNumber: 227,
                    cardSet: cardSetId,
                    name: "Witch's Web",
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 228,
                    cardSet: cardSetId,
                    name: 'Wolf Strike',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 229,
                    cardSet: cardSetId,
                    name: 'Wolfkin Outcast // Wedding Crasher',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 230,
                    cardSet: cardSetId,
                    name: 'Ancient Lumberknot',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 231,
                    cardSet: cardSetId,
                    name: 'Anje, Maid of Dishonor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 232,
                    cardSet: cardSetId,
                    name: 'Bloodtithe Harvester',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 233,
                    cardSet: cardSetId,
                    name: 'Brine Comber // Brinebound Gift',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 234,
                    cardSet: cardSetId,
                    name: 'Child of the Pack // Savage Packmate',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 235,
                    cardSet: cardSetId,
                    name: "Dorothea, Vengeful Victim // Dorothea's Retribution",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 236,
                    cardSet: cardSetId,
                    name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 237,
                    cardSet: cardSetId,
                    name: 'Eruth, Tormented Prophet',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 238,
                    cardSet: cardSetId,
                    name: 'Grolnok, the Omnivore',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 239,
                    cardSet: cardSetId,
                    name: 'Halana and Alena, Partners',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 240,
                    cardSet: cardSetId,
                    name: 'Kaya, Geist Hunter',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 241,
                    cardSet: cardSetId,
                    name: 'Markov Purifier',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 242,
                    cardSet: cardSetId,
                    name: 'Markov Waltzer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 243,
                    cardSet: cardSetId,
                    name: 'Odric, Blood-Cursed',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 244,
                    cardSet: cardSetId,
                    name: 'Old Rutstein',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 245,
                    cardSet: cardSetId,
                    name: 'Olivia, Crimson Bride',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 246,
                    cardSet: cardSetId,
                    name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 247,
                    cardSet: cardSetId,
                    name: 'Sigardian Paladin',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 248,
                    cardSet: cardSetId,
                    name: 'Skull Skaab',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 249,
                    cardSet: cardSetId,
                    name: 'Torens, Fist of the Angels',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 250,
                    cardSet: cardSetId,
                    name: 'Vilespawn Spider',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 251,
                    cardSet: cardSetId,
                    name: 'Wandering Mind',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 252,
                    cardSet: cardSetId,
                    name: 'Blood Servitor',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 253,
                    cardSet: cardSetId,
                    name: 'Boarded Window',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 254,
                    cardSet: cardSetId,
                    name: 'Ceremonial Knife',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 255,
                    cardSet: cardSetId,
                    name: 'Dollhouse of Horrors',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 256,
                    cardSet: cardSetId,
                    name: 'Foreboding Statue // Forsaken Thresher',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 257,
                    cardSet: cardSetId,
                    name: 'Honored Heirloom',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 258,
                    cardSet: cardSetId,
                    name: "Investigator's Journal",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 259,
                    cardSet: cardSetId,
                    name: 'Lantern of the Lost',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 260,
                    cardSet: cardSetId,
                    name: 'Wedding Invitation',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 261,
                    cardSet: cardSetId,
                    name: 'Deathcap Glade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 262,
                    cardSet: cardSetId,
                    name: 'Dreamroot Cascade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 263,
                    cardSet: cardSetId,
                    name: 'Evolving Wilds',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 264,
                    cardSet: cardSetId,
                    name: 'Shattered Sanctum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 265,
                    cardSet: cardSetId,
                    name: 'Stormcarved Coast',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 266,
                    cardSet: cardSetId,
                    name: 'Sundown Pass',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 267,
                    cardSet: cardSetId,
                    name: 'Voldaren Estate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 268,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 269,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 270,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 271,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 272,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 273,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 274,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 275,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 276,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 277,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 278,
                    cardSet: cardSetId,
                    name: 'Sorin the Mirthless',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 279,
                    cardSet: cardSetId,
                    name: 'Chandra, Dressed to Kill',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 280,
                    cardSet: cardSetId,
                    name: 'Kaya, Geist Hunter',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 281,
                    cardSet: cardSetId,
                    name: 'Deathcap Glade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 282,
                    cardSet: cardSetId,
                    name: 'Dreamroot Cascade',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 283,
                    cardSet: cardSetId,
                    name: 'Shattered Sanctum',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 284,
                    cardSet: cardSetId,
                    name: 'Stormcarved Coast',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 285,
                    cardSet: cardSetId,
                    name: 'Sundown Pass',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 286,
                    cardSet: cardSetId,
                    name: 'Unholy Officiant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 287,
                    cardSet: cardSetId,
                    name: 'Welcoming Vampire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 288,
                    cardSet: cardSetId,
                    name: 'Bloodcrazed Socialite',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 289,
                    cardSet: cardSetId,
                    name: 'Bloodsworn Squire // Bloodsworn Knight',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 290,
                    cardSet: cardSetId,
                    name: 'Bloodvial Purveyor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 291,
                    cardSet: cardSetId,
                    name: 'Falkenrath Forebear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 292,
                    cardSet: cardSetId,
                    name: 'Gluttonous Guest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 293,
                    cardSet: cardSetId,
                    name: 'Henrika Domnathi // Henrika, Infernal Seer',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 294,
                    cardSet: cardSetId,
                    name: 'Innocent Traveler // Malicious Invader',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 295,
                    cardSet: cardSetId,
                    name: 'Restless Bloodseeker // Bloodsoaked Reveler',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 296,
                    cardSet: cardSetId,
                    name: 'Skulking Killer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 297,
                    cardSet: cardSetId,
                    name: 'Sorin the Mirthless',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 298,
                    cardSet: cardSetId,
                    name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 299,
                    cardSet: cardSetId,
                    name: 'Wedding Security',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 300,
                    cardSet: cardSetId,
                    name: 'Alluring Suitor // Deadly Dancer',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 301,
                    cardSet: cardSetId,
                    name: 'Belligerent Guest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 302,
                    cardSet: cardSetId,
                    name: 'Blood Hypnotist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 303,
                    cardSet: cardSetId,
                    name: 'Blood Petal Celebrant',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 304,
                    cardSet: cardSetId,
                    name: 'Cemetery Gatekeeper',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 305,
                    cardSet: cardSetId,
                    name: 'Dominating Vampire',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 306,
                    cardSet: cardSetId,
                    name: 'Falkenrath Celebrants',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 307,
                    cardSet: cardSetId,
                    name: "Olivia's Attendants",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 308,
                    cardSet: cardSetId,
                    name: 'Voldaren Epicure',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 309,
                    cardSet: cardSetId,
                    name: 'Anje, Maid of Dishonor',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 310,
                    cardSet: cardSetId,
                    name: 'Bloodtithe Harvester',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 311,
                    cardSet: cardSetId,
                    name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 312,
                    cardSet: cardSetId,
                    name: 'Markov Purifier',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 313,
                    cardSet: cardSetId,
                    name: 'Markov Waltzer',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 314,
                    cardSet: cardSetId,
                    name: 'Odric, Blood-Cursed',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 315,
                    cardSet: cardSetId,
                    name: 'Olivia, Crimson Bride',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 316,
                    cardSet: cardSetId,
                    name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 317,
                    cardSet: cardSetId,
                    name: "Katilda, Dawnhart Martyr // Katilda's Rising Dawn",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 318,
                    cardSet: cardSetId,
                    name: 'Thalia, Guardian of Thraben',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 319,
                    cardSet: cardSetId,
                    name: 'Geralf, Visionary Stitcher',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 320,
                    cardSet: cardSetId,
                    name: "Jacob Hauken, Inspector // Hauken's Insight",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 321,
                    cardSet: cardSetId,
                    name: 'Toxrill, the Corrosive',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 322,
                    cardSet: cardSetId,
                    name: "Dorothea, Vengeful Victim // Dorothea's Retribution",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 323,
                    cardSet: cardSetId,
                    name: 'Eruth, Tormented Prophet',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 324,
                    cardSet: cardSetId,
                    name: 'Grolnok, the Omnivore',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 325,
                    cardSet: cardSetId,
                    name: 'Halana and Alena, Partners',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 326,
                    cardSet: cardSetId,
                    name: 'Old Rutstein',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 327,
                    cardSet: cardSetId,
                    name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 328,
                    cardSet: cardSetId,
                    name: 'Torens, Fist of the Angels',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 329,
                    cardSet: cardSetId,
                    name: 'Circle of Confinement',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 330,
                    cardSet: cardSetId,
                    name: 'Savior of Ollenbock',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 331,
                    cardSet: cardSetId,
                    name: 'Thalia, Guardian of Thraben',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 332,
                    cardSet: cardSetId,
                    name: "Jacob Hauken, Inspector // Hauken's Insight",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 333,
                    cardSet: cardSetId,
                    name: 'Thirst for Discovery',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 334,
                    cardSet: cardSetId,
                    name: 'Falkenrath Forebear',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 335,
                    cardSet: cardSetId,
                    name: 'Henrika Domnathi // Henrika, Infernal Seer',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 336,
                    cardSet: cardSetId,
                    name: 'Innocent Traveler // Malicious Invader',
                    rarity: 'U',
                    layout: 'transform',
                },
                {
                    cardNumber: 337,
                    cardSet: cardSetId,
                    name: 'Sorin the Mirthless',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 338,
                    cardSet: cardSetId,
                    name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 339,
                    cardSet: cardSetId,
                    name: "Vampires' Vengeance",
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 340,
                    cardSet: cardSetId,
                    name: 'Reclusive Taxidermist',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 341,
                    cardSet: cardSetId,
                    name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 342,
                    cardSet: cardSetId,
                    name: 'Eruth, Tormented Prophet',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 343,
                    cardSet: cardSetId,
                    name: 'Olivia, Crimson Bride',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 344,
                    cardSet: cardSetId,
                    name: 'Torens, Fist of the Angels',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 345,
                    cardSet: cardSetId,
                    name: "Investigator's Journal",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 346,
                    cardSet: cardSetId,
                    name: 'By Invitation Only',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 347,
                    cardSet: cardSetId,
                    name: 'Cemetery Protector',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 348,
                    cardSet: cardSetId,
                    name: "Faithbound Judge // Sinner's Judgment",
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 349,
                    cardSet: cardSetId,
                    name: 'Hallowed Haunting',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 350,
                    cardSet: cardSetId,
                    name: 'Hopeful Initiate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 351,
                    cardSet: cardSetId,
                    name: 'Lantern Flare',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 352,
                    cardSet: cardSetId,
                    name: 'Savior of Ollenbock',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 353,
                    cardSet: cardSetId,
                    name: "Sigarda's Summons",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 354,
                    cardSet: cardSetId,
                    name: 'Voice of the Blessed',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 355,
                    cardSet: cardSetId,
                    name: 'Wedding Announcement // Wedding Festivity',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 356,
                    cardSet: cardSetId,
                    name: 'Cemetery Illuminator',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 357,
                    cardSet: cardSetId,
                    name: 'Consuming Tide',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 358,
                    cardSet: cardSetId,
                    name: 'Dreamshackle Geist',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 359,
                    cardSet: cardSetId,
                    name: 'Hullbreaker Horror',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 360,
                    cardSet: cardSetId,
                    name: 'Inspired Idea',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 361,
                    cardSet: cardSetId,
                    name: 'Mirrorhall Mimic // Ghastly Mimicry',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 362,
                    cardSet: cardSetId,
                    name: 'Necroduality',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 363,
                    cardSet: cardSetId,
                    name: 'Overcharged Amalgam',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 364,
                    cardSet: cardSetId,
                    name: 'Patchwork Crawler',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 365,
                    cardSet: cardSetId,
                    name: 'Winged Portent',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 366,
                    cardSet: cardSetId,
                    name: 'Cemetery Desecrator',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 367,
                    cardSet: cardSetId,
                    name: 'Concealing Curtains // Revealing Eye',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 368,
                    cardSet: cardSetId,
                    name: 'Demonic Bargain',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 369,
                    cardSet: cardSetId,
                    name: 'Dreadfeast Demon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 370,
                    cardSet: cardSetId,
                    name: 'Dying to Serve',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 371,
                    cardSet: cardSetId,
                    name: 'Graf Reaver',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 372,
                    cardSet: cardSetId,
                    name: 'Headless Rider',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 373,
                    cardSet: cardSetId,
                    name: 'Path of Peril',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 374,
                    cardSet: cardSetId,
                    name: "Alchemist's Gambit",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 375,
                    cardSet: cardSetId,
                    name: 'Change of Fortune',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 376,
                    cardSet: cardSetId,
                    name: 'Creepy Puppeteer',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 377,
                    cardSet: cardSetId,
                    name: 'Curse of Hospitality',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 378,
                    cardSet: cardSetId,
                    name: 'Ill-Tempered Loner // Howlpack Avenger',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 379,
                    cardSet: cardSetId,
                    name: 'Kessig Wolfrider',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 380,
                    cardSet: cardSetId,
                    name: 'Manaform Hellkite',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 381,
                    cardSet: cardSetId,
                    name: 'Stensia Uprising',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 382,
                    cardSet: cardSetId,
                    name: 'Volatile Arsonist // Dire-Strain Anarchist',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 383,
                    cardSet: cardSetId,
                    name: 'Ascendant Packleader',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 384,
                    cardSet: cardSetId,
                    name: 'Avabruck Caretaker // Hollowhenge Huntmaster',
                    rarity: 'M',
                    layout: 'transform',
                },
                {
                    cardNumber: 385,
                    cardSet: cardSetId,
                    name: 'Cemetery Prowler',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 386,
                    cardSet: cardSetId,
                    name: 'Cultivator Colossus',
                    rarity: 'M',
                    layout: 'normal',
                },
                {
                    cardNumber: 387,
                    cardSet: cardSetId,
                    name: 'Dig Up',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 388,
                    cardSet: cardSetId,
                    name: 'Glorious Sunrise',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 389,
                    cardSet: cardSetId,
                    name: 'Hamlet Vanguard',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 390,
                    cardSet: cardSetId,
                    name: 'Hiveheart Shaman',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 391,
                    cardSet: cardSetId,
                    name: 'Howling Moon',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 392,
                    cardSet: cardSetId,
                    name: 'Howlpack Piper // Wildsong Howler',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 393,
                    cardSet: cardSetId,
                    name: 'Splendid Reclamation',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 394,
                    cardSet: cardSetId,
                    name: 'Ulvenwald Oddity // Ulvenwald Behemoth',
                    rarity: 'R',
                    layout: 'transform',
                },
                {
                    cardNumber: 395,
                    cardSet: cardSetId,
                    name: 'Dollhouse of Horrors',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 396,
                    cardSet: cardSetId,
                    name: "Investigator's Journal",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 397,
                    cardSet: cardSetId,
                    name: 'Voldaren Estate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 398,
                    cardSet: cardSetId,
                    name: 'Plains',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 399,
                    cardSet: cardSetId,
                    name: 'Island',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 400,
                    cardSet: cardSetId,
                    name: 'Swamp',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 401,
                    cardSet: cardSetId,
                    name: 'Mountain',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 402,
                    cardSet: cardSetId,
                    name: 'Forest',
                    rarity: 'C',
                    layout: 'normal',
                },
                {
                    cardNumber: 403,
                    cardSet: cardSetId,
                    name: 'Voldaren Estate',
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 404,
                    cardSet: cardSetId,
                    name: "Sigarda's Summons",
                    rarity: 'R',
                    layout: 'normal',
                },
                {
                    cardNumber: 405,
                    cardSet: cardSetId,
                    name: 'Geistlight Snare',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 406,
                    cardSet: cardSetId,
                    name: 'Fell Stinger',
                    rarity: 'U',
                    layout: 'normal',
                },
                {
                    cardNumber: 407,
                    cardSet: cardSetId,
                    name: 'Dominating Vampire',
                    rarity: 'R',
                    layout: 'normal',
                },
            ])
            .execute();

        const cardName = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'a')
            .select()
            .leftJoin(UniqueCard, 'b', 'a.name = b.card_name')
            .where('b.id is null')
            .groupBy('a.name')
            .getMany();

        const uniqueCardName = cardName.map(c => {
            return { cardName: c.name };
        });
        await queryRunner.manager
            .createQueryBuilder()
            .insert()
            .into(UniqueCard)
            .values(uniqueCardName)
            .execute();

        await queryRunner.query(
            'Update card a inner join unique_card b on a.name= b.card_name set a.unique_card_1 = b.id where a.unique_card_1 is null',
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Get the card set id
        const shortname = 'VOW';
        const cardSet = await queryRunner.manager.getRepository<CardSet>(CardSet).findOne({
            where: { shortName: shortname },
        });

        const deletableCardAmounts: CardAmount[] = await queryRunner.manager
            .createQueryBuilder<CardAmount>(CardAmount, 'ca')
            .innerJoin('card', 'card')
            .where('card.card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .getMany();

        if (deletableCardAmounts.length > 0) {
            await queryRunner.manager.delete<CardAmount>(CardAmount, deletableCardAmounts);
        }

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card')
            .where('card_set_1 = :cardsetid', { cardsetid: cardSet.id })
            .execute();

        await queryRunner.manager
            .createQueryBuilder()
            .delete()
            .from('card_set')
            .where('short_name = :shortname', { shortname })
            .execute();
    }
}
