import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationHelper } from './helper/migration-helper';

export class createSnc1650101408910 implements MigrationInterface {
    shortName = 'SNC';

    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            { cardNumber: 1, name: 'Angelic Observer', rarity: 'U', layout: 'normal' },
            { cardNumber: 2, name: 'Backup Agent', rarity: 'C', layout: 'normal' },
            { cardNumber: 3, name: 'Ballroom Brawlers', rarity: 'U', layout: 'normal' },
            { cardNumber: 4, name: 'Boon of Safety', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, name: 'Brokers Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 6, name: 'Buy Your Silence', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, name: 'Celebrity Fencer', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, name: "Citizen's Crowbar", rarity: 'U', layout: 'normal' },
            { cardNumber: 9, name: 'Dapper Shieldmate', rarity: 'C', layout: 'normal' },
            { cardNumber: 10, name: 'Depopulate', rarity: 'R', layout: 'normal' },
            { cardNumber: 11, name: 'Elspeth Resplendent', rarity: 'M', layout: 'normal' },
            { cardNumber: 12, name: 'Extraction Specialist', rarity: 'R', layout: 'normal' },
            { cardNumber: 13, name: 'Gathering Throng', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, name: 'Giada, Font of Hope', rarity: 'R', layout: 'normal' },
            { cardNumber: 15, name: 'Halo Fountain', rarity: 'M', layout: 'normal' },
            { cardNumber: 16, name: 'Hold for Ransom', rarity: 'C', layout: 'normal' },
            { cardNumber: 17, name: 'Illuminator Virtuoso', rarity: 'U', layout: 'normal' },
            { cardNumber: 18, name: 'Inspiring Overseer', rarity: 'C', layout: 'normal' },
            { cardNumber: 19, name: 'Kill Shot', rarity: 'C', layout: 'normal' },
            { cardNumber: 20, name: 'Knockout Blow', rarity: 'U', layout: 'normal' },
            { cardNumber: 21, name: "Mage's Attendant", rarity: 'U', layout: 'normal' },
            { cardNumber: 22, name: 'Mysterious Limousine', rarity: 'R', layout: 'normal' },
            { cardNumber: 23, name: 'Patch Up', rarity: 'U', layout: 'normal' },
            { cardNumber: 24, name: 'Rabble Rousing', rarity: 'R', layout: 'normal' },
            { cardNumber: 25, name: "Raffine's Guidance", rarity: 'C', layout: 'normal' },
            { cardNumber: 26, name: "Raffine's Informant", rarity: 'C', layout: 'normal' },
            { cardNumber: 27, name: 'Refuse to Yield', rarity: 'U', layout: 'normal' },
            { cardNumber: 28, name: 'Revelation of Power', rarity: 'C', layout: 'normal' },
            { cardNumber: 29, name: 'Rumor Gatherer', rarity: 'U', layout: 'normal' },
            { cardNumber: 30, name: 'Sanctuary Warden', rarity: 'M', layout: 'normal' },
            { cardNumber: 31, name: 'Sky Crier', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, name: 'Speakeasy Server', rarity: 'C', layout: 'normal' },
            { cardNumber: 33, name: 'Swooping Protector', rarity: 'U', layout: 'normal' },
            { cardNumber: 34, name: 'All-Seeing Arbiter', rarity: 'M', layout: 'normal' },
            { cardNumber: 35, name: 'Backstreet Bruiser', rarity: 'C', layout: 'normal' },
            { cardNumber: 36, name: 'Brokers Veteran', rarity: 'C', layout: 'normal' },
            { cardNumber: 37, name: 'Case the Joint', rarity: 'C', layout: 'normal' },
            { cardNumber: 38, name: 'Cut Your Losses', rarity: 'R', layout: 'normal' },
            { cardNumber: 39, name: 'Disdainful Stroke', rarity: 'C', layout: 'normal' },
            { cardNumber: 40, name: 'Echo Inspector', rarity: 'C', layout: 'normal' },
            { cardNumber: 41, name: 'Errant, Street Artist', rarity: 'R', layout: 'normal' },
            { cardNumber: 42, name: 'Even the Score', rarity: 'M', layout: 'normal' },
            { cardNumber: 43, name: 'Expendable Lackey', rarity: 'C', layout: 'normal' },
            { cardNumber: 44, name: 'Faerie Vandal', rarity: 'U', layout: 'normal' },
            { cardNumber: 45, name: 'Hypnotic Grifter', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, name: 'Ledger Shredder', rarity: 'R', layout: 'normal' },
            { cardNumber: 47, name: 'A Little Chat', rarity: 'U', layout: 'normal' },
            { cardNumber: 48, name: 'Majestic Metamorphosis', rarity: 'C', layout: 'normal' },
            { cardNumber: 49, name: 'Make Disappear', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, name: 'Obscura Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 51, name: "An Offer You Can't Refuse", rarity: 'U', layout: 'normal' },
            { cardNumber: 52, name: 'Out of the Way', rarity: 'U', layout: 'normal' },
            { cardNumber: 53, name: 'Psionic Snoop', rarity: 'C', layout: 'normal' },
            { cardNumber: 54, name: 'Psychic Pickpocket', rarity: 'U', layout: 'normal' },
            { cardNumber: 55, name: 'Public Enemy', rarity: 'U', layout: 'normal' },
            { cardNumber: 56, name: 'Reservoir Kraken', rarity: 'R', layout: 'normal' },
            { cardNumber: 57, name: 'Rooftop Nuisance', rarity: 'C', layout: 'normal' },
            { cardNumber: 58, name: 'Run Out of Town', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, name: 'Security Bypass', rarity: 'C', layout: 'normal' },
            { cardNumber: 60, name: 'Sewer Crocodile', rarity: 'C', layout: 'normal' },
            { cardNumber: 61, name: 'Sleep with the Fishes', rarity: 'U', layout: 'normal' },
            { cardNumber: 62, name: 'Slip Out the Back', rarity: 'U', layout: 'normal' },
            { cardNumber: 63, name: 'Undercover Operative', rarity: 'R', layout: 'normal' },
            { cardNumber: 64, name: 'Wingshield Agent', rarity: 'U', layout: 'normal' },
            { cardNumber: 65, name: 'Wiretapping', rarity: 'R', layout: 'normal' },
            { cardNumber: 66, name: 'Witness Protection', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, name: 'Angel of Suffering', rarity: 'M', layout: 'normal' },
            { cardNumber: 68, name: 'Body Launderer', rarity: 'M', layout: 'normal' },
            { cardNumber: 69, name: 'Cemetery Tampering', rarity: 'R', layout: 'normal' },
            { cardNumber: 70, name: 'Corrupt Court Official', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, name: 'Crooked Custodian', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, name: 'Cut of the Profits', rarity: 'R', layout: 'normal' },
            { cardNumber: 73, name: 'Cutthroat Contender', rarity: 'C', layout: 'normal' },
            { cardNumber: 74, name: 'Deal Gone Bad', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, name: "Demon's Due", rarity: 'C', layout: 'normal' },
            { cardNumber: 76, name: 'Dig Up the Body', rarity: 'C', layout: 'normal' },
            { cardNumber: 77, name: 'Dusk Mangler', rarity: 'U', layout: 'normal' },
            { cardNumber: 78, name: 'Extract the Truth', rarity: 'C', layout: 'normal' },
            { cardNumber: 79, name: 'Fake Your Own Death', rarity: 'C', layout: 'normal' },
            { cardNumber: 80, name: 'Girder Goons', rarity: 'C', layout: 'normal' },
            { cardNumber: 81, name: 'Graveyard Shift', rarity: 'U', layout: 'normal' },
            { cardNumber: 82, name: 'Grisly Sigil', rarity: 'U', layout: 'normal' },
            { cardNumber: 83, name: 'Illicit Shipment', rarity: 'U', layout: 'normal' },
            { cardNumber: 84, name: 'Incriminate', rarity: 'C', layout: 'normal' },
            { cardNumber: 85, name: 'Join the Maestros', rarity: 'C', layout: 'normal' },
            { cardNumber: 86, name: 'Maestros Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 87, name: 'Midnight Assassin', rarity: 'C', layout: 'normal' },
            { cardNumber: 88, name: 'Murder', rarity: 'C', layout: 'normal' },
            { cardNumber: 89, name: 'Night Clubber', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, name: "Raffine's Silencer", rarity: 'U', layout: 'normal' },
            { cardNumber: 91, name: 'Revel Ruiner', rarity: 'C', layout: 'normal' },
            { cardNumber: 92, name: "Rogues' Gallery", rarity: 'U', layout: 'normal' },
            { cardNumber: 93, name: 'Sanguine Spy', rarity: 'R', layout: 'normal' },
            { cardNumber: 94, name: 'Shadow of Mortality', rarity: 'R', layout: 'normal' },
            { cardNumber: 95, name: 'Shakedown Heavy', rarity: 'R', layout: 'normal' },
            { cardNumber: 96, name: 'Tavern Swindler', rarity: 'U', layout: 'normal' },
            { cardNumber: 97, name: 'Tenacious Underdog', rarity: 'R', layout: 'normal' },
            { cardNumber: 98, name: 'Vampire Scrivener', rarity: 'U', layout: 'normal' },
            { cardNumber: 99, name: 'Whack', rarity: 'U', layout: 'normal' },
            { cardNumber: 100, name: 'Antagonize', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, name: 'Arcane Bombardment', rarity: 'M', layout: 'normal' },
            { cardNumber: 102, name: 'Big Score', rarity: 'C', layout: 'normal' },
            { cardNumber: 103, name: 'Call In a Professional', rarity: 'U', layout: 'normal' },
            { cardNumber: 104, name: 'Daring Escape', rarity: 'C', layout: 'normal' },
            { cardNumber: 105, name: 'Devilish Valet', rarity: 'R', layout: 'normal' },
            { cardNumber: 106, name: 'Exhibition Magician', rarity: 'C', layout: 'normal' },
            { cardNumber: 107, name: 'Glittering Stockpile', rarity: 'U', layout: 'normal' },
            { cardNumber: 108, name: 'Goldhound', rarity: 'C', layout: 'normal' },
            { cardNumber: 109, name: 'Hoard Hauler', rarity: 'R', layout: 'normal' },
            { cardNumber: 110, name: 'Involuntary Employment', rarity: 'U', layout: 'normal' },
            { cardNumber: 111, name: 'Jackhammer', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, name: 'Jaxis, the Troublemaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 113, name: "Light 'Em Up", rarity: 'C', layout: 'normal' },
            { cardNumber: 114, name: 'Mayhem Patrol', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, name: 'Plasma Jockey', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, name: 'Professional Face-Breaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 117, name: 'Pugnacious Pugilist', rarity: 'U', layout: 'normal' },
            { cardNumber: 118, name: 'Pyre-Sledge Arsonist', rarity: 'U', layout: 'normal' },
            { cardNumber: 119, name: 'Ready to Rumble', rarity: 'C', layout: 'normal' },
            { cardNumber: 120, name: 'Riveteers Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 121, name: 'Riveteers Requisitioner', rarity: 'U', layout: 'normal' },
            { cardNumber: 122, name: 'Rob the Archives', rarity: 'U', layout: 'normal' },
            { cardNumber: 123, name: 'Sizzling Soloist', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, name: 'Sticky Fingers', rarity: 'C', layout: 'normal' },
            { cardNumber: 125, name: 'Strangle', rarity: 'C', layout: 'normal' },
            { cardNumber: 126, name: 'Structural Assault', rarity: 'R', layout: 'normal' },
            { cardNumber: 127, name: 'Torch Breath', rarity: 'U', layout: 'normal' },
            { cardNumber: 128, name: 'Unlucky Witness', rarity: 'U', layout: 'normal' },
            { cardNumber: 129, name: 'Urabrask, Heretic Praetor', rarity: 'M', layout: 'normal' },
            { cardNumber: 130, name: 'Widespread Thievery', rarity: 'R', layout: 'normal' },
            { cardNumber: 131, name: 'Witty Roaster', rarity: 'C', layout: 'normal' },
            { cardNumber: 132, name: 'Wrecking Crew', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, name: 'Attended Socialite', rarity: 'C', layout: 'normal' },
            { cardNumber: 134, name: "Bootleggers' Stash", rarity: 'M', layout: 'normal' },
            { cardNumber: 135, name: "Bouncer's Beatdown", rarity: 'U', layout: 'normal' },
            { cardNumber: 136, name: 'Broken Wings', rarity: 'C', layout: 'normal' },
            { cardNumber: 137, name: 'Cabaretti Initiate', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, name: 'Caldaia Strongarm', rarity: 'C', layout: 'normal' },
            { cardNumber: 139, name: 'Capenna Express', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, name: 'Civic Gardener', rarity: 'C', layout: 'normal' },
            { cardNumber: 141, name: 'Cleanup Crew', rarity: 'U', layout: 'normal' },
            { cardNumber: 142, name: "Courier's Briefcase", rarity: 'U', layout: 'normal' },
            { cardNumber: 143, name: 'Elegant Entourage', rarity: 'U', layout: 'normal' },
            { cardNumber: 144, name: 'Evolving Door', rarity: 'R', layout: 'normal' },
            { cardNumber: 145, name: 'Fight Rigging', rarity: 'R', layout: 'normal' },
            { cardNumber: 146, name: 'For the Family', rarity: 'C', layout: 'normal' },
            { cardNumber: 147, name: 'Freelance Muscle', rarity: 'U', layout: 'normal' },
            { cardNumber: 148, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 149, name: 'Glittermonger', rarity: 'C', layout: 'normal' },
            { cardNumber: 150, name: 'High-Rise Sawjack', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, name: 'Jewel Thief', rarity: 'C', layout: 'normal' },
            { cardNumber: 152, name: 'Luxurious Libation', rarity: 'U', layout: 'normal' },
            { cardNumber: 153, name: 'Most Wanted', rarity: 'C', layout: 'normal' },
            { cardNumber: 154, name: 'Prizefight', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, name: 'Rhox Pummeler', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, name: 'Riveteers Decoy', rarity: 'U', layout: 'normal' },
            { cardNumber: 157, name: 'Social Climber', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, name: 'Take to the Streets', rarity: 'U', layout: 'normal' },
            { cardNumber: 159, name: 'Titan of Industry', rarity: 'M', layout: 'normal' },
            { cardNumber: 160, name: 'Topiary Stomper', rarity: 'R', layout: 'normal' },
            { cardNumber: 161, name: 'Venom Connoisseur', rarity: 'U', layout: 'normal' },
            { cardNumber: 162, name: 'Vivien on the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 163, name: 'Voice of the Vermin', rarity: 'U', layout: 'normal' },
            { cardNumber: 164, name: 'Warm Welcome', rarity: 'C', layout: 'normal' },
            { cardNumber: 165, name: 'Workshop Warchief', rarity: 'R', layout: 'normal' },
            { cardNumber: 166, name: 'Aven Heartstabber', rarity: 'R', layout: 'normal' },
            { cardNumber: 167, name: 'Black Market Tycoon', rarity: 'R', layout: 'normal' },
            { cardNumber: 168, name: 'Body Dropper', rarity: 'C', layout: 'normal' },
            { cardNumber: 169, name: 'Brazen Upstart', rarity: 'U', layout: 'normal' },
            { cardNumber: 170, name: 'Brokers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 171, name: 'Brokers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 172, name: 'Cabaretti Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 173, name: 'Cabaretti Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 174, name: 'Celestial Regulator', rarity: 'C', layout: 'normal' },
            { cardNumber: 175, name: 'Ceremonial Groundbreaker', rarity: 'U', layout: 'normal' },
            { cardNumber: 176, name: 'Civil Servant', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, name: 'Cormela, Glamour Thief', rarity: 'U', layout: 'normal' },
            { cardNumber: 178, name: 'Corpse Appraiser', rarity: 'U', layout: 'normal' },
            { cardNumber: 179, name: 'Corpse Explosion', rarity: 'R', layout: 'normal' },
            { cardNumber: 180, name: 'Crew Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, name: 'Darling of the Masses', rarity: 'U', layout: 'normal' },
            { cardNumber: 182, name: 'Disciplined Duelist', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, name: 'Endless Detour', rarity: 'R', layout: 'normal' },
            { cardNumber: 184, name: 'Evelyn, the Covetous', rarity: 'R', layout: 'normal' },
            { cardNumber: 185, name: 'Exotic Pets', rarity: 'U', layout: 'normal' },
            { cardNumber: 186, name: 'Falco Spara, Pactweaver', rarity: 'M', layout: 'normal' },
            { cardNumber: 187, name: 'Fatal Grudge', rarity: 'U', layout: 'normal' },
            { cardNumber: 188, name: 'Fleetfoot Dancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 189, name: 'Forge Boss', rarity: 'U', layout: 'normal' },
            { cardNumber: 190, name: 'Glamorous Outlaw', rarity: 'C', layout: 'normal' },
            { cardNumber: 191, name: 'Hostile Takeover', rarity: 'R', layout: 'normal' },
            { cardNumber: 192, name: 'Incandescent Aria', rarity: 'R', layout: 'normal' },
            { cardNumber: 193, name: 'Jetmir, Nexus of Revels', rarity: 'M', layout: 'normal' },
            { cardNumber: 194, name: "Jetmir's Fixer", rarity: 'C', layout: 'normal' },
            { cardNumber: 195, name: "Jinnie Fay, Jetmir's Second", rarity: 'R', layout: 'normal' },
            { cardNumber: 196, name: 'Lagrella, the Magpie', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, name: 'Lord Xander, the Collector', rarity: 'M', layout: 'normal' },
            { cardNumber: 198, name: 'Maestros Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 199, name: 'Maestros Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 200, name: 'Maestros Diabolist', rarity: 'R', layout: 'normal' },
            { cardNumber: 201, name: 'Masked Bandits', rarity: 'C', layout: 'normal' },
            { cardNumber: 202, name: 'Meeting of the Five', rarity: 'M', layout: 'normal' },
            { cardNumber: 203, name: 'Metropolis Angel', rarity: 'U', layout: 'normal' },
            { cardNumber: 204, name: 'Mr. Orfeo, the Boulder', rarity: 'U', layout: 'normal' },
            { cardNumber: 205, name: 'Nimble Larcenist', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, name: 'Ob Nixilis, the Adversary', rarity: 'M', layout: 'normal' },
            { cardNumber: 207, name: 'Obscura Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 208, name: 'Obscura Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, name: 'Obscura Interceptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 210, name: "Ognis, the Dragon's Lash", rarity: 'R', layout: 'normal' },
            { cardNumber: 211, name: 'Park Heights Pegasus', rarity: 'R', layout: 'normal' },
            { cardNumber: 212, name: 'Queza, Augur of Agonies', rarity: 'U', layout: 'normal' },
            { cardNumber: 213, name: 'Raffine, Scheming Seer', rarity: 'M', layout: 'normal' },
            { cardNumber: 214, name: 'Rakish Revelers', rarity: 'C', layout: 'normal' },
            { cardNumber: 215, name: 'Rigo, Streetwise Mentor', rarity: 'R', layout: 'normal' },
            { cardNumber: 216, name: 'Riveteers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 217, name: 'Riveteers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 218, name: 'Rocco, Cabaretti Caterer', rarity: 'U', layout: 'normal' },
            { cardNumber: 219, name: 'Scheming Fence', rarity: 'R', layout: 'normal' },
            { cardNumber: 220, name: 'Security Rhox', rarity: 'U', layout: 'normal' },
            { cardNumber: 221, name: 'Shattered Seraph', rarity: 'C', layout: 'normal' },
            { cardNumber: 222, name: 'Snooping Newsie', rarity: 'C', layout: 'normal' },
            { cardNumber: 223, name: 'Soul of Emancipation', rarity: 'R', layout: 'normal' },
            { cardNumber: 224, name: "Spara's Adjudicators", rarity: 'C', layout: 'normal' },
            { cardNumber: 225, name: 'Stimulus Package', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, name: 'Syndicate Infiltrator', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, name: 'Tainted Indulgence', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, name: 'Toluz, Clever Conductor', rarity: 'R', layout: 'normal' },
            { cardNumber: 229, name: 'Unleash the Inferno', rarity: 'R', layout: 'normal' },
            { cardNumber: 230, name: 'Void Rend', rarity: 'R', layout: 'normal' },
            { cardNumber: 231, name: 'Ziatora, the Incinerator', rarity: 'M', layout: 'normal' },
            { cardNumber: 232, name: "Ziatora's Envoy", rarity: 'R', layout: 'normal' },
            { cardNumber: 233, name: 'Arc Spitter', rarity: 'U', layout: 'normal' },
            { cardNumber: 234, name: 'Brass Knuckles', rarity: 'U', layout: 'normal' },
            { cardNumber: 235, name: 'Cement Shoes', rarity: 'U', layout: 'normal' },
            { cardNumber: 236, name: 'Chrome Cat', rarity: 'C', layout: 'normal' },
            { cardNumber: 237, name: 'Getaway Car', rarity: 'R', layout: 'normal' },
            { cardNumber: 238, name: 'Gilded Pinions', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, name: 'Halo Scarab', rarity: 'C', layout: 'normal' },
            { cardNumber: 240, name: "Luxior, Giada's Gift", rarity: 'M', layout: 'normal' },
            { cardNumber: 241, name: 'Ominous Parcel', rarity: 'C', layout: 'normal' },
            { cardNumber: 242, name: 'Paragon of Modernity', rarity: 'C', layout: 'normal' },
            { cardNumber: 243, name: 'Quick-Draw Dagger', rarity: 'C', layout: 'normal' },
            { cardNumber: 244, name: 'Scuttling Butler', rarity: 'U', layout: 'normal' },
            { cardNumber: 245, name: 'Suspicious Bookcase', rarity: 'U', layout: 'normal' },
            { cardNumber: 246, name: 'Unlicensed Hearse', rarity: 'R', layout: 'normal' },
            { cardNumber: 247, name: 'Botanical Plaza', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, name: 'Brokers Hideout', rarity: 'C', layout: 'normal' },
            { cardNumber: 249, name: 'Cabaretti Courtyard', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, name: "Jetmir's Garden", rarity: 'R', layout: 'normal' },
            { cardNumber: 251, name: 'Maestros Theater', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, name: 'Obscura Storefront', rarity: 'C', layout: 'normal' },
            { cardNumber: 253, name: "Racers' Ring", rarity: 'C', layout: 'normal' },
            { cardNumber: 254, name: "Raffine's Tower", rarity: 'R', layout: 'normal' },
            { cardNumber: 255, name: 'Riveteers Overlook', rarity: 'C', layout: 'normal' },
            { cardNumber: 256, name: 'Skybridge Towers', rarity: 'C', layout: 'normal' },
            { cardNumber: 257, name: "Spara's Headquarters", rarity: 'R', layout: 'normal' },
            { cardNumber: 258, name: 'Tramway Station', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, name: 'Waterfront District', rarity: 'C', layout: 'normal' },
            { cardNumber: 260, name: "Xander's Lounge", rarity: 'R', layout: 'normal' },
            { cardNumber: 261, name: "Ziatora's Proving Ground", rarity: 'R', layout: 'normal' },
            { cardNumber: 262, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 276, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 277, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 278, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 279, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 280, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 281, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 282, name: 'Elspeth Resplendent', rarity: 'M', layout: 'normal' },
            { cardNumber: 283, name: 'Vivien on the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 284, name: 'Ob Nixilis, the Adversary', rarity: 'M', layout: 'normal' },
            { cardNumber: 285, name: 'Halo Fountain', rarity: 'M', layout: 'normal' },
            { cardNumber: 286, name: 'All-Seeing Arbiter', rarity: 'M', layout: 'normal' },
            { cardNumber: 287, name: 'Shadow of Mortality', rarity: 'R', layout: 'normal' },
            { cardNumber: 288, name: "Bootleggers' Stash", rarity: 'M', layout: 'normal' },
            { cardNumber: 289, name: 'Titan of Industry', rarity: 'M', layout: 'normal' },
            { cardNumber: 290, name: 'Topiary Stomper', rarity: 'R', layout: 'normal' },
            { cardNumber: 291, name: "Jetmir's Garden", rarity: 'R', layout: 'normal' },
            { cardNumber: 292, name: "Raffine's Tower", rarity: 'R', layout: 'normal' },
            { cardNumber: 293, name: "Spara's Headquarters", rarity: 'R', layout: 'normal' },
            { cardNumber: 294, name: "Xander's Lounge", rarity: 'R', layout: 'normal' },
            { cardNumber: 295, name: "Ziatora's Proving Ground", rarity: 'R', layout: 'normal' },
            { cardNumber: 296, name: 'Brazen Upstart', rarity: 'U', layout: 'normal' },
            { cardNumber: 297, name: 'Brokers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 298, name: 'Brokers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 299, name: 'Cabaretti Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 300, name: 'Cabaretti Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 301, name: 'Cormela, Glamour Thief', rarity: 'U', layout: 'normal' },
            { cardNumber: 302, name: 'Corpse Appraiser', rarity: 'U', layout: 'normal' },
            { cardNumber: 303, name: 'Crew Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 304, name: 'Disciplined Duelist', rarity: 'U', layout: 'normal' },
            { cardNumber: 305, name: 'Endless Detour', rarity: 'R', layout: 'normal' },
            { cardNumber: 306, name: 'Evelyn, the Covetous', rarity: 'R', layout: 'normal' },
            { cardNumber: 307, name: 'Falco Spara, Pactweaver', rarity: 'M', layout: 'normal' },
            { cardNumber: 308, name: 'Fleetfoot Dancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 309, name: 'Glamorous Outlaw', rarity: 'C', layout: 'normal' },
            { cardNumber: 310, name: 'Hostile Takeover', rarity: 'R', layout: 'normal' },
            { cardNumber: 311, name: 'Incandescent Aria', rarity: 'R', layout: 'normal' },
            { cardNumber: 312, name: 'Jetmir, Nexus of Revels', rarity: 'M', layout: 'normal' },
            { cardNumber: 313, name: "Jinnie Fay, Jetmir's Second", rarity: 'R', layout: 'normal' },
            { cardNumber: 314, name: 'Lagrella, the Magpie', rarity: 'U', layout: 'normal' },
            { cardNumber: 315, name: 'Lord Xander, the Collector', rarity: 'M', layout: 'normal' },
            { cardNumber: 316, name: 'Maestros Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 317, name: 'Maestros Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 318, name: 'Maestros Diabolist', rarity: 'R', layout: 'normal' },
            { cardNumber: 319, name: 'Masked Bandits', rarity: 'C', layout: 'normal' },
            { cardNumber: 320, name: 'Mr. Orfeo, the Boulder', rarity: 'U', layout: 'normal' },
            { cardNumber: 321, name: 'Nimble Larcenist', rarity: 'U', layout: 'normal' },
            { cardNumber: 322, name: 'Obscura Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 323, name: 'Obscura Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 324, name: 'Obscura Interceptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 325, name: "Ognis, the Dragon's Lash", rarity: 'R', layout: 'normal' },
            { cardNumber: 326, name: 'Queza, Augur of Agonies', rarity: 'U', layout: 'normal' },
            { cardNumber: 327, name: 'Raffine, Scheming Seer', rarity: 'M', layout: 'normal' },
            { cardNumber: 328, name: 'Rakish Revelers', rarity: 'C', layout: 'normal' },
            { cardNumber: 329, name: 'Rigo, Streetwise Mentor', rarity: 'R', layout: 'normal' },
            { cardNumber: 330, name: 'Riveteers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 331, name: 'Riveteers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 332, name: 'Rocco, Cabaretti Caterer', rarity: 'U', layout: 'normal' },
            { cardNumber: 333, name: 'Shattered Seraph', rarity: 'C', layout: 'normal' },
            { cardNumber: 334, name: 'Soul of Emancipation', rarity: 'R', layout: 'normal' },
            { cardNumber: 335, name: "Spara's Adjudicators", rarity: 'C', layout: 'normal' },
            { cardNumber: 336, name: 'Toluz, Clever Conductor', rarity: 'R', layout: 'normal' },
            { cardNumber: 337, name: 'Unleash the Inferno', rarity: 'R', layout: 'normal' },
            { cardNumber: 338, name: 'Void Rend', rarity: 'R', layout: 'normal' },
            { cardNumber: 339, name: 'Ziatora, the Incinerator', rarity: 'M', layout: 'normal' },
            { cardNumber: 340, name: "Ziatora's Envoy", rarity: 'R', layout: 'normal' },
            { cardNumber: 341, name: 'Elspeth Resplendent', rarity: 'M', layout: 'normal' },
            { cardNumber: 342, name: 'Giada, Font of Hope', rarity: 'R', layout: 'normal' },
            { cardNumber: 343, name: 'Sanctuary Warden', rarity: 'M', layout: 'normal' },
            { cardNumber: 344, name: 'Errant, Street Artist', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, name: 'Tenacious Underdog', rarity: 'R', layout: 'normal' },
            { cardNumber: 346, name: 'Urabrask, Heretic Praetor', rarity: 'M', layout: 'normal' },
            { cardNumber: 347, name: 'Vivien on the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 348, name: 'Ob Nixilis, the Adversary', rarity: 'M', layout: 'normal' },
            { cardNumber: 349, name: 'Scheming Fence', rarity: 'R', layout: 'normal' },
            { cardNumber: 350, name: 'Botanical Plaza', rarity: 'C', layout: 'normal' },
            { cardNumber: 351, name: "Jetmir's Garden", rarity: 'R', layout: 'normal' },
            { cardNumber: 352, name: "Racers' Ring", rarity: 'C', layout: 'normal' },
            { cardNumber: 353, name: "Raffine's Tower", rarity: 'R', layout: 'normal' },
            { cardNumber: 354, name: 'Skybridge Towers', rarity: 'C', layout: 'normal' },
            { cardNumber: 355, name: "Spara's Headquarters", rarity: 'R', layout: 'normal' },
            { cardNumber: 356, name: 'Tramway Station', rarity: 'C', layout: 'normal' },
            { cardNumber: 357, name: 'Waterfront District', rarity: 'C', layout: 'normal' },
            { cardNumber: 358, name: "Xander's Lounge", rarity: 'R', layout: 'normal' },
            { cardNumber: 359, name: "Ziatora's Proving Ground", rarity: 'R', layout: 'normal' },
            { cardNumber: 360, name: 'Urabrask, Heretic Praetor', rarity: 'M', layout: 'normal' },
            { cardNumber: 361, name: 'Brazen Upstart', rarity: 'U', layout: 'normal' },
            { cardNumber: 362, name: 'Brokers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 363, name: 'Brokers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 364, name: 'Cabaretti Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 365, name: 'Cabaretti Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 366, name: 'Cormela, Glamour Thief', rarity: 'U', layout: 'normal' },
            { cardNumber: 367, name: 'Corpse Appraiser', rarity: 'U', layout: 'normal' },
            { cardNumber: 368, name: 'Crew Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 369, name: 'Disciplined Duelist', rarity: 'U', layout: 'normal' },
            { cardNumber: 370, name: 'Endless Detour', rarity: 'R', layout: 'normal' },
            { cardNumber: 371, name: 'Evelyn, the Covetous', rarity: 'R', layout: 'normal' },
            { cardNumber: 372, name: 'Falco Spara, Pactweaver', rarity: 'M', layout: 'normal' },
            { cardNumber: 373, name: 'Fleetfoot Dancer', rarity: 'R', layout: 'normal' },
            { cardNumber: 374, name: 'Glamorous Outlaw', rarity: 'C', layout: 'normal' },
            { cardNumber: 375, name: 'Hostile Takeover', rarity: 'R', layout: 'normal' },
            { cardNumber: 376, name: 'Incandescent Aria', rarity: 'R', layout: 'normal' },
            { cardNumber: 377, name: 'Jetmir, Nexus of Revels', rarity: 'M', layout: 'normal' },
            { cardNumber: 378, name: "Jinnie Fay, Jetmir's Second", rarity: 'R', layout: 'normal' },
            { cardNumber: 379, name: 'Lagrella, the Magpie', rarity: 'U', layout: 'normal' },
            { cardNumber: 380, name: 'Lord Xander, the Collector', rarity: 'M', layout: 'normal' },
            { cardNumber: 381, name: 'Maestros Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 382, name: 'Maestros Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 383, name: 'Maestros Diabolist', rarity: 'R', layout: 'normal' },
            { cardNumber: 384, name: 'Masked Bandits', rarity: 'C', layout: 'normal' },
            { cardNumber: 385, name: 'Mr. Orfeo, the Boulder', rarity: 'U', layout: 'normal' },
            { cardNumber: 386, name: 'Nimble Larcenist', rarity: 'U', layout: 'normal' },
            { cardNumber: 387, name: 'Obscura Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 388, name: 'Obscura Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 389, name: 'Obscura Interceptor', rarity: 'R', layout: 'normal' },
            { cardNumber: 390, name: "Ognis, the Dragon's Lash", rarity: 'R', layout: 'normal' },
            { cardNumber: 391, name: 'Queza, Augur of Agonies', rarity: 'U', layout: 'normal' },
            { cardNumber: 392, name: 'Raffine, Scheming Seer', rarity: 'M', layout: 'normal' },
            { cardNumber: 393, name: 'Rakish Revelers', rarity: 'C', layout: 'normal' },
            { cardNumber: 394, name: 'Rigo, Streetwise Mentor', rarity: 'R', layout: 'normal' },
            { cardNumber: 395, name: 'Riveteers Ascendancy', rarity: 'R', layout: 'normal' },
            { cardNumber: 396, name: 'Riveteers Charm', rarity: 'U', layout: 'normal' },
            { cardNumber: 397, name: 'Rocco, Cabaretti Caterer', rarity: 'U', layout: 'normal' },
            { cardNumber: 398, name: 'Shattered Seraph', rarity: 'C', layout: 'normal' },
            { cardNumber: 399, name: 'Soul of Emancipation', rarity: 'R', layout: 'normal' },
            { cardNumber: 400, name: "Spara's Adjudicators", rarity: 'C', layout: 'normal' },
            { cardNumber: 401, name: 'Toluz, Clever Conductor', rarity: 'R', layout: 'normal' },
            { cardNumber: 402, name: 'Unleash the Inferno', rarity: 'R', layout: 'normal' },
            { cardNumber: 403, name: 'Void Rend', rarity: 'R', layout: 'normal' },
            { cardNumber: 404, name: 'Ziatora, the Incinerator', rarity: 'M', layout: 'normal' },
            { cardNumber: 405, name: "Ziatora's Envoy", rarity: 'R', layout: 'normal' },
            { cardNumber: 406, name: 'Depopulate', rarity: 'R', layout: 'normal' },
            { cardNumber: 407, name: 'Extraction Specialist', rarity: 'R', layout: 'normal' },
            { cardNumber: 408, name: 'Mysterious Limousine', rarity: 'R', layout: 'normal' },
            { cardNumber: 409, name: 'Rabble Rousing', rarity: 'R', layout: 'normal' },
            { cardNumber: 410, name: 'Cut Your Losses', rarity: 'R', layout: 'normal' },
            { cardNumber: 411, name: 'Even the Score', rarity: 'M', layout: 'normal' },
            { cardNumber: 412, name: 'Ledger Shredder', rarity: 'R', layout: 'normal' },
            { cardNumber: 413, name: 'Reservoir Kraken', rarity: 'R', layout: 'normal' },
            { cardNumber: 414, name: 'Undercover Operative', rarity: 'R', layout: 'normal' },
            { cardNumber: 415, name: 'Wiretapping', rarity: 'R', layout: 'normal' },
            { cardNumber: 416, name: 'Angel of Suffering', rarity: 'M', layout: 'normal' },
            { cardNumber: 417, name: 'Body Launderer', rarity: 'M', layout: 'normal' },
            { cardNumber: 418, name: 'Cemetery Tampering', rarity: 'R', layout: 'normal' },
            { cardNumber: 419, name: 'Cut of the Profits', rarity: 'R', layout: 'normal' },
            { cardNumber: 420, name: 'Sanguine Spy', rarity: 'R', layout: 'normal' },
            { cardNumber: 421, name: 'Shakedown Heavy', rarity: 'R', layout: 'normal' },
            { cardNumber: 422, name: 'Arcane Bombardment', rarity: 'M', layout: 'normal' },
            { cardNumber: 423, name: 'Devilish Valet', rarity: 'R', layout: 'normal' },
            { cardNumber: 424, name: 'Hoard Hauler', rarity: 'R', layout: 'normal' },
            { cardNumber: 425, name: 'Jaxis, the Troublemaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 426, name: 'Professional Face-Breaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 427, name: 'Structural Assault', rarity: 'R', layout: 'normal' },
            { cardNumber: 428, name: 'Widespread Thievery', rarity: 'R', layout: 'normal' },
            { cardNumber: 429, name: 'Evolving Door', rarity: 'R', layout: 'normal' },
            { cardNumber: 430, name: 'Fight Rigging', rarity: 'R', layout: 'normal' },
            { cardNumber: 431, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 432, name: 'Workshop Warchief', rarity: 'R', layout: 'normal' },
            { cardNumber: 433, name: 'Aven Heartstabber', rarity: 'R', layout: 'normal' },
            { cardNumber: 434, name: 'Black Market Tycoon', rarity: 'R', layout: 'normal' },
            { cardNumber: 435, name: 'Corpse Explosion', rarity: 'R', layout: 'normal' },
            { cardNumber: 436, name: 'Meeting of the Five', rarity: 'M', layout: 'normal' },
            { cardNumber: 437, name: 'Park Heights Pegasus', rarity: 'R', layout: 'normal' },
            { cardNumber: 438, name: 'Getaway Car', rarity: 'R', layout: 'normal' },
            { cardNumber: 439, name: "Luxior, Giada's Gift", rarity: 'M', layout: 'normal' },
            { cardNumber: 440, name: 'Unlicensed Hearse', rarity: 'R', layout: 'normal' },
            { cardNumber: 441, name: 'Elspeth Resplendent', rarity: 'M', layout: 'normal' },
            { cardNumber: 442, name: 'Giada, Font of Hope', rarity: 'R', layout: 'normal' },
            { cardNumber: 443, name: 'Sanctuary Warden', rarity: 'M', layout: 'normal' },
            { cardNumber: 444, name: 'Errant, Street Artist', rarity: 'R', layout: 'normal' },
            { cardNumber: 445, name: 'Tenacious Underdog', rarity: 'R', layout: 'normal' },
            { cardNumber: 446, name: 'Urabrask, Heretic Praetor', rarity: 'M', layout: 'normal' },
            { cardNumber: 447, name: 'Vivien on the Hunt', rarity: 'M', layout: 'normal' },
            { cardNumber: 448, name: 'Ob Nixilis, the Adversary', rarity: 'M', layout: 'normal' },
            { cardNumber: 449, name: 'Scheming Fence', rarity: 'R', layout: 'normal' },
            { cardNumber: 450, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 451, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 452, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 453, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 454, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 455, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 456, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 457, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 458, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 459, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 460, name: 'Gala Greeters', rarity: 'R', layout: 'normal' },
            { cardNumber: 461, name: 'Jaxis, the Troublemaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 462, name: 'Mysterious Limousine', rarity: 'R', layout: 'normal' },
            { cardNumber: 463, name: 'Rumor Gatherer', rarity: 'U', layout: 'normal' },
            { cardNumber: 464, name: "An Offer You Can't Refuse", rarity: 'U', layout: 'normal' },
            { cardNumber: 465, name: 'Incriminate', rarity: 'C', layout: 'normal' },
            { cardNumber: 466, name: "Light 'Em Up", rarity: 'C', layout: 'normal' },
            { cardNumber: 467, name: "Courier's Briefcase", rarity: 'U', layout: 'normal' },
        ];
        await MigrationHelper.cardSetUp(
            queryRunner,
            'Streets of New Capenna',
            this.shortName,
            cardValues,
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
