import { InsertResult, MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addDmu1661856164149 implements MigrationInterface {
    shortName = 'DMU';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            { cardNumber: 1, name: 'Karn, Living Legacy', rarity: 'M', layout: 'normal' },
            { cardNumber: 2, name: 'Anointed Peacekeeper', rarity: 'R', layout: 'normal' },
            { cardNumber: 3, name: 'Archangel of Wrath', rarity: 'R', layout: 'normal' },
            { cardNumber: 4, name: 'Argivian Cavalier', rarity: 'C', layout: 'normal' },
            { cardNumber: 5, name: 'Argivian Phalanx', rarity: 'C', layout: 'normal' },
            { cardNumber: 6, name: 'Artillery Blast', rarity: 'C', layout: 'normal' },
            { cardNumber: 7, name: 'Benalish Faithbonder', rarity: 'C', layout: 'normal' },
            { cardNumber: 8, name: 'Benalish Sleeper', rarity: 'C', layout: 'normal' },
            { cardNumber: 9, name: "Captain's Call", rarity: 'C', layout: 'normal' },
            { cardNumber: 10, name: 'Charismatic Vanguard', rarity: 'C', layout: 'normal' },
            { cardNumber: 11, name: "Citizen's Arrest", rarity: 'C', layout: 'normal' },
            { cardNumber: 12, name: 'Cleaving Skyrider', rarity: 'U', layout: 'normal' },
            { cardNumber: 13, name: 'Clockwork Drawbridge', rarity: 'C', layout: 'normal' },
            { cardNumber: 14, name: 'Coalition Skyknight', rarity: 'U', layout: 'normal' },
            { cardNumber: 15, name: "Danitha, Benalia's Hope", rarity: 'R', layout: 'normal' },
            { cardNumber: 16, name: 'Defiler of Faith', rarity: 'R', layout: 'normal' },
            { cardNumber: 17, name: 'Destroy Evil', rarity: 'C', layout: 'normal' },
            { cardNumber: 18, name: 'Griffin Protector', rarity: 'C', layout: 'normal' },
            { cardNumber: 19, name: 'Guardian of New Benalia', rarity: 'R', layout: 'normal' },
            { cardNumber: 20, name: 'Heroic Charge', rarity: 'C', layout: 'normal' },
            { cardNumber: 21, name: 'Join Forces', rarity: 'U', layout: 'normal' },
            { cardNumber: 22, name: 'Juniper Order Rootweaver', rarity: 'C', layout: 'normal' },
            { cardNumber: 23, name: "Knight of Dawn's Light", rarity: 'U', layout: 'normal' },
            { cardNumber: 24, name: 'Leyline Binding', rarity: 'R', layout: 'normal' },
            { cardNumber: 25, name: 'Love Song of Night and Day', rarity: 'U', layout: 'saga' },
            { cardNumber: 26, name: 'Mesa Cavalier', rarity: 'C', layout: 'normal' },
            { cardNumber: 27, name: 'Phyrexian Missionary', rarity: 'U', layout: 'normal' },
            { cardNumber: 28, name: 'Prayer of Binding', rarity: 'U', layout: 'normal' },
            { cardNumber: 29, name: 'Resolute Reinforcements', rarity: 'U', layout: 'normal' },
            { cardNumber: 30, name: 'Runic Shot', rarity: 'U', layout: 'normal' },
            { cardNumber: 31, name: 'Samite Herbalist', rarity: 'C', layout: 'normal' },
            { cardNumber: 32, name: 'Serra Paragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 33, name: "Shalai's Acolyte", rarity: 'U', layout: 'normal' },
            { cardNumber: 34, name: 'Stall for Time', rarity: 'C', layout: 'normal' },
            { cardNumber: 35, name: 'Take Up the Shield', rarity: 'C', layout: 'normal' },
            { cardNumber: 36, name: 'Temporary Lockdown', rarity: 'R', layout: 'normal' },
            { cardNumber: 37, name: 'Urza Assembles the Titans', rarity: 'R', layout: 'saga' },
            { cardNumber: 38, name: 'Valiant Veteran', rarity: 'R', layout: 'normal' },
            { cardNumber: 39, name: 'Wingmantle Chaplain', rarity: 'U', layout: 'normal' },
            { cardNumber: 40, name: 'Academy Loremaster', rarity: 'R', layout: 'normal' },
            { cardNumber: 41, name: 'Academy Wall', rarity: 'C', layout: 'normal' },
            { cardNumber: 42, name: 'Aether Channeler', rarity: 'R', layout: 'normal' },
            { cardNumber: 43, name: 'Battlewing Mystic', rarity: 'U', layout: 'normal' },
            { cardNumber: 44, name: 'Combat Research', rarity: 'U', layout: 'normal' },
            { cardNumber: 45, name: 'Coral Colony', rarity: 'U', layout: 'normal' },
            { cardNumber: 46, name: 'Defiler of Dreams', rarity: 'R', layout: 'normal' },
            { cardNumber: 47, name: 'Djinn of the Fountain', rarity: 'U', layout: 'normal' },
            { cardNumber: 48, name: "Ertai's Scorn", rarity: 'U', layout: 'normal' },
            { cardNumber: 49, name: 'Essence Scatter', rarity: 'C', layout: 'normal' },
            { cardNumber: 50, name: 'Founding the Third Path', rarity: 'U', layout: 'saga' },
            { cardNumber: 51, name: 'Frostfist Strider', rarity: 'U', layout: 'normal' },
            { cardNumber: 52, name: 'Haughty Djinn', rarity: 'R', layout: 'normal' },
            { cardNumber: 53, name: 'Haunting Figment', rarity: 'C', layout: 'normal' },
            { cardNumber: 54, name: 'Impede Momentum', rarity: 'C', layout: 'normal' },
            { cardNumber: 55, name: 'Impulse', rarity: 'C', layout: 'normal' },
            { cardNumber: 56, name: 'Joint Exploration', rarity: 'U', layout: 'normal' },
            { cardNumber: 57, name: 'Micromancer', rarity: 'U', layout: 'normal' },
            { cardNumber: 58, name: 'Negate', rarity: 'C', layout: 'normal' },
            { cardNumber: 59, name: 'The Phasing of Zhalfir', rarity: 'R', layout: 'saga' },
            { cardNumber: 60, name: 'Phyrexian Espionage', rarity: 'C', layout: 'normal' },
            { cardNumber: 61, name: 'Pixie Illusionist', rarity: 'C', layout: 'normal' },
            { cardNumber: 62, name: 'Protect the Negotiators', rarity: 'U', layout: 'normal' },
            { cardNumber: 63, name: "Rona's Vortex", rarity: 'U', layout: 'normal' },
            { cardNumber: 64, name: 'Shore Up', rarity: 'C', layout: 'normal' },
            { cardNumber: 65, name: 'Silver Scrutiny', rarity: 'R', layout: 'normal' },
            { cardNumber: 66, name: 'Soaring Drake', rarity: 'C', layout: 'normal' },
            { cardNumber: 67, name: 'Sphinx of Clear Skies', rarity: 'M', layout: 'normal' },
            { cardNumber: 68, name: 'Talas Lookout', rarity: 'C', layout: 'normal' },
            { cardNumber: 69, name: 'Tidepool Turtle', rarity: 'C', layout: 'normal' },
            { cardNumber: 70, name: 'Timely Interference', rarity: 'C', layout: 'normal' },
            { cardNumber: 71, name: 'Tolarian Geyser', rarity: 'C', layout: 'normal' },
            { cardNumber: 72, name: 'Tolarian Terror', rarity: 'C', layout: 'normal' },
            { cardNumber: 73, name: 'Vesuvan Duplimancy', rarity: 'M', layout: 'normal' },
            { cardNumber: 74, name: 'Voda Sea Scavenger', rarity: 'C', layout: 'normal' },
            { cardNumber: 75, name: 'Vodalian Hexcatcher', rarity: 'R', layout: 'normal' },
            { cardNumber: 76, name: 'Vodalian Mindsinger', rarity: 'R', layout: 'normal' },
            { cardNumber: 77, name: 'Volshe Tideturner', rarity: 'C', layout: 'normal' },
            { cardNumber: 78, name: 'Aggressive Sabotage', rarity: 'C', layout: 'normal' },
            { cardNumber: 79, name: 'Balduvian Atrocity', rarity: 'U', layout: 'normal' },
            { cardNumber: 80, name: 'Battle-Rage Blessing', rarity: 'C', layout: 'normal' },
            { cardNumber: 81, name: 'Battlefly Swarm', rarity: 'C', layout: 'normal' },
            { cardNumber: 82, name: 'Blight Pile', rarity: 'U', layout: 'normal' },
            { cardNumber: 83, name: 'Bone Splinters', rarity: 'C', layout: 'normal' },
            { cardNumber: 84, name: 'Braids, Arisen Nightmare', rarity: 'R', layout: 'normal' },
            { cardNumber: 85, name: "Braids's Frightful Return", rarity: 'U', layout: 'saga' },
            { cardNumber: 86, name: 'Choking Miasma', rarity: 'U', layout: 'normal' },
            { cardNumber: 87, name: 'The Cruelty of Gix', rarity: 'R', layout: 'saga' },
            { cardNumber: 88, name: 'Cult Conscript', rarity: 'U', layout: 'normal' },
            { cardNumber: 89, name: 'Cut Down', rarity: 'U', layout: 'normal' },
            { cardNumber: 90, name: 'Defiler of Flesh', rarity: 'R', layout: 'normal' },
            { cardNumber: 91, name: 'Drag to the Bottom', rarity: 'R', layout: 'normal' },
            { cardNumber: 92, name: 'Eerie Soultender', rarity: 'C', layout: 'normal' },
            { cardNumber: 93, name: 'Evolved Sleeper', rarity: 'R', layout: 'normal' },
            { cardNumber: 94, name: 'Extinguish the Light', rarity: 'C', layout: 'normal' },
            { cardNumber: 95, name: 'Gibbering Barricade', rarity: 'C', layout: 'normal' },
            { cardNumber: 96, name: "Knight of Dusk's Shadow", rarity: 'U', layout: 'normal' },
            { cardNumber: 97, name: 'Liliana of the Veil', rarity: 'M', layout: 'normal' },
            { cardNumber: 98, name: 'Monstrous War-Leech', rarity: 'U', layout: 'normal' },
            { cardNumber: 99, name: 'Phyrexian Rager', rarity: 'C', layout: 'normal' },
            { cardNumber: 100, name: 'Phyrexian Vivisector', rarity: 'C', layout: 'normal' },
            { cardNumber: 101, name: 'Phyrexian Warhorse', rarity: 'C', layout: 'normal' },
            { cardNumber: 102, name: 'Pilfer', rarity: 'U', layout: 'normal' },
            { cardNumber: 103, name: 'The Raven Man', rarity: 'R', layout: 'normal' },
            { cardNumber: 104, name: 'Sengir Connoisseur', rarity: 'U', layout: 'normal' },
            { cardNumber: 105, name: 'Shadow Prophecy', rarity: 'C', layout: 'normal' },
            { cardNumber: 106, name: 'Shadow-Rite Priest', rarity: 'R', layout: 'normal' },
            { cardNumber: 107, name: 'Sheoldred, the Apocalypse', rarity: 'M', layout: 'normal' },
            { cardNumber: 108, name: "Sheoldred's Restoration", rarity: 'U', layout: 'normal' },
            { cardNumber: 109, name: 'Splatter Goblin', rarity: 'C', layout: 'normal' },
            { cardNumber: 110, name: 'Stronghold Arena', rarity: 'R', layout: 'normal' },
            { cardNumber: 111, name: 'Tattered Apparition', rarity: 'C', layout: 'normal' },
            { cardNumber: 112, name: 'Toxic Abomination', rarity: 'C', layout: 'normal' },
            { cardNumber: 113, name: 'Tribute to Urborg', rarity: 'C', layout: 'normal' },
            { cardNumber: 114, name: 'Urborg Repossession', rarity: 'C', layout: 'normal' },
            { cardNumber: 115, name: 'Writhing Necromass', rarity: 'C', layout: 'normal' },
            { cardNumber: 116, name: 'Balduvian Berserker', rarity: 'U', layout: 'normal' },
            { cardNumber: 117, name: 'Chaotic Transformation', rarity: 'R', layout: 'normal' },
            { cardNumber: 118, name: 'Coalition Warbrute', rarity: 'C', layout: 'normal' },
            { cardNumber: 119, name: 'Defiler of Instinct', rarity: 'R', layout: 'normal' },
            { cardNumber: 120, name: 'Dragon Whelp', rarity: 'U', layout: 'normal' },
            { cardNumber: 121, name: 'The Elder Dragon War', rarity: 'R', layout: 'saga' },
            { cardNumber: 122, name: 'Electrostatic Infantry', rarity: 'U', layout: 'normal' },
            { cardNumber: 123, name: 'Fires of Victory', rarity: 'U', layout: 'normal' },
            { cardNumber: 124, name: 'Flowstone Infusion', rarity: 'C', layout: 'normal' },
            { cardNumber: 125, name: 'Flowstone Kavu', rarity: 'C', layout: 'normal' },
            { cardNumber: 126, name: 'Furious Bellow', rarity: 'C', layout: 'normal' },
            { cardNumber: 127, name: 'Ghitu Amplifier', rarity: 'C', layout: 'normal' },
            { cardNumber: 128, name: 'Goblin Picker', rarity: 'C', layout: 'normal' },
            { cardNumber: 129, name: 'Hammerhand', rarity: 'C', layout: 'normal' },
            { cardNumber: 130, name: 'Hurler Cyclops', rarity: 'U', layout: 'normal' },
            { cardNumber: 131, name: 'Hurloon Battle Hymn', rarity: 'U', layout: 'normal' },
            { cardNumber: 132, name: 'In Thrall to the Pit', rarity: 'C', layout: 'normal' },
            { cardNumber: 133, name: 'Jaya, Fiery Negotiator', rarity: 'M', layout: 'normal' },
            { cardNumber: 134, name: "Jaya's Firenado", rarity: 'C', layout: 'normal' },
            { cardNumber: 135, name: 'Keldon Flamesage', rarity: 'R', layout: 'normal' },
            { cardNumber: 136, name: 'Keldon Strike Team', rarity: 'C', layout: 'normal' },
            { cardNumber: 137, name: 'Lightning Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 138, name: "Meria's Outrider", rarity: 'C', layout: 'normal' },
            { cardNumber: 139, name: 'Molten Monstrosity', rarity: 'C', layout: 'normal' },
            { cardNumber: 140, name: 'Phoenix Chick', rarity: 'U', layout: 'normal' },
            { cardNumber: 141, name: "Radha's Firebrand", rarity: 'R', layout: 'normal' },
            { cardNumber: 142, name: 'Rundvelt Hordemaster', rarity: 'R', layout: 'normal' },
            { cardNumber: 143, name: 'Shivan Devastator', rarity: 'M', layout: 'normal' },
            { cardNumber: 144, name: 'Smash to Dust', rarity: 'C', layout: 'normal' },
            { cardNumber: 145, name: 'Sprouting Goblin', rarity: 'U', layout: 'normal' },
            { cardNumber: 146, name: 'Squee, Dubious Monarch', rarity: 'R', layout: 'normal' },
            { cardNumber: 147, name: 'Temporal Firestorm', rarity: 'R', layout: 'normal' },
            { cardNumber: 148, name: 'Thrill of Possibility', rarity: 'C', layout: 'normal' },
            { cardNumber: 149, name: 'Twinferno', rarity: 'U', layout: 'normal' },
            { cardNumber: 150, name: 'Viashino Branchrider', rarity: 'C', layout: 'normal' },
            { cardNumber: 151, name: "Warhost's Frenzy", rarity: 'U', layout: 'normal' },
            { cardNumber: 152, name: 'Yavimaya Steelcrusher', rarity: 'C', layout: 'normal' },
            { cardNumber: 153, name: 'Yotia Declares War', rarity: 'U', layout: 'saga' },
            { cardNumber: 154, name: 'Barkweave Crusher', rarity: 'C', layout: 'normal' },
            { cardNumber: 155, name: 'Bite Down', rarity: 'C', layout: 'normal' },
            { cardNumber: 156, name: 'Bog Badger', rarity: 'C', layout: 'normal' },
            { cardNumber: 157, name: 'Broken Wings', rarity: 'C', layout: 'normal' },
            { cardNumber: 158, name: 'Colossal Growth', rarity: 'C', layout: 'normal' },
            { cardNumber: 159, name: 'Deathbloom Gardener', rarity: 'C', layout: 'normal' },
            { cardNumber: 160, name: 'Defiler of Vigor', rarity: 'R', layout: 'normal' },
            { cardNumber: 161, name: 'Elfhame Wurm', rarity: 'C', layout: 'normal' },
            { cardNumber: 162, name: 'Elvish Hydromancer', rarity: 'U', layout: 'normal' },
            { cardNumber: 163, name: 'Floriferous Vinewall', rarity: 'C', layout: 'normal' },
            { cardNumber: 164, name: "Gaea's Might", rarity: 'C', layout: 'normal' },
            { cardNumber: 165, name: 'Herd Migration', rarity: 'R', layout: 'normal' },
            { cardNumber: 166, name: 'Hexbane Tortoise', rarity: 'C', layout: 'normal' },
            { cardNumber: 167, name: 'Leaf-Crowned Visionary', rarity: 'R', layout: 'normal' },
            { cardNumber: 168, name: 'Linebreaker Baloth', rarity: 'U', layout: 'normal' },
            { cardNumber: 169, name: 'Llanowar Greenwidow', rarity: 'R', layout: 'normal' },
            { cardNumber: 170, name: 'Llanowar Loamspeaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 171, name: 'Llanowar Stalker', rarity: 'C', layout: 'normal' },
            { cardNumber: 172, name: 'Magnigoth Sentry', rarity: 'C', layout: 'normal' },
            { cardNumber: 173, name: 'Mossbeard Ancient', rarity: 'U', layout: 'normal' },
            { cardNumber: 174, name: 'Nishoba Brawler', rarity: 'U', layout: 'normal' },
            { cardNumber: 175, name: 'Quirion Beastcaller', rarity: 'R', layout: 'normal' },
            { cardNumber: 176, name: 'Scout the Wilderness', rarity: 'C', layout: 'normal' },
            { cardNumber: 177, name: 'Silverback Elder', rarity: 'M', layout: 'normal' },
            { cardNumber: 178, name: "Slimefoot's Survey", rarity: 'U', layout: 'normal' },
            { cardNumber: 179, name: 'Snarespinner', rarity: 'C', layout: 'normal' },
            { cardNumber: 180, name: 'Strength of the Coalition', rarity: 'U', layout: 'normal' },
            { cardNumber: 181, name: 'Sunbathing Rootwalla', rarity: 'C', layout: 'normal' },
            { cardNumber: 182, name: 'Tail Swipe', rarity: 'U', layout: 'normal' },
            { cardNumber: 183, name: 'Tear Asunder', rarity: 'U', layout: 'normal' },
            { cardNumber: 184, name: 'Territorial Maro', rarity: 'U', layout: 'normal' },
            { cardNumber: 185, name: 'Threats Undetected', rarity: 'R', layout: 'normal' },
            { cardNumber: 186, name: 'Urborg Lhurgoyf', rarity: 'R', layout: 'normal' },
            { cardNumber: 187, name: 'Vineshaper Prodigy', rarity: 'C', layout: 'normal' },
            { cardNumber: 188, name: 'The Weatherseed Treaty', rarity: 'U', layout: 'saga' },
            { cardNumber: 189, name: 'The World Spell', rarity: 'M', layout: 'saga' },
            { cardNumber: 190, name: 'Yavimaya Iconoclast', rarity: 'U', layout: 'normal' },
            { cardNumber: 191, name: 'Yavimaya Sojourner', rarity: 'C', layout: 'normal' },
            { cardNumber: 192, name: 'Ajani, Sleeper Agent', rarity: 'M', layout: 'normal' },
            { cardNumber: 193, name: "Aron, Benalia's Ruin", rarity: 'U', layout: 'normal' },
            { cardNumber: 194, name: 'Astor, Bearer of Blades', rarity: 'R', layout: 'normal' },
            { cardNumber: 195, name: 'Baird, Argivian Recruiter', rarity: 'U', layout: 'normal' },
            { cardNumber: 196, name: 'Balmor, Battlemage Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 197, name: 'Bortuk Bonerattle', rarity: 'U', layout: 'normal' },
            {
                cardNumber: 198,
                name: 'Elas il-Kor, Sadistic Pilgrim',
                rarity: 'U',
                layout: 'normal',
            },
            { cardNumber: 199, name: 'Ertai Resurrected', rarity: 'R', layout: 'normal' },
            { cardNumber: 200, name: 'Garna, Bloodfist of Keld', rarity: 'U', layout: 'normal' },
            { cardNumber: 201, name: 'Ivy, Gleeful Spellthief', rarity: 'R', layout: 'normal' },
            { cardNumber: 202, name: 'Jhoira, Ageless Innovator', rarity: 'R', layout: 'normal' },
            { cardNumber: 203, name: 'Jodah, the Unifier', rarity: 'M', layout: 'normal' },
            { cardNumber: 204, name: 'King Darien XLVIII', rarity: 'R', layout: 'normal' },
            { cardNumber: 205, name: 'Lagomos, Hand of Hatred', rarity: 'U', layout: 'normal' },
            { cardNumber: 206, name: 'Meria, Scholar of Antiquity', rarity: 'R', layout: 'normal' },
            { cardNumber: 207, name: 'Nael, Avizoa Aeronaut', rarity: 'U', layout: 'normal' },
            { cardNumber: 208, name: 'Najal, the Storm Runner', rarity: 'U', layout: 'normal' },
            { cardNumber: 209, name: 'Nemata, Primeval Warden', rarity: 'R', layout: 'normal' },
            { cardNumber: 210, name: 'Queen Allenal of Ruadach', rarity: 'U', layout: 'normal' },
            { cardNumber: 211, name: 'Radha, Coalition Warlord', rarity: 'U', layout: 'normal' },
            { cardNumber: 212, name: 'Raff, Weatherlight Stalwart', rarity: 'U', layout: 'normal' },
            { cardNumber: 213, name: 'Ratadrabik of Urborg', rarity: 'R', layout: 'normal' },
            { cardNumber: 214, name: 'Rith, Liberated Primeval', rarity: 'M', layout: 'normal' },
            { cardNumber: 215, name: 'Rivaz of the Claw', rarity: 'R', layout: 'normal' },
            { cardNumber: 216, name: "Rona, Sheoldred's Faithful", rarity: 'U', layout: 'normal' },
            { cardNumber: 217, name: 'Rulik Mons, Warren Chief', rarity: 'U', layout: 'normal' },
            { cardNumber: 218, name: 'Shanna, Purifying Blade', rarity: 'M', layout: 'normal' },
            { cardNumber: 219, name: "Sol'Kanar the Tainted", rarity: 'M', layout: 'normal' },
            { cardNumber: 220, name: 'Soul of Windgrace', rarity: 'M', layout: 'normal' },
            { cardNumber: 221, name: 'Stenn, Paranoid Partisan', rarity: 'R', layout: 'normal' },
            { cardNumber: 222, name: 'Tatyova, Steward of Tides', rarity: 'U', layout: 'normal' },
            { cardNumber: 223, name: "Tori D'Avenant, Fury Rider", rarity: 'U', layout: 'normal' },
            { cardNumber: 224, name: 'Tura Kennerüd, Skyknight', rarity: 'U', layout: 'normal' },
            { cardNumber: 225, name: 'Uurg, Spawn of Turg', rarity: 'U', layout: 'normal' },
            { cardNumber: 226, name: 'Vohar, Vodalian Desecrator', rarity: 'U', layout: 'normal' },
            { cardNumber: 227, name: 'Zar Ojanen, Scion of Efrava', rarity: 'U', layout: 'normal' },
            { cardNumber: 228, name: 'Zur, Eternal Schemer', rarity: 'M', layout: 'normal' },
            { cardNumber: 229, name: 'Automatic Librarian', rarity: 'C', layout: 'normal' },
            { cardNumber: 230, name: 'Golden Argosy', rarity: 'R', layout: 'normal' },
            { cardNumber: 231, name: "Hero's Heirloom", rarity: 'U', layout: 'normal' },
            { cardNumber: 232, name: 'Inscribed Tablet', rarity: 'U', layout: 'normal' },
            { cardNumber: 233, name: "Jodah's Codex", rarity: 'U', layout: 'normal' },
            { cardNumber: 234, name: "Karn's Sylex", rarity: 'M', layout: 'normal' },
            { cardNumber: 235, name: 'Meteorite', rarity: 'C', layout: 'normal' },
            { cardNumber: 236, name: 'Relic of Legends', rarity: 'U', layout: 'normal' },
            { cardNumber: 237, name: 'Salvaged Manaworker', rarity: 'C', layout: 'normal' },
            { cardNumber: 238, name: 'Shield-Wall Sentinel', rarity: 'C', layout: 'normal' },
            { cardNumber: 239, name: 'Timeless Lotus', rarity: 'M', layout: 'normal' },
            { cardNumber: 240, name: "Vanquisher's Axe", rarity: 'C', layout: 'normal' },
            { cardNumber: 241, name: 'Walking Bulwark', rarity: 'U', layout: 'normal' },
            { cardNumber: 242, name: 'Weatherlight Compleated', rarity: 'M', layout: 'normal' },
            { cardNumber: 243, name: 'Adarkar Wastes', rarity: 'R', layout: 'normal' },
            { cardNumber: 244, name: 'Caves of Koilos', rarity: 'R', layout: 'normal' },
            { cardNumber: 245, name: 'Contaminated Aquifer', rarity: 'C', layout: 'normal' },
            { cardNumber: 246, name: 'Crystal Grotto', rarity: 'C', layout: 'normal' },
            { cardNumber: 247, name: 'Geothermal Bog', rarity: 'C', layout: 'normal' },
            { cardNumber: 248, name: 'Haunted Mire', rarity: 'C', layout: 'normal' },
            { cardNumber: 249, name: 'Idyllic Beachfront', rarity: 'C', layout: 'normal' },
            { cardNumber: 250, name: 'Karplusan Forest', rarity: 'R', layout: 'normal' },
            { cardNumber: 251, name: 'Molten Tributary', rarity: 'C', layout: 'normal' },
            { cardNumber: 252, name: 'Plaza of Heroes', rarity: 'R', layout: 'normal' },
            { cardNumber: 253, name: 'Radiant Grove', rarity: 'C', layout: 'normal' },
            { cardNumber: 254, name: 'Sacred Peaks', rarity: 'C', layout: 'normal' },
            { cardNumber: 255, name: 'Shivan Reef', rarity: 'R', layout: 'normal' },
            { cardNumber: 256, name: 'Sulfurous Springs', rarity: 'R', layout: 'normal' },
            { cardNumber: 257, name: 'Sunlit Marsh', rarity: 'C', layout: 'normal' },
            { cardNumber: 258, name: 'Tangled Islet', rarity: 'C', layout: 'normal' },
            { cardNumber: 259, name: 'Thran Portal', rarity: 'R', layout: 'normal' },
            { cardNumber: 260, name: 'Wooded Ridgeline', rarity: 'C', layout: 'normal' },
            { cardNumber: 261, name: 'Yavimaya Coast', rarity: 'R', layout: 'normal' },
            { cardNumber: 262, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 263, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 264, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 265, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 266, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 267, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 268, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 269, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 270, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 271, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 272, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 273, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 274, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 275, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 276, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 277, name: 'Plains', rarity: 'C', layout: 'normal' },
            { cardNumber: 278, name: 'Island', rarity: 'C', layout: 'normal' },
            { cardNumber: 279, name: 'Swamp', rarity: 'C', layout: 'normal' },
            { cardNumber: 280, name: 'Mountain', rarity: 'C', layout: 'normal' },
            { cardNumber: 281, name: 'Forest', rarity: 'C', layout: 'normal' },
            { cardNumber: 282, name: 'Serra Redeemer', rarity: 'R', layout: 'normal' },
            { cardNumber: 283, name: 'Cosmic Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 284, name: 'Tyrannical Pitlord', rarity: 'R', layout: 'normal' },
            { cardNumber: 285, name: 'Ragefire Hellkite', rarity: 'R', layout: 'normal' },
            { cardNumber: 286, name: 'Briar Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 287, name: "Danitha, Benalia's Hope", rarity: 'R', layout: 'normal' },
            { cardNumber: 288, name: 'Braids, Arisen Nightmare', rarity: 'R', layout: 'normal' },
            { cardNumber: 289, name: 'The Raven Man', rarity: 'R', layout: 'normal' },
            { cardNumber: 290, name: 'Sheoldred, the Apocalypse', rarity: 'M', layout: 'normal' },
            { cardNumber: 291, name: 'Squee, Dubious Monarch', rarity: 'R', layout: 'normal' },
            { cardNumber: 292, name: "Aron, Benalia's Ruin", rarity: 'U', layout: 'normal' },
            { cardNumber: 293, name: 'Astor, Bearer of Blades', rarity: 'R', layout: 'normal' },
            { cardNumber: 294, name: 'Baird, Argivian Recruiter', rarity: 'U', layout: 'normal' },
            { cardNumber: 295, name: 'Balmor, Battlemage Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 296, name: 'Bortuk Bonerattle', rarity: 'U', layout: 'normal' },
            {
                cardNumber: 297,
                name: 'Elas il-Kor, Sadistic Pilgrim',
                rarity: 'U',
                layout: 'normal',
            },
            { cardNumber: 298, name: 'Ertai Resurrected', rarity: 'R', layout: 'normal' },
            { cardNumber: 299, name: 'Garna, Bloodfist of Keld', rarity: 'U', layout: 'normal' },
            { cardNumber: 300, name: 'Ivy, Gleeful Spellthief', rarity: 'R', layout: 'normal' },
            { cardNumber: 301, name: 'Jhoira, Ageless Innovator', rarity: 'R', layout: 'normal' },
            { cardNumber: 302, name: 'Jodah, the Unifier', rarity: 'M', layout: 'normal' },
            { cardNumber: 303, name: 'King Darien XLVIII', rarity: 'R', layout: 'normal' },
            { cardNumber: 304, name: 'Lagomos, Hand of Hatred', rarity: 'U', layout: 'normal' },
            { cardNumber: 305, name: 'Meria, Scholar of Antiquity', rarity: 'R', layout: 'normal' },
            { cardNumber: 306, name: 'Nael, Avizoa Aeronaut', rarity: 'U', layout: 'normal' },
            { cardNumber: 307, name: 'Najal, the Storm Runner', rarity: 'U', layout: 'normal' },
            { cardNumber: 308, name: 'Nemata, Primeval Warden', rarity: 'R', layout: 'normal' },
            { cardNumber: 309, name: 'Queen Allenal of Ruadach', rarity: 'U', layout: 'normal' },
            { cardNumber: 310, name: 'Radha, Coalition Warlord', rarity: 'U', layout: 'normal' },
            { cardNumber: 311, name: 'Raff, Weatherlight Stalwart', rarity: 'U', layout: 'normal' },
            { cardNumber: 312, name: 'Ratadrabik of Urborg', rarity: 'R', layout: 'normal' },
            { cardNumber: 313, name: 'Rith, Liberated Primeval', rarity: 'M', layout: 'normal' },
            { cardNumber: 314, name: 'Rivaz of the Claw', rarity: 'R', layout: 'normal' },
            { cardNumber: 315, name: "Rona, Sheoldred's Faithful", rarity: 'U', layout: 'normal' },
            { cardNumber: 316, name: 'Rulik Mons, Warren Chief', rarity: 'U', layout: 'normal' },
            { cardNumber: 317, name: 'Shanna, Purifying Blade', rarity: 'M', layout: 'normal' },
            { cardNumber: 318, name: "Sol'Kanar the Tainted", rarity: 'M', layout: 'normal' },
            { cardNumber: 319, name: 'Soul of Windgrace', rarity: 'M', layout: 'normal' },
            { cardNumber: 320, name: 'Stenn, Paranoid Partisan', rarity: 'R', layout: 'normal' },
            { cardNumber: 321, name: 'Tatyova, Steward of Tides', rarity: 'U', layout: 'normal' },
            { cardNumber: 322, name: "Tori D'Avenant, Fury Rider", rarity: 'U', layout: 'normal' },
            { cardNumber: 323, name: 'Tura Kennerüd, Skyknight', rarity: 'U', layout: 'normal' },
            { cardNumber: 324, name: 'Uurg, Spawn of Turg', rarity: 'U', layout: 'normal' },
            { cardNumber: 325, name: 'Vohar, Vodalian Desecrator', rarity: 'U', layout: 'normal' },
            { cardNumber: 326, name: 'Zar Ojanen, Scion of Efrava', rarity: 'U', layout: 'normal' },
            { cardNumber: 327, name: 'Zur, Eternal Schemer', rarity: 'M', layout: 'normal' },
            { cardNumber: 328, name: "Danitha, Benalia's Hope", rarity: 'R', layout: 'normal' },
            { cardNumber: 329, name: 'Braids, Arisen Nightmare', rarity: 'R', layout: 'normal' },
            { cardNumber: 330, name: 'The Raven Man', rarity: 'R', layout: 'normal' },
            { cardNumber: 331, name: 'Sheoldred, the Apocalypse', rarity: 'M', layout: 'normal' },
            { cardNumber: 332, name: 'Squee, Dubious Monarch', rarity: 'R', layout: 'normal' },
            { cardNumber: 333, name: "Aron, Benalia's Ruin", rarity: 'U', layout: 'normal' },
            { cardNumber: 334, name: 'Astor, Bearer of Blades', rarity: 'R', layout: 'normal' },
            { cardNumber: 335, name: 'Baird, Argivian Recruiter', rarity: 'U', layout: 'normal' },
            { cardNumber: 336, name: 'Balmor, Battlemage Captain', rarity: 'U', layout: 'normal' },
            { cardNumber: 337, name: 'Bortuk Bonerattle', rarity: 'U', layout: 'normal' },
            {
                cardNumber: 338,
                name: 'Elas il-Kor, Sadistic Pilgrim',
                rarity: 'U',
                layout: 'normal',
            },
            { cardNumber: 339, name: 'Ertai Resurrected', rarity: 'R', layout: 'normal' },
            { cardNumber: 340, name: 'Garna, Bloodfist of Keld', rarity: 'U', layout: 'normal' },
            { cardNumber: 341, name: 'Ivy, Gleeful Spellthief', rarity: 'R', layout: 'normal' },
            { cardNumber: 342, name: 'Jhoira, Ageless Innovator', rarity: 'R', layout: 'normal' },
            { cardNumber: 343, name: 'Jodah, the Unifier', rarity: 'M', layout: 'normal' },
            { cardNumber: 344, name: 'King Darien XLVIII', rarity: 'R', layout: 'normal' },
            { cardNumber: 345, name: 'Lagomos, Hand of Hatred', rarity: 'U', layout: 'normal' },
            { cardNumber: 346, name: 'Meria, Scholar of Antiquity', rarity: 'R', layout: 'normal' },
            { cardNumber: 347, name: 'Nael, Avizoa Aeronaut', rarity: 'U', layout: 'normal' },
            { cardNumber: 348, name: 'Najal, the Storm Runner', rarity: 'U', layout: 'normal' },
            { cardNumber: 349, name: 'Nemata, Primeval Warden', rarity: 'R', layout: 'normal' },
            { cardNumber: 350, name: 'Queen Allenal of Ruadach', rarity: 'U', layout: 'normal' },
            { cardNumber: 351, name: 'Radha, Coalition Warlord', rarity: 'U', layout: 'normal' },
            { cardNumber: 352, name: 'Raff, Weatherlight Stalwart', rarity: 'U', layout: 'normal' },
            { cardNumber: 353, name: 'Ratadrabik of Urborg', rarity: 'R', layout: 'normal' },
            { cardNumber: 354, name: 'Rith, Liberated Primeval', rarity: 'M', layout: 'normal' },
            { cardNumber: 355, name: 'Rivaz of the Claw', rarity: 'R', layout: 'normal' },
            { cardNumber: 356, name: "Rona, Sheoldred's Faithful", rarity: 'U', layout: 'normal' },
            { cardNumber: 357, name: 'Rulik Mons, Warren Chief', rarity: 'U', layout: 'normal' },
            { cardNumber: 358, name: 'Shanna, Purifying Blade', rarity: 'M', layout: 'normal' },
            { cardNumber: 359, name: "Sol'Kanar the Tainted", rarity: 'M', layout: 'normal' },
            { cardNumber: 360, name: 'Soul of Windgrace', rarity: 'M', layout: 'normal' },
            { cardNumber: 361, name: 'Stenn, Paranoid Partisan', rarity: 'R', layout: 'normal' },
            { cardNumber: 362, name: 'Tatyova, Steward of Tides', rarity: 'U', layout: 'normal' },
            { cardNumber: 363, name: "Tori D'Avenant, Fury Rider", rarity: 'U', layout: 'normal' },
            { cardNumber: 364, name: 'Tura Kennerüd, Skyknight', rarity: 'U', layout: 'normal' },
            { cardNumber: 365, name: 'Uurg, Spawn of Turg', rarity: 'U', layout: 'normal' },
            { cardNumber: 366, name: 'Vohar, Vodalian Desecrator', rarity: 'U', layout: 'normal' },
            { cardNumber: 367, name: 'Zar Ojanen, Scion of Efrava', rarity: 'U', layout: 'normal' },
            { cardNumber: 368, name: 'Zur, Eternal Schemer', rarity: 'M', layout: 'normal' },
            { cardNumber: 369, name: 'Sheoldred, the Apocalypse', rarity: 'M', layout: 'normal' },
            { cardNumber: 370, name: 'Ajani, Sleeper Agent', rarity: 'M', layout: 'normal' },
            { cardNumber: 371, name: 'Ajani, Sleeper Agent', rarity: 'M', layout: 'normal' },
            { cardNumber: 372, name: 'Karn, Living Legacy', rarity: 'M', layout: 'normal' },
            { cardNumber: 373, name: 'Liliana of the Veil', rarity: 'M', layout: 'normal' },
            { cardNumber: 374, name: 'Jaya, Fiery Negotiator', rarity: 'M', layout: 'normal' },
            { cardNumber: 375, name: 'Ajani, Sleeper Agent', rarity: 'M', layout: 'normal' },
            { cardNumber: 376, name: 'Ajani, Sleeper Agent', rarity: 'M', layout: 'normal' },
            { cardNumber: 377, name: 'Adarkar Wastes', rarity: 'R', layout: 'normal' },
            { cardNumber: 378, name: 'Caves of Koilos', rarity: 'R', layout: 'normal' },
            { cardNumber: 379, name: 'Karplusan Forest', rarity: 'R', layout: 'normal' },
            { cardNumber: 380, name: 'Shivan Reef', rarity: 'R', layout: 'normal' },
            { cardNumber: 381, name: 'Sulfurous Springs', rarity: 'R', layout: 'normal' },
            { cardNumber: 382, name: 'Yavimaya Coast', rarity: 'R', layout: 'normal' },
            { cardNumber: 383, name: 'Anointed Peacekeeper', rarity: 'R', layout: 'normal' },
            { cardNumber: 384, name: 'Archangel of Wrath', rarity: 'R', layout: 'normal' },
            { cardNumber: 385, name: 'Defiler of Faith', rarity: 'R', layout: 'normal' },
            { cardNumber: 386, name: 'Guardian of New Benalia', rarity: 'R', layout: 'normal' },
            { cardNumber: 387, name: 'Leyline Binding', rarity: 'R', layout: 'normal' },
            { cardNumber: 388, name: 'Serra Paragon', rarity: 'M', layout: 'normal' },
            { cardNumber: 389, name: 'Temporary Lockdown', rarity: 'R', layout: 'normal' },
            { cardNumber: 390, name: 'Valiant Veteran', rarity: 'R', layout: 'normal' },
            { cardNumber: 391, name: 'Academy Loremaster', rarity: 'R', layout: 'normal' },
            { cardNumber: 392, name: 'Aether Channeler', rarity: 'R', layout: 'normal' },
            { cardNumber: 393, name: 'Defiler of Dreams', rarity: 'R', layout: 'normal' },
            { cardNumber: 394, name: 'Haughty Djinn', rarity: 'R', layout: 'normal' },
            { cardNumber: 395, name: 'Silver Scrutiny', rarity: 'R', layout: 'normal' },
            { cardNumber: 396, name: 'Sphinx of Clear Skies', rarity: 'M', layout: 'normal' },
            { cardNumber: 397, name: 'Vesuvan Duplimancy', rarity: 'M', layout: 'normal' },
            { cardNumber: 398, name: 'Vodalian Hexcatcher', rarity: 'R', layout: 'normal' },
            { cardNumber: 399, name: 'Vodalian Mindsinger', rarity: 'R', layout: 'normal' },
            { cardNumber: 400, name: 'Defiler of Flesh', rarity: 'R', layout: 'normal' },
            { cardNumber: 401, name: 'Drag to the Bottom', rarity: 'R', layout: 'normal' },
            { cardNumber: 402, name: 'Evolved Sleeper', rarity: 'R', layout: 'normal' },
            { cardNumber: 403, name: 'Shadow-Rite Priest', rarity: 'R', layout: 'normal' },
            { cardNumber: 404, name: 'Stronghold Arena', rarity: 'R', layout: 'normal' },
            { cardNumber: 405, name: 'Chaotic Transformation', rarity: 'R', layout: 'normal' },
            { cardNumber: 406, name: 'Defiler of Instinct', rarity: 'R', layout: 'normal' },
            { cardNumber: 407, name: 'Keldon Flamesage', rarity: 'R', layout: 'normal' },
            { cardNumber: 408, name: "Radha's Firebrand", rarity: 'R', layout: 'normal' },
            { cardNumber: 409, name: 'Rundvelt Hordemaster', rarity: 'R', layout: 'normal' },
            { cardNumber: 410, name: 'Shivan Devastator', rarity: 'M', layout: 'normal' },
            { cardNumber: 411, name: 'Temporal Firestorm', rarity: 'R', layout: 'normal' },
            { cardNumber: 412, name: 'Defiler of Vigor', rarity: 'R', layout: 'normal' },
            { cardNumber: 413, name: 'Herd Migration', rarity: 'R', layout: 'normal' },
            { cardNumber: 414, name: 'Leaf-Crowned Visionary', rarity: 'R', layout: 'normal' },
            { cardNumber: 415, name: 'Llanowar Greenwidow', rarity: 'R', layout: 'normal' },
            { cardNumber: 416, name: 'Llanowar Loamspeaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 417, name: 'Quirion Beastcaller', rarity: 'R', layout: 'normal' },
            { cardNumber: 418, name: 'Silverback Elder', rarity: 'M', layout: 'normal' },
            { cardNumber: 419, name: 'Threats Undetected', rarity: 'R', layout: 'normal' },
            { cardNumber: 420, name: 'Urborg Lhurgoyf', rarity: 'R', layout: 'normal' },
            { cardNumber: 421, name: 'Plaza of Heroes', rarity: 'R', layout: 'normal' },
            { cardNumber: 422, name: 'Thran Portal', rarity: 'R', layout: 'normal' },
            { cardNumber: 423, name: 'Serra Redeemer', rarity: 'R', layout: 'normal' },
            { cardNumber: 424, name: 'Cosmic Epiphany', rarity: 'R', layout: 'normal' },
            { cardNumber: 425, name: 'Tyrannical Pitlord', rarity: 'R', layout: 'normal' },
            { cardNumber: 426, name: 'Ragefire Hellkite', rarity: 'R', layout: 'normal' },
            { cardNumber: 427, name: 'Briar Hydra', rarity: 'R', layout: 'normal' },
            { cardNumber: 428, name: 'Llanowar Loamspeaker', rarity: 'R', layout: 'normal' },
            { cardNumber: 429, name: 'Herd Migration', rarity: 'R', layout: 'normal' },
            { cardNumber: 430, name: 'Resolute Reinforcements', rarity: 'U', layout: 'normal' },
            { cardNumber: 431, name: 'Micromancer', rarity: 'U', layout: 'normal' },
            { cardNumber: 432, name: 'Cut Down', rarity: 'U', layout: 'normal' },
            { cardNumber: 433, name: 'Lightning Strike', rarity: 'C', layout: 'normal' },
            { cardNumber: 434, name: 'Nishoba Brawler', rarity: 'U', layout: 'normal' },
        ];
        await MigrationHelper.cardSetUp(
            queryRunner,
            'Dominaria United',
            this.shortName,
            cardValues,
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select()
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
