import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationHelper } from './helper/migration-helper';

export class colorTypeVow1664012716322 implements MigrationInterface {
    shortName = 'VOW';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Adamant Will',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Angelic Quartermaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Arm the Cathars',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: "Bride's Gown",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'By Invitation Only',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Cemetery Protector',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Circle of Confinement',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Dawnhart Geist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Distracting Geist // Clever Distraction',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Drogskol Infantry // Drogskol Armaments',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Estwald Shieldbasher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: "Faithbound Judge // Sinner's Judgment",
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Fierce Retribution',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Fleeting Spirit',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Gryff Rider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Gryffwing Cavalry',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Hallowed Haunting',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Heron of Hope',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Heron-Blessed Geist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Hopeful Initiate',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: "Katilda, Dawnhart Martyr // Katilda's Rising Dawn",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: "Kindly Ancestor // Ancestor's Embrace",
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Lantern Flare',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Militia Rallier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Nebelgast Beguiler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Nurturing Presence',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Ollenbock Escort',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Panicked Bystander // Cackling Culprit',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Parish-Blade Trainee',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Piercing Light',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Radiant Grace // Radiant Restraints',
                rarity: 'U',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Resistance Squad',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Sanctify',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Savior of Ollenbock',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: "Sigarda's Imprisonment",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: "Sigarda's Summons",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Supernatural Rescue',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Traveling Minister',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Twinblade Geist // Twinblade Invocation',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Unholy Officiant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Valorous Stance',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Vampire Slayer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: 'Voice of the Blessed',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 45,
                name: 'Wedding Announcement // Wedding Festivity',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 46,
                name: 'Welcoming Vampire',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 47,
                name: "Alchemist's Retrieval",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Binding Geist // Spectral Binding',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Biolume Egg // Biolume Serpent',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Cemetery Illuminator',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Chill of the Grave',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Cobbled Lancer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Consuming Tide',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Cradle of Safety',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Cruel Witness',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Diver Skaab',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Dreadlight Monstrosity',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Dreamshackle Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Fear of Death',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Geistlight Snare',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Geralf, Visionary Stitcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Gutter Skulker // Gutter Shortcut',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Hullbreaker Horror',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Inspired Idea',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: "Jacob Hauken, Inspector // Hauken's Insight",
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: "Lantern Bearer // Lanterns' Lift",
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Lunar Rejection',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Mirrorhall Mimic // Ghastly Mimicry',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Mischievous Catgeist // Catlike Curiosity',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Necroduality',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Overcharged Amalgam',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Patchwork Crawler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Repository Skaab',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Scattered Thoughts',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Screaming Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Selhoff Entomber',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Serpentine Ambush',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Skywarp Skaab',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Soulcipher Board // Cipherbound Spirit',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Steelclad Spirit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Stitched Assistant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Stormchaser Drake',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Syncopate',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Syphon Essence',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: 'Thirst for Discovery',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 86,
                name: 'Wanderlight Spirit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 87,
                name: 'Wash Away',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 88,
                name: 'Whispering Wizard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 89,
                name: 'Winged Portent',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 90,
                name: 'Witness the Future',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 91,
                name: 'Wretched Throng',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 92,
                name: 'Aim for the Head',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Archghoul of Thraben',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Bleed Dry',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Blood Fountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Bloodcrazed Socialite',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Bloodsworn Squire // Bloodsworn Knight',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Bloodvial Purveyor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Catapult Fodder // Catapult Captain',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Cemetery Desecrator',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Concealing Curtains // Revealing Eye',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Courier Bat',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Demonic Bargain',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Desperate Farmer // Depraved Harvester',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Diregraf Scavenger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Doomed Dissenter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Dread Fugue',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Dreadfeast Demon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Dying to Serve',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: "Edgar's Awakening",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Falkenrath Forebear',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Fell Stinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Gift of Fangs',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Gluttonous Guest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Graf Reaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Grisly Ritual',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: "Groom's Finery",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Headless Rider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Henrika Domnathi // Henrika, Infernal Seer',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: "Hero's Downfall",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Innocent Traveler // Malicious Invader',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Mindleech Ghoul',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Parasitic Grasp',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Path of Peril',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 125,
                name: 'Persistent Specimen',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 126,
                name: 'Pointed Discussion',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 127,
                name: 'Ragged Recluse // Odious Witch',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 128,
                name: 'Restless Bloodseeker // Bloodsoaked Reveler',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 129,
                name: 'Rot-Tide Gargantua',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 130,
                name: 'Skulking Killer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 131,
                name: 'Sorin the Mirthless',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 132,
                name: 'Toxrill, the Corrosive',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 133,
                name: 'Undead Butler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 134,
                name: 'Undying Malice',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 135,
                name: 'Unhallowed Phalanx',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 136,
                name: "Vampire's Kiss",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 137,
                name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 138,
                name: 'Wedding Security',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 139,
                name: 'Abrade',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: "Alchemist's Gambit",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Alluring Suitor // Deadly Dancer',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Ancestral Anger',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Ballista Watcher // Ballista Wielder',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Belligerent Guest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Blood Hypnotist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Blood Petal Celebrant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Bloody Betrayal',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Cemetery Gatekeeper',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Chandra, Dressed to Kill',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Change of Fortune',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Creepy Puppeteer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Curse of Hospitality',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Daybreak Combatants',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Dominating Vampire',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'End the Festivities',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Falkenrath Celebrants',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Fearful Villager // Fearsome Werewolf',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Flame-Blessed Bolt',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Frenzied Devils',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Honeymoon Hearse',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Hungry Ridgewolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Ill-Tempered Loner // Howlpack Avenger',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Into the Night',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Kessig Flamebreather',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 165,
                name: 'Kessig Wolfrider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 166,
                name: 'Lacerate Flesh',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 167,
                name: 'Lambholt Raconteur // Lambholt Ravager',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Lightning Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 169,
                name: 'Magma Pummeler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 170,
                name: 'Manaform Hellkite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 171,
                name: 'Markov Retribution',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 172,
                name: "Olivia's Attendants",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 173,
                name: 'Pyre Spawn',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 174,
                name: 'Reckless Impulse',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 175,
                name: 'Rending Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 176,
                name: 'Runebound Wolf',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 177,
                name: 'Sanguine Statuette',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 178,
                name: 'Stensia Uprising',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 179,
                name: 'Sure Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 180,
                name: "Vampires' Vengeance",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 181,
                name: 'Volatile Arsonist // Dire-Strain Anarchist',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 182,
                name: 'Voldaren Epicure',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 183,
                name: 'Voltaic Visionary // Volt-Charged Berserker',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 184,
                name: 'Weary Prisoner // Wrathful Jailbreaker',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 185,
                name: 'Apprentice Sharpshooter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Ascendant Packleader',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Avabruck Caretaker // Hollowhenge Huntmaster',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Bramble Armor',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Bramble Wurm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: "Cartographer's Survey",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Cemetery Prowler',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Cloaked Cadet',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Crawling Infestation',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Crushing Canopy',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Cultivator Colossus',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Dawnhart Disciple',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Dig Up',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Dormant Grove // Gnarled Grovestrider',
                rarity: 'U',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Flourishing Hunter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Glorious Sunrise',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Hamlet Vanguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Hiveheart Shaman',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Hookhand Mariner // Riphook Raider',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Howling Moon',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 205,
                name: 'Howlpack Piper // Wildsong Howler',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 206,
                name: 'Infestation Expert // Infested Werewolf',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 207,
                name: 'Laid to Rest',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 208,
                name: 'Massive Might',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 209,
                name: 'Moldgraf Millipede',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 210,
                name: 'Mulch',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 211,
                name: "Nature's Embrace",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 212,
                name: 'Oakshade Stalker // Moonlit Ambusher',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 213,
                name: 'Packsong Pup',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 214,
                name: 'Reclusive Taxidermist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 215,
                name: 'Retrieve',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 216,
                name: 'Rural Recruit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 217,
                name: 'Sawblade Slinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 218,
                name: 'Sheltering Boughs',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 219,
                name: 'Snarling Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 220,
                name: 'Spiked Ripsaw',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 221,
                name: 'Splendid Reclamation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 222,
                name: 'Spore Crawler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 223,
                name: 'Sporeback Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 224,
                name: 'Toxic Scorpion',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 225,
                name: 'Ulvenwald Oddity // Ulvenwald Behemoth',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 226,
                name: 'Weaver of Blossoms // Blossom-Clad Werewolf',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 227,
                name: "Witch's Web",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 228,
                name: 'Wolf Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 229,
                name: 'Wolfkin Outcast // Wedding Crasher',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 230,
                name: 'Ancient Lumberknot',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 231,
                name: 'Anje, Maid of Dishonor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 232,
                name: 'Bloodtithe Harvester',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 233,
                name: 'Brine Comber // Brinebound Gift',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 234,
                name: 'Child of the Pack // Savage Packmate',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 235,
                name: "Dorothea, Vengeful Victim // Dorothea's Retribution",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 236,
                name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 237,
                name: 'Eruth, Tormented Prophet',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 238,
                name: 'Grolnok, the Omnivore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 239,
                name: 'Halana and Alena, Partners',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 240,
                name: 'Kaya, Geist Hunter',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B,W',
            },
            {
                cardNumber: 241,
                name: 'Markov Purifier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 242,
                name: 'Markov Waltzer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 243,
                name: 'Odric, Blood-Cursed',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 244,
                name: 'Old Rutstein',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 245,
                name: 'Olivia, Crimson Bride',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 246,
                name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 247,
                name: 'Sigardian Paladin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 248,
                name: 'Skull Skaab',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 249,
                name: 'Torens, Fist of the Angels',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 250,
                name: 'Vilespawn Spider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 251,
                name: 'Wandering Mind',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 252,
                name: 'Blood Servitor',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Boarded Window',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Ceremonial Knife',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Dollhouse of Horrors',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Foreboding Statue // Forsaken Thresher',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Honored Heirloom',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 258,
                name: "Investigator's Journal",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Lantern of the Lost',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Wedding Invitation',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Deathcap Glade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Dreamroot Cascade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Evolving Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Shattered Sanctum',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Stormcarved Coast',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Sundown Pass',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Voldaren Estate',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Sorin the Mirthless',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 279,
                name: 'Chandra, Dressed to Kill',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R',
            },
            {
                cardNumber: 280,
                name: 'Kaya, Geist Hunter',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B,W',
            },
            {
                cardNumber: 281,
                name: 'Deathcap Glade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Dreamroot Cascade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Shattered Sanctum',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Stormcarved Coast',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Sundown Pass',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Unholy Officiant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 287,
                name: 'Welcoming Vampire',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 288,
                name: 'Bloodcrazed Socialite',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 289,
                name: 'Bloodsworn Squire // Bloodsworn Knight',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 290,
                name: 'Bloodvial Purveyor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 291,
                name: 'Falkenrath Forebear',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 292,
                name: 'Gluttonous Guest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 293,
                name: 'Henrika Domnathi // Henrika, Infernal Seer',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 294,
                name: 'Innocent Traveler // Malicious Invader',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 295,
                name: 'Restless Bloodseeker // Bloodsoaked Reveler',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 296,
                name: 'Skulking Killer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 297,
                name: 'Sorin the Mirthless',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 298,
                name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 299,
                name: 'Wedding Security',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 300,
                name: 'Alluring Suitor // Deadly Dancer',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 301,
                name: 'Belligerent Guest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 302,
                name: 'Blood Hypnotist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 303,
                name: 'Blood Petal Celebrant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 304,
                name: 'Cemetery Gatekeeper',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 305,
                name: 'Dominating Vampire',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 306,
                name: 'Falkenrath Celebrants',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 307,
                name: "Olivia's Attendants",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 308,
                name: 'Voldaren Epicure',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 309,
                name: 'Anje, Maid of Dishonor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 310,
                name: 'Bloodtithe Harvester',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 311,
                name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 312,
                name: 'Markov Purifier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 313,
                name: 'Markov Waltzer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 314,
                name: 'Odric, Blood-Cursed',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 315,
                name: 'Olivia, Crimson Bride',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 316,
                name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 317,
                name: "Katilda, Dawnhart Martyr // Katilda's Rising Dawn",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 318,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 319,
                name: 'Geralf, Visionary Stitcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 320,
                name: "Jacob Hauken, Inspector // Hauken's Insight",
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 321,
                name: 'Toxrill, the Corrosive',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 322,
                name: "Dorothea, Vengeful Victim // Dorothea's Retribution",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 323,
                name: 'Eruth, Tormented Prophet',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 324,
                name: 'Grolnok, the Omnivore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 325,
                name: 'Halana and Alena, Partners',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 326,
                name: 'Old Rutstein',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 327,
                name: 'Runo Stromkirk // Krothuss, Lord of the Deep',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 328,
                name: 'Torens, Fist of the Angels',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 329,
                name: 'Circle of Confinement',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 330,
                name: 'Savior of Ollenbock',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 331,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 332,
                name: "Jacob Hauken, Inspector // Hauken's Insight",
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 333,
                name: 'Thirst for Discovery',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 334,
                name: 'Falkenrath Forebear',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 335,
                name: 'Henrika Domnathi // Henrika, Infernal Seer',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 336,
                name: 'Innocent Traveler // Malicious Invader',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 337,
                name: 'Sorin the Mirthless',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 338,
                name: 'Voldaren Bloodcaster // Bloodbat Summoner',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 339,
                name: "Vampires' Vengeance",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 340,
                name: 'Reclusive Taxidermist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 341,
                name: "Edgar, Charmed Groom // Edgar Markov's Coffin",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 342,
                name: 'Eruth, Tormented Prophet',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 343,
                name: 'Olivia, Crimson Bride',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 344,
                name: 'Torens, Fist of the Angels',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 345,
                name: "Investigator's Journal",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 346,
                name: 'By Invitation Only',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 347,
                name: 'Cemetery Protector',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 348,
                name: "Faithbound Judge // Sinner's Judgment",
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 349,
                name: 'Hallowed Haunting',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 350,
                name: 'Hopeful Initiate',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 351,
                name: 'Lantern Flare',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 352,
                name: 'Savior of Ollenbock',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 353,
                name: "Sigarda's Summons",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 354,
                name: 'Voice of the Blessed',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 355,
                name: 'Wedding Announcement // Wedding Festivity',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 356,
                name: 'Cemetery Illuminator',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 357,
                name: 'Consuming Tide',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 358,
                name: 'Dreamshackle Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 359,
                name: 'Hullbreaker Horror',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 360,
                name: 'Inspired Idea',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 361,
                name: 'Mirrorhall Mimic // Ghastly Mimicry',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 362,
                name: 'Necroduality',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 363,
                name: 'Overcharged Amalgam',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 364,
                name: 'Patchwork Crawler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 365,
                name: 'Winged Portent',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 366,
                name: 'Cemetery Desecrator',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 367,
                name: 'Concealing Curtains // Revealing Eye',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 368,
                name: 'Demonic Bargain',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 369,
                name: 'Dreadfeast Demon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 370,
                name: 'Dying to Serve',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 371,
                name: 'Graf Reaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 372,
                name: 'Headless Rider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 373,
                name: 'Path of Peril',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 374,
                name: "Alchemist's Gambit",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 375,
                name: 'Change of Fortune',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 376,
                name: 'Creepy Puppeteer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 377,
                name: 'Curse of Hospitality',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 378,
                name: 'Ill-Tempered Loner // Howlpack Avenger',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 379,
                name: 'Kessig Wolfrider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 380,
                name: 'Manaform Hellkite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 381,
                name: 'Stensia Uprising',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 382,
                name: 'Volatile Arsonist // Dire-Strain Anarchist',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 383,
                name: 'Ascendant Packleader',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 384,
                name: 'Avabruck Caretaker // Hollowhenge Huntmaster',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 385,
                name: 'Cemetery Prowler',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 386,
                name: 'Cultivator Colossus',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 387,
                name: 'Dig Up',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 388,
                name: 'Glorious Sunrise',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 389,
                name: 'Hamlet Vanguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 390,
                name: 'Hiveheart Shaman',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 391,
                name: 'Howling Moon',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 392,
                name: 'Howlpack Piper // Wildsong Howler',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 393,
                name: 'Splendid Reclamation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 394,
                name: 'Ulvenwald Oddity // Ulvenwald Behemoth',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 395,
                name: 'Dollhouse of Horrors',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 396,
                name: "Investigator's Journal",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 397,
                name: 'Voldaren Estate',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 398,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 399,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 400,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 401,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 402,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 403,
                name: 'Voldaren Estate',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 404,
                name: "Sigarda's Summons",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 405,
                name: 'Geistlight Snare',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 406,
                name: 'Fell Stinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 407,
                name: 'Dominating Vampire',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
        ];

        await MigrationHelper.colorAndTypeUp(queryRunner, this.shortName, cardValues);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await MigrationHelper.colorAndTypeDown(queryRunner, this.shortName);
    }
}
