import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationHelper } from './helper/migration-helper';

export class colorTypeMid1664013706149 implements MigrationInterface {
    shortName = 'MID';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Adeline, Resplendent Cathar',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Ambitious Farmhand // Seasoned Cathar',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Beloved Beggar // Generous Soul',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Bereaved Survivor // Dauntless Avenger',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Blessed Defiance',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Borrowed Time',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Brutal Cathar // Moonrage Brute',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Candlegrove Witch',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Candletrap',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Cathar Commando',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: "Cathar's Call",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Celestus Sanctifier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Chaplain of Alms // Chapel Shieldgeist',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Clarion Cathars',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Curse of Silence',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Duelcraft Trainer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Enduring Angel // Angelic Enforcer',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Fateful Absence',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Flare of Faith',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Gavony Dawnguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Gavony Silversmith',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Gavony Trapper',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: "Hedgewitch's Mask",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Homestead Courage',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Intrepid Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Loyal Gryff',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Lunarch Veteran // Luminous Phantom',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Mourning Patrol // Morning Apparition',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: "Odric's Outrider",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Ritual Guardian',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Ritual of Hope',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Search Party Captain',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: "Sigarda's Splendor",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Sigardian Savior',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Soul-Guide Gryff',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Sungold Barrage',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Sungold Sentinel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Sunset Revelry',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Thraben Exorcism',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Unruly Mob',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Vanquish the Horde',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Baithook Angler // Hook-Haunt Drifter',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 43,
                name: 'Component Collector',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 44,
                name: 'Consider',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Covetous Castaway // Ghostly Castigator',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Curse of Surveillance',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Delver of Secrets // Insectile Aberration',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Devious Cover-Up',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Dissipate',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Drownyard Amalgam',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Fading Hope',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Falcon Abomination',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Firmament Sage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Flip the Switch',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Galedrifter // Waildrifter',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Geistwave',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Grafted Identity',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Larder Zombie',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Lier, Disciple of the Drowned',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Locked in the Cemetery',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Malevolent Hermit // Benevolent Geist',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Memory Deluge',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Mysterious Tome // Chilling Chronicle',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Nebelgast Intruder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Ominous Roost',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Organ Hoarder',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Otherworldly Gaze',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Overwhelmed Archivist // Archive Haunt',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Patrician Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Phantom Carriage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Poppet Stitcher // Poppet Factory',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Revenge of the Drowned',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Secrets of the Key',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Shipwreck Sifters',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Skaab Wrangler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Sludge Monster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Spectral Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Startle',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Stormrider Spirit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Suspicious Stowaway // Seafaring Werewolf',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Triskaidekaphile',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Unblinking Observer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Vivisection',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Arrogant Outlaw',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Baneblade Scoundrel // Baneclaw Marauder',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Bat Whisperer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'Bladebrand',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: 'Blood Pact',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Bloodline Culling',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Bloodtithe Collector',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Champion of the Perished',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Covert Cutpurse // Covetous Geist',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Crawl from the Cellar',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Curse of Leeches // Leeching Lurker',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Defenestrate',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Diregraf Horde',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Dreadhound',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Duress',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Eaten Alive',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Ecstatic Awakener // Awoken Demon',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Foul Play',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Ghoulish Procession',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Gisa, Glorious Resurrector',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Graveyard Trespasser // Graveyard Glutton',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Heirloom Mirror // Inherited Fiend',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Hobbling Zombie',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Infernal Grasp',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Jadar, Ghoulcaller of Nephalia',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Jerren, Corrupted Bishop // Ormendahl, the Corrupter',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Lord of the Forsaken',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Mask of Griselbrand',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'The Meathook Massacre',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Morbid Opportunist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Morkrut Behemoth',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Necrosynthesis',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'No Way Out',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Novice Occultist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: "Olivia's Midnight Ambush",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Rotten Reunion',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Shady Traveler // Stalking Predator',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Siege Zombie',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Slaughter Specialist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Stromkirk Bloodthief',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Tainted Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 125,
                name: 'Vampire Interloper',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 126,
                name: 'Vengeful Strangler // Strangling Grasp',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 127,
                name: 'Abandon the Post',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Ardent Elementalist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Bloodthirsty Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Brimstone Vandal',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Burn Down the House',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Burn the Accursed',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Cathartic Pyre',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Curse of Shaken Faith',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Electric Revelation',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Falkenrath Perforator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Falkenrath Pit Fighter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Famished Foragers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Fangblade Brigand // Fangblade Eviscerator',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Festival Crasher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Flame Channeler // Embodiment of Flame',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Geistflame Reservoir',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Harvesttide Infiltrator // Harvesttide Assailant',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Immolation',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Lambholt Harrier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Light Up the Night',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Lunar Frenzy',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: "Moonrager's Slash",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Moonveil Regent',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Mounted Dreadknight',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: "Neonate's Rush",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Obsessive Astronomer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: "Pack's Betrayal",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Play with Fire',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Purifying Dragon',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Raze the Effigy',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Reckless Stormseeker // Storm-Charged Slasher',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Seize the Storm',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Smoldering Egg // Ashmouth Dragon',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Spellrune Painter // Spellrune Howler',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Stolen Vitality',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Sunstreak Phoenix',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Tavern Ruffian // Tavern Smasher',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Thermo-Alchemist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 165,
                name: 'Village Watch // Village Reavers',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 166,
                name: 'Voldaren Ambusher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 167,
                name: 'Voldaren Stinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Augur of Autumn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: 'Bird Admirer // Wing Shredder',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Bounding Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 171,
                name: 'Bramble Armor',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'Briarbridge Tracker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Brood Weaver',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: 'Burly Breaker // Dire-Strain Demolisher',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Candlelit Cavalry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'Clear Shot',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Consuming Blob',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Contortionist Troupe',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Dawnhart Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Dawnhart Rejuvenator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Deathbonnet Sprout // Deathbonnet Hulk',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Defend the Celestus',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: "Dryad's Revival",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Duel for Dominance',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Eccentric Farmer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Harvesttide Sentry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Hound Tamer // Untamed Pup',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Howl of the Hunt',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Might of the Old Ways',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Outland Liberator // Frenzied Trapbreaker',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Path to the Festival',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Pestilent Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Plummet',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Primal Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Return to Nature',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Rise of the Ants',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: "Saryth, the Viper's Fang",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Shadowbeast Sighting',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Snarling Wolf',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Storm the Festival',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Tapping at the Window',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Timberland Guide',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Tireless Hauler // Dire-Strain Brawler',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: "Tovolar's Huntmaster // Tovolar's Packleader",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 205,
                name: 'Turn the Earth',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 206,
                name: 'Unnatural Growth',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 207,
                name: 'Willow Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 208,
                name: 'Wrenn and Seven',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'G',
            },
            {
                cardNumber: 209,
                name: 'Angelfire Ignition',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,W',
            },
            {
                cardNumber: 210,
                name: 'Arcane Infusion',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 211,
                name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                rarity: 'M',
                layout: 'transform',
                types: 'Planeswalker',
                colors: 'G,R',
            },
            {
                cardNumber: 212,
                name: 'Bladestitched Skaab',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 213,
                name: "Can't Stay Away",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 214,
                name: 'Corpse Cobble',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,U',
            },
            {
                cardNumber: 215,
                name: 'Croaking Counterpart',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 216,
                name: 'Dawnhart Wardens',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 217,
                name: 'Dennick, Pious Apprentice // Dennick, Pious Apparition',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 218,
                name: 'Devoted Grafkeeper // Departed Soulkeeper',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 219,
                name: 'Dire-Strain Rampage',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,R',
            },
            {
                cardNumber: 220,
                name: 'Diregraf Rebirth',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 221,
                name: 'Faithful Mending',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U,W',
            },
            {
                cardNumber: 222,
                name: 'Fleshtaker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 223,
                name: 'Florian, Voldaren Scion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 224,
                name: 'Galvanic Iteration',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 225,
                name: "Ghoulcaller's Harvest",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 226,
                name: 'Grizzly Ghoul',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 227,
                name: 'Hallowed Respite',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 228,
                name: 'Hungry for More',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 229,
                name: 'Join the Dance',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,W',
            },
            {
                cardNumber: 230,
                name: 'Katilda, Dawnhart Prime',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 231,
                name: 'Kessig Naturalist // Lord of the Ulvenwald',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 232,
                name: 'Liesa, Forgotten Archangel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 233,
                name: "Ludevic, Necrogenius // Olag, Ludevic's Hubris",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 234,
                name: 'Old Stickfingers',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 235,
                name: 'Rem Karolus, Stalwart Slayer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 236,
                name: 'Rite of Harmony',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,W',
            },
            {
                cardNumber: 237,
                name: 'Rite of Oblivion',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 238,
                name: 'Rootcoil Creeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 239,
                name: 'Sacred Fire',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 240,
                name: 'Sigarda, Champion of Light',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 241,
                name: 'Siphon Insight',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,U',
            },
            {
                cardNumber: 242,
                name: 'Slogurk, the Overslime',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 243,
                name: 'Storm Skreelix',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 244,
                name: 'Sunrise Cavalier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 245,
                name: 'Teferi, Who Slows the Sunset',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'U,W',
            },
            {
                cardNumber: 246,
                name: 'Tovolar, Dire Overlord // Tovolar, the Midnight Scourge',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 247,
                name: 'Unnatural Moonrise',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,R',
            },
            {
                cardNumber: 248,
                name: 'Vadrik, Astral Archmage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 249,
                name: 'Vampire Socialite',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 250,
                name: 'Wake to Slaughter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 251,
                name: 'Winterthorn Blessing',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 252,
                name: 'The Celestus',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Crossroads Candleguide',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 254,
                name: "Jack-o'-Lantern",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Moonsilver Key',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Mystic Skull // Mystic Monstrosity',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Pithing Needle',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Silver Bolt',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Stuffed Bear',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Deserted Beach',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Evolving Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Field of Ruin',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Haunted Ridge',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Hostile Hostel // Creeping Inn',
                rarity: 'M',
                layout: 'transform',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Overgrown Farmland',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Rockfall Vale',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Shipwreck Marsh',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Wrenn and Seven',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'G',
            },
            {
                cardNumber: 279,
                name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                rarity: 'M',
                layout: 'transform',
                types: 'Planeswalker',
                colors: 'G,R',
            },
            {
                cardNumber: 280,
                name: 'Teferi, Who Slows the Sunset',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'U,W',
            },
            {
                cardNumber: 281,
                name: 'Deserted Beach',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Haunted Ridge',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Overgrown Farmland',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Rockfall Vale',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Shipwreck Marsh',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Brutal Cathar // Moonrage Brute',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 287,
                name: 'Candlegrove Witch',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 288,
                name: 'Suspicious Stowaway // Seafaring Werewolf',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 289,
                name: 'Baneblade Scoundrel // Baneclaw Marauder',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 290,
                name: 'Graveyard Trespasser // Graveyard Glutton',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 291,
                name: 'Shady Traveler // Stalking Predator',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 292,
                name: 'Fangblade Brigand // Fangblade Eviscerator',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 293,
                name: 'Harvesttide Infiltrator // Harvesttide Assailant',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 294,
                name: 'Reckless Stormseeker // Storm-Charged Slasher',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 295,
                name: 'Spellrune Painter // Spellrune Howler',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 296,
                name: 'Tavern Ruffian // Tavern Smasher',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 297,
                name: 'Village Watch // Village Reavers',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 298,
                name: 'Bird Admirer // Wing Shredder',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 299,
                name: 'Burly Breaker // Dire-Strain Demolisher',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 300,
                name: 'Dawnhart Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 301,
                name: 'Dawnhart Rejuvenator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 302,
                name: 'Hound Tamer // Untamed Pup',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 303,
                name: 'Outland Liberator // Frenzied Trapbreaker',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 304,
                name: "Saryth, the Viper's Fang",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 305,
                name: 'Tireless Hauler // Dire-Strain Brawler',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 306,
                name: "Tovolar's Huntmaster // Tovolar's Packleader",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 307,
                name: "Arlinn, the Pack's Hope // Arlinn, the Moon's Fury",
                rarity: 'M',
                layout: 'transform',
                types: 'Planeswalker',
                colors: 'G,R',
            },
            {
                cardNumber: 308,
                name: 'Dawnhart Wardens',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 309,
                name: 'Katilda, Dawnhart Prime',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 310,
                name: 'Kessig Naturalist // Lord of the Ulvenwald',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 311,
                name: 'Tovolar, Dire Overlord // Tovolar, the Midnight Scourge',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 312,
                name: 'Adeline, Resplendent Cathar',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 313,
                name: 'Lier, Disciple of the Drowned',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 314,
                name: 'Gisa, Glorious Resurrector',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 315,
                name: 'Jadar, Ghoulcaller of Nephalia',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 316,
                name: 'Jerren, Corrupted Bishop // Ormendahl, the Corrupter',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 317,
                name: 'Dennick, Pious Apprentice // Dennick, Pious Apparition',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 318,
                name: 'Florian, Voldaren Scion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 319,
                name: 'Liesa, Forgotten Archangel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 320,
                name: "Ludevic, Necrogenius // Olag, Ludevic's Hubris",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 321,
                name: 'Old Stickfingers',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 322,
                name: 'Rem Karolus, Stalwart Slayer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 323,
                name: 'Sigarda, Champion of Light',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 324,
                name: 'Slogurk, the Overslime',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 325,
                name: 'Vadrik, Astral Archmage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 326,
                name: 'Curse of Silence',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 327,
                name: 'Enduring Angel // Angelic Enforcer',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 328,
                name: 'Fateful Absence',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 329,
                name: 'Intrepid Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 330,
                name: "Sigarda's Splendor",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 331,
                name: 'Sigardian Savior',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 332,
                name: 'Sungold Sentinel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 333,
                name: 'Vanquish the Horde',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 334,
                name: 'Curse of Surveillance',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 335,
                name: 'Grafted Identity',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 336,
                name: 'Malevolent Hermit // Benevolent Geist',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 337,
                name: 'Memory Deluge',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 338,
                name: 'Patrician Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 339,
                name: 'Poppet Stitcher // Poppet Factory',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 340,
                name: 'Sludge Monster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 341,
                name: 'Spectral Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 342,
                name: 'Triskaidekaphile',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 343,
                name: 'Bloodline Culling',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 344,
                name: 'Champion of the Perished',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 345,
                name: 'Curse of Leeches // Leeching Lurker',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 346,
                name: 'Lord of the Forsaken',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 347,
                name: 'Mask of Griselbrand',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 348,
                name: 'The Meathook Massacre',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 349,
                name: 'Slaughter Specialist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 350,
                name: 'Tainted Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 351,
                name: 'Bloodthirsty Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 352,
                name: 'Burn Down the House',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 353,
                name: 'Curse of Shaken Faith',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 354,
                name: 'Falkenrath Pit Fighter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 355,
                name: 'Geistflame Reservoir',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 356,
                name: 'Light Up the Night',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 357,
                name: 'Moonveil Regent',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 358,
                name: 'Smoldering Egg // Ashmouth Dragon',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 359,
                name: 'Sunstreak Phoenix',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 360,
                name: 'Augur of Autumn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 361,
                name: 'Briarbridge Tracker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 362,
                name: 'Consuming Blob',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 363,
                name: 'Primal Adversary',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 364,
                name: 'Storm the Festival',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 365,
                name: 'Unnatural Growth',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 366,
                name: 'Willow Geist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 367,
                name: 'Angelfire Ignition',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,W',
            },
            {
                cardNumber: 368,
                name: "Can't Stay Away",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 369,
                name: 'Croaking Counterpart',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 370,
                name: 'Dire-Strain Rampage',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,R',
            },
            {
                cardNumber: 371,
                name: 'Galvanic Iteration',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 372,
                name: "Ghoulcaller's Harvest",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 373,
                name: 'Hallowed Respite',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 374,
                name: 'Rite of Harmony',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,W',
            },
            {
                cardNumber: 375,
                name: 'Siphon Insight',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,U',
            },
            {
                cardNumber: 376,
                name: 'Wake to Slaughter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 377,
                name: 'The Celestus',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 378,
                name: 'Pithing Needle',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 379,
                name: 'Hostile Hostel // Creeping Inn',
                rarity: 'M',
                layout: 'transform',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 380,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 381,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 382,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 383,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 384,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 385,
                name: 'Champion of the Perished',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 386,
                name: 'Triskaidekaphile',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 387,
                name: 'Gavony Dawnguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 388,
                name: 'Consider',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 389,
                name: 'Infernal Grasp',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 390,
                name: 'Play with Fire',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 391,
                name: 'Join the Dance',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,W',
            },
        ];

        await MigrationHelper.colorAndTypeUp(queryRunner, this.shortName, cardValues);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await MigrationHelper.colorAndTypeDown(queryRunner, this.shortName);
    }
}
