db:
  host: "localhost"
  database: "testmagic"
  username: "root"
  password: "admin"
  synchronize: true

jwt:
  secret: "topSecret51"

facebook:
  appId: "732644653890540"

log:
  logLevel: ["log", "error", "warn", "debug", "verbose"]

https: true

template:
  dir: "../templates/registration.hbs"
