INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Rivals of Ixalan','RIX');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Ixalan','XLN');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Hour of Devastation','HOU');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Amonkhet','AKH');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Aether Revolt','AER');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Kaladesh','KLD');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Eldritch Moon','EMN');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Shadows over Innistrad','SOI');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Oath of the Gatewatch','OGW');
INSERT INTO CardExpansion (CardExpansionName,CardExpansionShortName) values('Battle For Zendikar','BFZ');